/*********************************************************************
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                           www.segger.com                           *
**********************************************************************
*                                                                    *
* C-file generated by                                                *
*                                                                    *
*        emWin Font Converter (ST) version 5.32                      *
*        Compiled Oct  8 2015, 11:58:55                              *
*                                                                    *
*        (c) 1998 - 2015 Segger Microcontroller GmbH & Co. KG        *
*                                                                    *
**********************************************************************
*                                                                    *
* Source file: CHS16.c                                               *
* Font:        Î¢ÈíÑÅºÚ                                              *
* Height:      16                                                    *
*                                                                    *
**********************************************************************
*                                                                    *
* Initial font height:  16                                           *
* Range disabled:       0000 - FFFF                                  *
* Read pattern file: C:\Users\Administrator\Desktop\123.txt          *
*                                                                    *
**********************************************************************
*/

#include "GUI.h"

#ifndef GUI_CONST_STORAGE
  #define GUI_CONST_STORAGE const
#endif

/* The following line needs to be included in any file selecting the
   font.
*/
extern GUI_CONST_STORAGE GUI_FONT GUI_FontCHS16;

/* Start of unicode area <CJK Unified Ideographs> */
GUI_CONST_STORAGE unsigned char acGUI_FontCHS16_5145[ 18] = { /* code 5145 */
  ____XX__,________,
  XXXXXXXX,XX______,
  ____X__X,________,
  __XX___X,________,
  _XXXXXXX,X_______,
  ___X__X_,X_______,
  ___X__X_,_X______,
  __X___X_,_X______,
  XX____XX,XX______};

GUI_CONST_STORAGE unsigned char acGUI_FontCHS16_5173[ 18] = { /* code 5173 */
  __X____X,________,
  ___X__X_,________,
  _XXXXXXX,X_______,
  _____X__,________,
  XXXXXXXX,XX______,
  ____X___,________,
  ___X_X__,________,
  __X___XX,________,
  XX______,XX______};

GUI_CONST_STORAGE unsigned char acGUI_FontCHS16_5185[ 10] = { /* code 5185 */
  ____X___,
  ____X___,
  XXXXXXXX,
  X___X__X,
  X___X__X,
  X__XX__X,
  X_XX_X_X,
  XX____XX,
  X______X,
  X____XXX};

GUI_CONST_STORAGE unsigned char acGUI_FontCHS16_538B[ 18] = { /* code 538B */
  _XXXXXXX,XX______,
  _X___X__,________,
  _X___X__,________,
  _X_XXXXX,XX______,
  _X___X__,________,
  _X___X_X,________,
  _X___X__,X_______,
  X____X__,________,
  X_XXXXXX,XX______};

GUI_CONST_STORAGE unsigned char acGUI_FontCHS16_56FE[ 18] = { /* code 56FE */
  XXXXXXXX,X_______,
  X__X____,X_______,
  X_XXXXX_,X_______,
  XX_X_X__,X_______,
  XXXXXXXX,X_______,
  X__XX___,X_______,
  X_XXXX__,X_______,
  X____XX_,X_______,
  XXXXXXXX,X_______};

GUI_CONST_STORAGE unsigned char acGUI_FontCHS16_5F00[ 18] = { /* code 5F00 */
  XXXXXXXX,X_______,
  __X___X_,________,
  __X___X_,________,
  __X___X_,________,
  XXXXXXXX,X_______,
  __X___X_,________,
  __X___X_,________,
  _X____X_,________,
  X_____X_,________};

GUI_CONST_STORAGE unsigned char acGUI_FontCHS16_63A7[ 20] = { /* code 63A7 */
  _X___X__,________,
  _X___X__,________,
  XXXXXXXX,X_______,
  _X_X____,X_______,
  _X__XXXX,________,
  _XXX____,X_______,
  XX_XXXXX,X_______,
  _X___X__,________,
  _X___X__,________,
  XX_XXXXX,X_______};

GUI_CONST_STORAGE unsigned char acGUI_FontCHS16_653E[ 20] = { /* code 653E */
  _X____X_,________,
  __X___X_,________,
  XXXXXXXX,XX______,
  _X___X__,X_______,
  _XXXXX__,X_______,
  _X_X_X__,X_______,
  _X_X__XX,________,
  _X_X__X_,________,
  X__X_XXX,X_______,
  X_XXX___,_X______};

GUI_CONST_STORAGE unsigned char acGUI_FontCHS16_66F2[ 11] = { /* code 66F2 */
  __X__X__,
  __X__X__,
  XXXXXXXX,
  X_X__X_X,
  X_X__X_X,
  XXXXXXXX,
  X_X__X_X,
  X_X__X_X,
  X_X__X_X,
  XXXXXXXX,
  X______X};

GUI_CONST_STORAGE unsigned char acGUI_FontCHS16_6D41[ 18] = { /* code 6D41 */
  X____XX_,________,
  _XXXXXXX,XX______,
  X___X__X,X_______,
  _XXXXXXX,XX______,
  ___X_X_X,________,
  _X_X_X_X,________,
  _X_X_X_X,_X______,
  X_X__X_X,_X______,
  XX___X_X,XX______};

GUI_CONST_STORAGE unsigned char acGUI_FontCHS16_6E90[ 18] = { /* code 6E90 */
  XX_XXXXX,XX______,
  _XXX__X_,________,
  X__XXXXX,X_______,
  _X_XXXXX,X_______,
  ___XX___,X_______,
  _X_XXXXX,X_______,
  _X_X_XX_,X_______,
  X_X__XX_,_X______,
  X_X_XXX_,_X______};

GUI_CONST_STORAGE unsigned char acGUI_FontCHS16_7535[ 18] = { /* code 7535 */
  ___X____,________,
  XXXXXXXX,________,
  X__X___X,________,
  XXXXXXXX,________,
  X__X___X,________,
  X__X___X,________,
  XXXXXXXX,X_______,
  X__X____,X_______,
  ___XXXXX,________};

GUI_CONST_STORAGE unsigned char acGUI_FontCHS16_7A0B[ 22] = { /* code 7A0B */
  __XX____,________,
  XXX_XXXX,X_______,
  __X_X___,X_______,
  XXXXXXXX,X_______,
  __X_____,________,
  _XXXXXXX,XX______,
  _XXX__X_,________,
  X_X_XXXX,X_______,
  X_X___X_,________,
  __X_XXXX,XX______,
  __X_____,________};

GUI_CONST_STORAGE unsigned char acGUI_FontCHS16_7CFB[ 18] = { /* code 7CFB */
  ________,________,
  _XXXXXXX,X_______,
  ___X__XX,________,
  _XXXXX__,________,
  ___X__XX,________,
  _XXXXXXX,X_______,
  __X_X_X_,________,
  _X__X__X,________,
  X__XX___,X_______};

GUI_CONST_STORAGE unsigned char acGUI_FontCHS16_7EBF[ 18] = { /* code 7EBF */
  __X___X_,X_______,
  _X____X_,X_______,
  X__X__XX,XX______,
  XXX_XXX_,________,
  _X__XXXX,XX______,
  XXXX__X_,________,
  ______X_,X_______,
  XXXX__XX,_X______,
  ___XXX_X,XX______};

GUI_CONST_STORAGE unsigned char acGUI_FontCHS16_7EDF[ 18] = { /* code 7EDF */
  __X___XX,________,
  _X_XXXXX,XX______,
  X_X__XX_,________,
  XX__X___,X_______,
  X__XXXXX,XX______,
  XXX__X_X,________,
  _____X_X,_X______,
  XXXXX__X,_X______,
  ___X___X,XX______};

GUI_CONST_STORAGE unsigned char acGUI_FontCHS16_7F6E[ 18] = { /* code 7F6E */
  _XXXXXXX,X_______,
  _XXXXXXX,X_______,
  ____X___,________,
  XXXXXXXX,XX______,
  __XXXXXX,X_______,
  __XXXXXX,X_______,
  __XXXXXX,X_______,
  __XXXXXX,X_______,
  XXXXXXXX,XX______};

GUI_CONST_STORAGE unsigned char acGUI_FontCHS16_8BBE[ 18] = { /* code 8BBE */
  _X__XXXX,X_______,
  __X_X___,XX______,
  ___X____,________,
  XXX_____,________,
  __X_XXXX,X_______,
  __X_X___,X_______,
  __XX_X_X,________,
  _XX__XXX,________,
  ___XX___,XX______};

GUI_CONST_STORAGE unsigned char acGUI_FontCHS16_8D1F[ 18] = { /* code 8D1F */
  ___X____,________,
  __XXXXX_,________,
  _X___X__,________,
  XXXXXXXX,________,
  _X__X__X,________,
  _X__X__X,________,
  _X__X__X,________,
  ___X_XXX,________,
  XXX_____,X_______};

GUI_CONST_STORAGE unsigned char acGUI_FontCHS16_8F7D[ 18] = { /* code 8F7D */
  ___X__X_,X_______,
  XXXXXXX_,________,
  XXXXXXXX,XX______,
  __X___X_,________,
  XXXXXXX_,X_______,
  _X_X__XX,________,
  _XXXXX_X,_X______,
  XXXXXXXX,_X______,
  ___X_X__,XX______};

GUI_CONST_STORAGE unsigned char acGUI_FontCHS16_963B[ 18] = { /* code 963B */
  XXXXXXXX,________,
  X_XX___X,________,
  XX_X___X,________,
  XX_XXXXX,________,
  XX_X___X,________,
  X_XXXXXX,________,
  X_XX___X,________,
  XX_X___X,________,
  X_XXXXXX,X_______};

GUI_CONST_STORAGE GUI_CHARINFO_EXT GUI_FontCHS16_CharInfo[21] = {
   {  10,   9,   0,   4,  10, acGUI_FontCHS16_5145 } /* code 5145 */
  ,{  10,   9,   0,   4,  10, acGUI_FontCHS16_5173 } /* code 5173 */
  ,{   8,  10,   1,   3,  10, acGUI_FontCHS16_5185 } /* code 5185 */
  ,{  10,   9,   0,   4,  10, acGUI_FontCHS16_538B } /* code 538B */
  ,{   9,   9,   1,   4,  10, acGUI_FontCHS16_56FE } /* code 56FE */
  ,{   9,   9,   1,   4,  10, acGUI_FontCHS16_5F00 } /* code 5F00 */
  ,{   9,  10,   1,   3,  10, acGUI_FontCHS16_63A7 } /* code 63A7 */
  ,{  10,  10,   0,   3,  10, acGUI_FontCHS16_653E } /* code 653E */
  ,{   8,  11,   1,   3,  10, acGUI_FontCHS16_66F2 } /* code 66F2 */
  ,{  10,   9,   0,   4,  10, acGUI_FontCHS16_6D41 } /* code 6D41 */
  ,{  10,   9,   0,   4,  10, acGUI_FontCHS16_6E90 } /* code 6E90 */
  ,{   9,   9,   1,   4,  10, acGUI_FontCHS16_7535 } /* code 7535 */
  ,{  10,  11,   0,   3,  10, acGUI_FontCHS16_7A0B } /* code 7A0B */
  ,{   9,   9,   0,   4,  10, acGUI_FontCHS16_7CFB } /* code 7CFB */
  ,{  10,   9,   0,   4,  10, acGUI_FontCHS16_7EBF } /* code 7EBF */
  ,{  10,   9,   0,   4,  10, acGUI_FontCHS16_7EDF } /* code 7EDF */
  ,{  10,   9,   0,   4,  10, acGUI_FontCHS16_7F6E } /* code 7F6E */
  ,{  10,   9,   0,   4,  10, acGUI_FontCHS16_8BBE } /* code 8BBE */
  ,{   9,   9,   1,   4,  10, acGUI_FontCHS16_8D1F } /* code 8D1F */
  ,{  10,   9,   0,   4,  10, acGUI_FontCHS16_8F7D } /* code 8F7D */
  ,{   9,   9,   1,   4,  10, acGUI_FontCHS16_963B } /* code 963B */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontCHS16_Prop21 = {
   0x963B /* first character */
  ,0x963B /* last character  */
  ,&GUI_FontCHS16_CharInfo[ 20] /* address of first character */
  ,(GUI_CONST_STORAGE GUI_FONT_PROP_EXT *)0 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontCHS16_Prop20 = {
   0x8F7D /* first character */
  ,0x8F7D /* last character  */
  ,&GUI_FontCHS16_CharInfo[ 19] /* address of first character */
  ,&GUI_FontCHS16_Prop21 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontCHS16_Prop19 = {
   0x8D1F /* first character */
  ,0x8D1F /* last character  */
  ,&GUI_FontCHS16_CharInfo[ 18] /* address of first character */
  ,&GUI_FontCHS16_Prop20 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontCHS16_Prop18 = {
   0x8BBE /* first character */
  ,0x8BBE /* last character  */
  ,&GUI_FontCHS16_CharInfo[ 17] /* address of first character */
  ,&GUI_FontCHS16_Prop19 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontCHS16_Prop17 = {
   0x7F6E /* first character */
  ,0x7F6E /* last character  */
  ,&GUI_FontCHS16_CharInfo[ 16] /* address of first character */
  ,&GUI_FontCHS16_Prop18 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontCHS16_Prop16 = {
   0x7EDF /* first character */
  ,0x7EDF /* last character  */
  ,&GUI_FontCHS16_CharInfo[ 15] /* address of first character */
  ,&GUI_FontCHS16_Prop17 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontCHS16_Prop15 = {
   0x7EBF /* first character */
  ,0x7EBF /* last character  */
  ,&GUI_FontCHS16_CharInfo[ 14] /* address of first character */
  ,&GUI_FontCHS16_Prop16 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontCHS16_Prop14 = {
   0x7CFB /* first character */
  ,0x7CFB /* last character  */
  ,&GUI_FontCHS16_CharInfo[ 13] /* address of first character */
  ,&GUI_FontCHS16_Prop15 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontCHS16_Prop13 = {
   0x7A0B /* first character */
  ,0x7A0B /* last character  */
  ,&GUI_FontCHS16_CharInfo[ 12] /* address of first character */
  ,&GUI_FontCHS16_Prop14 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontCHS16_Prop12 = {
   0x7535 /* first character */
  ,0x7535 /* last character  */
  ,&GUI_FontCHS16_CharInfo[ 11] /* address of first character */
  ,&GUI_FontCHS16_Prop13 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontCHS16_Prop11 = {
   0x6E90 /* first character */
  ,0x6E90 /* last character  */
  ,&GUI_FontCHS16_CharInfo[ 10] /* address of first character */
  ,&GUI_FontCHS16_Prop12 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontCHS16_Prop10 = {
   0x6D41 /* first character */
  ,0x6D41 /* last character  */
  ,&GUI_FontCHS16_CharInfo[  9] /* address of first character */
  ,&GUI_FontCHS16_Prop11 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontCHS16_Prop9 = {
   0x66F2 /* first character */
  ,0x66F2 /* last character  */
  ,&GUI_FontCHS16_CharInfo[  8] /* address of first character */
  ,&GUI_FontCHS16_Prop10 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontCHS16_Prop8 = {
   0x653E /* first character */
  ,0x653E /* last character  */
  ,&GUI_FontCHS16_CharInfo[  7] /* address of first character */
  ,&GUI_FontCHS16_Prop9 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontCHS16_Prop7 = {
   0x63A7 /* first character */
  ,0x63A7 /* last character  */
  ,&GUI_FontCHS16_CharInfo[  6] /* address of first character */
  ,&GUI_FontCHS16_Prop8 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontCHS16_Prop6 = {
   0x5F00 /* first character */
  ,0x5F00 /* last character  */
  ,&GUI_FontCHS16_CharInfo[  5] /* address of first character */
  ,&GUI_FontCHS16_Prop7 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontCHS16_Prop5 = {
   0x56FE /* first character */
  ,0x56FE /* last character  */
  ,&GUI_FontCHS16_CharInfo[  4] /* address of first character */
  ,&GUI_FontCHS16_Prop6 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontCHS16_Prop4 = {
   0x538B /* first character */
  ,0x538B /* last character  */
  ,&GUI_FontCHS16_CharInfo[  3] /* address of first character */
  ,&GUI_FontCHS16_Prop5 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontCHS16_Prop3 = {
   0x5185 /* first character */
  ,0x5185 /* last character  */
  ,&GUI_FontCHS16_CharInfo[  2] /* address of first character */
  ,&GUI_FontCHS16_Prop4 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontCHS16_Prop2 = {
   0x5173 /* first character */
  ,0x5173 /* last character  */
  ,&GUI_FontCHS16_CharInfo[  1] /* address of first character */
  ,&GUI_FontCHS16_Prop3 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontCHS16_Prop1 = {
   0x5145 /* first character */
  ,0x5145 /* last character  */
  ,&GUI_FontCHS16_CharInfo[  0] /* address of first character */
  ,&GUI_FontCHS16_Prop2 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT GUI_FontCHS16 = {
   GUI_FONTTYPE_PROP_EXT /* type of font    */
  ,16 /* height of font  */
  ,16 /* space of font y */
  ,1 /* magnification x */
  ,1 /* magnification y */
  ,{&GUI_FontCHS16_Prop1}
  ,12 /* Baseline */
  ,5 /* Height of lowercase characters */
  ,8 /* Height of capital characters */
};

