/*********************************************************************
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                           www.segger.com                           *
**********************************************************************
*                                                                    *
* C-file generated by                                                *
*                                                                    *
*        Font converter for emWin version 5.22                       *
*        Compiled Jul  4 2013, 12:18:44                              *
*        (C) 1998 - 2013 Segger Microcontroller GmbH & Co. KG
*                                                                    *
**********************************************************************
*                                                                    *
* Source file: HZ12.c                                                *
* Font:        宋体                                                  *
* Height:      12                                                    *
*                                                                    *
**********************************************************************
*                                                                    *
* Initial font height:  12                                           *
* Range disabled:       0000 - FFFF                                  *
* Read pattern file: C:\Users\Administrator\Desktop\hz.txt           *
*                                                                    *
**********************************************************************
*/

#include "GUI.h"

#ifndef GUI_CONST_STORAGE
  #define GUI_CONST_STORAGE const
#endif

/* The following line needs to be included in any file selecting the
   font.
*/
extern GUI_CONST_STORAGE GUI_FONT GUI_FontHZ12;

/* Start of unicode area <CJK Unified Ideographs> */
GUI_CONST_STORAGE unsigned char acGUI_FontHZ12_4E2D[ 24] = { /* code 4E2D */
  ____X___,________,
  ____X___,________,
  ____X___,________,
  XXXXXXXX,X_______,
  X___X___,X_______,
  X___X___,X_______,
  X___X___,X_______,
  XXXXXXXX,X_______,
  X___X___,X_______,
  ____X___,________,
  ____X___,________,
  ____X___,________};

GUI_CONST_STORAGE unsigned char acGUI_FontHZ12_4E3B[ 24] = { /* code 4E3B */
  ____X___,________,
  _____X__,________,
  ________,________,
  _XXXXXXX,XX______,
  _____X__,________,
  _____X__,________,
  _____X__,________,
  _XXXXXXX,XX______,
  _____X__,________,
  _____X__,________,
  _____X__,________,
  XXXXXXXX,XXX_____};

GUI_CONST_STORAGE unsigned char acGUI_FontHZ12_4FDD[ 24] = { /* code 4FDD */
  ___X____,________,
  ___X_XXX,XX______,
  __X__X__,_X______,
  __X__X__,_X______,
  _XX__XXX,XX______,
  X_X____X,________,
  __X_XXXX,XXX_____,
  __X____X,________,
  __X___XX,X_______,
  __X__X_X,_X______,
  __X_X__X,__X_____,
  __X____X,________};

GUI_CONST_STORAGE unsigned char acGUI_FontHZ12_503C[ 24] = { /* code 503C */
  __X___X_,________,
  __X_XXXX,XXX_____,
  _X____X_,________,
  _X__XXXX,XX______,
  XX__X___,_X______,
  _X__XXXX,XX______,
  _X__X___,_X______,
  _X__XXXX,XX______,
  _X__X___,_X______,
  _X__XXXX,XX______,
  _X__X___,_X______,
  _X_XXXXX,XXX_____};

GUI_CONST_STORAGE unsigned char acGUI_FontHZ12_505C[ 24] = { /* code 505C */
  ___X___X,________,
  ___XXXXX,XXX_____,
  __X_____,________,
  __X__XXX,XX______,
  _XX__X__,_X______,
  X_X__XXX,XX______,
  __X_____,________,
  __X_XXXX,XXX_____,
  __X_X___,__X_____,
  __X__XXX,XX______,
  __X____X,________,
  __X___XX,________};

GUI_CONST_STORAGE unsigned char acGUI_FontHZ12_5145[ 24] = { /* code 5145 */
  ____X___,________,
  _____X__,________,
  XXXXXXXX,XXX_____,
  ____X___,________,
  ___X___X,________,
  __X_____,X_______,
  _XXXXXXX,XX______,
  ___X___X,_X______,
  ___X___X,________,
  ___X___X,__X_____,
  __X____X,__X_____,
  XX______,XXX_____};

GUI_CONST_STORAGE unsigned char acGUI_FontHZ12_5173[ 24] = { /* code 5173 */
  __X_____,X_______,
  ___X___X,________,
  ________,________,
  _XXXXXXX,XX______,
  _____X__,________,
  _____X__,________,
  XXXXXXXX,XXX_____,
  _____X__,________,
  ____X_X_,________,
  ___X___X,________,
  __X_____,X_______,
  XX______,_XX_____};

GUI_CONST_STORAGE unsigned char acGUI_FontHZ12_5185[ 24] = { /* code 5185 */
  ____X___,________,
  ____X___,________,
  XXXXXXXX,X_______,
  X___X___,X_______,
  X___X___,X_______,
  X__X_X__,X_______,
  X__X__X_,X_______,
  X_X___X_,X_______,
  X_______,X_______,
  X_______,X_______,
  X_______,X_______,
  X_____XX,X_______};

GUI_CONST_STORAGE unsigned char acGUI_FontHZ12_5217[ 24] = { /* code 5217 */
  ________,__X_____,
  XXXXXX__,__X_____,
  __X____X,__X_____,
  __X____X,__X_____,
  __XXXX_X,__X_____,
  _X___X_X,__X_____,
  X_X__X_X,__X_____,
  ___X_X_X,__X_____,
  ____X__X,__X_____,
  ___X____,__X_____,
  __X_____,__X_____,
  _X______,XXX_____};

GUI_CONST_STORAGE unsigned char acGUI_FontHZ12_52A8[ 24] = { /* code 52A8 */
  _______X,________,
  _XXX___X,________,
  _______X,________,
  ______XX,XXX_____,
  XXXXX__X,__X_____,
  __X____X,__X_____,
  _X_____X,__X_____,
  _X_X___X,__X_____,
  X___X__X,__X_____,
  XXXXX_X_,__X_____,
  ______X_,__X_____,
  _____X__,XX______};

GUI_CONST_STORAGE unsigned char acGUI_FontHZ12_5355[ 24] = { /* code 5355 */
  __X_____,X_______,
  ___X___X,________,
  _XXXXXXX,XX______,
  _X___X__,_X______,
  _XXXXXXX,XX______,
  _X___X__,_X______,
  _XXXXXXX,XX______,
  _____X__,________,
  XXXXXXXX,XXX_____,
  _____X__,________,
  _____X__,________,
  _____X__,________};

GUI_CONST_STORAGE unsigned char acGUI_FontHZ12_538B[ 22] = { /* code 538B */
  _XXXXXXX,XXX_____,
  _X______,________,
  _X____X_,________,
  _X____X_,________,
  _X____X_,________,
  _X_XXXXX,XX______,
  _X____X_,________,
  _X____X_,X_______,
  _X____X_,_X______,
  _X____X_,________,
  X_XXXXXX,XXX_____};

GUI_CONST_STORAGE unsigned char acGUI_FontHZ12_53D6[ 22] = { /* code 53D6 */
  XXXXXX__,________,
  _X__X_XX,XX______,
  _X__X__X,_X______,
  _XXXX__X,_X______,
  _X__X__X,_X______,
  _XXXX__X,_X______,
  _X__X__X,_X______,
  _X__XX__,X_______,
  XXXXX___,X_______,
  ____X__X,_X______,
  ____X_X_,__X_____};

GUI_CONST_STORAGE unsigned char acGUI_FontHZ12_53F7[ 24] = { /* code 53F7 */
  __XXXXXX,X_______,
  __X_____,X_______,
  __X_____,X_______,
  __XXXXXX,X_______,
  ________,________,
  XXXXXXXX,XXX_____,
  ___X____,________,
  __X_____,________,
  __XXXXXX,XX______,
  ________,_X______,
  ________,_X______,
  _______X,X_______};

GUI_CONST_STORAGE unsigned char acGUI_FontHZ12_5426[ 24] = { /* code 5426 */
  XXXXXXXX,XXX_____,
  _____X__,________,
  ____XX_X,X_______,
  __XX_X__,_X______,
  XX___X__,__X_____,
  _____X__,________,
  ________,________,
  _XXXXXXX,XX______,
  _X______,_X______,
  _X______,_X______,
  _XXXXXXX,XX______,
  _X______,_X______};

GUI_CONST_STORAGE unsigned char acGUI_FontHZ12_59CB[ 24] = { /* code 59CB */
  __X____X,________,
  __X____X,________,
  __X___X_,________,
  XXXX_X__,_X______,
  _X_X_XXX,XXX_____,
  _X_X____,__X_____,
  _X_X_XXX,XX______,
  X__X_X__,_X______,
  _X_X_X__,_X______,
  __X__X__,_X______,
  _X_X_XXX,XX______,
  X__X_X__,_X______};

GUI_CONST_STORAGE unsigned char acGUI_FontHZ12_5B50[ 22] = { /* code 5B50 */
  __XXXXXX,X_______,
  _______X,________,
  ______X_,________,
  _____X__,________,
  _____X__,________,
  XXXXXXXX,XXX_____,
  _____X__,________,
  _____X__,________,
  _____X__,________,
  _____X__,________,
  ___XXX__,________};

GUI_CONST_STORAGE unsigned char acGUI_FontHZ12_5B58[ 24] = { /* code 5B58 */
  ____X___,________,
  ____X___,________,
  XXXXXXXX,XXX_____,
  ___X____,________,
  __X__XXX,XX______,
  __X_____,X_______,
  _XX____X,________,
  X_X_XXXX,XXX_____,
  __X____X,________,
  __X____X,________,
  __X____X,________,
  __X___XX,________};

GUI_CONST_STORAGE unsigned char acGUI_FontHZ12_5B9A[ 24] = { /* code 5B9A */
  ____X___,________,
  _____X__,________,
  XXXXXXXX,XXX_____,
  X_______,__X_____,
  ________,________,
  XXXXXXXX,XXX_____,
  _____X__,________,
  __X__X__,________,
  __X__XXX,XX______,
  __X__X__,________,
  _X_X_X__,________,
  X___XXXX,XXX_____};

GUI_CONST_STORAGE unsigned char acGUI_FontHZ12_5F00[ 22] = { /* code 5F00 */
  _XXXXXXX,XX______,
  ___X___X,________,
  ___X___X,________,
  ___X___X,________,
  ___X___X,________,
  XXXXXXXX,XXX_____,
  ___X___X,________,
  ___X___X,________,
  __X____X,________,
  __X____X,________,
  _X_____X,________};

GUI_CONST_STORAGE unsigned char acGUI_FontHZ12_5F0F[ 24] = { /* code 5F0F */
  _______X,_X______,
  _______X,__X_____,
  _______X,________,
  XXXXXXXX,XXX_____,
  _______X,________,
  _______X,________,
  _XXXXX_X,________,
  ___X___X,________,
  ___X____,X_______,
  ___X____,X_X_____,
  ___XXXX_,_XX_____,
  XXX_____,__X_____};

GUI_CONST_STORAGE unsigned char acGUI_FontHZ12_6001[ 24] = { /* code 6001 */
  _____X__,________,
  _____X__,________,
  XXXXXXXX,XXX_____,
  ____X_X_,________,
  ___X___X,________,
  __X__X__,X_______,
  XX____X_,_XX_____,
  _____X__,________,
  _X_X__X_,_X______,
  _X_X__X_,__X_____,
  X__X____,X_X_____,
  ____XXXX,X_______};

GUI_CONST_STORAGE unsigned char acGUI_FontHZ12_62A4[ 24] = { /* code 62A4 */
  __X____X,________,
  __X_____,X_______,
  __X__XXX,XXX_____,
  XXXX_X__,__X_____,
  __X__X__,__X_____,
  __X__X__,__X_____,
  __XX_XXX,XXX_____,
  XXX__X__,__X_____,
  __X__X__,________,
  __X__X__,________,
  __X__X__,________,
  _XX_X___,________};

GUI_CONST_STORAGE unsigned char acGUI_FontHZ12_63A7[ 24] = { /* code 63A7 */
  _X____X_,________,
  _X_____X,________,
  _X__XXXX,XXX_____,
  XXX_X___,__X_____,
  _X____X_,X_______,
  _X___X__,_X______,
  _XX_X___,__X_____,
  XX___XXX,XX______,
  _X_____X,________,
  _X_____X,________,
  _X_____X,________,
  XX__XXXX,XXX_____};

GUI_CONST_STORAGE unsigned char acGUI_FontHZ12_653E[ 24] = { /* code 653E */
  _X_____X,________,
  __X____X,________,
  _______X,________,
  XXXXX__X,XXX_____,
  _X____X_,_X______,
  _X___X_X,_X______,
  _XXXX__X,_X______,
  _X__X__X,_X______,
  _X__X__X,_X______,
  _X__X___,X_______,
  _X__X__X,_X______,
  X__XX_X_,__X_____};

GUI_CONST_STORAGE unsigned char acGUI_FontHZ12_6587[ 24] = { /* code 6587 */
  ____X___,________,
  _____X__,________,
  XXXXXXXX,XXX_____,
  __X_____,X_______,
  __X_____,X_______,
  ___X___X,________,
  ___X___X,________,
  ____X_X_,________,
  _____X__,________,
  ____X_X_,________,
  __XX___X,X_______,
  XX______,_XX_____};

GUI_CONST_STORAGE unsigned char acGUI_FontHZ12_662F[ 24] = { /* code 662F */
  __XXXXXX,X_______,
  __X_____,X_______,
  __XXXXXX,X_______,
  __X_____,X_______,
  __XXXXXX,X_______,
  ________,________,
  XXXXXXXX,XXX_____,
  _____X__,________,
  __X__XXX,XX______,
  __X__X__,________,
  _X_X_X__,________,
  X___XXXX,XXX_____};

GUI_CONST_STORAGE unsigned char acGUI_FontHZ12_66F2[ 24] = { /* code 66F2 */
  ___X__X_,________,
  ___X__X_,________,
  XXXXXXXX,XX______,
  X__X__X_,_X______,
  X__X__X_,_X______,
  X__X__X_,_X______,
  XXXXXXXX,XX______,
  X__X__X_,_X______,
  X__X__X_,_X______,
  X__X__X_,_X______,
  XXXXXXXX,XX______,
  X_______,_X______};

GUI_CONST_STORAGE unsigned char acGUI_FontHZ12_679C[ 22] = { /* code 679C */
  _XXXXXXX,XX______,
  _X___X__,_X______,
  _XXXXXXX,XX______,
  _X___X__,_X______,
  _XXXXXXX,XX______,
  _____X__,________,
  XXXXXXXX,XXX_____,
  ___X_X_X,________,
  __X__X__,X_______,
  XX___X__,_XX_____,
  _____X__,________};

GUI_CONST_STORAGE unsigned char acGUI_FontHZ12_6A21[ 24] = { /* code 6A21 */
  __X___X_,X_______,
  __X_XXXX,XXX_____,
  __X___X_,X_______,
  XXXX_XXX,XX______,
  __X__X__,_X______,
  _XX__XXX,XX______,
  _XXX_X__,_X______,
  X_X__XXX,XX______,
  __X____X,________,
  __X_XXXX,XXX_____,
  __X___X_,X_______,
  __X_XX__,_XX_____};

GUI_CONST_STORAGE unsigned char acGUI_FontHZ12_6B62[ 24] = { /* code 6B62 */
  ______X_,________,
  ______X_,________,
  ______X_,________,
  __X___X_,________,
  __X___XX,XX______,
  __X___X_,________,
  __X___X_,________,
  __X___X_,________,
  __X___X_,________,
  __X___X_,________,
  __X___X_,________,
  XXXXXXXX,XXX_____};

GUI_CONST_STORAGE unsigned char acGUI_FontHZ12_6D41[ 24] = { /* code 6D41 */
  ______X_,________,
  X______X,________,
  _X_XXXXX,XXX_____,
  _____X__,________,
  ____X___,_X______,
  X__XXXXX,XXX_____,
  _X______,__X_____,
  ____X_X_,X_______,
  ____X_X_,X_______,
  _X__X_X_,X_X_____,
  X__X__X_,X_X_____,
  __X___X_,_XX_____};

GUI_CONST_STORAGE unsigned char acGUI_FontHZ12_6D4B[ 24] = { /* code 6D4B */
  ________,__X_____,
  X_XXXXX_,__X_____,
  _XX___X_,X_X_____,
  __X_X_X_,X_X_____,
  __X_X_X_,X_X_____,
  X_X_X_X_,X_X_____,
  _XX_X_X_,X_X_____,
  __X_X_X_,X_X_____,
  __X_X_X_,X_X_____,
  _X__X___,__X_____,
  X__X_X__,__X_____,
  __X___X_,_XX_____};

GUI_CONST_STORAGE unsigned char acGUI_FontHZ12_6E90[ 24] = { /* code 6E90 */
  X__XXXXX,XXX_____,
  _X_X___X,________,
  ___X__X_,________,
  ___X_XXX,XX______,
  X__X_X__,_X______,
  _X_X_XXX,XX______,
  ___X_X__,_X______,
  ___X_XXX,XX______,
  ___X___X,________,
  _X_X_X_X,_X______,
  X__XX__X,__X_____,
  __X___XX,________};

GUI_CONST_STORAGE unsigned char acGUI_FontHZ12_7535[ 24] = { /* code 7535 */
  ____X___,________,
  ____X___,________,
  XXXXXXXX,X_______,
  X___X___,X_______,
  X___X___,X_______,
  XXXXXXXX,X_______,
  X___X___,X_______,
  X___X___,X_______,
  XXXXXXXX,X_______,
  X___X___,__X_____,
  ____X___,__X_____,
  _____XXX,XXX_____};

GUI_CONST_STORAGE unsigned char acGUI_FontHZ12_786E[ 24] = { /* code 786E */
  ______X_,________,
  XXXX__XX,XX______,
  __X__X__,_X______,
  __X_____,X_______,
  _X___XXX,XXX_____,
  _XXX_X_X,__X_____,
  XX_X_XXX,XXX_____,
  _X_X_X_X,__X_____,
  _X_X_XXX,XXX_____,
  _XXX_X_X,__X_____,
  _X_X_X_X,__X_____,
  ____X___,_XX_____};

GUI_CONST_STORAGE unsigned char acGUI_FontHZ12_7A0B[ 24] = { /* code 7A0B */
  ___X_XXX,XX______,
  XXX__X__,_X______,
  __X__X__,_X______,
  __X__XXX,XX______,
  XXXX____,________,
  __X__XXX,XX______,
  _XXX___X,________,
  _XX_X__X,________,
  X_X__XXX,XX______,
  __X____X,________,
  __X____X,________,
  __X_XXXX,XXX_____};

GUI_CONST_STORAGE unsigned char acGUI_FontHZ12_7C7B[ 24] = { /* code 7C7B */
  _____X__,________,
  __X__X__,X_______,
  ___X_X_X,________,
  XXXXXXXX,XXX_____,
  ___X_X_X,________,
  __X__X__,X_______,
  _X______,_X______,
  _____X__,________,
  XXXXXXXX,XXX_____,
  ____X_X_,________,
  __XX___X,X_______,
  XX______,_XX_____};

GUI_CONST_STORAGE unsigned char acGUI_FontHZ12_7CFB[ 24] = { /* code 7CFB */
  ______XX,XX______,
  _XXXXX__,________,
  ____X___,________,
  ___X____,X_______,
  __XXXXXX,________,
  _____XX_,________,
  ___XX___,_X______,
  _XXXXXXX,XXX_____,
  _____X__,__X_____,
  __X__X__,X_______,
  _X___X__,_X______,
  X___XX__,__X_____};

GUI_CONST_STORAGE unsigned char acGUI_FontHZ12_7EBF[ 24] = { /* code 7EBF */
  __X____X,_X______,
  __X____X,__X_____,
  _X_____X,XXX_____,
  X__X_XXX,________,
  XXX____X,________,
  __X____X,XXX_____,
  _X___XXX,________,
  XXXX___X,_X______,
  _______X,X_______,
  __XX___X,__X_____,
  XX____X_,X_X_____,
  ____XX__,_XX_____};

GUI_CONST_STORAGE unsigned char acGUI_FontHZ12_7ED3[ 24] = { /* code 7ED3 */
  __X____X,________,
  __X____X,________,
  _X__XXXX,XXX_____,
  X__X___X,________,
  XXX____X,________,
  __X__XXX,XX______,
  _X______,________,
  XXXX_XXX,XX______,
  _____X__,_X______,
  __XX_X__,_X______,
  XX___XXX,XX______,
  _____X__,_X______};

GUI_CONST_STORAGE unsigned char acGUI_FontHZ12_7EDF[ 24] = { /* code 7EDF */
  __X____X,________,
  __X_____,X_______,
  _X___XXX,XXX_____,
  X__X___X,________,
  XXX___X_,_X______,
  __X__X__,__X_____,
  _X___XXX,XXX_____,
  XXXX__X_,X_X_____,
  ______X_,X_______,
  __XX__X_,X_______,
  XX___X__,X_X_____,
  ____X___,_XX_____};

GUI_CONST_STORAGE unsigned char acGUI_FontHZ12_7F6E[ 24] = { /* code 7F6E */
  _XXXXXXX,XX______,
  _X__X_X_,_X______,
  _XXXXXXX,XX______,
  _____X__,________,
  XXXXXXXX,XXX_____,
  _____X__,________,
  __XXXXXX,X_______,
  __X_____,X_______,
  __X_____,X_______,
  __X__X__,X_______,
  __X__X__,X_______,
  XXXXXXXX,XXX_____};

GUI_CONST_STORAGE unsigned char acGUI_FontHZ12_81EA[ 24] = { /* code 81EA */
  ____X___,________,
  ___X____,________,
  XXXXXXXX,X_______,
  X_______,X_______,
  X_______,X_______,
  XXXXXXXX,X_______,
  X_______,X_______,
  X_______,X_______,
  XXXXXXXX,X_______,
  X_______,X_______,
  X_______,X_______,
  XXXXXXXX,X_______};

GUI_CONST_STORAGE unsigned char acGUI_FontHZ12_82F1[ 24] = { /* code 82F1 */
  ___X___X,________,
  XXXXXXXX,XXX_____,
  ___X___X,________,
  _____X__,________,
  _XXXXXXX,XX______,
  _X___X__,_X______,
  _X___X__,_X______,
  _X___X__,_X______,
  XXXXXXXX,XXX_____,
  ____X_X_,________,
  __XX___X,X_______,
  XX______,_XX_____};

GUI_CONST_STORAGE unsigned char acGUI_FontHZ12_83DC[ 24] = { /* code 83DC */
  ___X___X,________,
  XXXXXXXX,XXX_____,
  ___X___X,________,
  _______X,XX______,
  XXXXXXX_,________,
  _X__X___,X_______,
  __X__X_X,________,
  _____X__,________,
  XXXXXXXX,XXX_____,
  ___X_X_X,________,
  __X__X__,X_______,
  XX___X__,_XX_____};

GUI_CONST_STORAGE unsigned char acGUI_FontHZ12_8868[ 24] = { /* code 8868 */
  _____X__,________,
  _____X__,________,
  _XXXXXXX,XX______,
  _____X__,________,
  __XXXXXX,X_______,
  _____X__,________,
  XXXXXXXX,XXX_____,
  ____X_X_,________,
  ___X__X_,__X_____,
  __XX___X,_X______,
  XX_X_X__,X_______,
  ___XX___,_XX_____};

GUI_CONST_STORAGE unsigned char acGUI_FontHZ12_8A00[ 24] = { /* code 8A00 */
  ____X___,________,
  _____X__,________,
  XXXXXXXX,XXX_____,
  ________,________,
  _XXXXXXX,XX______,
  ________,________,
  _XXXXXXX,XX______,
  ________,________,
  _XXXXXXX,XX______,
  _X______,_X______,
  _XXXXXXX,XX______,
  _X______,_X______};

GUI_CONST_STORAGE unsigned char acGUI_FontHZ12_8BBE[ 24] = { /* code 8BBE */
  _X___XXX,X_______,
  __X__X__,X_______,
  _____X__,X_______,
  _____X__,X_______,
  XXX_X___,_XX_____,
  __X_____,________,
  __X_XXXX,XX______,
  __X__X__,_X______,
  __X___X_,X_______,
  __XX___X,________,
  __X___X_,X_______,
  ____XX__,_XX_____};

GUI_CONST_STORAGE unsigned char acGUI_FontHZ12_8BD5[ 24] = { /* code 8BD5 */
  X_______,X_X_____,
  _X______,X_______,
  ____XXXX,XXX_____,
  ________,X_______,
  XX______,X_______,
  _X__XXX_,X_______,
  _X___X__,X_______,
  _X___X__,X_______,
  _X___X__,X_______,
  _X___XX_,X_X_____,
  _XX_XX__,_XX_____,
  _X______,__X_____};

GUI_CONST_STORAGE unsigned char acGUI_FontHZ12_8BED[ 24] = { /* code 8BED */
  X__XXXXX,XXX_____,
  _X____X_,________,
  ____XXXX,XX______,
  _____X__,_X______,
  XX___X__,_X______,
  _X_XXXXX,XXX_____,
  _X______,________,
  _X__XXXX,XX______,
  _X__X___,_X______,
  _XX_X___,_X______,
  _X__XXXX,XX______,
  ____X___,_X______};

GUI_CONST_STORAGE unsigned char acGUI_FontHZ12_8BFB[ 24] = { /* code 8BFB */
  X_____X_,________,
  _X__XXXX,XX______,
  ______X_,________,
  ___XXXXX,XXX_____,
  XX______,__X_____,
  _X___X_X,________,
  _X_X__XX,________,
  _X__X__X,________,
  _X_XXXXX,XXX_____,
  _XX___X_,X_______,
  _X___X__,_X______,
  ___XX___,__X_____};

GUI_CONST_STORAGE unsigned char acGUI_FontHZ12_8D1F[ 24] = { /* code 8D1F */
  __X_____,________,
  __XXXXXX,________,
  _X_____X,________,
  X_____X_,________,
  _XXXXXXX,XX______,
  _X______,_X______,
  _X___X__,_X______,
  _X___X__,_X______,
  _X___X__,_X______,
  ____X_XX,________,
  __XX____,XX______,
  XX______,__X_____};

GUI_CONST_STORAGE unsigned char acGUI_FontHZ12_8F7D[ 24] = { /* code 8F7D */
  ___X___X,_X______,
  _XXXXX_X,__X_____,
  ___X___X,________,
  XXXXXXXX,XXX_____,
  __X____X,________,
  XXXXXX_X,_X______,
  _X_X___X,_X______,
  _XXXXX_X,_X______,
  ___X____,X_______,
  ___XXX__,X_X_____,
  XXXX___X,_XX_____,
  ___X__X_,__X_____};

GUI_CONST_STORAGE unsigned char acGUI_FontHZ12_8FC7[ 24] = { /* code 8FC7 */
  _X______,_X______,
  __X_____,_X______,
  ________,_X______,
  ____XXXX,XXX_____,
  XXX_____,_X______,
  __X__X__,_X______,
  __X___X_,_X______,
  __X___X_,_X______,
  __X_____,_X______,
  __X____X,XX______,
  _X_X____,________,
  X___XXXX,XXX_____};

GUI_CONST_STORAGE unsigned char acGUI_FontHZ12_963B[ 22] = { /* code 963B */
  XXXX_XXX,XX______,
  X__X_X__,_X______,
  X__X_X__,_X______,
  X_X__XXX,XX______,
  X_X__X__,_X______,
  X__X_X__,_X______,
  X__X_XXX,XX______,
  X__X_X__,_X______,
  XXX__X__,_X______,
  X____X__,_X______,
  X___XXXX,XXX_____};

GUI_CONST_STORAGE GUI_CHARINFO_EXT GUI_FontHZ12_CharInfo[56] = {
   {   9,  12,   1,   0,  12, acGUI_FontHZ12_4E2D } /* code 4E2D */
  ,{  11,  12,   0,   0,  12, acGUI_FontHZ12_4E3B } /* code 4E3B */
  ,{  11,  12,   0,   0,  12, acGUI_FontHZ12_4FDD } /* code 4FDD */
  ,{  11,  12,   0,   0,  12, acGUI_FontHZ12_503C } /* code 503C */
  ,{  11,  12,   0,   0,  12, acGUI_FontHZ12_505C } /* code 505C */
  ,{  11,  12,   0,   0,  12, acGUI_FontHZ12_5145 } /* code 5145 */
  ,{  11,  12,   0,   0,  12, acGUI_FontHZ12_5173 } /* code 5173 */
  ,{   9,  12,   1,   0,  12, acGUI_FontHZ12_5185 } /* code 5185 */
  ,{  11,  12,   0,   0,  12, acGUI_FontHZ12_5217 } /* code 5217 */
  ,{  11,  12,   0,   0,  12, acGUI_FontHZ12_52A8 } /* code 52A8 */
  ,{  11,  12,   0,   0,  12, acGUI_FontHZ12_5355 } /* code 5355 */
  ,{  11,  11,   0,   1,  12, acGUI_FontHZ12_538B } /* code 538B */
  ,{  11,  11,   0,   1,  12, acGUI_FontHZ12_53D6 } /* code 53D6 */
  ,{  11,  12,   0,   0,  12, acGUI_FontHZ12_53F7 } /* code 53F7 */
  ,{  11,  12,   0,   0,  12, acGUI_FontHZ12_5426 } /* code 5426 */
  ,{  11,  12,   0,   0,  12, acGUI_FontHZ12_59CB } /* code 59CB */
  ,{  11,  11,   0,   1,  12, acGUI_FontHZ12_5B50 } /* code 5B50 */
  ,{  11,  12,   0,   0,  12, acGUI_FontHZ12_5B58 } /* code 5B58 */
  ,{  11,  12,   0,   0,  12, acGUI_FontHZ12_5B9A } /* code 5B9A */
  ,{  11,  11,   0,   1,  12, acGUI_FontHZ12_5F00 } /* code 5F00 */
  ,{  11,  12,   0,   0,  12, acGUI_FontHZ12_5F0F } /* code 5F0F */
  ,{  11,  12,   0,   0,  12, acGUI_FontHZ12_6001 } /* code 6001 */
  ,{  11,  12,   0,   0,  12, acGUI_FontHZ12_62A4 } /* code 62A4 */
  ,{  11,  12,   0,   0,  12, acGUI_FontHZ12_63A7 } /* code 63A7 */
  ,{  11,  12,   0,   0,  12, acGUI_FontHZ12_653E } /* code 653E */
  ,{  11,  12,   0,   0,  12, acGUI_FontHZ12_6587 } /* code 6587 */
  ,{  11,  12,   0,   0,  12, acGUI_FontHZ12_662F } /* code 662F */
  ,{  10,  12,   1,   0,  12, acGUI_FontHZ12_66F2 } /* code 66F2 */
  ,{  11,  11,   0,   1,  12, acGUI_FontHZ12_679C } /* code 679C */
  ,{  11,  12,   0,   0,  12, acGUI_FontHZ12_6A21 } /* code 6A21 */
  ,{  11,  12,   0,   0,  12, acGUI_FontHZ12_6B62 } /* code 6B62 */
  ,{  11,  12,   0,   0,  12, acGUI_FontHZ12_6D41 } /* code 6D41 */
  ,{  11,  12,   0,   0,  12, acGUI_FontHZ12_6D4B } /* code 6D4B */
  ,{  11,  12,   0,   0,  12, acGUI_FontHZ12_6E90 } /* code 6E90 */
  ,{  11,  12,   0,   0,  12, acGUI_FontHZ12_7535 } /* code 7535 */
  ,{  11,  12,   0,   0,  12, acGUI_FontHZ12_786E } /* code 786E */
  ,{  11,  12,   0,   0,  12, acGUI_FontHZ12_7A0B } /* code 7A0B */
  ,{  11,  12,   0,   0,  12, acGUI_FontHZ12_7C7B } /* code 7C7B */
  ,{  11,  12,   0,   0,  12, acGUI_FontHZ12_7CFB } /* code 7CFB */
  ,{  11,  12,   0,   0,  12, acGUI_FontHZ12_7EBF } /* code 7EBF */
  ,{  11,  12,   0,   0,  12, acGUI_FontHZ12_7ED3 } /* code 7ED3 */
  ,{  11,  12,   0,   0,  12, acGUI_FontHZ12_7EDF } /* code 7EDF */
  ,{  11,  12,   0,   0,  12, acGUI_FontHZ12_7F6E } /* code 7F6E */
  ,{   9,  12,   1,   0,  12, acGUI_FontHZ12_81EA } /* code 81EA */
  ,{  11,  12,   0,   0,  12, acGUI_FontHZ12_82F1 } /* code 82F1 */
  ,{  11,  12,   0,   0,  12, acGUI_FontHZ12_83DC } /* code 83DC */
  ,{  11,  12,   0,   0,  12, acGUI_FontHZ12_8868 } /* code 8868 */
  ,{  11,  12,   0,   0,  12, acGUI_FontHZ12_8A00 } /* code 8A00 */
  ,{  11,  12,   0,   0,  12, acGUI_FontHZ12_8BBE } /* code 8BBE */
  ,{  11,  12,   0,   0,  12, acGUI_FontHZ12_8BD5 } /* code 8BD5 */
  ,{  11,  12,   0,   0,  12, acGUI_FontHZ12_8BED } /* code 8BED */
  ,{  11,  12,   0,   0,  12, acGUI_FontHZ12_8BFB } /* code 8BFB */
  ,{  11,  12,   0,   0,  12, acGUI_FontHZ12_8D1F } /* code 8D1F */
  ,{  11,  12,   0,   0,  12, acGUI_FontHZ12_8F7D } /* code 8F7D */
  ,{  11,  12,   0,   0,  12, acGUI_FontHZ12_8FC7 } /* code 8FC7 */
  ,{  11,  11,   0,   1,  12, acGUI_FontHZ12_963B } /* code 963B */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontHZ12_Prop56 = {
   0x963B /* first character */
  ,0x963B /* last character  */
  ,&GUI_FontHZ12_CharInfo[ 55] /* address of first character */
  ,(GUI_CONST_STORAGE GUI_FONT_PROP_EXT *)0 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontHZ12_Prop55 = {
   0x8FC7 /* first character */
  ,0x8FC7 /* last character  */
  ,&GUI_FontHZ12_CharInfo[ 54] /* address of first character */
  ,&GUI_FontHZ12_Prop56 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontHZ12_Prop54 = {
   0x8F7D /* first character */
  ,0x8F7D /* last character  */
  ,&GUI_FontHZ12_CharInfo[ 53] /* address of first character */
  ,&GUI_FontHZ12_Prop55 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontHZ12_Prop53 = {
   0x8D1F /* first character */
  ,0x8D1F /* last character  */
  ,&GUI_FontHZ12_CharInfo[ 52] /* address of first character */
  ,&GUI_FontHZ12_Prop54 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontHZ12_Prop52 = {
   0x8BFB /* first character */
  ,0x8BFB /* last character  */
  ,&GUI_FontHZ12_CharInfo[ 51] /* address of first character */
  ,&GUI_FontHZ12_Prop53 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontHZ12_Prop51 = {
   0x8BED /* first character */
  ,0x8BED /* last character  */
  ,&GUI_FontHZ12_CharInfo[ 50] /* address of first character */
  ,&GUI_FontHZ12_Prop52 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontHZ12_Prop50 = {
   0x8BD5 /* first character */
  ,0x8BD5 /* last character  */
  ,&GUI_FontHZ12_CharInfo[ 49] /* address of first character */
  ,&GUI_FontHZ12_Prop51 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontHZ12_Prop49 = {
   0x8BBE /* first character */
  ,0x8BBE /* last character  */
  ,&GUI_FontHZ12_CharInfo[ 48] /* address of first character */
  ,&GUI_FontHZ12_Prop50 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontHZ12_Prop48 = {
   0x8A00 /* first character */
  ,0x8A00 /* last character  */
  ,&GUI_FontHZ12_CharInfo[ 47] /* address of first character */
  ,&GUI_FontHZ12_Prop49 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontHZ12_Prop47 = {
   0x8868 /* first character */
  ,0x8868 /* last character  */
  ,&GUI_FontHZ12_CharInfo[ 46] /* address of first character */
  ,&GUI_FontHZ12_Prop48 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontHZ12_Prop46 = {
   0x83DC /* first character */
  ,0x83DC /* last character  */
  ,&GUI_FontHZ12_CharInfo[ 45] /* address of first character */
  ,&GUI_FontHZ12_Prop47 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontHZ12_Prop45 = {
   0x82F1 /* first character */
  ,0x82F1 /* last character  */
  ,&GUI_FontHZ12_CharInfo[ 44] /* address of first character */
  ,&GUI_FontHZ12_Prop46 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontHZ12_Prop44 = {
   0x81EA /* first character */
  ,0x81EA /* last character  */
  ,&GUI_FontHZ12_CharInfo[ 43] /* address of first character */
  ,&GUI_FontHZ12_Prop45 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontHZ12_Prop43 = {
   0x7F6E /* first character */
  ,0x7F6E /* last character  */
  ,&GUI_FontHZ12_CharInfo[ 42] /* address of first character */
  ,&GUI_FontHZ12_Prop44 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontHZ12_Prop42 = {
   0x7EDF /* first character */
  ,0x7EDF /* last character  */
  ,&GUI_FontHZ12_CharInfo[ 41] /* address of first character */
  ,&GUI_FontHZ12_Prop43 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontHZ12_Prop41 = {
   0x7ED3 /* first character */
  ,0x7ED3 /* last character  */
  ,&GUI_FontHZ12_CharInfo[ 40] /* address of first character */
  ,&GUI_FontHZ12_Prop42 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontHZ12_Prop40 = {
   0x7EBF /* first character */
  ,0x7EBF /* last character  */
  ,&GUI_FontHZ12_CharInfo[ 39] /* address of first character */
  ,&GUI_FontHZ12_Prop41 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontHZ12_Prop39 = {
   0x7CFB /* first character */
  ,0x7CFB /* last character  */
  ,&GUI_FontHZ12_CharInfo[ 38] /* address of first character */
  ,&GUI_FontHZ12_Prop40 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontHZ12_Prop38 = {
   0x7C7B /* first character */
  ,0x7C7B /* last character  */
  ,&GUI_FontHZ12_CharInfo[ 37] /* address of first character */
  ,&GUI_FontHZ12_Prop39 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontHZ12_Prop37 = {
   0x7A0B /* first character */
  ,0x7A0B /* last character  */
  ,&GUI_FontHZ12_CharInfo[ 36] /* address of first character */
  ,&GUI_FontHZ12_Prop38 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontHZ12_Prop36 = {
   0x786E /* first character */
  ,0x786E /* last character  */
  ,&GUI_FontHZ12_CharInfo[ 35] /* address of first character */
  ,&GUI_FontHZ12_Prop37 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontHZ12_Prop35 = {
   0x7535 /* first character */
  ,0x7535 /* last character  */
  ,&GUI_FontHZ12_CharInfo[ 34] /* address of first character */
  ,&GUI_FontHZ12_Prop36 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontHZ12_Prop34 = {
   0x6E90 /* first character */
  ,0x6E90 /* last character  */
  ,&GUI_FontHZ12_CharInfo[ 33] /* address of first character */
  ,&GUI_FontHZ12_Prop35 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontHZ12_Prop33 = {
   0x6D4B /* first character */
  ,0x6D4B /* last character  */
  ,&GUI_FontHZ12_CharInfo[ 32] /* address of first character */
  ,&GUI_FontHZ12_Prop34 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontHZ12_Prop32 = {
   0x6D41 /* first character */
  ,0x6D41 /* last character  */
  ,&GUI_FontHZ12_CharInfo[ 31] /* address of first character */
  ,&GUI_FontHZ12_Prop33 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontHZ12_Prop31 = {
   0x6B62 /* first character */
  ,0x6B62 /* last character  */
  ,&GUI_FontHZ12_CharInfo[ 30] /* address of first character */
  ,&GUI_FontHZ12_Prop32 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontHZ12_Prop30 = {
   0x6A21 /* first character */
  ,0x6A21 /* last character  */
  ,&GUI_FontHZ12_CharInfo[ 29] /* address of first character */
  ,&GUI_FontHZ12_Prop31 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontHZ12_Prop29 = {
   0x679C /* first character */
  ,0x679C /* last character  */
  ,&GUI_FontHZ12_CharInfo[ 28] /* address of first character */
  ,&GUI_FontHZ12_Prop30 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontHZ12_Prop28 = {
   0x66F2 /* first character */
  ,0x66F2 /* last character  */
  ,&GUI_FontHZ12_CharInfo[ 27] /* address of first character */
  ,&GUI_FontHZ12_Prop29 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontHZ12_Prop27 = {
   0x662F /* first character */
  ,0x662F /* last character  */
  ,&GUI_FontHZ12_CharInfo[ 26] /* address of first character */
  ,&GUI_FontHZ12_Prop28 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontHZ12_Prop26 = {
   0x6587 /* first character */
  ,0x6587 /* last character  */
  ,&GUI_FontHZ12_CharInfo[ 25] /* address of first character */
  ,&GUI_FontHZ12_Prop27 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontHZ12_Prop25 = {
   0x653E /* first character */
  ,0x653E /* last character  */
  ,&GUI_FontHZ12_CharInfo[ 24] /* address of first character */
  ,&GUI_FontHZ12_Prop26 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontHZ12_Prop24 = {
   0x63A7 /* first character */
  ,0x63A7 /* last character  */
  ,&GUI_FontHZ12_CharInfo[ 23] /* address of first character */
  ,&GUI_FontHZ12_Prop25 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontHZ12_Prop23 = {
   0x62A4 /* first character */
  ,0x62A4 /* last character  */
  ,&GUI_FontHZ12_CharInfo[ 22] /* address of first character */
  ,&GUI_FontHZ12_Prop24 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontHZ12_Prop22 = {
   0x6001 /* first character */
  ,0x6001 /* last character  */
  ,&GUI_FontHZ12_CharInfo[ 21] /* address of first character */
  ,&GUI_FontHZ12_Prop23 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontHZ12_Prop21 = {
   0x5F0F /* first character */
  ,0x5F0F /* last character  */
  ,&GUI_FontHZ12_CharInfo[ 20] /* address of first character */
  ,&GUI_FontHZ12_Prop22 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontHZ12_Prop20 = {
   0x5F00 /* first character */
  ,0x5F00 /* last character  */
  ,&GUI_FontHZ12_CharInfo[ 19] /* address of first character */
  ,&GUI_FontHZ12_Prop21 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontHZ12_Prop19 = {
   0x5B9A /* first character */
  ,0x5B9A /* last character  */
  ,&GUI_FontHZ12_CharInfo[ 18] /* address of first character */
  ,&GUI_FontHZ12_Prop20 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontHZ12_Prop18 = {
   0x5B58 /* first character */
  ,0x5B58 /* last character  */
  ,&GUI_FontHZ12_CharInfo[ 17] /* address of first character */
  ,&GUI_FontHZ12_Prop19 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontHZ12_Prop17 = {
   0x5B50 /* first character */
  ,0x5B50 /* last character  */
  ,&GUI_FontHZ12_CharInfo[ 16] /* address of first character */
  ,&GUI_FontHZ12_Prop18 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontHZ12_Prop16 = {
   0x59CB /* first character */
  ,0x59CB /* last character  */
  ,&GUI_FontHZ12_CharInfo[ 15] /* address of first character */
  ,&GUI_FontHZ12_Prop17 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontHZ12_Prop15 = {
   0x5426 /* first character */
  ,0x5426 /* last character  */
  ,&GUI_FontHZ12_CharInfo[ 14] /* address of first character */
  ,&GUI_FontHZ12_Prop16 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontHZ12_Prop14 = {
   0x53F7 /* first character */
  ,0x53F7 /* last character  */
  ,&GUI_FontHZ12_CharInfo[ 13] /* address of first character */
  ,&GUI_FontHZ12_Prop15 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontHZ12_Prop13 = {
   0x53D6 /* first character */
  ,0x53D6 /* last character  */
  ,&GUI_FontHZ12_CharInfo[ 12] /* address of first character */
  ,&GUI_FontHZ12_Prop14 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontHZ12_Prop12 = {
   0x538B /* first character */
  ,0x538B /* last character  */
  ,&GUI_FontHZ12_CharInfo[ 11] /* address of first character */
  ,&GUI_FontHZ12_Prop13 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontHZ12_Prop11 = {
   0x5355 /* first character */
  ,0x5355 /* last character  */
  ,&GUI_FontHZ12_CharInfo[ 10] /* address of first character */
  ,&GUI_FontHZ12_Prop12 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontHZ12_Prop10 = {
   0x52A8 /* first character */
  ,0x52A8 /* last character  */
  ,&GUI_FontHZ12_CharInfo[  9] /* address of first character */
  ,&GUI_FontHZ12_Prop11 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontHZ12_Prop9 = {
   0x5217 /* first character */
  ,0x5217 /* last character  */
  ,&GUI_FontHZ12_CharInfo[  8] /* address of first character */
  ,&GUI_FontHZ12_Prop10 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontHZ12_Prop8 = {
   0x5185 /* first character */
  ,0x5185 /* last character  */
  ,&GUI_FontHZ12_CharInfo[  7] /* address of first character */
  ,&GUI_FontHZ12_Prop9 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontHZ12_Prop7 = {
   0x5173 /* first character */
  ,0x5173 /* last character  */
  ,&GUI_FontHZ12_CharInfo[  6] /* address of first character */
  ,&GUI_FontHZ12_Prop8 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontHZ12_Prop6 = {
   0x5145 /* first character */
  ,0x5145 /* last character  */
  ,&GUI_FontHZ12_CharInfo[  5] /* address of first character */
  ,&GUI_FontHZ12_Prop7 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontHZ12_Prop5 = {
   0x505C /* first character */
  ,0x505C /* last character  */
  ,&GUI_FontHZ12_CharInfo[  4] /* address of first character */
  ,&GUI_FontHZ12_Prop6 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontHZ12_Prop4 = {
   0x503C /* first character */
  ,0x503C /* last character  */
  ,&GUI_FontHZ12_CharInfo[  3] /* address of first character */
  ,&GUI_FontHZ12_Prop5 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontHZ12_Prop3 = {
   0x4FDD /* first character */
  ,0x4FDD /* last character  */
  ,&GUI_FontHZ12_CharInfo[  2] /* address of first character */
  ,&GUI_FontHZ12_Prop4 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontHZ12_Prop2 = {
   0x4E3B /* first character */
  ,0x4E3B /* last character  */
  ,&GUI_FontHZ12_CharInfo[  1] /* address of first character */
  ,&GUI_FontHZ12_Prop3 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontHZ12_Prop1 = {
   0x4E2D /* first character */
  ,0x4E2D /* last character  */
  ,&GUI_FontHZ12_CharInfo[  0] /* address of first character */
  ,&GUI_FontHZ12_Prop2 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT GUI_FontHZ12 = {
   GUI_FONTTYPE_PROP_EXT /* type of font    */
  ,12 /* height of font  */
  ,12 /* space of font y */
  ,1 /* magnification x */
  ,1 /* magnification y */
  ,{&GUI_FontHZ12_Prop1}
  ,10 /* Baseline */
  ,5 /* Height of lowercase characters */
  ,8 /* Height of capital characters */
};
