/*********************************************************************
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                           www.segger.com                           *
**********************************************************************
*                                                                    *
* C-file generated by                                                *
*                                                                    *
*        Font converter for emWin version 5.22                       *
*        Compiled Jul  4 2013, 12:18:44                              *
*        (C) 1998 - 2013 Segger Microcontroller GmbH & Co. KG
*                                                                    *
**********************************************************************
*                                                                    *
* Source file: HZ16.c                                                *
* Font:        宋体                                                  *
* Height:      16                                                    *
*                                                                    *
**********************************************************************
*                                                                    *
* Initial font height:  16                                           *
* Range disabled:       0000 - FFFF                                  *
* Read pattern file: C:\Users\Administrator\Desktop\hz.txt           *
*                                                                    *
**********************************************************************
*/

#include "GUI.h"

#ifndef GUI_CONST_STORAGE
  #define GUI_CONST_STORAGE const
#endif

/* The following line needs to be included in any file selecting the
   font.
*/
extern GUI_CONST_STORAGE GUI_FONT GUI_FontHZ16;

/* Start of unicode area <Basic Greek> */
GUI_CONST_STORAGE unsigned char acGUI_FontHZ16_03A9[ 48] = { /* code 03A9, GREEK CAPITAL LETTER OMEGA */
  ________,________,________,
  _____XXX,XX______,________,
  ____XX__,_XX_____,________,
  ___XX___,__XX____,________,
  __XX____,___XX___,________,
  __XX____,___XX___,________,
  __XX____,___XX___,________,
  __XX____,___XX___,________,
  ___XX___,__XX____,________,
  ____XX__,_XX_____,________,
  __XX_XX_,XX_XX___,________,
  __XXXXX_,XXXXX___,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________};

/* Start of unicode area <CJK Unified Ideographs> */
GUI_CONST_STORAGE unsigned char acGUI_FontHZ16_4E2D[ 48] = { /* code 4E2D */
  _______X,X_______,________,
  _______X,X_______,________,
  _______X,X_______,________,
  _______X,X_______,________,
  __XXXXXX,XXXXXX__,________,
  __XX___X,X___XX__,________,
  __XX___X,X___XX__,________,
  __XX___X,X___XX__,________,
  __XX___X,X___XX__,________,
  __XX___X,X___XX__,________,
  __XXXXXX,XXXXXX__,________,
  __XX___X,X___XX__,________,
  _______X,X_______,________,
  _______X,X_______,________,
  _______X,X_______,________,
  _______X,X_______,________};

GUI_CONST_STORAGE unsigned char acGUI_FontHZ16_4E3B[ 48] = { /* code 4E3B */
  ______XX,________,________,
  _______X,X_______,________,
  ________,________,________,
  _XXXXXXX,XXXXXXX_,________,
  _______X,X_______,________,
  _______X,X_______,________,
  _______X,X_______,________,
  _______X,X_______,________,
  __XXXXXX,XXXXXX__,________,
  _______X,X_______,________,
  _______X,X_______,________,
  _______X,X_______,________,
  _______X,X_______,________,
  _______X,X_______,________,
  XXXXXXXX,XXXXXXXX,________,
  ________,________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontHZ16_4FDD[ 48] = { /* code 4FDD */
  ____XX__,________,________,
  ____XXXX,XXXXXX__,________,
  ____XXXX,____XX__,________,
  ___XX_XX,____XX__,________,
  ___XX_XX,____XX__,________,
  __XXX_XX,XXXXXX__,________,
  __XXX___,_XX_____,________,
  _XXXX___,_XX_____,________,
  XX_XXXXX,XXXXXXX_,________,
  ___XX___,XXXX____,________,
  ___XX__X,XXXXX___,________,
  ___XX_XX,_XX_XX__,________,
  ___XXXX_,_XX__XX_,________,
  ___XXX__,_XX___XX,________,
  ___XX___,_XX_____,________,
  ___XX___,_XX_____,________};

GUI_CONST_STORAGE unsigned char acGUI_FontHZ16_503C[ 48] = { /* code 503C */
  ____XX__,_XX_____,________,
  ____XX__,_XX_____,________,
  ____XXXX,XXXXXXX_,________,
  ___XX___,_XX_____,________,
  ___XX___,_XX_____,________,
  __XXX_XX,XXXXXX__,________,
  __XXX_XX,____XX__,________,
  _XXXX_XX,XXXXXX__,________,
  XX_XX_XX,____XX__,________,
  ___XX_XX,XXXXXX__,________,
  ___XX_XX,____XX__,________,
  ___XX_XX,XXXXXX__,________,
  ___XX_XX,____XX__,________,
  ___XX_XX,____XX__,________,
  ___XXXXX,XXXXXXXX,________,
  ___XX___,________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontHZ16_505C[ 48] = { /* code 505C */
  ___XX___,XX______,________,
  ___XX___,_XX_____,________,
  ___XXXXX,XXXXXXX_,________,
  __XX____,________,________,
  __XX__XX,XXXXXX__,________,
  _XXX__XX,____XX__,________,
  _XXX__XX,XXXXXX__,________,
  XXXX____,________,________,
  __XXXXXX,XXXXXXXX,________,
  __XXXX__,______XX,________,
  __XX__XX,XXXXXX__,________,
  __XX____,_XX_____,________,
  __XX____,_XX_____,________,
  __XX____,_XX_____,________,
  __XX___X,XXX_____,________,
  __XX____,XX______,________};

GUI_CONST_STORAGE unsigned char acGUI_FontHZ16_5145[ 48] = { /* code 5145 */
  ______XX,________,________,
  _______X,X_______,________,
  XXXXXXXX,XXXXXXXX,________,
  _____XX_,________,________,
  _____XX_,________,________,
  ____XX__,__XX____,________,
  ___XX___,___XX___,________,
  __XXXXXX,XXXXXX__,________,
  _____XX_,_XX_XX__,________,
  _____XX_,_XX_____,________,
  _____XX_,_XX_____,________,
  _____XX_,_XX_____,________,
  ____XX__,_XX__XX_,________,
  ____XX__,_XX__XX_,________,
  ___XX___,_XX__XX_,________,
  _XXX____,__XXXXX_,________};

GUI_CONST_STORAGE unsigned char acGUI_FontHZ16_5185[ 48] = { /* code 5185 */
  _______X,X_______,________,
  _______X,X_______,________,
  _______X,X_______,________,
  _XXXXXXX,XXXXXXX_,________,
  _XX____X,X____XX_,________,
  _XX____X,X____XX_,________,
  _XX____X,X____XX_,________,
  _XX___XX,XX___XX_,________,
  _XX___XX,_XX__XX_,________,
  _XX__XX_,__XX_XX_,________,
  _XX_XX__,___XXXX_,________,
  _XXXX___,___XXXX_,________,
  _XX_____,_____XX_,________,
  _XX_____,_____XX_,________,
  _XX_____,___XXXX_,________,
  _XX_____,____XX__,________};

GUI_CONST_STORAGE unsigned char acGUI_FontHZ16_5217[ 48] = { /* code 5217 */
  ________,_____XX_,________,
  _XXXXXXX,XX___XX_,________,
  ____XX__,_____XX_,________,
  ____XX__,__XX_XX_,________,
  ___XXXXX,X_XX_XX_,________,
  ___XX__X,X_XX_XX_,________,
  __XX___X,X_XX_XX_,________,
  __XX___X,X_XX_XX_,________,
  _XXXX_XX,__XX_XX_,________,
  XX__XXXX,__XX_XX_,________,
  _____XX_,__XX_XX_,________,
  _____XX_,__XX_XX_,________,
  ____XX__,_____XX_,________,
  ___XX___,_____XX_,________,
  __XX____,___XXXX_,________,
  _XX_____,____XX__,________};

GUI_CONST_STORAGE unsigned char acGUI_FontHZ16_52A8[ 48] = { /* code 52A8 */
  ________,_XX_____,________,
  ________,_XX_____,________,
  _XXXXXX_,_XX_____,________,
  ________,_XX_____,________,
  _______X,XXXXXXX_,________,
  ________,_XX__XX_,________,
  XXXXXXXX,_XX__XX_,________,
  __XX____,_XX__XX_,________,
  __XX____,_XX__XX_,________,
  __XX____,XX___XX_,________,
  _XX_XX__,XX___XX_,________,
  _XX__XX_,XX___XX_,________,
  XXXXXXXX,X____XX_,________,
  _XX__XXX,X____XX_,________,
  ______XX,__XXXX__,________,
  _____XX_,___XX___,________};

GUI_CONST_STORAGE unsigned char acGUI_FontHZ16_5355[ 48] = { /* code 5355 */
  ___XX___,___XX___,________,
  ____XX__,__XX____,________,
  _____XX_,_XX_____,________,
  __XXXXXX,XXXXXX__,________,
  __XX___X,X___XX__,________,
  __XX___X,X___XX__,________,
  __XXXXXX,XXXXXX__,________,
  __XX___X,X___XX__,________,
  __XX___X,X___XX__,________,
  __XXXXXX,XXXXXX__,________,
  _______X,X_______,________,
  _______X,X_______,________,
  XXXXXXXX,XXXXXXXX,________,
  _______X,X_______,________,
  _______X,X_______,________,
  _______X,X_______,________};

GUI_CONST_STORAGE unsigned char acGUI_FontHZ16_538B[ 48] = { /* code 538B */
  ________,________,________,
  __XXXXXX,XXXXXXXX,________,
  __XX____,________,________,
  __XX____,XX______,________,
  __XX____,XX______,________,
  __XX____,XX______,________,
  __XX____,XX______,________,
  __XXXXXX,XXXXXXX_,________,
  __XX____,XX______,________,
  __XX____,XX______,________,
  __XX____,XX_XX___,________,
  __XX____,XX__XX__,________,
  __XX____,XX__XX__,________,
  _XX_____,XX______,________,
  _XXXXXXX,XXXXXXXX,________,
  XX______,________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontHZ16_53D6[ 48] = { /* code 53D6 */
  ________,________,________,
  XXXXXXXX,XX______,________,
  __XX__XX,XXXXXXX_,________,
  __XX__XX,_XX__XX_,________,
  __XXXXXX,_XX__XX_,________,
  __XX__XX,_XX__XX_,________,
  __XX__XX,_XX__XX_,________,
  __XXXXXX,_XX__XX_,________,
  __XX__XX,__XXXX__,________,
  __XX__XX,__XXXX__,________,
  __XX_XXX,XXXXXX__,________,
  XXXXXXXX,___XX___,________,
  _XX___XX,___XX___,________,
  ______XX,__XXXX__,________,
  ______XX,_XX__XX_,________,
  ______XX,XX____XX,________};

GUI_CONST_STORAGE unsigned char acGUI_FontHZ16_53F7[ 48] = { /* code 53F7 */
  ________,________,________,
  ___XXXXX,XXXXX___,________,
  ___XX___,___XX___,________,
  ___XX___,___XX___,________,
  ___XX___,___XX___,________,
  ___XXXXX,XXXXX___,________,
  ________,________,________,
  XXXXXXXX,XXXXXXXX,________,
  ____XX__,________,________,
  ___XX___,________,________,
  ___XXXXX,XXXXX___,________,
  ________,___XX___,________,
  ________,___XX___,________,
  ________,___XX___,________,
  ________,XXXX____,________,
  ________,_XX_____,________};

GUI_CONST_STORAGE unsigned char acGUI_FontHZ16_5426[ 48] = { /* code 5426 */
  ________,________,________,
  _XXXXXXX,XXXXXXX_,________,
  ________,XX______,________,
  _______X,X_______,________,
  ______XX,X_______,________,
  _____XXX,XXXX____,________,
  ____XX_X,X__XXX__,________,
  __XXX__X,X____XX_,________,
  XXX____X,X_____XX,________,
  ________,________,________,
  ___XXXXX,XXXXX___,________,
  ___XX___,___XX___,________,
  ___XX___,___XX___,________,
  ___XX___,___XX___,________,
  ___XXXXX,XXXXX___,________,
  ___XX___,___XX___,________};

GUI_CONST_STORAGE unsigned char acGUI_FontHZ16_59CB[ 48] = { /* code 59CB */
  ___XX___,__XX____,________,
  ___XX___,__XX____,________,
  ___XX___,__XX____,________,
  ___XX___,_XX_____,________,
  XXXXXXX_,_XX_XX__,________,
  __XX_XX_,XX___XX_,________,
  __XX_XXX,XXXXXXXX,________,
  __XX_XX_,XX____XX,________,
  __XX_XX_,________,________,
  _XX_XX__,XXXXXXX_,________,
  __XXXX__,XX___XX_,________,
  ___XX___,XX___XX_,________,
  __XXXX__,XX___XX_,________,
  _XX__XX_,XX___XX_,________,
  XX______,XXXXXXX_,________,
  ________,XX___XX_,________};

GUI_CONST_STORAGE unsigned char acGUI_FontHZ16_5B50[ 48] = { /* code 5B50 */
  ________,________,________,
  _XXXXXXX,XXXXXX__,________,
  ________,___XX___,________,
  ________,__XX____,________,
  ________,_XX_____,________,
  _______X,XX______,________,
  _______X,X_______,________,
  XXXXXXXX,XXXXXXXX,________,
  _______X,X_______,________,
  _______X,X_______,________,
  _______X,X_______,________,
  _______X,X_______,________,
  _______X,X_______,________,
  _______X,X_______,________,
  _____XXX,X_______,________,
  ______XX,________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontHZ16_5B58[ 48] = { /* code 5B58 */
  _____XX_,________,________,
  _____XX_,________,________,
  XXXXXXXX,XXXXXXXX,________,
  ____XX__,________,________,
  ____XX__,________,________,
  ___XX_XX,XXXXXX__,________,
  ___XX___,___XX___,________,
  __XXX___,__XX____,________,
  _XXXX___,_XX_____,________,
  XX_XXXXX,XXXXXXXX,________,
  ___XX___,_XX_____,________,
  ___XX___,_XX_____,________,
  ___XX___,_XX_____,________,
  ___XX___,_XX_____,________,
  ___XX__X,XXX_____,________,
  ___XX___,XX______,________};

GUI_CONST_STORAGE unsigned char acGUI_FontHZ16_5B9A[ 48] = { /* code 5B9A */
  ______XX,________,________,
  _______X,X_______,________,
  _XXXXXXX,XXXXXXXX,________,
  _XX_____,______XX,________,
  XX______,_____XX_,________,
  ________,________,________,
  __XXXXXX,XXXXXX__,________,
  _______X,X_______,________,
  _______X,X_______,________,
  ___XX__X,X_______,________,
  ___XX__X,XXXXXX__,________,
  ___XX__X,X_______,________,
  ___XX__X,X_______,________,
  __XXXX_X,X_______,________,
  _XX__XXX,XXXXXXXX,________,
  XX______,________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontHZ16_5F00[ 48] = { /* code 5F00 */
  ________,________,________,
  _XXXXXXX,XXXXXXX_,________,
  ____XX__,__XX____,________,
  ____XX__,__XX____,________,
  ____XX__,__XX____,________,
  ____XX__,__XX____,________,
  ____XX__,__XX____,________,
  XXXXXXXX,XXXXXXXX,________,
  ____XX__,__XX____,________,
  ____XX__,__XX____,________,
  ____XX__,__XX____,________,
  ____XX__,__XX____,________,
  ___XX___,__XX____,________,
  ___XX___,__XX____,________,
  __XX____,__XX____,________,
  _XX_____,__XX____,________};

GUI_CONST_STORAGE unsigned char acGUI_FontHZ16_5F0F[ 48] = { /* code 5F0F */
  ________,_XX_XX__,________,
  ________,_XX__XX_,________,
  ________,_XX__XX_,________,
  ________,_XX_____,________,
  XXXXXXXX,XXXXXXXX,________,
  ________,_XX_____,________,
  ________,_XX_____,________,
  __XXXXXX,_XX_____,________,
  ____XX__,_XX_____,________,
  ____XX__,_XX_____,________,
  ____XX__,__XX____,________,
  ____XX__,__XX__XX,________,
  ____XXXX,X__XX_XX,________,
  _XXXXX__,____XXXX,________,
  __XX____,_____XXX,________,
  ________,______XX,________};

GUI_CONST_STORAGE unsigned char acGUI_FontHZ16_6001[ 48] = { /* code 6001 */
  _______X,X_______,________,
  _______X,X_______,________,
  _XXXXXXX,XXXXXXX_,________,
  _______X,X_______,________,
  ______XX,XX______,________,
  _____XX_,_XX_____,________,
  ____XXXX,__XX____,________,
  __XXX__X,X__XXX__,________,
  XXX_____,_____XXX,________,
  _______X,X_______,________,
  ____XX__,XX__XX__,________,
  _XX_XX__,XX___XX_,________,
  _XX_XX__,___XX_XX,________,
  _XX_XX__,___XX_XX,________,
  XX___XXX,XXXXX___,________,
  ________,________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontHZ16_62A4[ 48] = { /* code 62A4 */
  ___XX___,_XX_____,________,
  ___XX___,__XX____,________,
  ___XX___,__XX____,________,
  ___XX__X,XXXXXXXX,________,
  XXXXXXXX,X_____XX,________,
  ___XX__X,X_____XX,________,
  ___XX__X,X_____XX,________,
  ___XXXXX,XXXXXXXX,________,
  ___XXX_X,X_____XX,________,
  __XXX__X,X_______,________,
  XXXXX__X,X_______,________,
  ___XX__X,X_______,________,
  ___XX_XX,________,________,
  ___XX_XX,________,________,
  _XXXXXX_,________,________,
  __XXXX__,________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontHZ16_63A7[ 48] = { /* code 63A7 */
  ___XX___,_XX_____,________,
  ___XX___,__XX____,________,
  ___XX___,__XX____,________,
  ___XX_XX,XXXXXXXX,________,
  XXXXXXXX,______XX,________,
  ___XXXX_,XX_XXXX_,________,
  ___XX__X,X___XX__,________,
  ___XXXXX,_____XX_,________,
  __XXX___,________,________,
  XXXXX__X,XXXXXXX_,________,
  ___XX___,__XX____,________,
  ___XX___,__XX____,________,
  ___XX___,__XX____,________,
  ___XX___,__XX____,________,
  _XXXXXXX,XXXXXXXX,________,
  __XX____,________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontHZ16_653E[ 48] = { /* code 653E */
  __XX____,_XX_____,________,
  ___XX___,_XX_____,________,
  ________,_XX_____,________,
  XXXXXXXX,XX______,________,
  __XX____,XXXXXXXX,________,
  __XX___X,X___XX__,________,
  __XXXXXX,XX__XX__,________,
  __XX_XX_,XX__XX__,________,
  __XX_XX_,XX__XX__,________,
  __XX_XX_,_XXXX___,________,
  __XX_XX_,_XXXX___,________,
  __XX_XX_,__XX____,________,
  _XX__XX_,_XXXX___,________,
  _XXXXXX_,XX__XX__,________,
  XX__XX_X,X____XX_,________,
  ______XX,______XX,________};

GUI_CONST_STORAGE unsigned char acGUI_FontHZ16_6587[ 48] = { /* code 6587 */
  ______XX,________,________,
  _______X,X_______,________,
  _______X,X_______,________,
  XXXXXXXX,XXXXXXXX,________,
  ___XX___,___XX___,________,
  ___XX___,___XX___,________,
  ____XX__,__XX____,________,
  ____XX__,__XX____,________,
  _____XX_,_XX_____,________,
  ______XX,XX______,________,
  _______X,X_______,________,
  ______XX,XX______,________,
  _____XX_,_XX_____,________,
  ____XX__,__XX____,________,
  __XXX___,___XXX__,________,
  XXX_____,_____XXX,________};

GUI_CONST_STORAGE unsigned char acGUI_FontHZ16_662F[ 48] = { /* code 662F */
  ___XXXXX,XXXXX___,________,
  ___XX___,___XX___,________,
  ___XX___,___XX___,________,
  ___XXXXX,XXXXX___,________,
  ___XX___,___XX___,________,
  ___XX___,___XX___,________,
  ___XXXXX,XXXXX___,________,
  ________,________,________,
  XXXXXXXX,XXXXXXXX,________,
  _______X,X_______,________,
  ___XX__X,X_______,________,
  ___XX__X,XXXXXX__,________,
  ___XX__X,X_______,________,
  __XXXX_X,X_______,________,
  _XX__XXX,X_______,________,
  XX____XX,XXXXXXXX,________};

GUI_CONST_STORAGE unsigned char acGUI_FontHZ16_66F2[ 48] = { /* code 66F2 */
  _____XX_,_XX_____,________,
  _____XX_,_XX_____,________,
  _____XX_,_XX_____,________,
  _____XX_,_XX_____,________,
  _XXXXXXX,XXXXXXX_,________,
  _XX__XX_,_XX__XX_,________,
  _XX__XX_,_XX__XX_,________,
  _XX__XX_,_XX__XX_,________,
  _XX__XX_,_XX__XX_,________,
  _XXXXXXX,XXXXXXX_,________,
  _XX__XX_,_XX__XX_,________,
  _XX__XX_,_XX__XX_,________,
  _XX__XX_,_XX__XX_,________,
  _XX__XX_,_XX__XX_,________,
  _XXXXXXX,XXXXXXX_,________,
  _XX_____,_____XX_,________};

GUI_CONST_STORAGE unsigned char acGUI_FontHZ16_679C[ 48] = { /* code 679C */
  ________,________,________,
  ___XXXXX,XXXXX___,________,
  ___XX__X,X__XX___,________,
  ___XX__X,X__XX___,________,
  ___XXXXX,XXXXX___,________,
  ___XX__X,X__XX___,________,
  ___XX__X,X__XX___,________,
  ___XXXXX,XXXXX___,________,
  ___XX__X,X__XX___,________,
  _______X,X_______,________,
  XXXXXXXX,XXXXXXXX,________,
  _____XXX,XXX_____,________,
  ____XX_X,X_XX____,________,
  __XXX__X,X__XXX__,________,
  XXX____X,X____XXX,________,
  _______X,X_______,________};

GUI_CONST_STORAGE unsigned char acGUI_FontHZ16_6A21[ 48] = { /* code 6A21 */
  ___XX__X,X__XX___,________,
  ___XX__X,X__XX___,________,
  ___XXXXX,XXXXXXX_,________,
  ___XX__X,X__XX___,________,
  XXXXXXX_,________,________,
  ___XX_XX,XXXXXX__,________,
  __XXX_XX,____XX__,________,
  __XXXXXX,XXXXXX__,________,
  _XXXXXXX,____XX__,________,
  _XXXX_XX,XXXXXX__,________,
  XX_XX___,_XX_____,________,
  ___XXXXX,XXXXXXX_,________,
  ___XX___,XXXX____,________,
  ___XX__X,X__XX___,________,
  ___XX_XX,____XX__,________,
  ___XXXX_,_____XXX,________};

GUI_CONST_STORAGE unsigned char acGUI_FontHZ16_6B62[ 48] = { /* code 6B62 */
  _______X,X_______,________,
  _______X,X_______,________,
  _______X,X_______,________,
  _______X,X_______,________,
  ___XX__X,X_______,________,
  ___XX__X,X_______,________,
  ___XX__X,XXXXXX__,________,
  ___XX__X,X_______,________,
  ___XX__X,X_______,________,
  ___XX__X,X_______,________,
  ___XX__X,X_______,________,
  ___XX__X,X_______,________,
  ___XX__X,X_______,________,
  ___XX__X,X_______,________,
  XXXXXXXX,XXXXXXXX,________,
  ________,________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontHZ16_6D41[ 48] = { /* code 6D41 */
  ________,XX______,________,
  __XX____,_XX_____,________,
  ___XXXXX,XXXXXXXX,________,
  ___XX___,XX______,________,
  XX_____X,X__XX___,________,
  _XX___XX,____XX__,________,
  _XX__XXX,XXXXXXX_,________,
  ___XX___,_____XX_,________,
  ___XX___,________,________,
  __XX__XX,_XX_XX__,________,
  XXXX__XX,_XX_XX__,________,
  __XX__XX,_XX_XX__,________,
  __XX__XX,_XX_XX__,________,
  __XX__XX,_XX_XXXX,________,
  __XX_XX_,_XX_XXXX,________,
  ____XX__,_XX__XXX,________};

GUI_CONST_STORAGE unsigned char acGUI_FontHZ16_6D4B[ 48] = { /* code 6D4B */
  ________,_____XX_,________,
  __XX_XXX,XXX__XX_,________,
  ___XXXX_,_XX__XX_,________,
  ___XXXX_,_XXXXXX_,________,
  XX___XXX,XXXXXXX_,________,
  _XX__XXX,XXXXXXX_,________,
  _XX__XXX,XXXXXXX_,________,
  ___XXXXX,XXXXXXX_,________,
  ___XXXXX,XXXXXXX_,________,
  __XX_XXX,XXXXXXX_,________,
  XXXX_XXX,XXXXXXX_,________,
  __XX___X,X____XX_,________,
  __XX__XX,XX___XX_,________,
  __XX__XX,_XX__XX_,________,
  __XX_XX_,___XXXX_,________,
  ____XX__,____XX__,________};

GUI_CONST_STORAGE unsigned char acGUI_FontHZ16_6E90[ 48] = { /* code 6E90 */
  ________,________,________,
  __XX_XXX,XXXXXXXX,________,
  ___XXXX_,__XX____,________,
  ___XXXX_,_XX_____,________,
  XX___XXX,XXXXXXX_,________,
  _XX__XXX,X____XX_,________,
  _XX__XXX,XXXXXXX_,________,
  ___XXXXX,X____XX_,________,
  ___XXXXX,XXXXXXX_,________,
  __XX_XXX,X_XX_XX_,________,
  XXXX_XX_,__XX____,________,
  __XX_XX_,XXXXXX__,________,
  __XXXX_X,X_XX_XX_,________,
  __XXXXXX,__XX__XX,________,
  __XXX___,XXXX____,________,
  ________,_XX_____,________};

GUI_CONST_STORAGE unsigned char acGUI_FontHZ16_7535[ 48] = { /* code 7535 */
  _______X,X_______,________,
  _______X,X_______,________,
  _______X,X_______,________,
  __XXXXXX,XXXXXX__,________,
  __XX___X,X___XX__,________,
  __XX___X,X___XX__,________,
  __XX___X,X___XX__,________,
  __XXXXXX,XXXXXX__,________,
  __XX___X,X___XX__,________,
  __XX___X,X___XX__,________,
  __XX___X,X___XX__,________,
  __XXXXXX,XXXXXX__,________,
  __XX___X,X___XXXX,________,
  _______X,X_____XX,________,
  _______X,X_____XX,________,
  ________,XXXXXXXX,________};

GUI_CONST_STORAGE unsigned char acGUI_FontHZ16_786E[ 48] = { /* code 786E */
  ________,_XX_____,________,
  ________,_XX_____,________,
  XXXXXXX_,_XXXXXX_,________,
  ___XX___,XX___XX_,________,
  ___XX__X,X___XX__,________,
  __XX__XX,XXXXXXXX,________,
  __XXXXX_,XX_XX_XX,________,
  _XXX_XX_,XX_XX_XX,________,
  _XXX_XX_,XXXXXXXX,________,
  XXXX_XX_,XX_XX_XX,________,
  __XX_XX_,XX_XX_XX,________,
  __XX_XX_,XXXXXXXX,________,
  __XXXXX_,XX_XX_XX,________,
  __XX_XXX,X__XX_XX,________,
  __XX___X,X___XXXX,________,
  ______XX,_____XX_,________};

GUI_CONST_STORAGE unsigned char acGUI_FontHZ16_7A0B[ 48] = { /* code 7A0B */
  ____XX__,________,________,
  ___XXXXX,XXXXXXX_,________,
  XXXXX__X,X____XX_,________,
  ___XX__X,X____XX_,________,
  ___XX__X,X____XX_,________,
  XXXXXXXX,XXXXXXX_,________,
  ___XX___,________,________,
  __XXX___,________,________,
  __XXXX_X,XXXXXXXX,________,
  _XXXXXX_,__XX____,________,
  _XXXXXX_,__XX____,________,
  XX_XX__X,XXXXXXX_,________,
  ___XX___,__XX____,________,
  ___XX___,__XX____,________,
  ___XX_XX,XXXXXXXX,________,
  ___XX___,________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontHZ16_7C7B[ 48] = { /* code 7C7B */
  _______X,X_______,________,
  ___XX__X,X__XX___,________,
  ____XX_X,X_XX____,________,
  _______X,X_______,________,
  _XXXXXXX,XXXXXXX_,________,
  _____XXX,XXX_____,________,
  ____XX_X,X_XX____,________,
  ___XX__X,X__XX___,________,
  _XXX____,____XX__,________,
  _______X,X_______,________,
  XXXXXXXX,XXXXXXXX,________,
  ______XX,XX______,________,
  _____XX_,_XX_____,________,
  ____XX__,__XX____,________,
  __XXX___,___XXX__,________,
  XXX_____,_____XXX,________};

GUI_CONST_STORAGE unsigned char acGUI_FontHZ16_7CFB[ 48] = { /* code 7CFB */
  ________,XXXXXX__,________,
  __XXXXXX,X_______,________,
  _____XX_,________,________,
  ____XX__,__XX____,________,
  ___XX___,_XX_____,________,
  __XXXXXX,XX______,________,
  _______X,X_______,________,
  _____XXX,___XX___,________,
  ___XXX__,____XX__,________,
  _XXXXXXX,XXXXXXX_,________,
  _______X,X____XX_,________,
  ____XX_X,X_XX____,________,
  ___XX__X,X__XX___,________,
  __XX___X,X___XX__,________,
  _XX__XXX,X____XX_,________,
  ______XX,________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontHZ16_7EBF[ 48] = { /* code 7EBF */
  ___XX___,_XXXX___,________,
  ___XX___,_XX_XX__,________,
  __XX____,_XX_____,________,
  __XX_XX_,_XXXXXX_,________,
  _XX__XXX,XXXX____,________,
  XXXXXX__,_XX_____,________,
  ___XX___,_XXXXXXX,________,
  __XX__XX,XXXX____,________,
  _XX_____,_XX__XX_,________,
  XXXXXXX_,_XX_XX__,________,
  _XX_____,__XXX___,________,
  ________,__XX__XX,________,
  ___XXXX_,_XXXX_XX,________,
  XXXX____,XX__XXXX,________,
  _XX___XX,X____XXX,________,
  ________,______XX,________};

GUI_CONST_STORAGE unsigned char acGUI_FontHZ16_7ED3[ 48] = { /* code 7ED3 */
  ___XX___,__XX____,________,
  ___XX___,__XX____,________,
  __XX____,__XX____,________,
  __XX_XXX,XXXXXXXX,________,
  _XX__XX_,__XX____,________,
  XXXXXX__,__XX____,________,
  ___XX__X,XXXXXXX_,________,
  __XX____,________,________,
  _XX_____,________,________,
  XXXXXXXX,XXXXXXX_,________,
  _XX____X,X____XX_,________,
  _______X,X____XX_,________,
  ___XXXXX,X____XX_,________,
  XXXX___X,X____XX_,________,
  _XX____X,XXXXXXX_,________,
  _______X,X____XX_,________};

GUI_CONST_STORAGE unsigned char acGUI_FontHZ16_7EDF[ 48] = { /* code 7EDF */
  ___XX___,_XX_____,________,
  ___XX___,__XX____,________,
  __XX____,__XX____,________,
  __XX__XX,XXXXXXXX,________,
  _XX_XX__,_XX_____,________,
  XXXXXX__,XX__XX__,________,
  ___XX__X,X____XX_,________,
  __XX__XX,XXXXXXXX,________,
  _XX_____,XX_XX_XX,________,
  XXXXXX__,XX_XX___,________,
  _XX_____,XX_XX___,________,
  ________,XX_XX___,________,
  ___XXX_X,X__XX_XX,________,
  XXXX___X,X__XX_XX,________,
  _XX___XX,____XXXX,________,
  _____XX_,________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontHZ16_7F6E[ 48] = { /* code 7F6E */
  _XXXXXXX,XXXXXXX_,________,
  _XX__XX_,_XX__XX_,________,
  _XXXXXXX,XXXXXXX_,________,
  _______X,X_______,________,
  _XXXXXXX,XXXXXXX_,________,
  _______X,X_______,________,
  ___XXXXX,XXXXX___,________,
  ___XX___,___XX___,________,
  ___XXXXX,XXXXX___,________,
  ___XX___,___XX___,________,
  ___XXXXX,XXXXX___,________,
  ___XX___,___XX___,________,
  ___XXXXX,XXXXX___,________,
  ___XX___,___XX___,________,
  XXXXXXXX,XXXXXXXX,________,
  ________,________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontHZ16_81EA[ 48] = { /* code 81EA */
  _______X,X_______,________,
  ______XX,________,________,
  _____XX_,________,________,
  ___XXXXX,XXXXX___,________,
  ___XX___,___XX___,________,
  ___XX___,___XX___,________,
  ___XX___,___XX___,________,
  ___XXXXX,XXXXX___,________,
  ___XX___,___XX___,________,
  ___XX___,___XX___,________,
  ___XXXXX,XXXXX___,________,
  ___XX___,___XX___,________,
  ___XX___,___XX___,________,
  ___XX___,___XX___,________,
  ___XXXXX,XXXXX___,________,
  ___XX___,___XX___,________};

GUI_CONST_STORAGE unsigned char acGUI_FontHZ16_82F1[ 48] = { /* code 82F1 */
  ____XX__,__XX____,________,
  ____XX__,__XX____,________,
  XXXXXXXX,XXXXXXXX,________,
  ____XX__,__XX____,________,
  _______X,X_______,________,
  _______X,X_______,________,
  ___XXXXX,XXXXX___,________,
  ___XX__X,X__XX___,________,
  ___XX__X,X__XX___,________,
  ___XX__X,X__XX___,________,
  XXXXXXXX,XXXXXXXX,________,
  ______XX,XX______,________,
  _____XX_,_XX_____,________,
  ____XX__,__XX____,________,
  __XXX___,___XXX__,________,
  XXX_____,_____XXX,________};

GUI_CONST_STORAGE unsigned char acGUI_FontHZ16_83DC[ 48] = { /* code 83DC */
  ____XX__,__XX____,________,
  ____XX__,__XX____,________,
  XXXXXXXX,XXXXXXXX,________,
  ____XX__,__XX____,________,
  ________,___XX___,________,
  ________,XXXXXX__,________,
  __XXXXXX,X_______,________,
  ___XX__X,X__XX___,________,
  ____XX__,__XX____,________,
  _______X,X_______,________,
  _XXXXXXX,XXXXXXX_,________,
  _____XXX,XXX_____,________,
  ____XX_X,X_XX____,________,
  __XXX__X,X__XXX__,________,
  XXX____X,X____XXX,________,
  _______X,X_______,________};

GUI_CONST_STORAGE unsigned char acGUI_FontHZ16_8868[ 48] = { /* code 8868 */
  _______X,X_______,________,
  _______X,X_______,________,
  _XXXXXXX,XXXXXXX_,________,
  _______X,X_______,________,
  _______X,X_______,________,
  __XXXXXX,XXXXXX__,________,
  _______X,X_______,________,
  _______X,X_______,________,
  XXXXXXXX,XXXXXXXX,________,
  _____XXX,X_______,________,
  ____XX__,XX__XX__,________,
  ___XXX__,_XXXX___,________,
  __XXXX__,__XX____,________,
  XXX_XX_X,X__XXX__,________,
  ____XXXX,_____XXX,________,
  ____XXX_,________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontHZ16_8A00[ 48] = { /* code 8A00 */
  ______XX,________,________,
  _______X,X_______,________,
  XXXXXXXX,XXXXXXXX,________,
  ________,________,________,
  ________,________,________,
  __XXXXXX,XXXXXX__,________,
  ________,________,________,
  ________,________,________,
  __XXXXXX,XXXXXX__,________,
  ________,________,________,
  ________,________,________,
  __XXXXXX,XXXXXX__,________,
  __XX____,____XX__,________,
  __XX____,____XX__,________,
  __XXXXXX,XXXXXX__,________,
  __XX____,____XX__,________};

GUI_CONST_STORAGE unsigned char acGUI_FontHZ16_8BBE[ 48] = { /* code 8BBE */
  ________,________,________,
  __XX___X,XXXXX___,________,
  ___XX__X,X__XX___,________,
  ___XX__X,X__XX___,________,
  _______X,X__XX___,________,
  ______XX,____XXXX,________,
  XXXXXXX_,________,________,
  ___XX_XX,XXXXXX__,________,
  ___XX__X,X___XX__,________,
  ___XX__X,X__XX___,________,
  ___XX___,XX_XX___,________,
  ___XXXX_,XXXX____,________,
  ___XXX__,_XX_____,________,
  ___XX___,XXXX____,________,
  ______XX,X__XXX__,________,
  ____XXX_,_____XXX,________};

GUI_CONST_STORAGE unsigned char acGUI_FontHZ16_8BD5[ 48] = { /* code 8BD5 */
  ________,__XXXX__,________,
  __XX____,__XX_XX_,________,
  ___XX___,__XX_XX_,________,
  ___XX___,__XX____,________,
  _____XXX,XXXXXXXX,________,
  ________,__XX____,________,
  XXXXX___,__XX____,________,
  ___XXXXX,XXXX____,________,
  ___XX__X,X_XX____,________,
  ___XX__X,X__XX___,________,
  ___XX__X,X__XX___,________,
  ___XXXXX,X__XX___,________,
  ___XXX_X,XXX_XXXX,________,
  ___XXXXX,X___XXXX,________,
  ______XX,_____XXX,________,
  ________,______XX,________};

GUI_CONST_STORAGE unsigned char acGUI_FontHZ16_8BED[ 48] = { /* code 8BED */
  ________,________,________,
  _XX__XXX,XXXXXXX_,________,
  __XX____,_XX_____,________,
  __XX____,_XX_____,________,
  ______XX,XXXXXX__,________,
  ________,XX__XX__,________,
  XXXX____,XX__XX__,________,
  __XX_XXX,XXXXXXXX,________,
  __XX____,________,________,
  __XX____,________,________,
  __XX__XX,XXXXXX__,________,
  __XX__XX,____XX__,________,
  __XXXXXX,____XX__,________,
  __XXX_XX,____XX__,________,
  __XX__XX,XXXXXX__,________,
  ______XX,____XX__,________};

GUI_CONST_STORAGE unsigned char acGUI_FontHZ16_8BFB[ 48] = { /* code 8BFB */
  ________,__XX____,________,
  __XX____,__XX____,________,
  ___XX__X,XXXXXXX_,________,
  ___XX___,__XX____,________,
  ________,__XX____,________,
  ______XX,XXXXXXXX,________,
  XXXXX___,______XX,________,
  ___XX___,XX_XXXX_,________,
  ___XX___,_XXXX___,________,
  ___XX__X,X__XX___,________,
  ___XX___,XX_XX___,________,
  ___XX_XX,XXXXXXXX,________,
  ___XXXX_,__XXXX__,________,
  ___XXX__,_XX__XX_,________,
  ___XX___,XX____XX,________,
  ______XX,X_____XX,________};

GUI_CONST_STORAGE unsigned char acGUI_FontHZ16_8D1F[ 48] = { /* code 8D1F */
  _____XX_,________,________,
  _____XX_,________,________,
  ____XXXX,XXXX____,________,
  ___XX___,__XX____,________,
  __XX____,_XX_____,________,
  _XXXXXXX,XXXXX___,________,
  ___XX___,___XX___,________,
  ___XX__X,X__XX___,________,
  ___XX__X,X__XX___,________,
  ___XX__X,X__XX___,________,
  ___XX__X,X__XX___,________,
  ___XX_XX,___XX___,________,
  ______XX,XXX_____,________,
  _____XX_,__XX____,________,
  ___XXX__,___XX___,________,
  _XXX____,____XX__,________};

GUI_CONST_STORAGE unsigned char acGUI_FontHZ16_8F7D[ 48] = { /* code 8F7D */
  ____XX__,__XX____,________,
  ____XX__,__XXXX__,________,
  _XXXXXXX,X_XX_XX_,________,
  ____XX__,__XX____,________,
  XXXXXXXX,XXXXXXXX,________,
  ___XX___,__XX____,________,
  ___XX___,__XX_XX_,________,
  XXXXXXXX,X_XX_XX_,________,
  __XX____,__XX_XX_,________,
  _XX_XX__,__XXXX__,________,
  _XXXXXXX,X_XXXX__,________,
  ____XX__,___XX___,________,
  ____XXXX,X__XX_XX,________,
  XXXXXX__,__XXXXXX,________,
  ____XX__,_XX__XXX,________,
  ____XX__,XX____XX,________};

GUI_CONST_STORAGE unsigned char acGUI_FontHZ16_8FC7[ 48] = { /* code 8FC7 */
  ________,___XX___,________,
  __XX____,___XX___,________,
  ___XX___,___XX___,________,
  ___XXXXX,XXXXXXXX,________,
  ________,___XX___,________,
  ________,___XX___,________,
  XXXXX_XX,___XX___,________,
  ___XX__X,X__XX___,________,
  ___XX__X,X__XX___,________,
  ___XX___,___XX___,________,
  ___XX___,___XX___,________,
  ___XX___,_XXXX___,________,
  ___XX___,__XX____,________,
  __XXXX__,________,________,
  _XX__XXX,XXXXXXXX,________,
  ________,________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontHZ16_963B[ 48] = { /* code 963B */
  ________,________,________,
  _XXXXXXX,XXXXXX__,________,
  _XX__XXX,X___XX__,________,
  _XX_XX_X,X___XX__,________,
  _XX_XX_X,X___XX__,________,
  _XXXX__X,XXXXXX__,________,
  _XX_XX_X,X___XX__,________,
  _XX_XX_X,X___XX__,________,
  _XX__XXX,X___XX__,________,
  _XX__XXX,XXXXXX__,________,
  _XX__XXX,X___XX__,________,
  _XXXXX_X,X___XX__,________,
  _XXXX__X,X___XX__,________,
  _XX____X,X___XX__,________,
  _XX__XXX,XXXXXXXX,________,
  _XX_____,________,________};

GUI_CONST_STORAGE GUI_CHARINFO GUI_FontHZ16_CharInfo[56] = {
   {  17,  17,  3, acGUI_FontHZ16_03A9 } /* code 03A9 */
  ,{  17,  17,  3, acGUI_FontHZ16_4E2D } /* code 4E2D */
  ,{  17,  17,  3, acGUI_FontHZ16_4E3B } /* code 4E3B */
  ,{  17,  17,  3, acGUI_FontHZ16_4FDD } /* code 4FDD */
  ,{  17,  17,  3, acGUI_FontHZ16_503C } /* code 503C */
  ,{  17,  17,  3, acGUI_FontHZ16_505C } /* code 505C */
  ,{  17,  17,  3, acGUI_FontHZ16_5145 } /* code 5145 */
  ,{  17,  17,  3, acGUI_FontHZ16_5185 } /* code 5185 */
  ,{  17,  17,  3, acGUI_FontHZ16_5217 } /* code 5217 */
  ,{  17,  17,  3, acGUI_FontHZ16_52A8 } /* code 52A8 */
  ,{  17,  17,  3, acGUI_FontHZ16_5355 } /* code 5355 */
  ,{  17,  17,  3, acGUI_FontHZ16_538B } /* code 538B */
  ,{  17,  17,  3, acGUI_FontHZ16_53D6 } /* code 53D6 */
  ,{  17,  17,  3, acGUI_FontHZ16_53F7 } /* code 53F7 */
  ,{  17,  17,  3, acGUI_FontHZ16_5426 } /* code 5426 */
  ,{  17,  17,  3, acGUI_FontHZ16_59CB } /* code 59CB */
  ,{  17,  17,  3, acGUI_FontHZ16_5B50 } /* code 5B50 */
  ,{  17,  17,  3, acGUI_FontHZ16_5B58 } /* code 5B58 */
  ,{  17,  17,  3, acGUI_FontHZ16_5B9A } /* code 5B9A */
  ,{  17,  17,  3, acGUI_FontHZ16_5F00 } /* code 5F00 */
  ,{  17,  17,  3, acGUI_FontHZ16_5F0F } /* code 5F0F */
  ,{  17,  17,  3, acGUI_FontHZ16_6001 } /* code 6001 */
  ,{  17,  17,  3, acGUI_FontHZ16_62A4 } /* code 62A4 */
  ,{  17,  17,  3, acGUI_FontHZ16_63A7 } /* code 63A7 */
  ,{  17,  17,  3, acGUI_FontHZ16_653E } /* code 653E */
  ,{  17,  17,  3, acGUI_FontHZ16_6587 } /* code 6587 */
  ,{  17,  17,  3, acGUI_FontHZ16_662F } /* code 662F */
  ,{  17,  17,  3, acGUI_FontHZ16_66F2 } /* code 66F2 */
  ,{  17,  17,  3, acGUI_FontHZ16_679C } /* code 679C */
  ,{  17,  17,  3, acGUI_FontHZ16_6A21 } /* code 6A21 */
  ,{  17,  17,  3, acGUI_FontHZ16_6B62 } /* code 6B62 */
  ,{  17,  17,  3, acGUI_FontHZ16_6D41 } /* code 6D41 */
  ,{  17,  17,  3, acGUI_FontHZ16_6D4B } /* code 6D4B */
  ,{  17,  17,  3, acGUI_FontHZ16_6E90 } /* code 6E90 */
  ,{  17,  17,  3, acGUI_FontHZ16_7535 } /* code 7535 */
  ,{  17,  17,  3, acGUI_FontHZ16_786E } /* code 786E */
  ,{  17,  17,  3, acGUI_FontHZ16_7A0B } /* code 7A0B */
  ,{  17,  17,  3, acGUI_FontHZ16_7C7B } /* code 7C7B */
  ,{  17,  17,  3, acGUI_FontHZ16_7CFB } /* code 7CFB */
  ,{  17,  17,  3, acGUI_FontHZ16_7EBF } /* code 7EBF */
  ,{  17,  17,  3, acGUI_FontHZ16_7ED3 } /* code 7ED3 */
  ,{  17,  17,  3, acGUI_FontHZ16_7EDF } /* code 7EDF */
  ,{  17,  17,  3, acGUI_FontHZ16_7F6E } /* code 7F6E */
  ,{  17,  17,  3, acGUI_FontHZ16_81EA } /* code 81EA */
  ,{  17,  17,  3, acGUI_FontHZ16_82F1 } /* code 82F1 */
  ,{  17,  17,  3, acGUI_FontHZ16_83DC } /* code 83DC */
  ,{  17,  17,  3, acGUI_FontHZ16_8868 } /* code 8868 */
  ,{  17,  17,  3, acGUI_FontHZ16_8A00 } /* code 8A00 */
  ,{  17,  17,  3, acGUI_FontHZ16_8BBE } /* code 8BBE */
  ,{  17,  17,  3, acGUI_FontHZ16_8BD5 } /* code 8BD5 */
  ,{  17,  17,  3, acGUI_FontHZ16_8BED } /* code 8BED */
  ,{  17,  17,  3, acGUI_FontHZ16_8BFB } /* code 8BFB */
  ,{  17,  17,  3, acGUI_FontHZ16_8D1F } /* code 8D1F */
  ,{  17,  17,  3, acGUI_FontHZ16_8F7D } /* code 8F7D */
  ,{  17,  17,  3, acGUI_FontHZ16_8FC7 } /* code 8FC7 */
  ,{  17,  17,  3, acGUI_FontHZ16_963B } /* code 963B */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontHZ16_Prop56 = {
   0x963B /* first character */
  ,0x963B /* last character  */
  ,&GUI_FontHZ16_CharInfo[ 55] /* address of first character */
  ,(GUI_CONST_STORAGE GUI_FONT_PROP *)0 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontHZ16_Prop55 = {
   0x8FC7 /* first character */
  ,0x8FC7 /* last character  */
  ,&GUI_FontHZ16_CharInfo[ 54] /* address of first character */
  ,&GUI_FontHZ16_Prop56 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontHZ16_Prop54 = {
   0x8F7D /* first character */
  ,0x8F7D /* last character  */
  ,&GUI_FontHZ16_CharInfo[ 53] /* address of first character */
  ,&GUI_FontHZ16_Prop55 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontHZ16_Prop53 = {
   0x8D1F /* first character */
  ,0x8D1F /* last character  */
  ,&GUI_FontHZ16_CharInfo[ 52] /* address of first character */
  ,&GUI_FontHZ16_Prop54 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontHZ16_Prop52 = {
   0x8BFB /* first character */
  ,0x8BFB /* last character  */
  ,&GUI_FontHZ16_CharInfo[ 51] /* address of first character */
  ,&GUI_FontHZ16_Prop53 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontHZ16_Prop51 = {
   0x8BED /* first character */
  ,0x8BED /* last character  */
  ,&GUI_FontHZ16_CharInfo[ 50] /* address of first character */
  ,&GUI_FontHZ16_Prop52 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontHZ16_Prop50 = {
   0x8BD5 /* first character */
  ,0x8BD5 /* last character  */
  ,&GUI_FontHZ16_CharInfo[ 49] /* address of first character */
  ,&GUI_FontHZ16_Prop51 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontHZ16_Prop49 = {
   0x8BBE /* first character */
  ,0x8BBE /* last character  */
  ,&GUI_FontHZ16_CharInfo[ 48] /* address of first character */
  ,&GUI_FontHZ16_Prop50 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontHZ16_Prop48 = {
   0x8A00 /* first character */
  ,0x8A00 /* last character  */
  ,&GUI_FontHZ16_CharInfo[ 47] /* address of first character */
  ,&GUI_FontHZ16_Prop49 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontHZ16_Prop47 = {
   0x8868 /* first character */
  ,0x8868 /* last character  */
  ,&GUI_FontHZ16_CharInfo[ 46] /* address of first character */
  ,&GUI_FontHZ16_Prop48 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontHZ16_Prop46 = {
   0x83DC /* first character */
  ,0x83DC /* last character  */
  ,&GUI_FontHZ16_CharInfo[ 45] /* address of first character */
  ,&GUI_FontHZ16_Prop47 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontHZ16_Prop45 = {
   0x82F1 /* first character */
  ,0x82F1 /* last character  */
  ,&GUI_FontHZ16_CharInfo[ 44] /* address of first character */
  ,&GUI_FontHZ16_Prop46 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontHZ16_Prop44 = {
   0x81EA /* first character */
  ,0x81EA /* last character  */
  ,&GUI_FontHZ16_CharInfo[ 43] /* address of first character */
  ,&GUI_FontHZ16_Prop45 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontHZ16_Prop43 = {
   0x7F6E /* first character */
  ,0x7F6E /* last character  */
  ,&GUI_FontHZ16_CharInfo[ 42] /* address of first character */
  ,&GUI_FontHZ16_Prop44 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontHZ16_Prop42 = {
   0x7EDF /* first character */
  ,0x7EDF /* last character  */
  ,&GUI_FontHZ16_CharInfo[ 41] /* address of first character */
  ,&GUI_FontHZ16_Prop43 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontHZ16_Prop41 = {
   0x7ED3 /* first character */
  ,0x7ED3 /* last character  */
  ,&GUI_FontHZ16_CharInfo[ 40] /* address of first character */
  ,&GUI_FontHZ16_Prop42 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontHZ16_Prop40 = {
   0x7EBF /* first character */
  ,0x7EBF /* last character  */
  ,&GUI_FontHZ16_CharInfo[ 39] /* address of first character */
  ,&GUI_FontHZ16_Prop41 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontHZ16_Prop39 = {
   0x7CFB /* first character */
  ,0x7CFB /* last character  */
  ,&GUI_FontHZ16_CharInfo[ 38] /* address of first character */
  ,&GUI_FontHZ16_Prop40 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontHZ16_Prop38 = {
   0x7C7B /* first character */
  ,0x7C7B /* last character  */
  ,&GUI_FontHZ16_CharInfo[ 37] /* address of first character */
  ,&GUI_FontHZ16_Prop39 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontHZ16_Prop37 = {
   0x7A0B /* first character */
  ,0x7A0B /* last character  */
  ,&GUI_FontHZ16_CharInfo[ 36] /* address of first character */
  ,&GUI_FontHZ16_Prop38 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontHZ16_Prop36 = {
   0x786E /* first character */
  ,0x786E /* last character  */
  ,&GUI_FontHZ16_CharInfo[ 35] /* address of first character */
  ,&GUI_FontHZ16_Prop37 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontHZ16_Prop35 = {
   0x7535 /* first character */
  ,0x7535 /* last character  */
  ,&GUI_FontHZ16_CharInfo[ 34] /* address of first character */
  ,&GUI_FontHZ16_Prop36 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontHZ16_Prop34 = {
   0x6E90 /* first character */
  ,0x6E90 /* last character  */
  ,&GUI_FontHZ16_CharInfo[ 33] /* address of first character */
  ,&GUI_FontHZ16_Prop35 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontHZ16_Prop33 = {
   0x6D4B /* first character */
  ,0x6D4B /* last character  */
  ,&GUI_FontHZ16_CharInfo[ 32] /* address of first character */
  ,&GUI_FontHZ16_Prop34 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontHZ16_Prop32 = {
   0x6D41 /* first character */
  ,0x6D41 /* last character  */
  ,&GUI_FontHZ16_CharInfo[ 31] /* address of first character */
  ,&GUI_FontHZ16_Prop33 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontHZ16_Prop31 = {
   0x6B62 /* first character */
  ,0x6B62 /* last character  */
  ,&GUI_FontHZ16_CharInfo[ 30] /* address of first character */
  ,&GUI_FontHZ16_Prop32 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontHZ16_Prop30 = {
   0x6A21 /* first character */
  ,0x6A21 /* last character  */
  ,&GUI_FontHZ16_CharInfo[ 29] /* address of first character */
  ,&GUI_FontHZ16_Prop31 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontHZ16_Prop29 = {
   0x679C /* first character */
  ,0x679C /* last character  */
  ,&GUI_FontHZ16_CharInfo[ 28] /* address of first character */
  ,&GUI_FontHZ16_Prop30 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontHZ16_Prop28 = {
   0x66F2 /* first character */
  ,0x66F2 /* last character  */
  ,&GUI_FontHZ16_CharInfo[ 27] /* address of first character */
  ,&GUI_FontHZ16_Prop29 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontHZ16_Prop27 = {
   0x662F /* first character */
  ,0x662F /* last character  */
  ,&GUI_FontHZ16_CharInfo[ 26] /* address of first character */
  ,&GUI_FontHZ16_Prop28 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontHZ16_Prop26 = {
   0x6587 /* first character */
  ,0x6587 /* last character  */
  ,&GUI_FontHZ16_CharInfo[ 25] /* address of first character */
  ,&GUI_FontHZ16_Prop27 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontHZ16_Prop25 = {
   0x653E /* first character */
  ,0x653E /* last character  */
  ,&GUI_FontHZ16_CharInfo[ 24] /* address of first character */
  ,&GUI_FontHZ16_Prop26 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontHZ16_Prop24 = {
   0x63A7 /* first character */
  ,0x63A7 /* last character  */
  ,&GUI_FontHZ16_CharInfo[ 23] /* address of first character */
  ,&GUI_FontHZ16_Prop25 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontHZ16_Prop23 = {
   0x62A4 /* first character */
  ,0x62A4 /* last character  */
  ,&GUI_FontHZ16_CharInfo[ 22] /* address of first character */
  ,&GUI_FontHZ16_Prop24 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontHZ16_Prop22 = {
   0x6001 /* first character */
  ,0x6001 /* last character  */
  ,&GUI_FontHZ16_CharInfo[ 21] /* address of first character */
  ,&GUI_FontHZ16_Prop23 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontHZ16_Prop21 = {
   0x5F0F /* first character */
  ,0x5F0F /* last character  */
  ,&GUI_FontHZ16_CharInfo[ 20] /* address of first character */
  ,&GUI_FontHZ16_Prop22 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontHZ16_Prop20 = {
   0x5F00 /* first character */
  ,0x5F00 /* last character  */
  ,&GUI_FontHZ16_CharInfo[ 19] /* address of first character */
  ,&GUI_FontHZ16_Prop21 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontHZ16_Prop19 = {
   0x5B9A /* first character */
  ,0x5B9A /* last character  */
  ,&GUI_FontHZ16_CharInfo[ 18] /* address of first character */
  ,&GUI_FontHZ16_Prop20 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontHZ16_Prop18 = {
   0x5B58 /* first character */
  ,0x5B58 /* last character  */
  ,&GUI_FontHZ16_CharInfo[ 17] /* address of first character */
  ,&GUI_FontHZ16_Prop19 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontHZ16_Prop17 = {
   0x5B50 /* first character */
  ,0x5B50 /* last character  */
  ,&GUI_FontHZ16_CharInfo[ 16] /* address of first character */
  ,&GUI_FontHZ16_Prop18 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontHZ16_Prop16 = {
   0x59CB /* first character */
  ,0x59CB /* last character  */
  ,&GUI_FontHZ16_CharInfo[ 15] /* address of first character */
  ,&GUI_FontHZ16_Prop17 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontHZ16_Prop15 = {
   0x5426 /* first character */
  ,0x5426 /* last character  */
  ,&GUI_FontHZ16_CharInfo[ 14] /* address of first character */
  ,&GUI_FontHZ16_Prop16 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontHZ16_Prop14 = {
   0x53F7 /* first character */
  ,0x53F7 /* last character  */
  ,&GUI_FontHZ16_CharInfo[ 13] /* address of first character */
  ,&GUI_FontHZ16_Prop15 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontHZ16_Prop13 = {
   0x53D6 /* first character */
  ,0x53D6 /* last character  */
  ,&GUI_FontHZ16_CharInfo[ 12] /* address of first character */
  ,&GUI_FontHZ16_Prop14 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontHZ16_Prop12 = {
   0x538B /* first character */
  ,0x538B /* last character  */
  ,&GUI_FontHZ16_CharInfo[ 11] /* address of first character */
  ,&GUI_FontHZ16_Prop13 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontHZ16_Prop11 = {
   0x5355 /* first character */
  ,0x5355 /* last character  */
  ,&GUI_FontHZ16_CharInfo[ 10] /* address of first character */
  ,&GUI_FontHZ16_Prop12 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontHZ16_Prop10 = {
   0x52A8 /* first character */
  ,0x52A8 /* last character  */
  ,&GUI_FontHZ16_CharInfo[  9] /* address of first character */
  ,&GUI_FontHZ16_Prop11 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontHZ16_Prop9 = {
   0x5217 /* first character */
  ,0x5217 /* last character  */
  ,&GUI_FontHZ16_CharInfo[  8] /* address of first character */
  ,&GUI_FontHZ16_Prop10 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontHZ16_Prop8 = {
   0x5185 /* first character */
  ,0x5185 /* last character  */
  ,&GUI_FontHZ16_CharInfo[  7] /* address of first character */
  ,&GUI_FontHZ16_Prop9 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontHZ16_Prop7 = {
   0x5145 /* first character */
  ,0x5145 /* last character  */
  ,&GUI_FontHZ16_CharInfo[  6] /* address of first character */
  ,&GUI_FontHZ16_Prop8 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontHZ16_Prop6 = {
   0x505C /* first character */
  ,0x505C /* last character  */
  ,&GUI_FontHZ16_CharInfo[  5] /* address of first character */
  ,&GUI_FontHZ16_Prop7 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontHZ16_Prop5 = {
   0x503C /* first character */
  ,0x503C /* last character  */
  ,&GUI_FontHZ16_CharInfo[  4] /* address of first character */
  ,&GUI_FontHZ16_Prop6 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontHZ16_Prop4 = {
   0x4FDD /* first character */
  ,0x4FDD /* last character  */
  ,&GUI_FontHZ16_CharInfo[  3] /* address of first character */
  ,&GUI_FontHZ16_Prop5 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontHZ16_Prop3 = {
   0x4E3B /* first character */
  ,0x4E3B /* last character  */
  ,&GUI_FontHZ16_CharInfo[  2] /* address of first character */
  ,&GUI_FontHZ16_Prop4 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontHZ16_Prop2 = {
   0x4E2D /* first character */
  ,0x4E2D /* last character  */
  ,&GUI_FontHZ16_CharInfo[  1] /* address of first character */
  ,&GUI_FontHZ16_Prop3 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontHZ16_Prop1 = {
   0x03A9 /* first character */
  ,0x03A9 /* last character  */
  ,&GUI_FontHZ16_CharInfo[  0] /* address of first character */
  ,&GUI_FontHZ16_Prop2 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT GUI_FontHZ16 = {
   GUI_FONTTYPE_PROP /* type of font    */
  ,16 /* height of font  */
  ,16 /* space of font y */
  ,1 /* magnification x */
  ,1 /* magnification y */
  ,{&GUI_FontHZ16_Prop1}
  ,14 /* Baseline */
  ,7 /* Height of lowercase characters */
  ,11 /* Height of capital characters */
};

