/*********************************************************************
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                           www.segger.com                           *
**********************************************************************
*                                                                    *
* C-file generated by                                                *
*                                                                    *
*        emWin Font Converter (ST) version 5.32                      *
*        Compiled Oct  8 2015, 11:58:55                              *
*                                                                    *
*        (c) 1998 - 2015 Segger Microcontroller GmbH & Co. KG        *
*                                                                    *
**********************************************************************
*                                                                    *
* Source file: SONGB12.c                                             *
* Font:        ËÎÌו                                                  *
* Height:      12                                                    *
*                                                                    *
**********************************************************************
*                                                                    *
* Initial font height:  12                                           *
* Range disabled:       0000 - FFFF                                  *
* Read pattern file: C:\Users\Administrator\Desktop\123.txt          *
*                                                                    *
**********************************************************************
*/

#include "GUI.h"

#ifndef GUI_CONST_STORAGE
  #define GUI_CONST_STORAGE const
#endif

/* The following line needs to be included in any file selecting the
   font.
*/
extern GUI_CONST_STORAGE GUI_FONT GUI_FontSONGB12;

/* Start of unicode area <Basic Latin> */
GUI_CONST_STORAGE unsigned char acGUI_FontSONGB12_0021[  8] = { /* code 0021, EXCLAMATION MARK */
  XX______,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______,
  ________,
  XX______};

GUI_CONST_STORAGE unsigned char acGUI_FontSONGB12_0022[  3] = { /* code 0022, QUOTATION MARK */
  _XXXX___,
  XXXX____,
  XXXX____};

GUI_CONST_STORAGE unsigned char acGUI_FontSONGB12_0023[  8] = { /* code 0023, NUMBER SIGN */
  __XXXX__,
  __XXXX__,
  XXXXXXX_,
  __XXXX__,
  _XXXX___,
  XXXXXXX_,
  _XXXX___,
  _XXXX___};

GUI_CONST_STORAGE unsigned char acGUI_FontSONGB12_0024[ 10] = { /* code 0024, DOLLAR SIGN */
  __XX____,
  _XXXXX__,
  XXXXXX__,
  XXXX____,
  _XXX____,
  __XXX___,
  __XXXX__,
  XXXXXX__,
  XXXXX___,
  __XX____};

GUI_CONST_STORAGE unsigned char acGUI_FontSONGB12_0025[  8] = { /* code 0025, PERCENT SIGN */
  _XX_XX__,
  XXXXXX__,
  XXXXX___,
  _XXXX___,
  __XXXX__,
  __XXXXX_,
  _XXXXXX_,
  _XX_XX__};

GUI_CONST_STORAGE unsigned char acGUI_FontSONGB12_0026[  8] = { /* code 0026, AMPERSAND */
  __XX____,
  _XXXX___,
  _XXXX___,
  _XXXXX__,
  XXXXXX__,
  XXXXXX__,
  XX_XX___,
  _XXXXXX_};

GUI_CONST_STORAGE unsigned char acGUI_FontSONGB12_0028[ 10] = { /* code 0028, LEFT PARENTHESIS */
  __XX____,
  _XX_____,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______,
  _XX_____,
  __XX____};

GUI_CONST_STORAGE unsigned char acGUI_FontSONGB12_0029[ 10] = { /* code 0029, RIGHT PARENTHESIS */
  XX______,
  _XX_____,
  __XX____,
  __XX____,
  __XX____,
  __XX____,
  __XX____,
  __XX____,
  _XX_____,
  XX______};

GUI_CONST_STORAGE unsigned char acGUI_FontSONGB12_002A[  6] = { /* code 002A, ASTERISK */
  __XX____,
  XXXXXX__,
  _XXXX___,
  _XXXX___,
  XXXXXX__,
  __XX____};

GUI_CONST_STORAGE unsigned char acGUI_FontSONGB12_002B[  7] = { /* code 002B, PLUS SIGN */
  __XX____,
  __XX____,
  __XX____,
  XXXXXX__,
  __XX____,
  __XX____,
  __XX____};

GUI_CONST_STORAGE unsigned char acGUI_FontSONGB12_002C[  3] = { /* code 002C, COMMA */
  _XX_____,
  _XX_____,
  XX______};

GUI_CONST_STORAGE unsigned char acGUI_FontSONGB12_002D[  1] = { /* code 002D, HYPHEN-MINUS */
  XXXXXX__};

GUI_CONST_STORAGE unsigned char acGUI_FontSONGB12_002E[  1] = { /* code 002E, FULL STOP */
  XX______};

GUI_CONST_STORAGE unsigned char acGUI_FontSONGB12_002F[ 10] = { /* code 002F, SOLIDUS */
  ____XX__,
  ___XX___,
  ___XX___,
  ___XX___,
  __XX____,
  __XX____,
  _XX_____,
  _XX_____,
  _XX_____,
  XX______};

GUI_CONST_STORAGE unsigned char acGUI_FontSONGB12_0030[  8] = { /* code 0030, DIGIT ZERO */
  _XXXX___,
  XX__XX__,
  XX__XX__,
  XX__XX__,
  XX__XX__,
  XX__XX__,
  XX__XX__,
  _XXXX___};

GUI_CONST_STORAGE unsigned char acGUI_FontSONGB12_0031[  8] = { /* code 0031, DIGIT ONE */
  _XX_____,
  XXX_____,
  _XX_____,
  _XX_____,
  _XX_____,
  _XX_____,
  _XX_____,
  XXXX____};

GUI_CONST_STORAGE unsigned char acGUI_FontSONGB12_0032[  8] = { /* code 0032, DIGIT TWO */
  _XXXX___,
  XX__XX__,
  XX__XX__,
  ___XX___,
  __XX____,
  _XX_____,
  XX______,
  XXXXXX__};

GUI_CONST_STORAGE unsigned char acGUI_FontSONGB12_0033[  8] = { /* code 0033, DIGIT THREE */
  _XXXX___,
  XX__XX__,
  ____XX__,
  __XXX___,
  ____XX__,
  ____XX__,
  XX__XX__,
  _XXXX___};

GUI_CONST_STORAGE unsigned char acGUI_FontSONGB12_0034[  8] = { /* code 0034, DIGIT FOUR */
  ___XX___,
  __XXX___,
  _XXXX___,
  _XXXX___,
  XX_XX___,
  _XXXXX__,
  ___XX___,
  ___XXX__};

GUI_CONST_STORAGE unsigned char acGUI_FontSONGB12_0035[  8] = { /* code 0035, DIGIT FIVE */
  XXXXXX__,
  XX______,
  XX______,
  XXXXX___,
  ____XX__,
  ____XX__,
  XX__XX__,
  _XXXX___};

GUI_CONST_STORAGE unsigned char acGUI_FontSONGB12_0036[  8] = { /* code 0036, DIGIT SIX */
  _XXXX___,
  XX_XX___,
  XX______,
  XXXXX___,
  XX__XX__,
  XX__XX__,
  XX__XX__,
  _XXXX___};

GUI_CONST_STORAGE unsigned char acGUI_FontSONGB12_0037[  8] = { /* code 0037, DIGIT SEVEN */
  XXXXXX__,
  XX_XX___,
  ___XX___,
  __XX____,
  __XX____,
  __XX____,
  __XX____,
  __XX____};

GUI_CONST_STORAGE unsigned char acGUI_FontSONGB12_0038[  8] = { /* code 0038, DIGIT EIGHT */
  _XXXX___,
  XX__XX__,
  XX__XX__,
  _XXXX___,
  XX__XX__,
  XX__XX__,
  XX__XX__,
  _XXXX___};

GUI_CONST_STORAGE unsigned char acGUI_FontSONGB12_0039[  8] = { /* code 0039, DIGIT NINE */
  _XXXX___,
  XX__XX__,
  XX__XX__,
  XX__XX__,
  _XXXXX__,
  ____XX__,
  _XX_XX__,
  _XXXX___};

GUI_CONST_STORAGE unsigned char acGUI_FontSONGB12_003A[  6] = { /* code 003A, COLON */
  XX______,
  ________,
  ________,
  ________,
  ________,
  XX______};

GUI_CONST_STORAGE unsigned char acGUI_FontSONGB12_003B[  6] = { /* code 003B, SEMICOLON */
  XX______,
  ________,
  ________,
  ________,
  XX______,
  XX______};

GUI_CONST_STORAGE unsigned char acGUI_FontSONGB12_003C[  9] = { /* code 003C, LESS-THAN SIGN */
  ____XX__,
  ___XX___,
  __XX____,
  _XX_____,
  XX______,
  _XX_____,
  __XX____,
  ___XX___,
  ____XX__};

GUI_CONST_STORAGE unsigned char acGUI_FontSONGB12_003D[  4] = { /* code 003D, EQUALS SIGN */
  XXXXXX__,
  ________,
  ________,
  XXXXXX__};

GUI_CONST_STORAGE unsigned char acGUI_FontSONGB12_003E[  9] = { /* code 003E, GREATER-THAN SIGN */
  XX______,
  _XX_____,
  __XX____,
  ___XX___,
  ____XX__,
  ___XX___,
  __XX____,
  _XX_____,
  XX______};

GUI_CONST_STORAGE unsigned char acGUI_FontSONGB12_003F[  8] = { /* code 003F, QUESTION MARK */
  _XXXX___,
  XX__XX__,
  XX__XX__,
  ___XX___,
  __XX____,
  __XX____,
  ________,
  __XX____};

GUI_CONST_STORAGE unsigned char acGUI_FontSONGB12_0040[  8] = { /* code 0040, COMMERCIAL AT */
  _XXXX___,
  XX__XX__,
  XX_XXX__,
  XXXXXX__,
  XXXXXX__,
  XXXXXX__,
  XX______,
  _XXXXX__};

GUI_CONST_STORAGE unsigned char acGUI_FontSONGB12_0041[  8] = { /* code 0041, LATIN CAPITAL LETTER A */
  __XX____,
  __XX____,
  __XXX___,
  _XXXX___,
  _XXXX___,
  _XXXXX__,
  _XX_XX__,
  XXX_XXX_};

GUI_CONST_STORAGE unsigned char acGUI_FontSONGB12_0042[  8] = { /* code 0042, LATIN CAPITAL LETTER B */
  XXXXX___,
  _XX_XX__,
  _XX_XX__,
  _XXXX___,
  _XX_XX__,
  _XX_XX__,
  _XX_XX__,
  XXXXX___};

GUI_CONST_STORAGE unsigned char acGUI_FontSONGB12_0043[  8] = { /* code 0043, LATIN CAPITAL LETTER C */
  _XXXXX__,
  XX__XX__,
  XX______,
  XX______,
  XX______,
  XX______,
  XX__XX__,
  _XXXX___};

GUI_CONST_STORAGE unsigned char acGUI_FontSONGB12_0044[  8] = { /* code 0044, LATIN CAPITAL LETTER D */
  XXXXX___,
  _XX_XX__,
  _XX_XX__,
  _XX_XX__,
  _XX_XX__,
  _XX_XX__,
  _XX_XX__,
  XXXXX___};

GUI_CONST_STORAGE unsigned char acGUI_FontSONGB12_0045[  8] = { /* code 0045, LATIN CAPITAL LETTER E */
  XXXXXX__,
  _XX_XX__,
  _XXXX___,
  _XXXX___,
  _XXXX___,
  _XX_____,
  _XX_XX__,
  XXXXXX__};

GUI_CONST_STORAGE unsigned char acGUI_FontSONGB12_0046[  8] = { /* code 0046, LATIN CAPITAL LETTER F */
  XXXXXX__,
  _XX_XX__,
  _XXXX___,
  _XXXX___,
  _XXXX___,
  _XX_____,
  _XX_____,
  XXXX____};

GUI_CONST_STORAGE unsigned char acGUI_FontSONGB12_0047[  8] = { /* code 0047, LATIN CAPITAL LETTER G */
  __XXXX__,
  _XX_XX__,
  XX______,
  XX______,
  XX_XXXX_,
  XX__XX__,
  _XX_XX__,
  __XXX___};

GUI_CONST_STORAGE unsigned char acGUI_FontSONGB12_0048[  8] = { /* code 0048, LATIN CAPITAL LETTER H */
  XXX_XXX_,
  _XX_XX__,
  _XX_XX__,
  _XXXXX__,
  _XX_XX__,
  _XX_XX__,
  _XX_XX__,
  XXX_XXX_};

GUI_CONST_STORAGE unsigned char acGUI_FontSONGB12_0049[  8] = { /* code 0049, LATIN CAPITAL LETTER I */
  XXXXXX__,
  __XX____,
  __XX____,
  __XX____,
  __XX____,
  __XX____,
  __XX____,
  XXXXXX__};

GUI_CONST_STORAGE unsigned char acGUI_FontSONGB12_004A[  9] = { /* code 004A, LATIN CAPITAL LETTER J */
  _XXXXXX_,
  ___XX___,
  ___XX___,
  ___XX___,
  ___XX___,
  ___XX___,
  ___XX___,
  XX_XX___,
  XXXX____};

GUI_CONST_STORAGE unsigned char acGUI_FontSONGB12_004B[  8] = { /* code 004B, LATIN CAPITAL LETTER K */
  XXXXXXX_,
  _XX_XX__,
  _XXXX___,
  _XXX____,
  _XXXX___,
  _XXXX___,
  _XX_XX__,
  XXXXXXX_};

GUI_CONST_STORAGE unsigned char acGUI_FontSONGB12_004C[  8] = { /* code 004C, LATIN CAPITAL LETTER L */
  XXXX____,
  _XX_____,
  _XX_____,
  _XX_____,
  _XX_____,
  _XX_____,
  _XX__XX_,
  XXXXXXX_};

GUI_CONST_STORAGE unsigned char acGUI_FontSONGB12_004D[  8] = { /* code 004D, LATIN CAPITAL LETTER M */
  XXXXXX__,
  XXXXXX__,
  XXXXXX__,
  XXXXXX__,
  XXXXXX__,
  XXXXXX__,
  XXXXXX__,
  XXXXXX__};

GUI_CONST_STORAGE unsigned char acGUI_FontSONGB12_004E[  8] = { /* code 004E, LATIN CAPITAL LETTER N */
  XXXXXXX_,
  _XX_XX__,
  _XXXXX__,
  _XXXXX__,
  _XXXXX__,
  _XXXXX__,
  _XX_XX__,
  XXXXXX__};

GUI_CONST_STORAGE unsigned char acGUI_FontSONGB12_004F[  8] = { /* code 004F, LATIN CAPITAL LETTER O */
  _XXXX___,
  XX__XX__,
  XX__XX__,
  XX__XX__,
  XX__XX__,
  XX__XX__,
  XX__XX__,
  _XXXX___};

GUI_CONST_STORAGE unsigned char acGUI_FontSONGB12_0050[  8] = { /* code 0050, LATIN CAPITAL LETTER P */
  XXXXX___,
  _XX_XX__,
  _XX_XX__,
  _XXXX___,
  _XX_____,
  _XX_____,
  _XX_____,
  XXXX____};

GUI_CONST_STORAGE unsigned char acGUI_FontSONGB12_0051[  9] = { /* code 0051, LATIN CAPITAL LETTER Q */
  _XXXX___,
  XX__XX__,
  XX__XX__,
  XX__XX__,
  XX__XX__,
  XXXXXX__,
  XX_XXX__,
  _XXXX___,
  ___XXX__};

GUI_CONST_STORAGE unsigned char acGUI_FontSONGB12_0052[  8] = { /* code 0052, LATIN CAPITAL LETTER R */
  XXXXX___,
  _XX_XX__,
  _XX_XX__,
  _XXXX___,
  _XXXX___,
  _XX_XX__,
  _XX_XX__,
  XXXXXXX_};

GUI_CONST_STORAGE unsigned char acGUI_FontSONGB12_0053[  8] = { /* code 0053, LATIN CAPITAL LETTER S */
  _XXXXX__,
  XX__XX__,
  XX______,
  _XXX____,
  ___XX___,
  ____XX__,
  XX__XX__,
  XXXXX___};

GUI_CONST_STORAGE unsigned char acGUI_FontSONGB12_0054[  8] = { /* code 0054, LATIN CAPITAL LETTER T */
  XXXXXX__,
  XXXXXX__,
  __XX____,
  __XX____,
  __XX____,
  __XX____,
  __XX____,
  _XXXX___};

GUI_CONST_STORAGE unsigned char acGUI_FontSONGB12_0055[  8] = { /* code 0055, LATIN CAPITAL LETTER U */
  XXX_XXX_,
  _XX_XX__,
  _XX_XX__,
  _XX_XX__,
  _XX_XX__,
  _XX_XX__,
  _XX_XX__,
  __XXX___};

GUI_CONST_STORAGE unsigned char acGUI_FontSONGB12_0056[  8] = { /* code 0056, LATIN CAPITAL LETTER V */
  XXX_XXX_,
  _XX_XX__,
  _XX_XX__,
  _XXXX___,
  _XXXX___,
  __XXX___,
  __XX____,
  __XX____};

GUI_CONST_STORAGE unsigned char acGUI_FontSONGB12_0057[  8] = { /* code 0057, LATIN CAPITAL LETTER W */
  XXXXXX__,
  XXXXXX__,
  XXXXXX__,
  _XXXX___,
  _XXXX___,
  _XXXX___,
  _XXXX___,
  _XXXX___};

GUI_CONST_STORAGE unsigned char acGUI_FontSONGB12_0058[  8] = { /* code 0058, LATIN CAPITAL LETTER X */
  XXXXXX__,
  _XXXX___,
  _XXXX___,
  __XX____,
  __XX____,
  _XXXX___,
  _XXXX___,
  XXXXXX__};

GUI_CONST_STORAGE unsigned char acGUI_FontSONGB12_0059[  8] = { /* code 0059, LATIN CAPITAL LETTER Y */
  XXXXXX__,
  _XXXX___,
  _XXXX___,
  __XX____,
  __XX____,
  __XX____,
  __XX____,
  _XXXX___};

GUI_CONST_STORAGE unsigned char acGUI_FontSONGB12_005A[  8] = { /* code 005A, LATIN CAPITAL LETTER Z */
  XXXXXX__,
  XX_XX___,
  ___XX___,
  __XX____,
  __XX____,
  _XX_____,
  _XX_XX__,
  XXXXXX__};

GUI_CONST_STORAGE unsigned char acGUI_FontSONGB12_005B[ 10] = { /* code 005B, LEFT SQUARE BRACKET */
  XXXX____,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______,
  XXXX____};

GUI_CONST_STORAGE unsigned char acGUI_FontSONGB12_005C[ 10] = { /* code 005C, REVERSE SOLIDUS */
  XX______,
  XX______,
  XX______,
  _XX_____,
  _XX_____,
  __XX____,
  __XX____,
  __XX____,
  ___XX___,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontSONGB12_005D[ 10] = { /* code 005D, RIGHT SQUARE BRACKET */
  XXXX____,
  __XX____,
  __XX____,
  __XX____,
  __XX____,
  __XX____,
  __XX____,
  __XX____,
  __XX____,
  XXXX____};

GUI_CONST_STORAGE unsigned char acGUI_FontSONGB12_005E[  2] = { /* code 005E, CIRCUMFLEX ACCENT */
  _XX_____,
  XXXX____};

GUI_CONST_STORAGE unsigned char acGUI_FontSONGB12_005F[  1] = { /* code 005F, LOW LINE */
  XXXXXXX_};

GUI_CONST_STORAGE unsigned char acGUI_FontSONGB12_0061[  5] = { /* code 0061, LATIN SMALL LETTER A */
  _XXX____,
  XX_XX___,
  _XXXX___,
  XX_XX___,
  _XXXXX__};

GUI_CONST_STORAGE unsigned char acGUI_FontSONGB12_0062[  8] = { /* code 0062, LATIN SMALL LETTER B */
  XXX_____,
  _XX_____,
  _XX_____,
  _XXXX___,
  _XX_XX__,
  _XX_XX__,
  _XX_XX__,
  _XXXX___};

GUI_CONST_STORAGE unsigned char acGUI_FontSONGB12_0063[  5] = { /* code 0063, LATIN SMALL LETTER C */
  _XXXX___,
  XX_XX___,
  XX______,
  XX______,
  _XXXX___};

GUI_CONST_STORAGE unsigned char acGUI_FontSONGB12_0064[  8] = { /* code 0064, LATIN SMALL LETTER D */
  __XXX___,
  ___XX___,
  ___XX___,
  _XXXX___,
  XX_XX___,
  XX_XX___,
  XX_XX___,
  _XXXXX__};

GUI_CONST_STORAGE unsigned char acGUI_FontSONGB12_0065[  5] = { /* code 0065, LATIN SMALL LETTER E */
  _XXX____,
  XX_XX___,
  XXXXX___,
  XX______,
  _XXXX___};

GUI_CONST_STORAGE unsigned char acGUI_FontSONGB12_0066[  8] = { /* code 0066, LATIN SMALL LETTER F */
  __XXXX__,
  _XX_____,
  _XX_____,
  XXXXX___,
  _XX_____,
  _XX_____,
  _XX_____,
  XXXXX___};

GUI_CONST_STORAGE unsigned char acGUI_FontSONGB12_0067[  7] = { /* code 0067, LATIN SMALL LETTER G */
  _XXXXX__,
  XX_XX___,
  _XXX____,
  XX______,
  XXXXX___,
  XX__XX__,
  _XXXX___};

GUI_CONST_STORAGE unsigned char acGUI_FontSONGB12_0068[  8] = { /* code 0068, LATIN SMALL LETTER H */
  XXX_____,
  _XX_____,
  _XX_____,
  _XXXX___,
  _XX_XX__,
  _XX_XX__,
  _XX_XX__,
  XXXXXXX_};

GUI_CONST_STORAGE unsigned char acGUI_FontSONGB12_0069[  8] = { /* code 0069, LATIN SMALL LETTER I */
  _XX_____,
  ________,
  ________,
  XXX_____,
  _XX_____,
  _XX_____,
  _XX_____,
  XXXX____};

GUI_CONST_STORAGE unsigned char acGUI_FontSONGB12_006A[ 10] = { /* code 006A, LATIN SMALL LETTER J */
  ___XX___,
  ________,
  ________,
  __XXX___,
  ___XX___,
  ___XX___,
  ___XX___,
  ___XX___,
  ___XX___,
  XXXX____};

GUI_CONST_STORAGE unsigned char acGUI_FontSONGB12_006B[  8] = { /* code 006B, LATIN SMALL LETTER K */
  XXX_____,
  _XX_____,
  _XX_____,
  _XXXXXX_,
  _XXXX___,
  _XXXX___,
  _XX_XX__,
  XXXXXXX_};

GUI_CONST_STORAGE unsigned char acGUI_FontSONGB12_006C[  8] = { /* code 006C, LATIN SMALL LETTER L */
  XXXX____,
  __XX____,
  __XX____,
  __XX____,
  __XX____,
  __XX____,
  __XX____,
  XXXXXX__};

GUI_CONST_STORAGE unsigned char acGUI_FontSONGB12_006D[  5] = { /* code 006D, LATIN SMALL LETTER M */
  XXXXX___,
  XXXXXX__,
  XXXXXX__,
  XXXXXX__,
  XXXXXX__};

GUI_CONST_STORAGE unsigned char acGUI_FontSONGB12_006E[  5] = { /* code 006E, LATIN SMALL LETTER N */
  XXXXX___,
  _XX_XX__,
  _XX_XX__,
  _XX_XX__,
  XXXXXXX_};

GUI_CONST_STORAGE unsigned char acGUI_FontSONGB12_006F[  5] = { /* code 006F, LATIN SMALL LETTER O */
  _XXX____,
  XX_XX___,
  XX_XX___,
  XX_XX___,
  _XXX____};

GUI_CONST_STORAGE unsigned char acGUI_FontSONGB12_0070[  7] = { /* code 0070, LATIN SMALL LETTER P */
  XXXXX___,
  _XX_XX__,
  _XX_XX__,
  _XX_XX__,
  _XXXX___,
  _XX_____,
  XXXX____};

GUI_CONST_STORAGE unsigned char acGUI_FontSONGB12_0071[  7] = { /* code 0071, LATIN SMALL LETTER Q */
  _XXXX___,
  XX_XX___,
  XX_XX___,
  XX_XX___,
  _XXXX___,
  ___XX___,
  __XXXX__};

GUI_CONST_STORAGE unsigned char acGUI_FontSONGB12_0072[  5] = { /* code 0072, LATIN SMALL LETTER R */
  XXXXXX__,
  _XXX____,
  _XX_____,
  _XX_____,
  XXXX____};

GUI_CONST_STORAGE unsigned char acGUI_FontSONGB12_0073[  5] = { /* code 0073, LATIN SMALL LETTER S */
  XXXXX___,
  XX______,
  _XXX____,
  ___XX___,
  XXXXX___};

GUI_CONST_STORAGE unsigned char acGUI_FontSONGB12_0074[  7] = { /* code 0074, LATIN SMALL LETTER T */
  _XX_____,
  _XX_____,
  XXXX____,
  _XX_____,
  _XX_____,
  _XX_____,
  __XXX___};

GUI_CONST_STORAGE unsigned char acGUI_FontSONGB12_0075[  5] = { /* code 0075, LATIN SMALL LETTER U */
  XXXXXX__,
  _XX_XX__,
  _XX_XX__,
  _XX_XX__,
  __XXXXX_};

GUI_CONST_STORAGE unsigned char acGUI_FontSONGB12_0076[  5] = { /* code 0076, LATIN SMALL LETTER V */
  XXXXXXX_,
  _XX_XX__,
  _XXXX___,
  __XXX___,
  __XX____};

GUI_CONST_STORAGE unsigned char acGUI_FontSONGB12_0077[  5] = { /* code 0077, LATIN SMALL LETTER W */
  XXXXXX__,
  XXXXXX__,
  _XXXX___,
  _XXXX___,
  _XXXX___};

GUI_CONST_STORAGE unsigned char acGUI_FontSONGB12_0078[  5] = { /* code 0078, LATIN SMALL LETTER X */
  XXXXXX__,
  _XXXX___,
  __XX____,
  _XXXX___,
  XXXXXX__};

GUI_CONST_STORAGE unsigned char acGUI_FontSONGB12_0079[  7] = { /* code 0079, LATIN SMALL LETTER Y */
  XXXXXXX_,
  _XX_XX__,
  _XXXX___,
  __XXX___,
  __XX____,
  __XX____,
  XXX_____};

GUI_CONST_STORAGE unsigned char acGUI_FontSONGB12_007A[  5] = { /* code 007A, LATIN SMALL LETTER Z */
  XXXXX___,
  __XX____,
  _XX_____,
  _XX_____,
  XXXXX___};

GUI_CONST_STORAGE unsigned char acGUI_FontSONGB12_007B[ 10] = { /* code 007B, LEFT CURLY BRACKET */
  _XXX____,
  _XX_____,
  _XX_____,
  _XX_____,
  XX______,
  _XX_____,
  _XX_____,
  _XX_____,
  _XX_____,
  _XXX____};

GUI_CONST_STORAGE unsigned char acGUI_FontSONGB12_007C[ 12] = { /* code 007C, VERTICAL LINE */
  XX______,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______};

GUI_CONST_STORAGE unsigned char acGUI_FontSONGB12_007D[ 10] = { /* code 007D, RIGHT CURLY BRACKET */
  XXX_____,
  _XX_____,
  _XX_____,
  _XX_____,
  __XX____,
  _XX_____,
  _XX_____,
  _XX_____,
  _XX_____,
  XXX_____};

GUI_CONST_STORAGE unsigned char acGUI_FontSONGB12_007E[  3] = { /* code 007E, TILDE */
  _XX_____,
  XXXX_XX_,
  ___XXX__};

/* Start of unicode area <Basic Greek> */
GUI_CONST_STORAGE unsigned char acGUI_FontSONGB12_03A9[ 16] = { /* code 03A9, GREEK CAPITAL LETTER OMEGA */
  ___XXXX_,________,
  __XX__XX,________,
  _XXX__XX,X_______,
  _XXX__XX,X_______,
  _XXX__XX,X_______,
  __XX__XX,________,
  XXXXXXXX,XX______,
  XXXXXXXX,XX______};

/* Start of unicode area <CJK Unified Ideographs> */
GUI_CONST_STORAGE unsigned char acGUI_FontSONGB12_4E0A[ 24] = { /* code 4E0A */
  ____XX__,________,
  ____XX__,________,
  ____XX__,________,
  ____XX__,________,
  ____XXXX,XXX_____,
  ____XX__,________,
  ____XX__,________,
  ____XX__,________,
  ____XX__,________,
  ____XX__,________,
  ____XX__,________,
  XXXXXXXX,XXXX____};

GUI_CONST_STORAGE unsigned char acGUI_FontSONGB12_4E0B[ 22] = { /* code 4E0B */
  XXXXXXXX,XXXX____,
  ____XX__,________,
  ____XX__,________,
  ____XXXX,________,
  ____XX_X,X_______,
  ____XX__,XX______,
  ____XX__,_XX_____,
  ____XX__,_XX_____,
  ____XX__,________,
  ____XX__,________,
  ____XX__,________};

GUI_CONST_STORAGE unsigned char acGUI_FontSONGB12_4E2D[ 24] = { /* code 4E2D */
  ____XX__,________,
  ____XX__,________,
  ____XX__,________,
  XXXXXXXX,XX______,
  XX__XX__,XX______,
  XX__XX__,XX______,
  XX__XX__,XX______,
  XXXXXXXX,XX______,
  XX__XX__,XX______,
  ____XX__,________,
  ____XX__,________,
  ____XX__,________};

GUI_CONST_STORAGE unsigned char acGUI_FontSONGB12_5145[ 24] = { /* code 5145 */
  ____XX__,________,
  _____XX_,________,
  XXXXXXXX,XXXX____,
  ____XX__,________,
  ___XX__X,X_______,
  __XX____,XX______,
  _XXXXXXX,XXX_____,
  ___XX__X,XXX_____,
  ___XX__X,X_______,
  ___XX__X,X_XX____,
  __XX___X,X_XX____,
  XXX_____,XXXX____};

GUI_CONST_STORAGE unsigned char acGUI_FontSONGB12_5173[ 24] = { /* code 5173 */
  __XX____,XX______,
  ___XX__X,X_______,
  ________,________,
  _XXXXXXX,XXX_____,
  _____XX_,________,
  _____XX_,________,
  XXXXXXXX,XXXX____,
  _____XX_,________,
  ____XXXX,________,
  ___XX__X,X_______,
  __XX____,XX______,
  XXX_____,_XXX____};

GUI_CONST_STORAGE unsigned char acGUI_FontSONGB12_5185[ 24] = { /* code 5185 */
  ____XX__,________,
  ____XX__,________,
  XXXXXXXX,XX______,
  XX__XX__,XX______,
  XX__XX__,XX______,
  XX_XXXX_,XX______,
  XX_XX_XX,XX______,
  XXXX__XX,XX______,
  XX______,XX______,
  XX______,XX______,
  XX______,XX______,
  XX____XX,XX______};

GUI_CONST_STORAGE unsigned char acGUI_FontSONGB12_51FA[ 24] = { /* code 51FA */
  _____XX_,________,
  _XX__XX_,_XX_____,
  _XX__XX_,_XX_____,
  _XX__XX_,_XX_____,
  _XXXXXXX,XXX_____,
  _____XX_,________,
  _____XX_,________,
  XX___XX_,__XX____,
  XX___XX_,__XX____,
  XX___XX_,__XX____,
  XXXXXXXX,XXXX____,
  ________,__XX____};

GUI_CONST_STORAGE unsigned char acGUI_FontSONGB12_5206[ 24] = { /* code 5206 */
  ___XX__X,X_______,
  ___XX__X,X_______,
  __XX____,XX______,
  __XX____,XX______,
  _XX_____,_XX_____,
  XXXXXXXX,XXXX____,
  ____XX__,XX______,
  ____XX__,XX______,
  ___XX___,XX______,
  ___XX___,XX______,
  __XX____,XX______,
  _XX__XXX,X_______};

GUI_CONST_STORAGE unsigned char acGUI_FontSONGB12_5236[ 24] = { /* code 5236 */
  ___XX___,__XX____,
  _XXXX___,__XX____,
  _XXXXXXX,X_XX____,
  XX_XX__X,X_XX____,
  XXXXXXXX,X_XX____,
  ___XX__X,X_XX____,
  _XXXXXXX,X_XX____,
  _XXXXXXX,X_XX____,
  _XXXXXXX,X_XX____,
  _XXXXXX_,__XX____,
  _XXXXXX_,__XX____,
  ___XX___,XXXX____};

GUI_CONST_STORAGE unsigned char acGUI_FontSONGB12_538B[ 22] = { /* code 538B */
  _XXXXXXX,XXXX____,
  _XX_____,________,
  _XX___XX,________,
  _XX___XX,________,
  _XX___XX,________,
  _XXXXXXX,XXX_____,
  _XX___XX,________,
  _XX___XX,XX______,
  _XX___XX,_XX_____,
  _XX___XX,________,
  XXXXXXXX,XXXX____};

GUI_CONST_STORAGE unsigned char acGUI_FontSONGB12_56FE[ 24] = { /* code 56FE */
  XXXXXXXX,XXXX____,
  XX__XX__,__XX____,
  XX_XXXXX,X_XX____,
  XXXXX__X,X_XX____,
  XX__XXXX,__XX____,
  XXXXX__X,XXXX____,
  XX__XXX_,__XX____,
  XX____XX,__XX____,
  XX_XXX__,__XX____,
  XX___XXX,__XX____,
  XXXXXXXX,XXXX____,
  XX______,__XX____};

GUI_CONST_STORAGE unsigned char acGUI_FontSONGB12_578B[ 24] = { /* code 578B */
  ________,__XX____,
  _XXXXXXX,XXXX____,
  __XX_XX_,XXXX____,
  __XX_XX_,XXXX____,
  XXXXXXXX,XXXX____,
  __XX_XX_,XXXX____,
  _XX__XX_,__XX____,
  XX______,_XXX____,
  _____XX_,________,
  _XXXXXXX,XXX_____,
  _____XX_,________,
  XXXXXXXX,XXXX____};

GUI_CONST_STORAGE unsigned char acGUI_FontSONGB12_58F0[ 24] = { /* code 58F0 */
  _____XX_,________,
  XXXXXXXX,XXXX____,
  _____XX_,________,
  _XXXXXXX,XXX_____,
  ________,________,
  _XXXXXXX,XXX_____,
  _XX__XX_,_XX_____,
  _XX__XX_,_XX_____,
  _XXXXXXX,XXX_____,
  _XX_____,_XX_____,
  _XX_____,________,
  XX______,________};

GUI_CONST_STORAGE unsigned char acGUI_FontSONGB12_59CB[ 24] = { /* code 59CB */
  __XX___X,X_______,
  __XX___X,X_______,
  __XX__XX,________,
  XXXXXXX_,_XX_____,
  _XXXXXXX,XXXX____,
  _XXXX___,__XX____,
  _XXXXXXX,XXX_____,
  XX_XXXX_,_XX_____,
  _XXXXXX_,_XX_____,
  __XX_XX_,_XX_____,
  _XXXXXXX,XXX_____,
  XX_XXXX_,_XX_____};

GUI_CONST_STORAGE unsigned char acGUI_FontSONGB12_5F00[ 22] = { /* code 5F00 */
  _XXXXXXX,XXX_____,
  ___XX__X,X_______,
  ___XX__X,X_______,
  ___XX__X,X_______,
  ___XX__X,X_______,
  XXXXXXXX,XXXX____,
  ___XX__X,X_______,
  ___XX__X,X_______,
  __XX___X,X_______,
  __XX___X,X_______,
  _XX____X,X_______};

GUI_CONST_STORAGE unsigned char acGUI_FontSONGB12_5FAA[ 24] = { /* code 5FAA */
  __XX____,_XXX____,
  _XX_XXXX,XX______,
  XX__XX__,XX______,
  __XXXXXX,XXXX____,
  _XX_XX__,XX______,
  XXX_XXXX,XXXX____,
  _XX_XXXX,__XX____,
  _XX_XXXX,XXXX____,
  _XX_XXXX,__XX____,
  _XX_XXXX,XXXX____,
  _XX_XXXX,__XX____,
  _XXXX_XX,XXXX____};

GUI_CONST_STORAGE unsigned char acGUI_FontSONGB12_622A[ 24] = { /* code 622A */
  ___XX__X,XXX_____,
  _XXXXXXX,X_XX____,
  ___XX__X,X_______,
  XXXXXXXX,XXXX____,
  __XXXX_X,X_______,
  _XXXXXXX,XXX_____,
  XXX_XX_X,XXX_____,
  _XXXXXXX,XXX_____,
  _XX_XX__,XX______,
  _XXXXXXX,XXXX____,
  _XX_XX_X,XXXX____,
  _XXXXXXX,__XX____};

GUI_CONST_STORAGE unsigned char acGUI_FontSONGB12_62A5[ 24] = { /* code 62A5 */
  __XX____,________,
  __XX_XXX,XXXX____,
  __XX_XX_,__XX____,
  XXXXXXX_,__XX____,
  __XX_XX_,XXX_____,
  __XX_XX_,________,
  __XXXXXX,XXXX____,
  XXXX_XXX,X_XX____,
  __XX_XXX,XXX_____,
  __XX_XX_,XX______,
  __XX_XXX,XXX_____,
  _XXX_XXX,__XX____};

GUI_CONST_STORAGE unsigned char acGUI_FontSONGB12_63A7[ 24] = { /* code 63A7 */
  _XX___XX,________,
  _XX____X,X_______,
  _XX_XXXX,XXXX____,
  XXXXXX__,__XX____,
  _XX___XX,XX______,
  _XX__XX_,_XX_____,
  _XXXXX__,__XX____,
  XXX__XXX,XXX_____,
  _XX____X,X_______,
  _XX____X,X_______,
  _XX____X,X_______,
  XXX_XXXX,XXXX____};

GUI_CONST_STORAGE unsigned char acGUI_FontSONGB12_653E[ 24] = { /* code 653E */
  _XX____X,X_______,
  __XX___X,X_______,
  _______X,X_______,
  XXXXXX_X,XXXX____,
  _XX___XX,_XX_____,
  _XX__XXX,XXX_____,
  _XXXXX_X,XXX_____,
  _XX_XX_X,XXX_____,
  _XX_XX_X,XXX_____,
  _XX_XX__,XX______,
  _XX_XX_X,XXX_____,
  XX_XXXXX,__XX____};

GUI_CONST_STORAGE unsigned char acGUI_FontSONGB12_6570[ 24] = { /* code 6570 */
  ___XX__X,X_______,
  _XXXXXXX,X_______,
  ___XX__X,X_______,
  XXXXXXXX,XXXX____,
  __XXX_XX,_XX_____,
  _XXXXX_X,XXX_____,
  XX_XXXXX,XXX_____,
  __XX___X,XXX_____,
  XXXXXX_X,XXX_____,
  _XX_XX__,XX______,
  __XXX__X,XXX_____,
  XXX_XXXX,__XX____};

GUI_CONST_STORAGE unsigned char acGUI_FontSONGB12_6587[ 24] = { /* code 6587 */
  ____XX__,________,
  _____XX_,________,
  XXXXXXXX,XXXX____,
  __XX____,XX______,
  __XX____,XX______,
  ___XX__X,X_______,
  ___XX__X,X_______,
  ____XXXX,________,
  _____XX_,________,
  ____XXXX,________,
  __XXX__X,XX______,
  XXX_____,_XXX____};

GUI_CONST_STORAGE unsigned char acGUI_FontSONGB12_65F6[ 24] = { /* code 65F6 */
  ________,_XX_____,
  XXXXX___,_XX_____,
  XX_XX___,_XX_____,
  XX_XXXXX,XXXX____,
  XX_XX___,_XX_____,
  XXXXX___,_XX_____,
  XX_XX_XX,_XX_____,
  XX_XX__X,XXX_____,
  XX_XX__X,XXX_____,
  XXXXX___,_XX_____,
  XX_XX___,_XX_____,
  _______X,XXX_____};

GUI_CONST_STORAGE unsigned char acGUI_FontSONGB12_66F2[ 24] = { /* code 66F2 */
  ___XX_XX,________,
  ___XX_XX,________,
  XXXXXXXX,XXX_____,
  XX_XX_XX,_XX_____,
  XX_XX_XX,_XX_____,
  XX_XX_XX,_XX_____,
  XXXXXXXX,XXX_____,
  XX_XX_XX,_XX_____,
  XX_XX_XX,_XX_____,
  XX_XX_XX,_XX_____,
  XXXXXXXX,XXX_____,
  XX______,_XX_____};

GUI_CONST_STORAGE unsigned char acGUI_FontSONGB12_69DB[ 24] = { /* code 69DB */
  __XX__XX,XX______,
  __XXXXXX,XX______,
  __XXXXXX,XXXX____,
  XXXXXXXX,X_______,
  __XXXXXX,_XX_____,
  _XXX__XX,__XX____,
  _XXXX___,________,
  XXXXXXXX,XXXX____,
  __XXXXXX,XXXX____,
  __XXXXXX,XXXX____,
  __XXXXXX,XXXX____,
  __XXXXXX,XXXX____};

GUI_CONST_STORAGE unsigned char acGUI_FontSONGB12_6B21[ 24] = { /* code 6B21 */
  _____XX_,________,
  XX___XX_,________,
  _XX__XXX,XXXX____,
  ____XX__,__XX____,
  ____XXXX,_XX_____,
  ___XX_XX,________,
  ______XX,________,
  __XX_XXX,X_______,
  _XX__XXX,X_______,
  XX__XX__,XX______,
  ___XX___,_XX_____,
  __XX____,__XX____};

GUI_CONST_STORAGE unsigned char acGUI_FontSONGB12_6B62[ 24] = { /* code 6B62 */
  ______XX,________,
  ______XX,________,
  ______XX,________,
  __XX__XX,________,
  __XX__XX,XXX_____,
  __XX__XX,________,
  __XX__XX,________,
  __XX__XX,________,
  __XX__XX,________,
  __XX__XX,________,
  __XX__XX,________,
  XXXXXXXX,XXXX____};

GUI_CONST_STORAGE unsigned char acGUI_FontSONGB12_6B65[ 24] = { /* code 6B65 */
  _____XX_,________,
  __XX_XX_,________,
  __XX_XXX,XXX_____,
  __XX_XX_,________,
  __XX_XX_,________,
  XXXXXXXX,XXXX____,
  ________,________,
  ___XXXX_,_XX_____,
  __XX_XX_,XX______,
  _XX__XXX,X_______,
  ____XXX_,________,
  _XXXX___,________};

GUI_CONST_STORAGE unsigned char acGUI_FontSONGB12_6C60[ 24] = { /* code 6C60 */
  ______XX,________,
  XX____XX,________,
  _XXXX_XX,XXX_____,
  ___XX_XX,XXX_____,
  ___XXXXX,_XX_____,
  XX_XXXXX,_XX_____,
  _XXXX_XX,_XX_____,
  ___XX_XX,_XX_____,
  ___XX_XX,XXX_____,
  _XXXX_XX,________,
  XX_XX___,__XX____,
  ____XXXX,XXXX____};

GUI_CONST_STORAGE unsigned char acGUI_FontSONGB12_6D41[ 24] = { /* code 6D41 */
  ______XX,________,
  XX_____X,X_______,
  _XXXXXXX,XXXX____,
  _____XX_,________,
  ____XX__,_XX_____,
  XX_XXXXX,XXXX____,
  _XX_____,__XX____,
  ____XXXX,XX______,
  ____XXXX,XX______,
  _XX_XXXX,XXXX____,
  XX_XX_XX,XXXX____,
  __XX__XX,_XXX____};

GUI_CONST_STORAGE unsigned char acGUI_FontSONGB12_6D4B[ 24] = { /* code 6D4B */
  ________,__XX____,
  XXXXXXXX,__XX____,
  _XXX__XX,XXXX____,
  __XXXXXX,XXXX____,
  __XXXXXX,XXXX____,
  XXXXXXXX,XXXX____,
  _XXXXXXX,XXXX____,
  __XXXXXX,XXXX____,
  __XXXXXX,XXXX____,
  _XX_XX__,__XX____,
  XX_XXXX_,__XX____,
  __XX__XX,_XXX____};

GUI_CONST_STORAGE unsigned char acGUI_FontSONGB12_6E90[ 24] = { /* code 6E90 */
  XX_XXXXX,XXXX____,
  _XXXX__X,X_______,
  ___XX_XX,________,
  ___XXXXX,XXX_____,
  XX_XXXX_,_XX_____,
  _XXXXXXX,XXX_____,
  ___XXXX_,_XX_____,
  ___XXXXX,XXX_____,
  ___XX__X,X_______,
  _XXXXXXX,XXX_____,
  XX_XXX_X,X_XX____,
  __XX__XX,X_______};

GUI_CONST_STORAGE unsigned char acGUI_FontSONGB12_73AF[ 22] = { /* code 73AF */
  XXXXXXXX,XXXX____,
  __XX____,XX______,
  __XX___X,X_______,
  __XX___X,X_______,
  XXXXX_XX,XXX_____,
  __XX_XXX,X_XX____,
  __XXXX_X,X_XX____,
  __XX___X,X_______,
  __XXX__X,X_______,
  XXX____X,X_______,
  _______X,X_______};

GUI_CONST_STORAGE unsigned char acGUI_FontSONGB12_7535[ 24] = { /* code 7535 */
  ____XX__,________,
  ____XX__,________,
  XXXXXXXX,XX______,
  XX__XX__,XX______,
  XX__XX__,XX______,
  XXXXXXXX,XX______,
  XX__XX__,XX______,
  XX__XX__,XX______,
  XXXXXXXX,XX______,
  XX__XX__,__XX____,
  ____XX__,__XX____,
  _____XXX,XXXX____};

GUI_CONST_STORAGE unsigned char acGUI_FontSONGB12_77ED[ 24] = { /* code 77ED */
  _XX_____,________,
  _XX_XXXX,XXXX____,
  _XXXX___,________,
  XXXX_XXX,XXX_____,
  __XX_XX_,_XX_____,
  __XX_XX_,_XX_____,
  XXXXXXXX,XXX_____,
  __XX____,________,
  __XX_XX_,_XX_____,
  _XXXX_XX,XX______,
  _XXXX___,________,
  XX__XXXX,XXXX____};

GUI_CONST_STORAGE unsigned char acGUI_FontSONGB12_7A0B[ 24] = { /* code 7A0B */
  ___XXXXX,XXX_____,
  XXXX_XX_,_XX_____,
  __XX_XX_,_XX_____,
  __XX_XXX,XXX_____,
  XXXXX___,________,
  __XX_XXX,XXX_____,
  _XXXX__X,X_______,
  _XXXXX_X,X_______,
  XXXX_XXX,XXX_____,
  __XX___X,X_______,
  __XX___X,X_______,
  __XXXXXX,XXXX____};

GUI_CONST_STORAGE unsigned char acGUI_FontSONGB12_7C7B[ 24] = { /* code 7C7B */
  _____XX_,________,
  __XX_XX_,XX______,
  ___XXXXX,X_______,
  XXXXXXXX,XXXX____,
  ___XXXXX,X_______,
  __XX_XX_,XX______,
  _XX_____,_XX_____,
  _____XX_,________,
  XXXXXXXX,XXXX____,
  ____XXXX,________,
  __XXX__X,XX______,
  XXX_____,_XXX____};

GUI_CONST_STORAGE unsigned char acGUI_FontSONGB12_7CFB[ 24] = { /* code 7CFB */
  ______XX,XXX_____,
  _XXXXXX_,________,
  ____XX__,________,
  ___XX___,XX______,
  __XXXXXX,X_______,
  _____XXX,________,
  ___XXX__,_XX_____,
  _XXXXXXX,XXXX____,
  _____XX_,__XX____,
  __XX_XX_,XX______,
  _XX__XX_,_XX_____,
  XX__XXX_,__XX____};

GUI_CONST_STORAGE unsigned char acGUI_FontSONGB12_7EBF[ 24] = { /* code 7EBF */
  __XX___X,XXX_____,
  __XX___X,X_XX____,
  _XX____X,XXXX____,
  XX_XXXXX,X_______,
  XXXX___X,X_______,
  __XX___X,XXXX____,
  _XX__XXX,X_______,
  XXXXX__X,XXX_____,
  _______X,XX______,
  __XXX__X,X_XX____,
  XXX___XX,XXXX____,
  ____XXX_,_XXX____};

GUI_CONST_STORAGE unsigned char acGUI_FontSONGB12_7EDF[ 24] = { /* code 7EDF */
  __XX___X,X_______,
  __XX____,XX______,
  _XX__XXX,XXXX____,
  XX_XX__X,X_______,
  XXXX__XX,_XX_____,
  __XX_XX_,__XX____,
  _XX__XXX,XXXX____,
  XXXXX_XX,XXXX____,
  ______XX,XX______,
  __XXX_XX,XX______,
  XXX__XX_,XXXX____,
  ____XX__,_XXX____};

GUI_CONST_STORAGE unsigned char acGUI_FontSONGB12_7F6E[ 24] = { /* code 7F6E */
  _XXXXXXX,XXX_____,
  _XX_XXXX,_XX_____,
  _XXXXXXX,XXX_____,
  _____XX_,________,
  XXXXXXXX,XXXX____,
  _____XX_,________,
  __XXXXXX,XX______,
  __XX____,XX______,
  __XX____,XX______,
  __XX_XX_,XX______,
  __XX_XX_,XX______,
  XXXXXXXX,XXXX____};

GUI_CONST_STORAGE unsigned char acGUI_FontSONGB12_8B66[ 24] = { /* code 8B66 */
  _XX_XX_X,X_______,
  XXXXXXXX,XXXX____,
  _XX_XXXX,_XX_____,
  _XXXXXXX,XXX_____,
  XXXXXXX_,XX______,
  _XXXXXXX,XXX_____,
  ____XXXX,__XX____,
  XXXXXXXX,XXXX____,
  ________,________,
  _XXXXXXX,XXX_____,
  __XX____,XX______,
  __XXXXXX,XX______};

GUI_CONST_STORAGE unsigned char acGUI_FontSONGB12_8BBE[ 24] = { /* code 8BBE */
  _XX__XXX,XX______,
  __XX_XX_,XX______,
  _____XX_,XX______,
  _____XX_,XX______,
  XXXXXX__,_XXX____,
  __XX____,________,
  __XXXXXX,XXX_____,
  __XX_XX_,_XX_____,
  __XX__XX,XX______,
  __XXX__X,X_______,
  __XX__XX,XX______,
  ____XXX_,_XXX____};

GUI_CONST_STORAGE unsigned char acGUI_FontSONGB12_8BD5[ 24] = { /* code 8BD5 */
  XX______,XXXX____,
  _XX_____,XX______,
  ____XXXX,XXXX____,
  ________,XX______,
  XXX_____,XX______,
  _XX_XXXX,XX______,
  _XX__XX_,XX______,
  _XX__XX_,XX______,
  _XX__XX_,XX______,
  _XX__XXX,XXXX____,
  _XXXXXX_,_XXX____,
  _XX_____,__XX____};

GUI_CONST_STORAGE unsigned char acGUI_FontSONGB12_8D1F[ 24] = { /* code 8D1F */
  __XX____,________,
  __XXXXXX,X_______,
  _XX____X,X_______,
  XX____XX,________,
  _XXXXXXX,XXX_____,
  _XX_____,_XX_____,
  _XX__XX_,_XX_____,
  _XX__XX_,_XX_____,
  _XX__XX_,_XX_____,
  ____XXXX,X_______,
  __XXX___,XXX_____,
  XXX_____,__XX____};

GUI_CONST_STORAGE unsigned char acGUI_FontSONGB12_8D77[ 24] = { /* code 8D77 */
  ___XX___,________,
  ___XX_XX,XXX_____,
  _XXXXX__,_XX_____,
  ___XX___,_XX_____,
  ___XX_XX,XXX_____,
  XXXXXXXX,________,
  ___XX_XX,________,
  _XXXX_XX,__XX____,
  _XXXXXXX,__XX____,
  _XXXX__X,XXXX____,
  _XXXX___,________,
  XX_XXXXX,XXXX____};

GUI_CONST_STORAGE unsigned char acGUI_FontSONGB12_8DEF[ 24] = { /* code 8DEF */
  ______XX,________,
  XXXXX_XX,XXX_____,
  XX_XXXX_,_XX_____,
  XX_XXXXX,XX______,
  XXXXX__X,X_______,
  __XX__XX,XX______,
  __XXXXX_,_XXX____,
  XXXXXXXX,XXX_____,
  XXXX_XX_,_XX_____,
  XXXX_XX_,_XX_____,
  XXXXXXXX,XXX_____,
  XXX__XX_,_XX_____};

GUI_CONST_STORAGE unsigned char acGUI_FontSONGB12_8F7D[ 24] = { /* code 8F7D */
  ___XX__X,XXX_____,
  _XXXXXXX,X_XX____,
  ___XX__X,X_______,
  XXXXXXXX,XXXX____,
  __XX___X,X_______,
  XXXXXXXX,XXX_____,
  _XXXX__X,XXX_____,
  _XXXXXXX,XXX_____,
  ___XX___,XX______,
  ___XXXX_,XXXX____,
  XXXXX__X,XXXX____,
  ___XX_XX,__XX____};

GUI_CONST_STORAGE unsigned char acGUI_FontSONGB12_8F93[ 24] = { /* code 8F93 */
  __XX___X,X_______,
  __XX__XX,XX______,
  XXXXXXX_,_XX_____,
  _XX_XXXX,XXXX____,
  XXXX____,________,
  XXXXXXXX,__XX____,
  __XXXXXX,XXXX____,
  __XXXXXX,XXXX____,
  XXXXXXXX,XXXX____,
  __XXXXXX,XXXX____,
  __XXXXXX,__XX____,
  __XXXXXX,_XXX____};

GUI_CONST_STORAGE unsigned char acGUI_FontSONGB12_8FC7[ 24] = { /* code 8FC7 */
  _XX_____,_XX_____,
  __XX____,_XX_____,
  ________,_XX_____,
  ____XXXX,XXXX____,
  XXXX____,_XX_____,
  __XX_XX_,_XX_____,
  __XX__XX,_XX_____,
  __XX__XX,_XX_____,
  __XX____,_XX_____,
  __XX___X,XXX_____,
  _XXXX___,________,
  XX__XXXX,XXXX____};

GUI_CONST_STORAGE unsigned char acGUI_FontSONGB12_8FDB[ 24] = { /* code 8FDB */
  _XX__XX_,XX______,
  __XX_XX_,XX______,
  ____XXXX,XXX_____,
  _____XX_,XX______,
  XXXX_XX_,XX______,
  __XX_XX_,XX______,
  __XXXXXX,XXXX____,
  __XX_XX_,XX______,
  __XX_XX_,XX______,
  __XXXX__,XX______,
  _XXXX___,________,
  XX__XXXX,XXXX____};

GUI_CONST_STORAGE unsigned char acGUI_FontSONGB12_9009[ 24] = { /* code 9009 */
  _XX____X,X_______,
  __XX_XXX,X_______,
  _____XXX,XXX_____,
  ____XX_X,X_______,
  XXXX___X,X_______,
  __XXXXXX,XXXX____,
  __XX__XX,XX______,
  __XX__XX,XX______,
  __XX_XX_,XXXX____,
  __XXXX__,_XXX____,
  _XXXX___,________,
  XX__XXXX,XXXX____};

GUI_CONST_STORAGE unsigned char acGUI_FontSONGB12_9502[ 24] = { /* code 9502 */
  _XX__XXX,XXX_____,
  _XX__XXX,XXX_____,
  _XXXXXXX,XXX_____,
  XX___XXX,XXX_____,
  XXXXXXXX,XXX_____,
  _XX__XXX,XXX_____,
  _XX__XXX,XXX_____,
  XXXXX__X,X_______,
  _XX__XXX,XXX_____,
  _XXXX__X,X_______,
  _XXX___X,X_______,
  _XX_XXXX,XXXX____};

GUI_CONST_STORAGE unsigned char acGUI_FontSONGB12_95E8[ 24] = { /* code 95E8 */
  XX_XXXXX,XXX_____,
  _XX_____,_XX_____,
  ________,_XX_____,
  XX______,_XX_____,
  XX______,_XX_____,
  XX______,_XX_____,
  XX______,_XX_____,
  XX______,_XX_____,
  XX______,_XX_____,
  XX______,_XX_____,
  XX______,_XX_____,
  XX_____X,XXX_____};

GUI_CONST_STORAGE unsigned char acGUI_FontSONGB12_95F4[ 24] = { /* code 95F4 */
  XX_XXXXX,XXX_____,
  _XX_____,_XX_____,
  ________,_XX_____,
  XXXXXXXX,XXX_____,
  XXXX___X,XXX_____,
  XXXX___X,XXX_____,
  XXXXXXXX,XXX_____,
  XXXX___X,XXX_____,
  XXXX___X,XXX_____,
  XXXXXXXX,XXX_____,
  XX______,_XX_____,
  XX_____X,XXX_____};

GUI_CONST_STORAGE unsigned char acGUI_FontSONGB12_963B[ 22] = { /* code 963B */
  XXXXXXXX,XXX_____,
  XX_XXXX_,_XX_____,
  XX_XXXX_,_XX_____,
  XXXX_XXX,XXX_____,
  XXXX_XX_,_XX_____,
  XX_XXXX_,_XX_____,
  XX_XXXXX,XXX_____,
  XX_XXXX_,_XX_____,
  XXXX_XX_,_XX_____,
  XX___XX_,_XX_____,
  XX__XXXX,XXXX____};

GUI_CONST_STORAGE unsigned char acGUI_FontSONGB12_9650[ 24] = { /* code 9650 */
  XXXXXXXX,XXX_____,
  XX_XXXX_,_XX_____,
  XX_XXXX_,_XX_____,
  XXXX_XXX,XXX_____,
  XXXX_XX_,_XX_____,
  XX_XXXX_,_XX_____,
  XX_XXXXX,XXX_____,
  XX_XXXXX,X_XX____,
  XX_XXXXX,XXX_____,
  XXXX_XX_,XX______,
  XX___XXX,_XX_____,
  XX___XX_,__XX____};

GUI_CONST_STORAGE unsigned char acGUI_FontSONGB12_97F3[ 24] = { /* code 97F3 */
  _____XX_,________,
  _XXXXXXX,XXX_____,
  __XX____,XX______,
  ___XX__X,X_______,
  XXXXXXXX,XXXX____,
  ________,________,
  _XXXXXXX,XXX_____,
  _XX_____,_XX_____,
  _XXXXXXX,XXX_____,
  _XX_____,_XX_____,
  _XXXXXXX,XXX_____,
  _XX_____,_XX_____};

GUI_CONST_STORAGE GUI_CHARINFO_EXT GUI_FontSONGB12_CharInfo[151] = {
   {   2,   8,   2,   2,   7, acGUI_FontSONGB12_0021 } /* code 0021, EXCLAMATION MARK */
  ,{   5,   3,   1,   1,   7, acGUI_FontSONGB12_0022 } /* code 0022, QUOTATION MARK */
  ,{   7,   8,   0,   2,   7, acGUI_FontSONGB12_0023 } /* code 0023, NUMBER SIGN */
  ,{   6,  10,   0,   1,   7, acGUI_FontSONGB12_0024 } /* code 0024, DOLLAR SIGN */
  ,{   7,   8,   0,   2,   7, acGUI_FontSONGB12_0025 } /* code 0025, PERCENT SIGN */
  ,{   7,   8,   0,   2,   7, acGUI_FontSONGB12_0026 } /* code 0026, AMPERSAND */
  ,{   4,  10,   3,   1,   7, acGUI_FontSONGB12_0028 } /* code 0028, LEFT PARENTHESIS */
  ,{   4,  10,   1,   1,   7, acGUI_FontSONGB12_0029 } /* code 0029, RIGHT PARENTHESIS */
  ,{   6,   6,   0,   3,   7, acGUI_FontSONGB12_002A } /* code 002A, ASTERISK */
  ,{   6,   7,   0,   2,   7, acGUI_FontSONGB12_002B } /* code 002B, PLUS SIGN */
  ,{   3,   3,   0,   9,   7, acGUI_FontSONGB12_002C } /* code 002C, COMMA */
  ,{   6,   1,   0,   5,   7, acGUI_FontSONGB12_002D } /* code 002D, HYPHEN-MINUS */
  ,{   2,   1,   1,   9,   7, acGUI_FontSONGB12_002E } /* code 002E, FULL STOP */
  ,{   6,  10,   0,   1,   7, acGUI_FontSONGB12_002F } /* code 002F, SOLIDUS */
  ,{   6,   8,   0,   2,   7, acGUI_FontSONGB12_0030 } /* code 0030, DIGIT ZERO */
  ,{   4,   8,   1,   2,   7, acGUI_FontSONGB12_0031 } /* code 0031, DIGIT ONE */
  ,{   6,   8,   0,   2,   7, acGUI_FontSONGB12_0032 } /* code 0032, DIGIT TWO */
  ,{   6,   8,   0,   2,   7, acGUI_FontSONGB12_0033 } /* code 0033, DIGIT THREE */
  ,{   7,   8,   0,   2,   7, acGUI_FontSONGB12_0034 } /* code 0034, DIGIT FOUR */
  ,{   6,   8,   0,   2,   7, acGUI_FontSONGB12_0035 } /* code 0035, DIGIT FIVE */
  ,{   6,   8,   0,   2,   7, acGUI_FontSONGB12_0036 } /* code 0036, DIGIT SIX */
  ,{   6,   8,   0,   2,   7, acGUI_FontSONGB12_0037 } /* code 0037, DIGIT SEVEN */
  ,{   6,   8,   0,   2,   7, acGUI_FontSONGB12_0038 } /* code 0038, DIGIT EIGHT */
  ,{   6,   8,   0,   2,   7, acGUI_FontSONGB12_0039 } /* code 0039, DIGIT NINE */
  ,{   2,   6,   2,   4,   7, acGUI_FontSONGB12_003A } /* code 003A, COLON */
  ,{   2,   6,   2,   5,   7, acGUI_FontSONGB12_003B } /* code 003B, SEMICOLON */
  ,{   6,   9,   1,   1,   7, acGUI_FontSONGB12_003C } /* code 003C, LESS-THAN SIGN */
  ,{   6,   4,   0,   4,   7, acGUI_FontSONGB12_003D } /* code 003D, EQUALS SIGN */
  ,{   6,   9,   1,   1,   7, acGUI_FontSONGB12_003E } /* code 003E, GREATER-THAN SIGN */
  ,{   6,   8,   0,   2,   7, acGUI_FontSONGB12_003F } /* code 003F, QUESTION MARK */
  ,{   6,   8,   0,   2,   7, acGUI_FontSONGB12_0040 } /* code 0040, COMMERCIAL AT */
  ,{   7,   8,   0,   2,   7, acGUI_FontSONGB12_0041 } /* code 0041, LATIN CAPITAL LETTER A */
  ,{   6,   8,   0,   2,   7, acGUI_FontSONGB12_0042 } /* code 0042, LATIN CAPITAL LETTER B */
  ,{   6,   8,   0,   2,   7, acGUI_FontSONGB12_0043 } /* code 0043, LATIN CAPITAL LETTER C */
  ,{   6,   8,   0,   2,   7, acGUI_FontSONGB12_0044 } /* code 0044, LATIN CAPITAL LETTER D */
  ,{   6,   8,   0,   2,   7, acGUI_FontSONGB12_0045 } /* code 0045, LATIN CAPITAL LETTER E */
  ,{   6,   8,   0,   2,   7, acGUI_FontSONGB12_0046 } /* code 0046, LATIN CAPITAL LETTER F */
  ,{   7,   8,   0,   2,   7, acGUI_FontSONGB12_0047 } /* code 0047, LATIN CAPITAL LETTER G */
  ,{   7,   8,   0,   2,   7, acGUI_FontSONGB12_0048 } /* code 0048, LATIN CAPITAL LETTER H */
  ,{   6,   8,   0,   2,   7, acGUI_FontSONGB12_0049 } /* code 0049, LATIN CAPITAL LETTER I */
  ,{   7,   9,   0,   2,   7, acGUI_FontSONGB12_004A } /* code 004A, LATIN CAPITAL LETTER J */
  ,{   7,   8,   0,   2,   7, acGUI_FontSONGB12_004B } /* code 004B, LATIN CAPITAL LETTER K */
  ,{   7,   8,   0,   2,   7, acGUI_FontSONGB12_004C } /* code 004C, LATIN CAPITAL LETTER L */
  ,{   6,   8,   0,   2,   7, acGUI_FontSONGB12_004D } /* code 004D, LATIN CAPITAL LETTER M */
  ,{   7,   8,   0,   2,   7, acGUI_FontSONGB12_004E } /* code 004E, LATIN CAPITAL LETTER N */
  ,{   6,   8,   0,   2,   7, acGUI_FontSONGB12_004F } /* code 004F, LATIN CAPITAL LETTER O */
  ,{   6,   8,   0,   2,   7, acGUI_FontSONGB12_0050 } /* code 0050, LATIN CAPITAL LETTER P */
  ,{   6,   9,   0,   2,   7, acGUI_FontSONGB12_0051 } /* code 0051, LATIN CAPITAL LETTER Q */
  ,{   7,   8,   0,   2,   7, acGUI_FontSONGB12_0052 } /* code 0052, LATIN CAPITAL LETTER R */
  ,{   6,   8,   0,   2,   7, acGUI_FontSONGB12_0053 } /* code 0053, LATIN CAPITAL LETTER S */
  ,{   6,   8,   0,   2,   7, acGUI_FontSONGB12_0054 } /* code 0054, LATIN CAPITAL LETTER T */
  ,{   7,   8,   0,   2,   7, acGUI_FontSONGB12_0055 } /* code 0055, LATIN CAPITAL LETTER U */
  ,{   7,   8,   0,   2,   7, acGUI_FontSONGB12_0056 } /* code 0056, LATIN CAPITAL LETTER V */
  ,{   6,   8,   0,   2,   7, acGUI_FontSONGB12_0057 } /* code 0057, LATIN CAPITAL LETTER W */
  ,{   6,   8,   0,   2,   7, acGUI_FontSONGB12_0058 } /* code 0058, LATIN CAPITAL LETTER X */
  ,{   6,   8,   0,   2,   7, acGUI_FontSONGB12_0059 } /* code 0059, LATIN CAPITAL LETTER Y */
  ,{   6,   8,   0,   2,   7, acGUI_FontSONGB12_005A } /* code 005A, LATIN CAPITAL LETTER Z */
  ,{   4,  10,   2,   1,   7, acGUI_FontSONGB12_005B } /* code 005B, LEFT SQUARE BRACKET */
  ,{   5,  10,   1,   1,   7, acGUI_FontSONGB12_005C } /* code 005C, REVERSE SOLIDUS */
  ,{   4,  10,   1,   1,   7, acGUI_FontSONGB12_005D } /* code 005D, RIGHT SQUARE BRACKET */
  ,{   4,   2,   1,   1,   7, acGUI_FontSONGB12_005E } /* code 005E, CIRCUMFLEX ACCENT */
  ,{   7,   1,   0,  11,   7, acGUI_FontSONGB12_005F } /* code 005F, LOW LINE */
  ,{   6,   5,   1,   5,   7, acGUI_FontSONGB12_0061 } /* code 0061, LATIN SMALL LETTER A */
  ,{   6,   8,   0,   2,   7, acGUI_FontSONGB12_0062 } /* code 0062, LATIN SMALL LETTER B */
  ,{   5,   5,   1,   5,   7, acGUI_FontSONGB12_0063 } /* code 0063, LATIN SMALL LETTER C */
  ,{   6,   8,   1,   2,   7, acGUI_FontSONGB12_0064 } /* code 0064, LATIN SMALL LETTER D */
  ,{   5,   5,   1,   5,   7, acGUI_FontSONGB12_0065 } /* code 0065, LATIN SMALL LETTER E */
  ,{   6,   8,   1,   2,   7, acGUI_FontSONGB12_0066 } /* code 0066, LATIN SMALL LETTER F */
  ,{   6,   7,   1,   5,   7, acGUI_FontSONGB12_0067 } /* code 0067, LATIN SMALL LETTER G */
  ,{   7,   8,   0,   2,   7, acGUI_FontSONGB12_0068 } /* code 0068, LATIN SMALL LETTER H */
  ,{   4,   8,   1,   2,   7, acGUI_FontSONGB12_0069 } /* code 0069, LATIN SMALL LETTER I */
  ,{   5,  10,   0,   2,   7, acGUI_FontSONGB12_006A } /* code 006A, LATIN SMALL LETTER J */
  ,{   7,   8,   0,   2,   7, acGUI_FontSONGB12_006B } /* code 006B, LATIN SMALL LETTER K */
  ,{   6,   8,   0,   2,   7, acGUI_FontSONGB12_006C } /* code 006C, LATIN SMALL LETTER L */
  ,{   6,   5,   0,   5,   7, acGUI_FontSONGB12_006D } /* code 006D, LATIN SMALL LETTER M */
  ,{   7,   5,   0,   5,   7, acGUI_FontSONGB12_006E } /* code 006E, LATIN SMALL LETTER N */
  ,{   5,   5,   1,   5,   7, acGUI_FontSONGB12_006F } /* code 006F, LATIN SMALL LETTER O */
  ,{   6,   7,   0,   5,   7, acGUI_FontSONGB12_0070 } /* code 0070, LATIN SMALL LETTER P */
  ,{   6,   7,   1,   5,   7, acGUI_FontSONGB12_0071 } /* code 0071, LATIN SMALL LETTER Q */
  ,{   6,   5,   0,   5,   7, acGUI_FontSONGB12_0072 } /* code 0072, LATIN SMALL LETTER R */
  ,{   5,   5,   1,   5,   7, acGUI_FontSONGB12_0073 } /* code 0073, LATIN SMALL LETTER S */
  ,{   5,   7,   1,   3,   7, acGUI_FontSONGB12_0074 } /* code 0074, LATIN SMALL LETTER T */
  ,{   7,   5,   0,   5,   7, acGUI_FontSONGB12_0075 } /* code 0075, LATIN SMALL LETTER U */
  ,{   7,   5,   0,   5,   7, acGUI_FontSONGB12_0076 } /* code 0076, LATIN SMALL LETTER V */
  ,{   6,   5,   0,   5,   7, acGUI_FontSONGB12_0077 } /* code 0077, LATIN SMALL LETTER W */
  ,{   6,   5,   0,   5,   7, acGUI_FontSONGB12_0078 } /* code 0078, LATIN SMALL LETTER X */
  ,{   7,   7,   0,   5,   7, acGUI_FontSONGB12_0079 } /* code 0079, LATIN SMALL LETTER Y */
  ,{   5,   5,   1,   5,   7, acGUI_FontSONGB12_007A } /* code 007A, LATIN SMALL LETTER Z */
  ,{   4,  10,   2,   1,   7, acGUI_FontSONGB12_007B } /* code 007B, LEFT CURLY BRACKET */
  ,{   2,  12,   3,   0,   7, acGUI_FontSONGB12_007C } /* code 007C, VERTICAL LINE */
  ,{   4,  10,   1,   1,   7, acGUI_FontSONGB12_007D } /* code 007D, RIGHT CURLY BRACKET */
  ,{   7,   3,   0,   0,   7, acGUI_FontSONGB12_007E } /* code 007E, TILDE */
  ,{  10,   8,   1,   1,  13, acGUI_FontSONGB12_03A9 } /* code 03A9, GREEK CAPITAL LETTER OMEGA */
  ,{  12,  12,   0,   0,  13, acGUI_FontSONGB12_4E0A } /* code 4E0A */
  ,{  12,  11,   0,   1,  13, acGUI_FontSONGB12_4E0B } /* code 4E0B */
  ,{  10,  12,   1,   0,  13, acGUI_FontSONGB12_4E2D } /* code 4E2D */
  ,{  12,  12,   0,   0,  13, acGUI_FontSONGB12_5145 } /* code 5145 */
  ,{  12,  12,   0,   0,  13, acGUI_FontSONGB12_5173 } /* code 5173 */
  ,{  10,  12,   1,   0,  13, acGUI_FontSONGB12_5185 } /* code 5185 */
  ,{  12,  12,   0,   0,  13, acGUI_FontSONGB12_51FA } /* code 51FA */
  ,{  12,  12,   0,   0,  13, acGUI_FontSONGB12_5206 } /* code 5206 */
  ,{  12,  12,   0,   0,  13, acGUI_FontSONGB12_5236 } /* code 5236 */
  ,{  12,  11,   0,   1,  13, acGUI_FontSONGB12_538B } /* code 538B */
  ,{  12,  12,   0,   0,  13, acGUI_FontSONGB12_56FE } /* code 56FE */
  ,{  12,  12,   0,   0,  13, acGUI_FontSONGB12_578B } /* code 578B */
  ,{  12,  12,   0,   0,  13, acGUI_FontSONGB12_58F0 } /* code 58F0 */
  ,{  12,  12,   0,   0,  13, acGUI_FontSONGB12_59CB } /* code 59CB */
  ,{  12,  11,   0,   1,  13, acGUI_FontSONGB12_5F00 } /* code 5F00 */
  ,{  12,  12,   0,   0,  13, acGUI_FontSONGB12_5FAA } /* code 5FAA */
  ,{  12,  12,   0,   0,  13, acGUI_FontSONGB12_622A } /* code 622A */
  ,{  12,  12,   0,   0,  13, acGUI_FontSONGB12_62A5 } /* code 62A5 */
  ,{  12,  12,   0,   0,  13, acGUI_FontSONGB12_63A7 } /* code 63A7 */
  ,{  12,  12,   0,   0,  13, acGUI_FontSONGB12_653E } /* code 653E */
  ,{  12,  12,   0,   0,  13, acGUI_FontSONGB12_6570 } /* code 6570 */
  ,{  12,  12,   0,   0,  13, acGUI_FontSONGB12_6587 } /* code 6587 */
  ,{  12,  12,   0,   0,  13, acGUI_FontSONGB12_65F6 } /* code 65F6 */
  ,{  11,  12,   1,   0,  13, acGUI_FontSONGB12_66F2 } /* code 66F2 */
  ,{  12,  12,   0,   0,  13, acGUI_FontSONGB12_69DB } /* code 69DB */
  ,{  12,  12,   0,   0,  13, acGUI_FontSONGB12_6B21 } /* code 6B21 */
  ,{  12,  12,   0,   0,  13, acGUI_FontSONGB12_6B62 } /* code 6B62 */
  ,{  12,  12,   0,   0,  13, acGUI_FontSONGB12_6B65 } /* code 6B65 */
  ,{  12,  12,   0,   0,  13, acGUI_FontSONGB12_6C60 } /* code 6C60 */
  ,{  12,  12,   0,   0,  13, acGUI_FontSONGB12_6D41 } /* code 6D41 */
  ,{  12,  12,   0,   0,  13, acGUI_FontSONGB12_6D4B } /* code 6D4B */
  ,{  12,  12,   0,   0,  13, acGUI_FontSONGB12_6E90 } /* code 6E90 */
  ,{  12,  11,   0,   1,  13, acGUI_FontSONGB12_73AF } /* code 73AF */
  ,{  12,  12,   0,   0,  13, acGUI_FontSONGB12_7535 } /* code 7535 */
  ,{  12,  12,   0,   0,  13, acGUI_FontSONGB12_77ED } /* code 77ED */
  ,{  12,  12,   0,   0,  13, acGUI_FontSONGB12_7A0B } /* code 7A0B */
  ,{  12,  12,   0,   0,  13, acGUI_FontSONGB12_7C7B } /* code 7C7B */
  ,{  12,  12,   0,   0,  13, acGUI_FontSONGB12_7CFB } /* code 7CFB */
  ,{  12,  12,   0,   0,  13, acGUI_FontSONGB12_7EBF } /* code 7EBF */
  ,{  12,  12,   0,   0,  13, acGUI_FontSONGB12_7EDF } /* code 7EDF */
  ,{  12,  12,   0,   0,  13, acGUI_FontSONGB12_7F6E } /* code 7F6E */
  ,{  12,  12,   0,   0,  13, acGUI_FontSONGB12_8B66 } /* code 8B66 */
  ,{  12,  12,   0,   0,  13, acGUI_FontSONGB12_8BBE } /* code 8BBE */
  ,{  12,  12,   0,   0,  13, acGUI_FontSONGB12_8BD5 } /* code 8BD5 */
  ,{  12,  12,   0,   0,  13, acGUI_FontSONGB12_8D1F } /* code 8D1F */
  ,{  12,  12,   0,   0,  13, acGUI_FontSONGB12_8D77 } /* code 8D77 */
  ,{  12,  12,   0,   0,  13, acGUI_FontSONGB12_8DEF } /* code 8DEF */
  ,{  12,  12,   0,   0,  13, acGUI_FontSONGB12_8F7D } /* code 8F7D */
  ,{  12,  12,   0,   0,  13, acGUI_FontSONGB12_8F93 } /* code 8F93 */
  ,{  12,  12,   0,   0,  13, acGUI_FontSONGB12_8FC7 } /* code 8FC7 */
  ,{  12,  12,   0,   0,  13, acGUI_FontSONGB12_8FDB } /* code 8FDB */
  ,{  12,  12,   0,   0,  13, acGUI_FontSONGB12_9009 } /* code 9009 */
  ,{  12,  12,   0,   0,  13, acGUI_FontSONGB12_9502 } /* code 9502 */
  ,{  11,  12,   1,   0,  13, acGUI_FontSONGB12_95E8 } /* code 95E8 */
  ,{  11,  12,   1,   0,  13, acGUI_FontSONGB12_95F4 } /* code 95F4 */
  ,{  12,  11,   0,   1,  13, acGUI_FontSONGB12_963B } /* code 963B */
  ,{  12,  12,   0,   0,  13, acGUI_FontSONGB12_9650 } /* code 9650 */
  ,{  12,  12,   0,   0,  13, acGUI_FontSONGB12_97F3 } /* code 97F3 */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontSONGB12_Prop61 = {
   0x97F3 /* first character */
  ,0x97F3 /* last character  */
  ,&GUI_FontSONGB12_CharInfo[150] /* address of first character */
  ,(GUI_CONST_STORAGE GUI_FONT_PROP_EXT *)0 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontSONGB12_Prop60 = {
   0x9650 /* first character */
  ,0x9650 /* last character  */
  ,&GUI_FontSONGB12_CharInfo[149] /* address of first character */
  ,&GUI_FontSONGB12_Prop61 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontSONGB12_Prop59 = {
   0x963B /* first character */
  ,0x963B /* last character  */
  ,&GUI_FontSONGB12_CharInfo[148] /* address of first character */
  ,&GUI_FontSONGB12_Prop60 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontSONGB12_Prop58 = {
   0x95F4 /* first character */
  ,0x95F4 /* last character  */
  ,&GUI_FontSONGB12_CharInfo[147] /* address of first character */
  ,&GUI_FontSONGB12_Prop59 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontSONGB12_Prop57 = {
   0x95E8 /* first character */
  ,0x95E8 /* last character  */
  ,&GUI_FontSONGB12_CharInfo[146] /* address of first character */
  ,&GUI_FontSONGB12_Prop58 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontSONGB12_Prop56 = {
   0x9502 /* first character */
  ,0x9502 /* last character  */
  ,&GUI_FontSONGB12_CharInfo[145] /* address of first character */
  ,&GUI_FontSONGB12_Prop57 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontSONGB12_Prop55 = {
   0x9009 /* first character */
  ,0x9009 /* last character  */
  ,&GUI_FontSONGB12_CharInfo[144] /* address of first character */
  ,&GUI_FontSONGB12_Prop56 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontSONGB12_Prop54 = {
   0x8FDB /* first character */
  ,0x8FDB /* last character  */
  ,&GUI_FontSONGB12_CharInfo[143] /* address of first character */
  ,&GUI_FontSONGB12_Prop55 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontSONGB12_Prop53 = {
   0x8FC7 /* first character */
  ,0x8FC7 /* last character  */
  ,&GUI_FontSONGB12_CharInfo[142] /* address of first character */
  ,&GUI_FontSONGB12_Prop54 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontSONGB12_Prop52 = {
   0x8F93 /* first character */
  ,0x8F93 /* last character  */
  ,&GUI_FontSONGB12_CharInfo[141] /* address of first character */
  ,&GUI_FontSONGB12_Prop53 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontSONGB12_Prop51 = {
   0x8F7D /* first character */
  ,0x8F7D /* last character  */
  ,&GUI_FontSONGB12_CharInfo[140] /* address of first character */
  ,&GUI_FontSONGB12_Prop52 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontSONGB12_Prop50 = {
   0x8DEF /* first character */
  ,0x8DEF /* last character  */
  ,&GUI_FontSONGB12_CharInfo[139] /* address of first character */
  ,&GUI_FontSONGB12_Prop51 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontSONGB12_Prop49 = {
   0x8D77 /* first character */
  ,0x8D77 /* last character  */
  ,&GUI_FontSONGB12_CharInfo[138] /* address of first character */
  ,&GUI_FontSONGB12_Prop50 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontSONGB12_Prop48 = {
   0x8D1F /* first character */
  ,0x8D1F /* last character  */
  ,&GUI_FontSONGB12_CharInfo[137] /* address of first character */
  ,&GUI_FontSONGB12_Prop49 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontSONGB12_Prop47 = {
   0x8BD5 /* first character */
  ,0x8BD5 /* last character  */
  ,&GUI_FontSONGB12_CharInfo[136] /* address of first character */
  ,&GUI_FontSONGB12_Prop48 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontSONGB12_Prop46 = {
   0x8BBE /* first character */
  ,0x8BBE /* last character  */
  ,&GUI_FontSONGB12_CharInfo[135] /* address of first character */
  ,&GUI_FontSONGB12_Prop47 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontSONGB12_Prop45 = {
   0x8B66 /* first character */
  ,0x8B66 /* last character  */
  ,&GUI_FontSONGB12_CharInfo[134] /* address of first character */
  ,&GUI_FontSONGB12_Prop46 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontSONGB12_Prop44 = {
   0x7F6E /* first character */
  ,0x7F6E /* last character  */
  ,&GUI_FontSONGB12_CharInfo[133] /* address of first character */
  ,&GUI_FontSONGB12_Prop45 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontSONGB12_Prop43 = {
   0x7EDF /* first character */
  ,0x7EDF /* last character  */
  ,&GUI_FontSONGB12_CharInfo[132] /* address of first character */
  ,&GUI_FontSONGB12_Prop44 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontSONGB12_Prop42 = {
   0x7EBF /* first character */
  ,0x7EBF /* last character  */
  ,&GUI_FontSONGB12_CharInfo[131] /* address of first character */
  ,&GUI_FontSONGB12_Prop43 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontSONGB12_Prop41 = {
   0x7CFB /* first character */
  ,0x7CFB /* last character  */
  ,&GUI_FontSONGB12_CharInfo[130] /* address of first character */
  ,&GUI_FontSONGB12_Prop42 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontSONGB12_Prop40 = {
   0x7C7B /* first character */
  ,0x7C7B /* last character  */
  ,&GUI_FontSONGB12_CharInfo[129] /* address of first character */
  ,&GUI_FontSONGB12_Prop41 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontSONGB12_Prop39 = {
   0x7A0B /* first character */
  ,0x7A0B /* last character  */
  ,&GUI_FontSONGB12_CharInfo[128] /* address of first character */
  ,&GUI_FontSONGB12_Prop40 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontSONGB12_Prop38 = {
   0x77ED /* first character */
  ,0x77ED /* last character  */
  ,&GUI_FontSONGB12_CharInfo[127] /* address of first character */
  ,&GUI_FontSONGB12_Prop39 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontSONGB12_Prop37 = {
   0x7535 /* first character */
  ,0x7535 /* last character  */
  ,&GUI_FontSONGB12_CharInfo[126] /* address of first character */
  ,&GUI_FontSONGB12_Prop38 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontSONGB12_Prop36 = {
   0x73AF /* first character */
  ,0x73AF /* last character  */
  ,&GUI_FontSONGB12_CharInfo[125] /* address of first character */
  ,&GUI_FontSONGB12_Prop37 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontSONGB12_Prop35 = {
   0x6E90 /* first character */
  ,0x6E90 /* last character  */
  ,&GUI_FontSONGB12_CharInfo[124] /* address of first character */
  ,&GUI_FontSONGB12_Prop36 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontSONGB12_Prop34 = {
   0x6D4B /* first character */
  ,0x6D4B /* last character  */
  ,&GUI_FontSONGB12_CharInfo[123] /* address of first character */
  ,&GUI_FontSONGB12_Prop35 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontSONGB12_Prop33 = {
   0x6D41 /* first character */
  ,0x6D41 /* last character  */
  ,&GUI_FontSONGB12_CharInfo[122] /* address of first character */
  ,&GUI_FontSONGB12_Prop34 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontSONGB12_Prop32 = {
   0x6C60 /* first character */
  ,0x6C60 /* last character  */
  ,&GUI_FontSONGB12_CharInfo[121] /* address of first character */
  ,&GUI_FontSONGB12_Prop33 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontSONGB12_Prop31 = {
   0x6B65 /* first character */
  ,0x6B65 /* last character  */
  ,&GUI_FontSONGB12_CharInfo[120] /* address of first character */
  ,&GUI_FontSONGB12_Prop32 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontSONGB12_Prop30 = {
   0x6B62 /* first character */
  ,0x6B62 /* last character  */
  ,&GUI_FontSONGB12_CharInfo[119] /* address of first character */
  ,&GUI_FontSONGB12_Prop31 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontSONGB12_Prop29 = {
   0x6B21 /* first character */
  ,0x6B21 /* last character  */
  ,&GUI_FontSONGB12_CharInfo[118] /* address of first character */
  ,&GUI_FontSONGB12_Prop30 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontSONGB12_Prop28 = {
   0x69DB /* first character */
  ,0x69DB /* last character  */
  ,&GUI_FontSONGB12_CharInfo[117] /* address of first character */
  ,&GUI_FontSONGB12_Prop29 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontSONGB12_Prop27 = {
   0x66F2 /* first character */
  ,0x66F2 /* last character  */
  ,&GUI_FontSONGB12_CharInfo[116] /* address of first character */
  ,&GUI_FontSONGB12_Prop28 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontSONGB12_Prop26 = {
   0x65F6 /* first character */
  ,0x65F6 /* last character  */
  ,&GUI_FontSONGB12_CharInfo[115] /* address of first character */
  ,&GUI_FontSONGB12_Prop27 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontSONGB12_Prop25 = {
   0x6587 /* first character */
  ,0x6587 /* last character  */
  ,&GUI_FontSONGB12_CharInfo[114] /* address of first character */
  ,&GUI_FontSONGB12_Prop26 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontSONGB12_Prop24 = {
   0x6570 /* first character */
  ,0x6570 /* last character  */
  ,&GUI_FontSONGB12_CharInfo[113] /* address of first character */
  ,&GUI_FontSONGB12_Prop25 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontSONGB12_Prop23 = {
   0x653E /* first character */
  ,0x653E /* last character  */
  ,&GUI_FontSONGB12_CharInfo[112] /* address of first character */
  ,&GUI_FontSONGB12_Prop24 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontSONGB12_Prop22 = {
   0x63A7 /* first character */
  ,0x63A7 /* last character  */
  ,&GUI_FontSONGB12_CharInfo[111] /* address of first character */
  ,&GUI_FontSONGB12_Prop23 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontSONGB12_Prop21 = {
   0x62A5 /* first character */
  ,0x62A5 /* last character  */
  ,&GUI_FontSONGB12_CharInfo[110] /* address of first character */
  ,&GUI_FontSONGB12_Prop22 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontSONGB12_Prop20 = {
   0x622A /* first character */
  ,0x622A /* last character  */
  ,&GUI_FontSONGB12_CharInfo[109] /* address of first character */
  ,&GUI_FontSONGB12_Prop21 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontSONGB12_Prop19 = {
   0x5FAA /* first character */
  ,0x5FAA /* last character  */
  ,&GUI_FontSONGB12_CharInfo[108] /* address of first character */
  ,&GUI_FontSONGB12_Prop20 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontSONGB12_Prop18 = {
   0x5F00 /* first character */
  ,0x5F00 /* last character  */
  ,&GUI_FontSONGB12_CharInfo[107] /* address of first character */
  ,&GUI_FontSONGB12_Prop19 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontSONGB12_Prop17 = {
   0x59CB /* first character */
  ,0x59CB /* last character  */
  ,&GUI_FontSONGB12_CharInfo[106] /* address of first character */
  ,&GUI_FontSONGB12_Prop18 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontSONGB12_Prop16 = {
   0x58F0 /* first character */
  ,0x58F0 /* last character  */
  ,&GUI_FontSONGB12_CharInfo[105] /* address of first character */
  ,&GUI_FontSONGB12_Prop17 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontSONGB12_Prop15 = {
   0x578B /* first character */
  ,0x578B /* last character  */
  ,&GUI_FontSONGB12_CharInfo[104] /* address of first character */
  ,&GUI_FontSONGB12_Prop16 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontSONGB12_Prop14 = {
   0x56FE /* first character */
  ,0x56FE /* last character  */
  ,&GUI_FontSONGB12_CharInfo[103] /* address of first character */
  ,&GUI_FontSONGB12_Prop15 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontSONGB12_Prop13 = {
   0x538B /* first character */
  ,0x538B /* last character  */
  ,&GUI_FontSONGB12_CharInfo[102] /* address of first character */
  ,&GUI_FontSONGB12_Prop14 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontSONGB12_Prop12 = {
   0x5236 /* first character */
  ,0x5236 /* last character  */
  ,&GUI_FontSONGB12_CharInfo[101] /* address of first character */
  ,&GUI_FontSONGB12_Prop13 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontSONGB12_Prop11 = {
   0x5206 /* first character */
  ,0x5206 /* last character  */
  ,&GUI_FontSONGB12_CharInfo[100] /* address of first character */
  ,&GUI_FontSONGB12_Prop12 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontSONGB12_Prop10 = {
   0x51FA /* first character */
  ,0x51FA /* last character  */
  ,&GUI_FontSONGB12_CharInfo[ 99] /* address of first character */
  ,&GUI_FontSONGB12_Prop11 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontSONGB12_Prop9 = {
   0x5185 /* first character */
  ,0x5185 /* last character  */
  ,&GUI_FontSONGB12_CharInfo[ 98] /* address of first character */
  ,&GUI_FontSONGB12_Prop10 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontSONGB12_Prop8 = {
   0x5173 /* first character */
  ,0x5173 /* last character  */
  ,&GUI_FontSONGB12_CharInfo[ 97] /* address of first character */
  ,&GUI_FontSONGB12_Prop9 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontSONGB12_Prop7 = {
   0x5145 /* first character */
  ,0x5145 /* last character  */
  ,&GUI_FontSONGB12_CharInfo[ 96] /* address of first character */
  ,&GUI_FontSONGB12_Prop8 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontSONGB12_Prop6 = {
   0x4E2D /* first character */
  ,0x4E2D /* last character  */
  ,&GUI_FontSONGB12_CharInfo[ 95] /* address of first character */
  ,&GUI_FontSONGB12_Prop7 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontSONGB12_Prop5 = {
   0x4E0A /* first character */
  ,0x4E0B /* last character  */
  ,&GUI_FontSONGB12_CharInfo[ 93] /* address of first character */
  ,&GUI_FontSONGB12_Prop6 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontSONGB12_Prop4 = {
   0x03A9 /* first character */
  ,0x03A9 /* last character  */
  ,&GUI_FontSONGB12_CharInfo[ 92] /* address of first character */
  ,&GUI_FontSONGB12_Prop5 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontSONGB12_Prop3 = {
   0x0061 /* first character */
  ,0x007E /* last character  */
  ,&GUI_FontSONGB12_CharInfo[ 62] /* address of first character */
  ,&GUI_FontSONGB12_Prop4 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontSONGB12_Prop2 = {
   0x0028 /* first character */
  ,0x005F /* last character  */
  ,&GUI_FontSONGB12_CharInfo[  6] /* address of first character */
  ,&GUI_FontSONGB12_Prop3 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontSONGB12_Prop1 = {
   0x0021 /* first character */
  ,0x0026 /* last character  */
  ,&GUI_FontSONGB12_CharInfo[  0] /* address of first character */
  ,&GUI_FontSONGB12_Prop2 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT GUI_FontSONGB12 = {
   GUI_FONTTYPE_PROP_EXT /* type of font    */
  ,12 /* height of font  */
  ,12 /* space of font y */
  ,1 /* magnification x */
  ,1 /* magnification y */
  ,{&GUI_FontSONGB12_Prop1}
  ,10 /* Baseline */
  ,5 /* Height of lowercase characters */
  ,8 /* Height of capital characters */
};

