/*********************************************************************
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                           www.segger.com                           *
**********************************************************************
*                                                                    *
* C-file generated by                                                *
*                                                                    *
*        emWin Font Converter (ST) version 5.32                      *
*        Compiled Oct  8 2015, 11:58:55                              *
*                                                                    *
*        (c) 1998 - 2015 Segger Microcontroller GmbH & Co. KG        *
*                                                                    *
**********************************************************************
*                                                                    *
* Source file: SONG12.c                                              *
* Font:        ËÎÌו                                                  *
* Height:      12                                                    *
*                                                                    *
**********************************************************************
*                                                                    *
* Initial font height:  12                                           *
* Range disabled:       0000 - FFFF                                  *
* Read pattern file: C:\Users\Administrator\Desktop\123.txt          *
* Character enabled:   0x27 (39)                                     *
*                                                                    *
**********************************************************************
*/

#include "GUI.h"

#ifndef GUI_CONST_STORAGE
  #define GUI_CONST_STORAGE const
#endif

/* The following line needs to be included in any file selecting the
   font.
*/
extern GUI_CONST_STORAGE GUI_FONT GUI_FontSONG12;

/* Start of unicode area <Basic Latin> */
GUI_CONST_STORAGE unsigned char acGUI_FontSONG12_0020[  1] = { /* code 0020, SPACE */
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontSONG12_0021[  8] = { /* code 0021, EXCLAMATION MARK */
  X_______,
  X_______,
  X_______,
  X_______,
  X_______,
  X_______,
  ________,
  X_______};

GUI_CONST_STORAGE unsigned char acGUI_FontSONG12_0022[  3] = { /* code 0022, QUOTATION MARK */
  _X_X____,
  X_X_____,
  X_X_____};

GUI_CONST_STORAGE unsigned char acGUI_FontSONG12_0023[  8] = { /* code 0023, NUMBER SIGN */
  __X_X___,
  __X_X___,
  XXXXXX__,
  __X_X___,
  _X_X____,
  XXXXXX__,
  _X_X____,
  _X_X____};

GUI_CONST_STORAGE unsigned char acGUI_FontSONG12_0024[ 10] = { /* code 0024, DOLLAR SIGN */
  __X_____,
  _XXXX___,
  X_X_X___,
  X_X_____,
  _XX_____,
  __XX____,
  __X_X___,
  X_X_X___,
  XXXX____,
  __X_____};

GUI_CONST_STORAGE unsigned char acGUI_FontSONG12_0025[  8] = { /* code 0025, PERCENT SIGN */
  _X__X___,
  X_X_X___,
  X_XX____,
  _X_X____,
  __X_X___,
  __XX_X__,
  _X_X_X__,
  _X__X___};

GUI_CONST_STORAGE unsigned char acGUI_FontSONG12_0026[  8] = { /* code 0026, AMPERSAND */
  __X_____,
  _X_X____,
  _X_X____,
  _XXXX___,
  X_X_X___,
  X_X_X___,
  X__X____,
  _XX_XX__};

GUI_CONST_STORAGE unsigned char acGUI_FontSONG12_0027[  3] = { /* code 0027, APOSTROPHE */
  _X______,
  _X______,
  X_______};

GUI_CONST_STORAGE unsigned char acGUI_FontSONG12_0028[ 10] = { /* code 0028, LEFT PARENTHESIS */
  __X_____,
  _X______,
  X_______,
  X_______,
  X_______,
  X_______,
  X_______,
  X_______,
  _X______,
  __X_____};

GUI_CONST_STORAGE unsigned char acGUI_FontSONG12_0029[ 10] = { /* code 0029, RIGHT PARENTHESIS */
  X_______,
  _X______,
  __X_____,
  __X_____,
  __X_____,
  __X_____,
  __X_____,
  __X_____,
  _X______,
  X_______};

GUI_CONST_STORAGE unsigned char acGUI_FontSONG12_002A[  6] = { /* code 002A, ASTERISK */
  __X_____,
  X_X_X___,
  _XXX____,
  _XXX____,
  X_X_X___,
  __X_____};

GUI_CONST_STORAGE unsigned char acGUI_FontSONG12_002B[  7] = { /* code 002B, PLUS SIGN */
  __X_____,
  __X_____,
  __X_____,
  XXXXX___,
  __X_____,
  __X_____,
  __X_____};

GUI_CONST_STORAGE unsigned char acGUI_FontSONG12_002C[  3] = { /* code 002C, COMMA */
  _X______,
  _X______,
  X_______};

GUI_CONST_STORAGE unsigned char acGUI_FontSONG12_002D[  1] = { /* code 002D, HYPHEN-MINUS */
  XXXXX___};

GUI_CONST_STORAGE unsigned char acGUI_FontSONG12_002E[  1] = { /* code 002E, FULL STOP */
  X_______};

GUI_CONST_STORAGE unsigned char acGUI_FontSONG12_002F[ 10] = { /* code 002F, SOLIDUS */
  ____X___,
  ___X____,
  ___X____,
  ___X____,
  __X_____,
  __X_____,
  _X______,
  _X______,
  _X______,
  X_______};

GUI_CONST_STORAGE unsigned char acGUI_FontSONG12_0030[  8] = { /* code 0030, DIGIT ZERO */
  _XXX____,
  X___X___,
  X___X___,
  X___X___,
  X___X___,
  X___X___,
  X___X___,
  _XXX____};

GUI_CONST_STORAGE unsigned char acGUI_FontSONG12_0031[  8] = { /* code 0031, DIGIT ONE */
  _X______,
  XX______,
  _X______,
  _X______,
  _X______,
  _X______,
  _X______,
  XXX_____};

GUI_CONST_STORAGE unsigned char acGUI_FontSONG12_0032[  8] = { /* code 0032, DIGIT TWO */
  _XXX____,
  X___X___,
  X___X___,
  ___X____,
  __X_____,
  _X______,
  X_______,
  XXXXX___};

GUI_CONST_STORAGE unsigned char acGUI_FontSONG12_0033[  8] = { /* code 0033, DIGIT THREE */
  _XXX____,
  X___X___,
  ____X___,
  __XX____,
  ____X___,
  ____X___,
  X___X___,
  _XXX____};

GUI_CONST_STORAGE unsigned char acGUI_FontSONG12_0034[  8] = { /* code 0034, DIGIT FOUR */
  ___X____,
  __XX____,
  _X_X____,
  _X_X____,
  X__X____,
  _XXXX___,
  ___X____,
  ___XX___};

GUI_CONST_STORAGE unsigned char acGUI_FontSONG12_0035[  8] = { /* code 0035, DIGIT FIVE */
  XXXXX___,
  X_______,
  X_______,
  XXXX____,
  ____X___,
  ____X___,
  X___X___,
  _XXX____};

GUI_CONST_STORAGE unsigned char acGUI_FontSONG12_0036[  8] = { /* code 0036, DIGIT SIX */
  _XXX____,
  X__X____,
  X_______,
  XXXX____,
  X___X___,
  X___X___,
  X___X___,
  _XXX____};

GUI_CONST_STORAGE unsigned char acGUI_FontSONG12_0037[  8] = { /* code 0037, DIGIT SEVEN */
  XXXXX___,
  X__X____,
  ___X____,
  __X_____,
  __X_____,
  __X_____,
  __X_____,
  __X_____};

GUI_CONST_STORAGE unsigned char acGUI_FontSONG12_0038[  8] = { /* code 0038, DIGIT EIGHT */
  _XXX____,
  X___X___,
  X___X___,
  _XXX____,
  X___X___,
  X___X___,
  X___X___,
  _XXX____};

GUI_CONST_STORAGE unsigned char acGUI_FontSONG12_0039[  8] = { /* code 0039, DIGIT NINE */
  _XXX____,
  X___X___,
  X___X___,
  X___X___,
  _XXXX___,
  ____X___,
  _X__X___,
  _XXX____};

GUI_CONST_STORAGE unsigned char acGUI_FontSONG12_003A[  6] = { /* code 003A, COLON */
  X_______,
  ________,
  ________,
  ________,
  ________,
  X_______};

GUI_CONST_STORAGE unsigned char acGUI_FontSONG12_003B[  6] = { /* code 003B, SEMICOLON */
  X_______,
  ________,
  ________,
  ________,
  X_______,
  X_______};

GUI_CONST_STORAGE unsigned char acGUI_FontSONG12_003C[  9] = { /* code 003C, LESS-THAN SIGN */
  ____X___,
  ___X____,
  __X_____,
  _X______,
  X_______,
  _X______,
  __X_____,
  ___X____,
  ____X___};

GUI_CONST_STORAGE unsigned char acGUI_FontSONG12_003D[  4] = { /* code 003D, EQUALS SIGN */
  XXXXX___,
  ________,
  ________,
  XXXXX___};

GUI_CONST_STORAGE unsigned char acGUI_FontSONG12_003E[  9] = { /* code 003E, GREATER-THAN SIGN */
  X_______,
  _X______,
  __X_____,
  ___X____,
  ____X___,
  ___X____,
  __X_____,
  _X______,
  X_______};

GUI_CONST_STORAGE unsigned char acGUI_FontSONG12_003F[  8] = { /* code 003F, QUESTION MARK */
  _XXX____,
  X___X___,
  X___X___,
  ___X____,
  __X_____,
  __X_____,
  ________,
  __X_____};

GUI_CONST_STORAGE unsigned char acGUI_FontSONG12_0040[  8] = { /* code 0040, COMMERCIAL AT */
  _XXX____,
  X___X___,
  X__XX___,
  X_X_X___,
  X_X_X___,
  X_XXX___,
  X_______,
  _XXXX___};

GUI_CONST_STORAGE unsigned char acGUI_FontSONG12_0041[  8] = { /* code 0041, LATIN CAPITAL LETTER A */
  __X_____,
  __X_____,
  __XX____,
  _X_X____,
  _X_X____,
  _XXXX___,
  _X__X___,
  XX__XX__};

GUI_CONST_STORAGE unsigned char acGUI_FontSONG12_0042[  8] = { /* code 0042, LATIN CAPITAL LETTER B */
  XXXX____,
  _X__X___,
  _X__X___,
  _XXX____,
  _X__X___,
  _X__X___,
  _X__X___,
  XXXX____};

GUI_CONST_STORAGE unsigned char acGUI_FontSONG12_0043[  8] = { /* code 0043, LATIN CAPITAL LETTER C */
  _XXXX___,
  X___X___,
  X_______,
  X_______,
  X_______,
  X_______,
  X___X___,
  _XXX____};

GUI_CONST_STORAGE unsigned char acGUI_FontSONG12_0044[  8] = { /* code 0044, LATIN CAPITAL LETTER D */
  XXXX____,
  _X__X___,
  _X__X___,
  _X__X___,
  _X__X___,
  _X__X___,
  _X__X___,
  XXXX____};

GUI_CONST_STORAGE unsigned char acGUI_FontSONG12_0045[  8] = { /* code 0045, LATIN CAPITAL LETTER E */
  XXXXX___,
  _X__X___,
  _X_X____,
  _XXX____,
  _X_X____,
  _X______,
  _X__X___,
  XXXXX___};

GUI_CONST_STORAGE unsigned char acGUI_FontSONG12_0046[  8] = { /* code 0046, LATIN CAPITAL LETTER F */
  XXXXX___,
  _X__X___,
  _X_X____,
  _XXX____,
  _X_X____,
  _X______,
  _X______,
  XXX_____};

GUI_CONST_STORAGE unsigned char acGUI_FontSONG12_0047[  8] = { /* code 0047, LATIN CAPITAL LETTER G */
  __XXX___,
  _X__X___,
  X_______,
  X_______,
  X__XXX__,
  X___X___,
  _X__X___,
  __XX____};

GUI_CONST_STORAGE unsigned char acGUI_FontSONG12_0048[  8] = { /* code 0048, LATIN CAPITAL LETTER H */
  XX__XX__,
  _X__X___,
  _X__X___,
  _XXXX___,
  _X__X___,
  _X__X___,
  _X__X___,
  XX__XX__};

GUI_CONST_STORAGE unsigned char acGUI_FontSONG12_0049[  8] = { /* code 0049, LATIN CAPITAL LETTER I */
  XXXXX___,
  __X_____,
  __X_____,
  __X_____,
  __X_____,
  __X_____,
  __X_____,
  XXXXX___};

GUI_CONST_STORAGE unsigned char acGUI_FontSONG12_004A[  9] = { /* code 004A, LATIN CAPITAL LETTER J */
  _XXXXX__,
  ___X____,
  ___X____,
  ___X____,
  ___X____,
  ___X____,
  ___X____,
  X__X____,
  XXX_____};

GUI_CONST_STORAGE unsigned char acGUI_FontSONG12_004B[  8] = { /* code 004B, LATIN CAPITAL LETTER K */
  XXX_XX__,
  _X__X___,
  _X_X____,
  _XX_____,
  _X_X____,
  _X_X____,
  _X__X___,
  XXX_XX__};

GUI_CONST_STORAGE unsigned char acGUI_FontSONG12_004C[  8] = { /* code 004C, LATIN CAPITAL LETTER L */
  XXX_____,
  _X______,
  _X______,
  _X______,
  _X______,
  _X______,
  _X___X__,
  XXXXXX__};

GUI_CONST_STORAGE unsigned char acGUI_FontSONG12_004D[  8] = { /* code 004D, LATIN CAPITAL LETTER M */
  XX_XX___,
  XX_XX___,
  XX_XX___,
  XX_XX___,
  X_X_X___,
  X_X_X___,
  X_X_X___,
  X_X_X___};

GUI_CONST_STORAGE unsigned char acGUI_FontSONG12_004E[  8] = { /* code 004E, LATIN CAPITAL LETTER N */
  XX_XXX__,
  _X__X___,
  _XX_X___,
  _XX_X___,
  _X_XX___,
  _X_XX___,
  _X__X___,
  XXX_X___};

GUI_CONST_STORAGE unsigned char acGUI_FontSONG12_004F[  8] = { /* code 004F, LATIN CAPITAL LETTER O */
  _XXX____,
  X___X___,
  X___X___,
  X___X___,
  X___X___,
  X___X___,
  X___X___,
  _XXX____};

GUI_CONST_STORAGE unsigned char acGUI_FontSONG12_0050[  8] = { /* code 0050, LATIN CAPITAL LETTER P */
  XXXX____,
  _X__X___,
  _X__X___,
  _XXX____,
  _X______,
  _X______,
  _X______,
  XXX_____};

GUI_CONST_STORAGE unsigned char acGUI_FontSONG12_0051[  9] = { /* code 0051, LATIN CAPITAL LETTER Q */
  _XXX____,
  X___X___,
  X___X___,
  X___X___,
  X___X___,
  XXX_X___,
  X__XX___,
  _XXX____,
  ___XX___};

GUI_CONST_STORAGE unsigned char acGUI_FontSONG12_0052[  8] = { /* code 0052, LATIN CAPITAL LETTER R */
  XXXX____,
  _X__X___,
  _X__X___,
  _XXX____,
  _X_X____,
  _X__X___,
  _X__X___,
  XXX_XX__};

GUI_CONST_STORAGE unsigned char acGUI_FontSONG12_0053[  8] = { /* code 0053, LATIN CAPITAL LETTER S */
  _XXXX___,
  X___X___,
  X_______,
  _XX_____,
  ___X____,
  ____X___,
  X___X___,
  XXXX____};

GUI_CONST_STORAGE unsigned char acGUI_FontSONG12_0054[  8] = { /* code 0054, LATIN CAPITAL LETTER T */
  XXXXX___,
  X_X_X___,
  __X_____,
  __X_____,
  __X_____,
  __X_____,
  __X_____,
  _XXX____};

GUI_CONST_STORAGE unsigned char acGUI_FontSONG12_0055[  8] = { /* code 0055, LATIN CAPITAL LETTER U */
  XX__XX__,
  _X__X___,
  _X__X___,
  _X__X___,
  _X__X___,
  _X__X___,
  _X__X___,
  __XX____};

GUI_CONST_STORAGE unsigned char acGUI_FontSONG12_0056[  8] = { /* code 0056, LATIN CAPITAL LETTER V */
  XX__XX__,
  _X__X___,
  _X__X___,
  _X_X____,
  _X_X____,
  __XX____,
  __X_____,
  __X_____};

GUI_CONST_STORAGE unsigned char acGUI_FontSONG12_0057[  8] = { /* code 0057, LATIN CAPITAL LETTER W */
  X_X_X___,
  X_X_X___,
  X_X_X___,
  _XXX____,
  _X_X____,
  _X_X____,
  _X_X____,
  _X_X____};

GUI_CONST_STORAGE unsigned char acGUI_FontSONG12_0058[  8] = { /* code 0058, LATIN CAPITAL LETTER X */
  XX_XX___,
  _X_X____,
  _X_X____,
  __X_____,
  __X_____,
  _X_X____,
  _X_X____,
  XX_XX___};

GUI_CONST_STORAGE unsigned char acGUI_FontSONG12_0059[  8] = { /* code 0059, LATIN CAPITAL LETTER Y */
  XX_XX___,
  _X_X____,
  _X_X____,
  __X_____,
  __X_____,
  __X_____,
  __X_____,
  _XXX____};

GUI_CONST_STORAGE unsigned char acGUI_FontSONG12_005A[  8] = { /* code 005A, LATIN CAPITAL LETTER Z */
  XXXXX___,
  X__X____,
  ___X____,
  __X_____,
  __X_____,
  _X______,
  _X__X___,
  XXXXX___};

GUI_CONST_STORAGE unsigned char acGUI_FontSONG12_005B[ 10] = { /* code 005B, LEFT SQUARE BRACKET */
  XXX_____,
  X_______,
  X_______,
  X_______,
  X_______,
  X_______,
  X_______,
  X_______,
  X_______,
  XXX_____};

GUI_CONST_STORAGE unsigned char acGUI_FontSONG12_005C[ 10] = { /* code 005C, REVERSE SOLIDUS */
  X_______,
  X_______,
  X_______,
  _X______,
  _X______,
  __X_____,
  __X_____,
  __X_____,
  ___X____,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontSONG12_005D[ 10] = { /* code 005D, RIGHT SQUARE BRACKET */
  XXX_____,
  __X_____,
  __X_____,
  __X_____,
  __X_____,
  __X_____,
  __X_____,
  __X_____,
  __X_____,
  XXX_____};

GUI_CONST_STORAGE unsigned char acGUI_FontSONG12_005E[  2] = { /* code 005E, CIRCUMFLEX ACCENT */
  _X______,
  X_X_____};

GUI_CONST_STORAGE unsigned char acGUI_FontSONG12_005F[  1] = { /* code 005F, LOW LINE */
  XXXXXX__};

GUI_CONST_STORAGE unsigned char acGUI_FontSONG12_0060[  1] = { /* code 0060, GRAVE ACCENT */
  _X______};

GUI_CONST_STORAGE unsigned char acGUI_FontSONG12_0061[  5] = { /* code 0061, LATIN SMALL LETTER A */
  _XX_____,
  X__X____,
  _XXX____,
  X__X____,
  _XXXX___};

GUI_CONST_STORAGE unsigned char acGUI_FontSONG12_0062[  8] = { /* code 0062, LATIN SMALL LETTER B */
  XX______,
  _X______,
  _X______,
  _XXX____,
  _X__X___,
  _X__X___,
  _X__X___,
  _XXX____};

GUI_CONST_STORAGE unsigned char acGUI_FontSONG12_0063[  5] = { /* code 0063, LATIN SMALL LETTER C */
  _XXX____,
  X__X____,
  X_______,
  X_______,
  _XXX____};

GUI_CONST_STORAGE unsigned char acGUI_FontSONG12_0064[  8] = { /* code 0064, LATIN SMALL LETTER D */
  __XX____,
  ___X____,
  ___X____,
  _XXX____,
  X__X____,
  X__X____,
  X__X____,
  _XXXX___};

GUI_CONST_STORAGE unsigned char acGUI_FontSONG12_0065[  5] = { /* code 0065, LATIN SMALL LETTER E */
  _XX_____,
  X__X____,
  XXXX____,
  X_______,
  _XXX____};

GUI_CONST_STORAGE unsigned char acGUI_FontSONG12_0066[  8] = { /* code 0066, LATIN SMALL LETTER F */
  __XXX___,
  _X______,
  _X______,
  XXXX____,
  _X______,
  _X______,
  _X______,
  XXXX____};

GUI_CONST_STORAGE unsigned char acGUI_FontSONG12_0067[  7] = { /* code 0067, LATIN SMALL LETTER G */
  _XXXX___,
  X__X____,
  _XX_____,
  X_______,
  XXXX____,
  X___X___,
  _XXX____};

GUI_CONST_STORAGE unsigned char acGUI_FontSONG12_0068[  8] = { /* code 0068, LATIN SMALL LETTER H */
  XX______,
  _X______,
  _X______,
  _XXX____,
  _X__X___,
  _X__X___,
  _X__X___,
  XXX_XX__};

GUI_CONST_STORAGE unsigned char acGUI_FontSONG12_0069[  8] = { /* code 0069, LATIN SMALL LETTER I */
  _X______,
  ________,
  ________,
  XX______,
  _X______,
  _X______,
  _X______,
  XXX_____};

GUI_CONST_STORAGE unsigned char acGUI_FontSONG12_006A[ 10] = { /* code 006A, LATIN SMALL LETTER J */
  ___X____,
  ________,
  ________,
  __XX____,
  ___X____,
  ___X____,
  ___X____,
  ___X____,
  ___X____,
  XXX_____};

GUI_CONST_STORAGE unsigned char acGUI_FontSONG12_006B[  8] = { /* code 006B, LATIN SMALL LETTER K */
  XX______,
  _X______,
  _X______,
  _X_XXX__,
  _X_X____,
  _XXX____,
  _X__X___,
  XXX_XX__};

GUI_CONST_STORAGE unsigned char acGUI_FontSONG12_006C[  8] = { /* code 006C, LATIN SMALL LETTER L */
  XXX_____,
  __X_____,
  __X_____,
  __X_____,
  __X_____,
  __X_____,
  __X_____,
  XXXXX___};

GUI_CONST_STORAGE unsigned char acGUI_FontSONG12_006D[  5] = { /* code 006D, LATIN SMALL LETTER M */
  XXXX____,
  X_X_X___,
  X_X_X___,
  X_X_X___,
  X_X_X___};

GUI_CONST_STORAGE unsigned char acGUI_FontSONG12_006E[  5] = { /* code 006E, LATIN SMALL LETTER N */
  XXXX____,
  _X__X___,
  _X__X___,
  _X__X___,
  XXX_XX__};

GUI_CONST_STORAGE unsigned char acGUI_FontSONG12_006F[  5] = { /* code 006F, LATIN SMALL LETTER O */
  _XX_____,
  X__X____,
  X__X____,
  X__X____,
  _XX_____};

GUI_CONST_STORAGE unsigned char acGUI_FontSONG12_0070[  7] = { /* code 0070, LATIN SMALL LETTER P */
  XXXX____,
  _X__X___,
  _X__X___,
  _X__X___,
  _XXX____,
  _X______,
  XXX_____};

GUI_CONST_STORAGE unsigned char acGUI_FontSONG12_0071[  7] = { /* code 0071, LATIN SMALL LETTER Q */
  _XXX____,
  X__X____,
  X__X____,
  X__X____,
  _XXX____,
  ___X____,
  __XXX___};

GUI_CONST_STORAGE unsigned char acGUI_FontSONG12_0072[  5] = { /* code 0072, LATIN SMALL LETTER R */
  XX_XX___,
  _XX_____,
  _X______,
  _X______,
  XXX_____};

GUI_CONST_STORAGE unsigned char acGUI_FontSONG12_0073[  5] = { /* code 0073, LATIN SMALL LETTER S */
  XXXX____,
  X_______,
  _XX_____,
  ___X____,
  XXXX____};

GUI_CONST_STORAGE unsigned char acGUI_FontSONG12_0074[  7] = { /* code 0074, LATIN SMALL LETTER T */
  _X______,
  _X______,
  XXX_____,
  _X______,
  _X______,
  _X______,
  __XX____};

GUI_CONST_STORAGE unsigned char acGUI_FontSONG12_0075[  5] = { /* code 0075, LATIN SMALL LETTER U */
  XX_XX___,
  _X__X___,
  _X__X___,
  _X__X___,
  __XXXX__};

GUI_CONST_STORAGE unsigned char acGUI_FontSONG12_0076[  5] = { /* code 0076, LATIN SMALL LETTER V */
  XXX_XX__,
  _X__X___,
  _X_X____,
  __XX____,
  __X_____};

GUI_CONST_STORAGE unsigned char acGUI_FontSONG12_0077[  5] = { /* code 0077, LATIN SMALL LETTER W */
  X_X_X___,
  X_X_X___,
  _XXX____,
  _X_X____,
  _X_X____};

GUI_CONST_STORAGE unsigned char acGUI_FontSONG12_0078[  5] = { /* code 0078, LATIN SMALL LETTER X */
  XX_XX___,
  _X_X____,
  __X_____,
  _X_X____,
  XX_XX___};

GUI_CONST_STORAGE unsigned char acGUI_FontSONG12_0079[  7] = { /* code 0079, LATIN SMALL LETTER Y */
  XXX_XX__,
  _X__X___,
  _X_X____,
  __XX____,
  __X_____,
  __X_____,
  XX______};

GUI_CONST_STORAGE unsigned char acGUI_FontSONG12_007A[  5] = { /* code 007A, LATIN SMALL LETTER Z */
  XXXX____,
  __X_____,
  _X______,
  _X______,
  XXXX____};

GUI_CONST_STORAGE unsigned char acGUI_FontSONG12_007B[ 10] = { /* code 007B, LEFT CURLY BRACKET */
  _XX_____,
  _X______,
  _X______,
  _X______,
  X_______,
  _X______,
  _X______,
  _X______,
  _X______,
  _XX_____};

GUI_CONST_STORAGE unsigned char acGUI_FontSONG12_007C[ 12] = { /* code 007C, VERTICAL LINE */
  X_______,
  X_______,
  X_______,
  X_______,
  X_______,
  X_______,
  X_______,
  X_______,
  X_______,
  X_______,
  X_______,
  X_______};

GUI_CONST_STORAGE unsigned char acGUI_FontSONG12_007D[ 10] = { /* code 007D, RIGHT CURLY BRACKET */
  XX______,
  _X______,
  _X______,
  _X______,
  __X_____,
  _X______,
  _X______,
  _X______,
  _X______,
  XX______};

GUI_CONST_STORAGE unsigned char acGUI_FontSONG12_007E[  3] = { /* code 007E, TILDE */
  _X______,
  X_X__X__,
  ___XX___};

/* Start of unicode area <Basic Greek> */
GUI_CONST_STORAGE unsigned char acGUI_FontSONG12_03A9[ 16] = { /* code 03A9, GREEK CAPITAL LETTER OMEGA */
  ___XXX__,________,
  __X___X_,________,
  _XX___XX,________,
  _XX___XX,________,
  _XX___XX,________,
  __X___X_,________,
  X_XX_XX_,X_______,
  XXXX_XXX,X_______};

/* Start of unicode area <CJK Unified Ideographs> */
GUI_CONST_STORAGE unsigned char acGUI_FontSONG12_4E0A[ 24] = { /* code 4E0A */
  ____X___,________,
  ____X___,________,
  ____X___,________,
  ____X___,________,
  ____XXXX,XX______,
  ____X___,________,
  ____X___,________,
  ____X___,________,
  ____X___,________,
  ____X___,________,
  ____X___,________,
  XXXXXXXX,XXX_____};

GUI_CONST_STORAGE unsigned char acGUI_FontSONG12_4E0B[ 22] = { /* code 4E0B */
  XXXXXXXX,XXX_____,
  ____X___,________,
  ____X___,________,
  ____X_X_,________,
  ____X__X,________,
  ____X___,X_______,
  ____X___,_X______,
  ____X___,_X______,
  ____X___,________,
  ____X___,________,
  ____X___,________};

GUI_CONST_STORAGE unsigned char acGUI_FontSONG12_4E2D[ 24] = { /* code 4E2D */
  ____X___,________,
  ____X___,________,
  ____X___,________,
  XXXXXXXX,X_______,
  X___X___,X_______,
  X___X___,X_______,
  X___X___,X_______,
  XXXXXXXX,X_______,
  X___X___,X_______,
  ____X___,________,
  ____X___,________,
  ____X___,________};

GUI_CONST_STORAGE unsigned char acGUI_FontSONG12_4EA7[ 24] = { /* code 4EA7 */
  ____X___,________,
  _____X__,________,
  _XXXXXXX,XXX_____,
  ________,________,
  ___X____,X_______,
  ____X__X,________,
  _XXXXXXX,XXX_____,
  _X______,________,
  _X______,________,
  _X______,________,
  _X______,________,
  X_______,________};

GUI_CONST_STORAGE unsigned char acGUI_FontSONG12_4EEA[ 24] = { /* code 4EEA */
  ___X__X_,________,
  ___X___X,________,
  __X____X,__X_____,
  __X_X___,__X_____,
  _XX_X___,__X_____,
  X_X__X__,_X______,
  __X__X__,_X______,
  __X___X_,X_______,
  __X____X,________,
  __X___X_,X_______,
  __X__X__,_X______,
  __X_X___,__X_____};

GUI_CONST_STORAGE unsigned char acGUI_FontSONG12_4EF6[ 24] = { /* code 4EF6 */
  __X____X,________,
  __X_X__X,________,
  _X__X__X,________,
  _X__XXXX,XXX_____,
  XX_X___X,________,
  _X_____X,________,
  _X_____X,________,
  _X_XXXXX,XXX_____,
  _X_____X,________,
  _X_____X,________,
  _X_____X,________,
  _X_____X,________};

GUI_CONST_STORAGE unsigned char acGUI_FontSONG12_4FE1[ 24] = { /* code 4FE1 */
  __X___X_,________,
  __X____X,________,
  _X_XXXXX,XXX_____,
  _X______,________,
  XX__XXXX,XX______,
  _X______,________,
  _X__XXXX,XX______,
  _X______,________,
  _X__XXXX,XX______,
  _X__X___,_X______,
  _X__XXXX,XX______,
  _X__X___,_X______};

GUI_CONST_STORAGE unsigned char acGUI_FontSONG12_5145[ 24] = { /* code 5145 */
  ____X___,________,
  _____X__,________,
  XXXXXXXX,XXX_____,
  ____X___,________,
  ___X___X,________,
  __X_____,X_______,
  _XXXXXXX,XX______,
  ___X___X,_X______,
  ___X___X,________,
  ___X___X,__X_____,
  __X____X,__X_____,
  XX______,XXX_____};

GUI_CONST_STORAGE unsigned char acGUI_FontSONG12_5165[ 24] = { /* code 5165 */
  __XX____,________,
  ____X___,________,
  _____X__,________,
  _____X__,________,
  ____X_X_,________,
  ____X_X_,________,
  ____X_X_,________,
  ___X___X,________,
  ___X___X,________,
  __X_____,X_______,
  _X______,_X______,
  X_______,__X_____};

GUI_CONST_STORAGE unsigned char acGUI_FontSONG12_5173[ 24] = { /* code 5173 */
  __X_____,X_______,
  ___X___X,________,
  ________,________,
  _XXXXXXX,XX______,
  _____X__,________,
  _____X__,________,
  XXXXXXXX,XXX_____,
  _____X__,________,
  ____X_X_,________,
  ___X___X,________,
  __X_____,X_______,
  XX______,_XX_____};

GUI_CONST_STORAGE unsigned char acGUI_FontSONG12_5185[ 24] = { /* code 5185 */
  ____X___,________,
  ____X___,________,
  XXXXXXXX,X_______,
  X___X___,X_______,
  X___X___,X_______,
  X__X_X__,X_______,
  X__X__X_,X_______,
  X_X___X_,X_______,
  X_______,X_______,
  X_______,X_______,
  X_______,X_______,
  X_____XX,X_______};

GUI_CONST_STORAGE unsigned char acGUI_FontSONG12_51FA[ 24] = { /* code 51FA */
  _____X__,________,
  _X___X__,_X______,
  _X___X__,_X______,
  _X___X__,_X______,
  _XXXXXXX,XX______,
  _____X__,________,
  _____X__,________,
  X____X__,__X_____,
  X____X__,__X_____,
  X____X__,__X_____,
  XXXXXXXX,XXX_____,
  ________,__X_____};

GUI_CONST_STORAGE unsigned char acGUI_FontSONG12_5206[ 24] = { /* code 5206 */
  ___X___X,________,
  ___X___X,________,
  __X_____,X_______,
  __X_____,X_______,
  _X______,_X______,
  X_XXXXXX,X_X_____,
  ____X___,X_______,
  ____X___,X_______,
  ___X____,X_______,
  ___X____,X_______,
  __X_____,X_______,
  _X___XXX,________};

GUI_CONST_STORAGE unsigned char acGUI_FontSONG12_5236[ 24] = { /* code 5236 */
  ___X____,__X_____,
  _X_X____,__X_____,
  _XXXXX_X,__X_____,
  X__X___X,__X_____,
  XXXXXXXX,__X_____,
  ___X___X,__X_____,
  _XXXXX_X,__X_____,
  _X_X_X_X,__X_____,
  _X_X_X_X,__X_____,
  _X_X_X__,__X_____,
  _X_XXX__,__X_____,
  ___X____,XXX_____};

GUI_CONST_STORAGE unsigned char acGUI_FontSONG12_538B[ 22] = { /* code 538B */
  _XXXXXXX,XXX_____,
  _X______,________,
  _X____X_,________,
  _X____X_,________,
  _X____X_,________,
  _X_XXXXX,XX______,
  _X____X_,________,
  _X____X_,X_______,
  _X____X_,_X______,
  _X____X_,________,
  X_XXXXXX,XXX_____};

GUI_CONST_STORAGE unsigned char acGUI_FontSONG12_53F7[ 24] = { /* code 53F7 */
  __XXXXXX,X_______,
  __X_____,X_______,
  __X_____,X_______,
  __XXXXXX,X_______,
  ________,________,
  XXXXXXXX,XXX_____,
  ___X____,________,
  __X_____,________,
  __XXXXXX,XX______,
  ________,_X______,
  ________,_X______,
  _______X,X_______};

GUI_CONST_STORAGE unsigned char acGUI_FontSONG12_542F[ 24] = { /* code 542F */
  _____X__,________,
  ______X_,________,
  __XXXXXX,XXX_____,
  __X_____,__X_____,
  __X_____,__X_____,
  __XXXXXX,XXX_____,
  __X_____,________,
  __XXXXXX,XXX_____,
  __XX____,__X_____,
  _X_X____,__X_____,
  _X_XXXXX,XXX_____,
  X__X____,__X_____};

GUI_CONST_STORAGE unsigned char acGUI_FontSONG12_5668[ 24] = { /* code 5668 */
  _XXXX_XX,XX______,
  _X__X_X_,_X______,
  _XXXX_XX,XX______,
  _____X__,X_______,
  _____X__,_X______,
  XXXXXXXX,XXX_____,
  ____X_X_,________,
  __XX___X,X_______,
  XX______,_XX_____,
  _XXXX_XX,XX______,
  _X__X_X_,_X______,
  _XXXX_XX,XX______};

GUI_CONST_STORAGE unsigned char acGUI_FontSONG12_56FE[ 24] = { /* code 56FE */
  XXXXXXXX,XXX_____,
  X___X___,__X_____,
  X__XXXXX,__X_____,
  X_XX___X,__X_____,
  X___XXX_,__X_____,
  XXXX___X,XXX_____,
  X___XX__,__X_____,
  X_____X_,__X_____,
  X__XX___,__X_____,
  X____XX_,__X_____,
  XXXXXXXX,XXX_____,
  X_______,__X_____};

GUI_CONST_STORAGE unsigned char acGUI_FontSONG12_5728[ 24] = { /* code 5728 */
  ____X___,________,
  ____X___,________,
  XXXXXXXX,XXX_____,
  ___X____,________,
  ___X___X,________,
  __X____X,________,
  _XX____X,________,
  X_X__XXX,XX______,
  __X____X,________,
  __X____X,________,
  __X____X,________,
  __X_XXXX,XXX_____};

GUI_CONST_STORAGE unsigned char acGUI_FontSONG12_578B[ 24] = { /* code 578B */
  ________,__X_____,
  _XXXXXX_,X_X_____,
  __X__X__,X_X_____,
  __X__X__,X_X_____,
  XXXXXXX_,X_X_____,
  __X__X__,X_X_____,
  _X___X__,__X_____,
  X_______,_XX_____,
  _____X__,________,
  _XXXXXXX,XX______,
  _____X__,________,
  XXXXXXXX,XXX_____};

GUI_CONST_STORAGE unsigned char acGUI_FontSONG12_58F0[ 24] = { /* code 58F0 */
  _____X__,________,
  XXXXXXXX,XXX_____,
  _____X__,________,
  _XXXXXXX,XX______,
  ________,________,
  _XXXXXXX,XX______,
  _X___X__,_X______,
  _X___X__,_X______,
  _XXXXXXX,XX______,
  _X______,_X______,
  _X______,________,
  X_______,________};

GUI_CONST_STORAGE unsigned char acGUI_FontSONG12_59CB[ 24] = { /* code 59CB */
  __X____X,________,
  __X____X,________,
  __X___X_,________,
  XXXX_X__,_X______,
  _X_X_XXX,XXX_____,
  _X_X____,__X_____,
  _X_X_XXX,XX______,
  X__X_X__,_X______,
  _X_X_X__,_X______,
  __X__X__,_X______,
  _X_X_XXX,XX______,
  X__X_X__,_X______};

GUI_CONST_STORAGE unsigned char acGUI_FontSONG12_5B9A[ 24] = { /* code 5B9A */
  ____X___,________,
  _____X__,________,
  XXXXXXXX,XXX_____,
  X_______,__X_____,
  ________,________,
  XXXXXXXX,XXX_____,
  _____X__,________,
  __X__X__,________,
  __X__XXX,XX______,
  __X__X__,________,
  _X_X_X__,________,
  X___XXXX,XXX_____};

GUI_CONST_STORAGE unsigned char acGUI_FontSONG12_5BC6[ 24] = { /* code 5BC6 */
  _____X__,________,
  XXXXXXXX,XXX_____,
  X___X___,__X_____,
  _____X_X,________,
  _X_X__X_,_X______,
  _X_X_X__,X_X_____,
  X___XXXX,X_X_____,
  __XX____,________,
  _____X__,________,
  _X___X__,_X______,
  _X___X__,_X______,
  _XXXXXXX,XX______};

GUI_CONST_STORAGE unsigned char acGUI_FontSONG12_5C0F[ 24] = { /* code 5C0F */
  _____X__,________,
  _____X__,________,
  _____X__,________,
  _____X__,________,
  __X__X__,X_______,
  __X__X__,_X______,
  _X___X__,_X______,
  _X___X__,__X_____,
  X____X__,__X_____,
  _____X__,________,
  _____X__,________,
  ___XXX__,________};

GUI_CONST_STORAGE unsigned char acGUI_FontSONG12_5F00[ 22] = { /* code 5F00 */
  _XXXXXXX,XX______,
  ___X___X,________,
  ___X___X,________,
  ___X___X,________,
  ___X___X,________,
  XXXXXXXX,XXX_____,
  ___X___X,________,
  ___X___X,________,
  __X____X,________,
  __X____X,________,
  _X_____X,________};

GUI_CONST_STORAGE unsigned char acGUI_FontSONG12_5F85[ 24] = { /* code 5F85 */
  ___X___X,________,
  __X____X,________,
  _X___XXX,XX______,
  X__X___X,________,
  __X_XXXX,XXX_____,
  _XX_____,X_______,
  X_X_XXXX,XXX_____,
  __X_____,X_______,
  __X__X__,X_______,
  __X___X_,X_______,
  __X_____,X_______,
  __X___XX,X_______};

GUI_CONST_STORAGE unsigned char acGUI_FontSONG12_5FAA[ 24] = { /* code 5FAA */
  __X_____,_XX_____,
  _X__XXXX,X_______,
  X___X___,X_______,
  __X_XXXX,XXX_____,
  _X__X___,X_______,
  XX__X_XX,XXX_____,
  _X__X_X_,__X_____,
  _X__X_XX,XXX_____,
  _X__X_X_,__X_____,
  _X__X_XX,XXX_____,
  _X__X_X_,__X_____,
  _X_X__XX,XXX_____};

GUI_CONST_STORAGE unsigned char acGUI_FontSONG12_606F[ 24] = { /* code 606F */
  ____X___,________,
  _XXXXXXX,XX______,
  _X______,_X______,
  _XXXXXXX,XX______,
  _X______,_X______,
  _XXXXXXX,XX______,
  _X______,_X______,
  _XXXXXXX,XX______,
  _____X__,________,
  _X_X__X_,_X______,
  _X_X____,X_X_____,
  X___XXXX,X_X_____};

GUI_CONST_STORAGE unsigned char acGUI_FontSONG12_622A[ 24] = { /* code 622A */
  ___X___X,_X______,
  _XXXXX_X,__X_____,
  ___X___X,________,
  XXXXXXXX,XXX_____,
  __X_X__X,________,
  _XXXXXXX,_X______,
  XX__X__X,_X______,
  _XXXXXXX,_X______,
  _X__X___,X_______,
  _XXXXXX_,X_X_____,
  _X__X__X,_XX_____,
  _XXXXXX_,__X_____};

GUI_CONST_STORAGE unsigned char acGUI_FontSONG12_62A5[ 24] = { /* code 62A5 */
  __X_____,________,
  __X__XXX,XXX_____,
  __X__X__,__X_____,
  XXXX_X__,__X_____,
  __X__X__,XX______,
  __X__X__,________,
  __XX_XXX,XXX_____,
  XXX__X_X,__X_____,
  __X__X_X,_X______,
  __X__X__,X_______,
  __X__X_X,_X______,
  _XX__XX_,__X_____};

GUI_CONST_STORAGE unsigned char acGUI_FontSONG12_63A7[ 24] = { /* code 63A7 */
  _X____X_,________,
  _X_____X,________,
  _X__XXXX,XXX_____,
  XXX_X___,__X_____,
  _X____X_,X_______,
  _X___X__,_X______,
  _XX_X___,__X_____,
  XX___XXX,XX______,
  _X_____X,________,
  _X_____X,________,
  _X_____X,________,
  XX__XXXX,XXX_____};

GUI_CONST_STORAGE unsigned char acGUI_FontSONG12_653E[ 24] = { /* code 653E */
  _X_____X,________,
  __X____X,________,
  _______X,________,
  XXXXX__X,XXX_____,
  _X____X_,_X______,
  _X___X_X,_X______,
  _XXXX__X,_X______,
  _X__X__X,_X______,
  _X__X__X,_X______,
  _X__X___,X_______,
  _X__X__X,_X______,
  X__XX_X_,__X_____};

GUI_CONST_STORAGE unsigned char acGUI_FontSONG12_6570[ 24] = { /* code 6570 */
  ___X___X,________,
  _X_X_X_X,________,
  ___X___X,________,
  XXXXXX_X,XXX_____,
  __XX__X_,_X______,
  _X_XX__X,_X______,
  X__X_X_X,_X______,
  __X____X,_X______,
  XXXXX__X,_X______,
  _X__X___,X_______,
  __XX___X,_X______,
  XX__X_X_,__X_____};

GUI_CONST_STORAGE unsigned char acGUI_FontSONG12_6587[ 24] = { /* code 6587 */
  ____X___,________,
  _____X__,________,
  XXXXXXXX,XXX_____,
  __X_____,X_______,
  __X_____,X_______,
  ___X___X,________,
  ___X___X,________,
  ____X_X_,________,
  _____X__,________,
  ____X_X_,________,
  __XX___X,X_______,
  XX______,_XX_____};

GUI_CONST_STORAGE unsigned char acGUI_FontSONG12_65E5[ 22] = { /* code 65E5 */
  XXXXXXXX,X_______,
  X_______,X_______,
  X_______,X_______,
  X_______,X_______,
  XXXXXXXX,X_______,
  X_______,X_______,
  X_______,X_______,
  X_______,X_______,
  X_______,X_______,
  XXXXXXXX,X_______,
  X_______,X_______};

GUI_CONST_STORAGE unsigned char acGUI_FontSONG12_65F6[ 24] = { /* code 65F6 */
  ________,_X______,
  XXXX____,_X______,
  X__X____,_X______,
  X__X_XXX,XXX_____,
  X__X____,_X______,
  XXXX____,_X______,
  X__X__X_,_X______,
  X__X___X,_X______,
  X__X___X,_X______,
  XXXX____,_X______,
  X__X____,_X______,
  _______X,XX______};

GUI_CONST_STORAGE unsigned char acGUI_FontSONG12_662F[ 24] = { /* code 662F */
  __XXXXXX,X_______,
  __X_____,X_______,
  __XXXXXX,X_______,
  __X_____,X_______,
  __XXXXXX,X_______,
  ________,________,
  XXXXXXXX,XXX_____,
  _____X__,________,
  __X__XXX,XX______,
  __X__X__,________,
  _X_X_X__,________,
  X___XXXX,XXX_____};

GUI_CONST_STORAGE unsigned char acGUI_FontSONG12_66F2[ 24] = { /* code 66F2 */
  ___X__X_,________,
  ___X__X_,________,
  XXXXXXXX,XX______,
  X__X__X_,_X______,
  X__X__X_,_X______,
  X__X__X_,_X______,
  XXXXXXXX,XX______,
  X__X__X_,_X______,
  X__X__X_,_X______,
  X__X__X_,_X______,
  XXXXXXXX,XX______,
  X_______,_X______};

GUI_CONST_STORAGE unsigned char acGUI_FontSONG12_671F[ 24] = { /* code 671F */
  _X__X___,________,
  _X__X__X,XXX_____,
  XXXXXX_X,__X_____,
  _X__X__X,__X_____,
  _XXXX__X,XXX_____,
  _X__X__X,__X_____,
  _XXXX__X,__X_____,
  _X__X__X,XXX_____,
  XXXXXX_X,__X_____,
  _______X,__X_____,
  _X__X__X,__X_____,
  X____XX_,_XX_____};

GUI_CONST_STORAGE unsigned char acGUI_FontSONG12_672A[ 24] = { /* code 672A */
  _____X__,________,
  _____X__,________,
  _XXXXXXX,XX______,
  _____X__,________,
  _____X__,________,
  XXXXXXXX,XXX_____,
  ____XXX_,________,
  ___X_X_X,________,
  __X__X__,X_______,
  XX___X__,_XX_____,
  _____X__,________,
  _____X__,________};

GUI_CONST_STORAGE unsigned char acGUI_FontSONG12_672C[ 24] = { /* code 672C */
  _____X__,________,
  _____X__,________,
  XXXXXXXX,XXX_____,
  _____X__,________,
  ____XXX_,________,
  ___X_X_X,________,
  ___X_X_X,________,
  __X__X__,X_______,
  _X___X__,_X______,
  X_XXXXXX,X_X_____,
  _____X__,________,
  _____X__,________};

GUI_CONST_STORAGE unsigned char acGUI_FontSONG12_69DB[ 24] = { /* code 69DB */
  __X___X_,X_______,
  __X_X_X_,X_______,
  __X_X_X_,XXX_____,
  XXXXX_XX,________,
  __X_X_X_,_X______,
  _XX___X_,__X_____,
  _XXX____,________,
  X_X_XXXX,XXX_____,
  __X_X_X_,X_X_____,
  __X_X_X_,X_X_____,
  __X_X_X_,X_X_____,
  __XXXXXX,XXX_____};

GUI_CONST_STORAGE unsigned char acGUI_FontSONG12_6B21[ 24] = { /* code 6B21 */
  _____X__,________,
  X____X__,________,
  _X___XXX,XXX_____,
  ____X___,__X_____,
  ____X_X_,_X______,
  ___X__X_,________,
  ______X_,________,
  __X__X_X,________,
  _X___X_X,________,
  X___X___,X_______,
  ___X____,_X______,
  __X_____,__X_____};

GUI_CONST_STORAGE unsigned char acGUI_FontSONG12_6B62[ 24] = { /* code 6B62 */
  ______X_,________,
  ______X_,________,
  ______X_,________,
  __X___X_,________,
  __X___XX,XX______,
  __X___X_,________,
  __X___X_,________,
  __X___X_,________,
  __X___X_,________,
  __X___X_,________,
  __X___X_,________,
  XXXXXXXX,XXX_____};

GUI_CONST_STORAGE unsigned char acGUI_FontSONG12_6B63[ 22] = { /* code 6B63 */
  _XXXXXXX,XX______,
  _____X__,________,
  _____X__,________,
  _____X__,________,
  __X__X__,________,
  __X__XXX,XX______,
  __X__X__,________,
  __X__X__,________,
  __X__X__,________,
  __X__X__,________,
  XXXXXXXX,XXX_____};

GUI_CONST_STORAGE unsigned char acGUI_FontSONG12_6B65[ 24] = { /* code 6B65 */
  _____X__,________,
  __X__X__,________,
  __X__XXX,XX______,
  __X__X__,________,
  __X__X__,________,
  XXXXXXXX,XXX_____,
  ________,________,
  ___X_X__,_X______,
  __X__X__,X_______,
  _X___XXX,________,
  ____XX__,________,
  _XXX____,________};

GUI_CONST_STORAGE unsigned char acGUI_FontSONG12_6C22[ 24] = { /* code 6C22 */
  __XXXXXX,XX______,
  _X______,________,
  X_XXXXXX,X_______,
  ________,________,
  _XXXXXXX,X_______,
  ________,X_______,
  _XXXXX__,X_______,
  ___XX___,X_______,
  XXX__XX_,X_______,
  _XXXXX__,X_X_____,
  ___X____,_XX_____,
  XXXXXXX_,__X_____};

GUI_CONST_STORAGE unsigned char acGUI_FontSONG12_6C60[ 24] = { /* code 6C60 */
  ______X_,________,
  X_____X_,________,
  _X_X__X_,XX______,
  ___X__XX,_X______,
  ___X_XX_,_X______,
  X__XX_X_,_X______,
  _XXX__X_,_X______,
  ___X__X_,_X______,
  ___X__X_,XX______,
  _X_X__X_,________,
  X__X____,__X_____,
  ____XXXX,XXX_____};

GUI_CONST_STORAGE unsigned char acGUI_FontSONG12_6D41[ 24] = { /* code 6D41 */
  ______X_,________,
  X______X,________,
  _X_XXXXX,XXX_____,
  _____X__,________,
  ____X___,_X______,
  X__XXXXX,XXX_____,
  _X______,__X_____,
  ____X_X_,X_______,
  ____X_X_,X_______,
  _X__X_X_,X_X_____,
  X__X__X_,X_X_____,
  __X___X_,_XX_____};

GUI_CONST_STORAGE unsigned char acGUI_FontSONG12_6D4B[ 24] = { /* code 6D4B */
  ________,__X_____,
  X_XXXXX_,__X_____,
  _XX___X_,X_X_____,
  __X_X_X_,X_X_____,
  __X_X_X_,X_X_____,
  X_X_X_X_,X_X_____,
  _XX_X_X_,X_X_____,
  __X_X_X_,X_X_____,
  __X_X_X_,X_X_____,
  _X__X___,__X_____,
  X__X_X__,__X_____,
  __X___X_,_XX_____};

GUI_CONST_STORAGE unsigned char acGUI_FontSONG12_6E90[ 24] = { /* code 6E90 */
  X__XXXXX,XXX_____,
  _X_X___X,________,
  ___X__X_,________,
  ___X_XXX,XX______,
  X__X_X__,_X______,
  _X_X_XXX,XX______,
  ___X_X__,_X______,
  ___X_XXX,XX______,
  ___X___X,________,
  _X_X_X_X,_X______,
  X__XX__X,__X_____,
  __X___XX,________};

GUI_CONST_STORAGE unsigned char acGUI_FontSONG12_7248[ 24] = { /* code 7248 */
  ___X____,_XX_____,
  _X_X_XXX,X_______,
  _X_X_X__,________,
  _X_X_X__,________,
  _XXXXXXX,XXX_____,
  _X___X_X,__X_____,
  _X___X_X,__X_____,
  _XXX_X_X,_X______,
  _X_X_X_X,_X______,
  _X_X_X__,X_______,
  _X_XX__X,_X______,
  X__X__X_,__X_____};

GUI_CONST_STORAGE unsigned char acGUI_FontSONG12_73AF[ 22] = { /* code 73AF */
  XXXX_XXX,XXX_____,
  __X_____,X_______,
  __X____X,________,
  __X____X,________,
  XXXX__XX,_X______,
  __X__X_X,__X_____,
  __X_X__X,__X_____,
  __X____X,________,
  __XX___X,________,
  XX_____X,________,
  _______X,________};

GUI_CONST_STORAGE unsigned char acGUI_FontSONG12_751F[ 24] = { /* code 751F */
  _____X__,________,
  __X__X__,________,
  __X__X__,________,
  __XXXXXX,XX______,
  _X___X__,________,
  X____X__,________,
  _____X__,________,
  __XXXXXX,X_______,
  _____X__,________,
  _____X__,________,
  _____X__,________,
  XXXXXXXX,XXX_____};

GUI_CONST_STORAGE unsigned char acGUI_FontSONG12_7535[ 24] = { /* code 7535 */
  ____X___,________,
  ____X___,________,
  XXXXXXXX,X_______,
  X___X___,X_______,
  X___X___,X_______,
  XXXXXXXX,X_______,
  X___X___,X_______,
  X___X___,X_______,
  XXXXXXXX,X_______,
  X___X___,__X_____,
  ____X___,__X_____,
  _____XXX,XXX_____};

GUI_CONST_STORAGE unsigned char acGUI_FontSONG12_77ED[ 24] = { /* code 77ED */
  _X______,________,
  _X__XXXX,XXX_____,
  _XXX____,________,
  X_X__XXX,XX______,
  __X__X__,_X______,
  __X__X__,_X______,
  XXXX_XXX,XX______,
  __X_____,________,
  __X__X__,_X______,
  _X_X__X_,X_______,
  _X_X____,________,
  X___XXXX,XXX_____};

GUI_CONST_STORAGE unsigned char acGUI_FontSONG12_7801[ 24] = { /* code 7801 */
  ____XXXX,XX______,
  XXXX____,_X______,
  __X__X__,_X______,
  __X__X__,_X______,
  _X___X__,_X______,
  _XXX_XXX,XXX_____,
  XX_X____,__X_____,
  _X_X____,__X_____,
  _X_XXXXX,X_X_____,
  _XXX____,__X_____,
  _X_X____,__X_____,
  ________,XX______};

GUI_CONST_STORAGE unsigned char acGUI_FontSONG12_786C[ 22] = { /* code 786C */
  XXXX_XXX,XXX_____,
  __X____X,________,
  __X__XXX,XX______,
  _X___X_X,_X______,
  _XXX_XXX,XX______,
  XX_X_X_X,_X______,
  _X_X_XXX,XX______,
  _X_XX__X,________,
  _X_X_X_X,________,
  _XXX__XX,________,
  _X_X_X__,XXX_____};

GUI_CONST_STORAGE unsigned char acGUI_FontSONG12_7A0B[ 24] = { /* code 7A0B */
  ___X_XXX,XX______,
  XXX__X__,_X______,
  __X__X__,_X______,
  __X__XXX,XX______,
  XXXX____,________,
  __X__XXX,XX______,
  _XXX___X,________,
  _XX_X__X,________,
  X_X__XXX,XX______,
  __X____X,________,
  __X____X,________,
  __X_XXXX,XXX_____};

GUI_CONST_STORAGE unsigned char acGUI_FontSONG12_7B49[ 24] = { /* code 7B49 */
  _X____X_,________,
  _XXXX_XX,XXX_____,
  X__X_X__,X_______,
  _____X__,________,
  _XXXXXXX,XX______,
  _____X__,________,
  XXXXXXXX,XXX_____,
  _______X,________,
  XXXXXXXX,XXX_____,
  __X____X,________,
  ___X___X,________,
  _____XXX,________};

GUI_CONST_STORAGE unsigned char acGUI_FontSONG12_7C7B[ 24] = { /* code 7C7B */
  _____X__,________,
  __X__X__,X_______,
  ___X_X_X,________,
  XXXXXXXX,XXX_____,
  ___X_X_X,________,
  __X__X__,X_______,
  _X______,_X______,
  _____X__,________,
  XXXXXXXX,XXX_____,
  ____X_X_,________,
  __XX___X,X_______,
  XX______,_XX_____};

GUI_CONST_STORAGE unsigned char acGUI_FontSONG12_7CFB[ 24] = { /* code 7CFB */
  ______XX,XX______,
  _XXXXX__,________,
  ____X___,________,
  ___X____,X_______,
  __XXXXXX,________,
  _____XX_,________,
  ___XX___,_X______,
  _XXXXXXX,XXX_____,
  _____X__,__X_____,
  __X__X__,X_______,
  _X___X__,_X______,
  X___XX__,__X_____};

GUI_CONST_STORAGE unsigned char acGUI_FontSONG12_7EBF[ 24] = { /* code 7EBF */
  __X____X,_X______,
  __X____X,__X_____,
  _X_____X,XXX_____,
  X__X_XXX,________,
  XXX____X,________,
  __X____X,XXX_____,
  _X___XXX,________,
  XXXX___X,_X______,
  _______X,X_______,
  __XX___X,__X_____,
  XX____X_,X_X_____,
  ____XX__,_XX_____};

GUI_CONST_STORAGE unsigned char acGUI_FontSONG12_7EDF[ 24] = { /* code 7EDF */
  __X____X,________,
  __X_____,X_______,
  _X___XXX,XXX_____,
  X__X___X,________,
  XXX___X_,_X______,
  __X__X__,__X_____,
  _X___XXX,XXX_____,
  XXXX__X_,X_X_____,
  ______X_,X_______,
  __XX__X_,X_______,
  XX___X__,X_X_____,
  ____X___,_XX_____};

GUI_CONST_STORAGE unsigned char acGUI_FontSONG12_7F16[ 24] = { /* code 7F16 */
  _X_____X,________,
  _X__XXXX,XXX_____,
  X___X___,__X_____,
  X_X_XXXX,XXX_____,
  XX__X___,________,
  _X__XXXX,XXX_____,
  X___X_X_,X_X_____,
  XX_XX_X_,X_X_____,
  ____XXXX,XXX_____,
  __X_X_X_,X_X_____,
  XX__X_X_,X_X_____,
  ____X___,_XX_____};

GUI_CONST_STORAGE unsigned char acGUI_FontSONG12_7F6E[ 24] = { /* code 7F6E */
  _XXXXXXX,XX______,
  _X__X_X_,_X______,
  _XXXXXXX,XX______,
  _____X__,________,
  XXXXXXXX,XXX_____,
  _____X__,________,
  __XXXXXX,X_______,
  __X_____,X_______,
  __X_____,X_______,
  __X__X__,X_______,
  __X__X__,X_______,
  XXXXXXXX,XXX_____};

GUI_CONST_STORAGE unsigned char acGUI_FontSONG12_8017[ 24] = { /* code 8017 */
  __X_____,XX______,
  __X__XXX,________,
  XXXXX__X,________,
  __X____X,XX______,
  _XXX_XXX,________,
  __X____X,________,
  XXXXX__X,XXX_____,
  __X__XXX,________,
  _XXX___X,________,
  X_X_X__X,__X_____,
  __X____X,__X_____,
  __X_____,XXX_____};

GUI_CONST_STORAGE unsigned char acGUI_FontSONG12_884C[ 24] = { /* code 884C */
  ___X____,________,
  __X__XXX,XX______,
  _X______,________,
  X__X____,________,
  __X_XXXX,XXX_____,
  _XX_____,X_______,
  X_X_____,X_______,
  __X_____,X_______,
  __X_____,X_______,
  __X_____,X_______,
  __X_____,X_______,
  __X___XX,X_______};

GUI_CONST_STORAGE unsigned char acGUI_FontSONG12_8A00[ 24] = { /* code 8A00 */
  ____X___,________,
  _____X__,________,
  XXXXXXXX,XXX_____,
  ________,________,
  _XXXXXXX,XX______,
  ________,________,
  _XXXXXXX,XX______,
  ________,________,
  _XXXXXXX,XX______,
  _X______,_X______,
  _XXXXXXX,XX______,
  _X______,_X______};

GUI_CONST_STORAGE unsigned char acGUI_FontSONG12_8B66[ 24] = { /* code 8B66 */
  _X__X__X,________,
  XXXXXX_X,XXX_____,
  _X__X_X_,_X______,
  _XXXXX_X,_X______,
  XX_X_X__,X_______,
  _XXX_X_X,_X______,
  ____X_X_,__X_____,
  XXXXXXXX,XXX_____,
  ________,________,
  _XXXXXXX,XX______,
  __X_____,X_______,
  __XXXXXX,X_______};

GUI_CONST_STORAGE unsigned char acGUI_FontSONG12_8BBE[ 24] = { /* code 8BBE */
  _X___XXX,X_______,
  __X__X__,X_______,
  _____X__,X_______,
  _____X__,X_______,
  XXX_X___,_XX_____,
  __X_____,________,
  __X_XXXX,XX______,
  __X__X__,_X______,
  __X___X_,X_______,
  __XX___X,________,
  __X___X_,X_______,
  ____XX__,_XX_____};

GUI_CONST_STORAGE unsigned char acGUI_FontSONG12_8BD5[ 24] = { /* code 8BD5 */
  X_______,X_X_____,
  _X______,X_______,
  ____XXXX,XXX_____,
  ________,X_______,
  XX______,X_______,
  _X__XXX_,X_______,
  _X___X__,X_______,
  _X___X__,X_______,
  _X___X__,X_______,
  _X___XX_,X_X_____,
  _XX_XX__,_XX_____,
  _X______,__X_____};

GUI_CONST_STORAGE unsigned char acGUI_FontSONG12_8BED[ 24] = { /* code 8BED */
  X__XXXXX,XXX_____,
  _X____X_,________,
  ____XXXX,XX______,
  _____X__,_X______,
  XX___X__,_X______,
  _X_XXXXX,XXX_____,
  _X______,________,
  _X__XXXX,XX______,
  _X__X___,_X______,
  _XX_X___,_X______,
  _X__XXXX,XX______,
  ____X___,_X______};

GUI_CONST_STORAGE unsigned char acGUI_FontSONG12_8D1F[ 24] = { /* code 8D1F */
  __X_____,________,
  __XXXXXX,________,
  _X_____X,________,
  X_____X_,________,
  _XXXXXXX,XX______,
  _X______,_X______,
  _X___X__,_X______,
  _X___X__,_X______,
  _X___X__,_X______,
  ____X_XX,________,
  __XX____,XX______,
  XX______,__X_____};

GUI_CONST_STORAGE unsigned char acGUI_FontSONG12_8D77[ 24] = { /* code 8D77 */
  ___X____,________,
  ___X__XX,XX______,
  _XXXX___,_X______,
  ___X____,_X______,
  ___X__XX,XX______,
  XXXXX_X_,________,
  ___X__X_,________,
  _X_X__X_,__X_____,
  _X_XX_X_,__X_____,
  _X_X___X,XXX_____,
  _XXX____,________,
  X__XXXXX,XXX_____};

GUI_CONST_STORAGE unsigned char acGUI_FontSONG12_8DEF[ 24] = { /* code 8DEF */
  ______X_,________,
  XXXX__XX,XX______,
  X__X_X__,_X______,
  X__XX_X_,X_______,
  XXXX___X,________,
  __X___X_,X_______,
  __X_XX__,_XX_____,
  X_XX_XXX,XX______,
  X_X__X__,_X______,
  X_X__X__,_X______,
  X_XX_XXX,XX______,
  XX___X__,_X______};

GUI_CONST_STORAGE unsigned char acGUI_FontSONG12_8F6F[ 24] = { /* code 8F6F */
  __X___X_,________,
  __X___X_,________,
  XXXX__XX,XXX_____,
  _X___X__,__X_____,
  _XX__X__,_X______,
  X_X_X__X,________,
  XXXX___X,________,
  __X____X,________,
  __XX__X_,X_______,
  XXX___X_,X_______,
  __X__X__,_X______,
  __X_X___,__X_____};

GUI_CONST_STORAGE unsigned char acGUI_FontSONG12_8F7D[ 24] = { /* code 8F7D */
  ___X___X,_X______,
  _XXXXX_X,__X_____,
  ___X___X,________,
  XXXXXXXX,XXX_____,
  __X____X,________,
  XXXXXX_X,_X______,
  _X_X___X,_X______,
  _XXXXX_X,_X______,
  ___X____,X_______,
  ___XXX__,X_X_____,
  XXXX___X,_XX_____,
  ___X__X_,__X_____};

GUI_CONST_STORAGE unsigned char acGUI_FontSONG12_8F93[ 24] = { /* code 8F93 */
  __X____X,________,
  __X___X_,X_______,
  XXXX_X__,_X______,
  _X__X_XX,X_X_____,
  X_X_____,________,
  XXXXXXX_,__X_____,
  __X_X_X_,X_X_____,
  __XXXXX_,X_X_____,
  XXX_X_X_,X_X_____,
  __X_XXX_,X_X_____,
  __X_X_X_,__X_____,
  __X_X_X_,_XX_____};

GUI_CONST_STORAGE unsigned char acGUI_FontSONG12_8FC7[ 24] = { /* code 8FC7 */
  _X______,_X______,
  __X_____,_X______,
  ________,_X______,
  ____XXXX,XXX_____,
  XXX_____,_X______,
  __X__X__,_X______,
  __X___X_,_X______,
  __X___X_,_X______,
  __X_____,_X______,
  __X____X,XX______,
  _X_X____,________,
  X___XXXX,XXX_____};

GUI_CONST_STORAGE unsigned char acGUI_FontSONG12_8FD0[ 24] = { /* code 8FD0 */
  _X______,________,
  __X__XXX,XX______,
  ________,________,
  ________,________,
  XXX_XXXX,XXX_____,
  __X____X,________,
  __X___X_,________,
  __X__X__,_X______,
  __X_XXXX,XXX_____,
  __X_____,__X_____,
  _X_X____,________,
  X___XXXX,XXX_____};

GUI_CONST_STORAGE unsigned char acGUI_FontSONG12_8FD9[ 24] = { /* code 8FD9 */
  _X____X_,________,
  __X____X,________,
  ____XXXX,XXX_____,
  ________,_X______,
  XXX__X__,_X______,
  __X___X_,X_______,
  __X____X,________,
  __X___X_,X_______,
  __X__X__,_X______,
  __X_X___,__X_____,
  _X_X____,________,
  X___XXXX,XXX_____};

GUI_CONST_STORAGE unsigned char acGUI_FontSONG12_8FDB[ 24] = { /* code 8FDB */
  _X___X__,X_______,
  __X__X__,X_______,
  ____XXXX,XX______,
  _____X__,X_______,
  XXX__X__,X_______,
  __X__X__,X_______,
  __XXXXXX,XXX_____,
  __X__X__,X_______,
  __X__X__,X_______,
  __X_X___,X_______,
  _X_X____,________,
  X___XXXX,XXX_____};

GUI_CONST_STORAGE unsigned char acGUI_FontSONG12_9009[ 24] = { /* code 9009 */
  _X_____X,________,
  __X__X_X,________,
  _____XXX,XX______,
  ____X__X,________,
  XXX____X,________,
  __X_XXXX,XXX_____,
  __X___X_,X_______,
  __X___X_,X_______,
  __X__X__,X_X_____,
  __X_X___,_XX_____,
  _X_X____,________,
  X___XXXX,XXX_____};

GUI_CONST_STORAGE unsigned char acGUI_FontSONG12_9178[ 24] = { /* code 9178 */
  _______X,________,
  XXXXX_X_,_X______,
  __X___XX,XXX_____,
  XXXXX___,__X_____,
  X_X_X_X_,_X______,
  X_X_XX_X,__X_____,
  XX_XX__X,XX______,
  X___X_X_,_X______,
  XXXXXX_X,_X______,
  X___X___,X_______,
  XXXXX__X,_X______,
  X___X_X_,__X_____};

GUI_CONST_STORAGE unsigned char acGUI_FontSONG12_94C5[ 24] = { /* code 94C5 */
  _X___XXX,XX______,
  _X___X__,_X______,
  _XXX_X__,_X______,
  X____X__,_X______,
  XXX_X___,__X_____,
  _X______,________,
  _X___XXX,XX______,
  XXXX_X__,_X______,
  _X___X__,_X______,
  _X_X_X__,_X______,
  _XX__XXX,XX______,
  _X___X__,_X______};

GUI_CONST_STORAGE unsigned char acGUI_FontSONG12_9501[ 24] = { /* code 9501 */
  _X_____X,________,
  _XX_X__X,__X_____,
  X____X_X,_X______,
  _______X,________,
  XXX_XXXX,XXX_____,
  _X__X___,__X_____,
  _X__X__X,__X_____,
  XXX_X__X,__X_____,
  _X__X__X,__X_____,
  _X____X_,X_______,
  _XX__X__,_X______,
  _X_XX___,__X_____};

GUI_CONST_STORAGE unsigned char acGUI_FontSONG12_9502[ 24] = { /* code 9502 */
  _X___XXX,XX______,
  _X___X_X,_X______,
  _XXX_X_X,_X______,
  X____XXX,XX______,
  XXXX_X_X,_X______,
  _X___X_X,_X______,
  _X___XXX,XX______,
  XXXX___X,________,
  _X___XXX,XX______,
  _X_X___X,________,
  _XX____X,________,
  _X__XXXX,XXX_____};

GUI_CONST_STORAGE unsigned char acGUI_FontSONG12_9530[ 24] = { /* code 9530 */
  _X___XXX,XX______,
  _XX_____,X_______,
  X______X,________,
  ____XXXX,XXX_____,
  XXX____X,________,
  _X____XX,________,
  _X______,________,
  XXX_XXXX,XXX_____,
  _X__X_X_,X_X_____,
  _X__X_X_,X_X_____,
  _XX_X_X_,X_X_____,
  _X_XXXXX,XXX_____};

GUI_CONST_STORAGE unsigned char acGUI_FontSONG12_9549[ 24] = { /* code 9549 */
  _X__XXXX,XXX_____,
  _X______,________,
  _XXX_XXX,XX______,
  X____X__,_X______,
  XXXX_XXX,XX______,
  _X______,________,
  _X__XXXX,XXX_____,
  XXXXX_X_,X_X_____,
  _X__X__X,__X_____,
  _X__X_XX,X_X_____,
  _XX_X__X,__X_____,
  _X__X__X,_XX_____};

GUI_CONST_STORAGE unsigned char acGUI_FontSONG12_954D[ 24] = { /* code 954D */
  _X_____X,________,
  _X___XXX,XX______,
  _XXX_X__,_X______,
  X____XXX,XX______,
  XXXX_X__,_X______,
  _X___XXX,XX______,
  _X___X__,_X______,
  XXXX_XXX,XX______,
  _X_____X,________,
  _X_XXXXX,XXX_____,
  _XX__X_X,_X______,
  _X__X__X,__X_____};

GUI_CONST_STORAGE unsigned char acGUI_FontSONG12_95E8[ 24] = { /* code 95E8 */
  X__XXXXX,XX______,
  _X______,_X______,
  ________,_X______,
  X_______,_X______,
  X_______,_X______,
  X_______,_X______,
  X_______,_X______,
  X_______,_X______,
  X_______,_X______,
  X_______,_X______,
  X_______,_X______,
  X______X,XX______};

GUI_CONST_STORAGE unsigned char acGUI_FontSONG12_95F4[ 24] = { /* code 95F4 */
  X__XXXXX,XX______,
  _X______,_X______,
  ________,_X______,
  X_XXXXXX,_X______,
  X_X____X,_X______,
  X_X____X,_X______,
  X_XXXXXX,_X______,
  X_X____X,_X______,
  X_X____X,_X______,
  X_XXXXXX,_X______,
  X_______,_X______,
  X______X,XX______};

GUI_CONST_STORAGE unsigned char acGUI_FontSONG12_963B[ 22] = { /* code 963B */
  XXXX_XXX,XX______,
  X__X_X__,_X______,
  X__X_X__,_X______,
  X_X__XXX,XX______,
  X_X__X__,_X______,
  X__X_X__,_X______,
  X__X_XXX,XX______,
  X__X_X__,_X______,
  XXX__X__,_X______,
  X____X__,_X______,
  X___XXXX,XXX_____};

GUI_CONST_STORAGE unsigned char acGUI_FontSONG12_9650[ 24] = { /* code 9650 */
  XXXX_XXX,XX______,
  X__X_X__,_X______,
  X__X_X__,_X______,
  X_X__XXX,XX______,
  X_X__X__,_X______,
  X__X_X__,_X______,
  X__X_XXX,XX______,
  X__X_X_X,__X_____,
  X__X_X_X,_X______,
  XXX__X__,X_______,
  X____XX_,_X______,
  X____X__,__X_____};

GUI_CONST_STORAGE unsigned char acGUI_FontSONG12_9762[ 22] = { /* code 9762 */
  XXXXXXXX,XXX_____,
  _____X__,________,
  ____X___,________,
  _XXXXXXX,XXX_____,
  _X__X__X,__X_____,
  _X__XXXX,__X_____,
  _X__X__X,__X_____,
  _X__XXXX,__X_____,
  _X__X__X,__X_____,
  _XXXXXXX,XXX_____,
  _X______,__X_____};

GUI_CONST_STORAGE unsigned char acGUI_FontSONG12_97F3[ 24] = { /* code 97F3 */
  _____X__,________,
  _XXXXXXX,XX______,
  __X_____,X_______,
  ___X___X,________,
  XXXXXXXX,XXX_____,
  ________,________,
  _XXXXXXX,XX______,
  _X______,_X______,
  _XXXXXXX,XX______,
  _X______,_X______,
  _XXXXXXX,XX______,
  _X______,_X______};

GUI_CONST_STORAGE unsigned char acGUI_FontSONG12_9875[ 24] = { /* code 9875 */
  XXXXXXXX,XXX_____,
  _____X__,________,
  ____X___,________,
  _XXXXXXX,XX______,
  _X______,_X______,
  _X______,_X______,
  _X___X__,_X______,
  _X___X__,_X______,
  _X___X__,_X______,
  ____X_XX,________,
  __XX____,XX______,
  XX______,__X_____};

/* Start of unicode area <Halfwidth and Fullwidth Forms> */
GUI_CONST_STORAGE unsigned char acGUI_FontSONG12_FF0C[  4] = { /* code FF0C, FULLWIDTH COMMA */
  XX______,
  XX______,
  _X______,
  X_______};

GUI_CONST_STORAGE unsigned char acGUI_FontSONG12_FF1A[  6] = { /* code FF1A, FULLWIDTH COLON */
  XX______,
  XX______,
  ________,
  ________,
  XX______,
  XX______};

GUI_CONST_STORAGE GUI_CHARINFO_EXT GUI_FontSONG12_CharInfo[198] = {
   {   1,   1,   0,  10,   6, acGUI_FontSONG12_0020 } /* code 0020, SPACE */
  ,{   1,   8,   2,   2,   6, acGUI_FontSONG12_0021 } /* code 0021, EXCLAMATION MARK */
  ,{   4,   3,   1,   1,   6, acGUI_FontSONG12_0022 } /* code 0022, QUOTATION MARK */
  ,{   6,   8,   0,   2,   6, acGUI_FontSONG12_0023 } /* code 0023, NUMBER SIGN */
  ,{   5,  10,   0,   1,   6, acGUI_FontSONG12_0024 } /* code 0024, DOLLAR SIGN */
  ,{   6,   8,   0,   2,   6, acGUI_FontSONG12_0025 } /* code 0025, PERCENT SIGN */
  ,{   6,   8,   0,   2,   6, acGUI_FontSONG12_0026 } /* code 0026, AMPERSAND */
  ,{   2,   3,   0,   1,   6, acGUI_FontSONG12_0027 } /* code 0027, APOSTROPHE */
  ,{   3,  10,   3,   1,   6, acGUI_FontSONG12_0028 } /* code 0028, LEFT PARENTHESIS */
  ,{   3,  10,   1,   1,   6, acGUI_FontSONG12_0029 } /* code 0029, RIGHT PARENTHESIS */
  ,{   5,   6,   0,   3,   6, acGUI_FontSONG12_002A } /* code 002A, ASTERISK */
  ,{   5,   7,   0,   2,   6, acGUI_FontSONG12_002B } /* code 002B, PLUS SIGN */
  ,{   2,   3,   0,   9,   6, acGUI_FontSONG12_002C } /* code 002C, COMMA */
  ,{   5,   1,   0,   5,   6, acGUI_FontSONG12_002D } /* code 002D, HYPHEN-MINUS */
  ,{   1,   1,   1,   9,   6, acGUI_FontSONG12_002E } /* code 002E, FULL STOP */
  ,{   5,  10,   0,   1,   6, acGUI_FontSONG12_002F } /* code 002F, SOLIDUS */
  ,{   5,   8,   0,   2,   6, acGUI_FontSONG12_0030 } /* code 0030, DIGIT ZERO */
  ,{   3,   8,   1,   2,   6, acGUI_FontSONG12_0031 } /* code 0031, DIGIT ONE */
  ,{   5,   8,   0,   2,   6, acGUI_FontSONG12_0032 } /* code 0032, DIGIT TWO */
  ,{   5,   8,   0,   2,   6, acGUI_FontSONG12_0033 } /* code 0033, DIGIT THREE */
  ,{   6,   8,   0,   2,   6, acGUI_FontSONG12_0034 } /* code 0034, DIGIT FOUR */
  ,{   5,   8,   0,   2,   6, acGUI_FontSONG12_0035 } /* code 0035, DIGIT FIVE */
  ,{   5,   8,   0,   2,   6, acGUI_FontSONG12_0036 } /* code 0036, DIGIT SIX */
  ,{   5,   8,   0,   2,   6, acGUI_FontSONG12_0037 } /* code 0037, DIGIT SEVEN */
  ,{   5,   8,   0,   2,   6, acGUI_FontSONG12_0038 } /* code 0038, DIGIT EIGHT */
  ,{   5,   8,   0,   2,   6, acGUI_FontSONG12_0039 } /* code 0039, DIGIT NINE */
  ,{   1,   6,   2,   4,   6, acGUI_FontSONG12_003A } /* code 003A, COLON */
  ,{   1,   6,   2,   5,   6, acGUI_FontSONG12_003B } /* code 003B, SEMICOLON */
  ,{   5,   9,   1,   1,   6, acGUI_FontSONG12_003C } /* code 003C, LESS-THAN SIGN */
  ,{   5,   4,   0,   4,   6, acGUI_FontSONG12_003D } /* code 003D, EQUALS SIGN */
  ,{   5,   9,   1,   1,   6, acGUI_FontSONG12_003E } /* code 003E, GREATER-THAN SIGN */
  ,{   5,   8,   0,   2,   6, acGUI_FontSONG12_003F } /* code 003F, QUESTION MARK */
  ,{   5,   8,   0,   2,   6, acGUI_FontSONG12_0040 } /* code 0040, COMMERCIAL AT */
  ,{   6,   8,   0,   2,   6, acGUI_FontSONG12_0041 } /* code 0041, LATIN CAPITAL LETTER A */
  ,{   5,   8,   0,   2,   6, acGUI_FontSONG12_0042 } /* code 0042, LATIN CAPITAL LETTER B */
  ,{   5,   8,   0,   2,   6, acGUI_FontSONG12_0043 } /* code 0043, LATIN CAPITAL LETTER C */
  ,{   5,   8,   0,   2,   6, acGUI_FontSONG12_0044 } /* code 0044, LATIN CAPITAL LETTER D */
  ,{   5,   8,   0,   2,   6, acGUI_FontSONG12_0045 } /* code 0045, LATIN CAPITAL LETTER E */
  ,{   5,   8,   0,   2,   6, acGUI_FontSONG12_0046 } /* code 0046, LATIN CAPITAL LETTER F */
  ,{   6,   8,   0,   2,   6, acGUI_FontSONG12_0047 } /* code 0047, LATIN CAPITAL LETTER G */
  ,{   6,   8,   0,   2,   6, acGUI_FontSONG12_0048 } /* code 0048, LATIN CAPITAL LETTER H */
  ,{   5,   8,   0,   2,   6, acGUI_FontSONG12_0049 } /* code 0049, LATIN CAPITAL LETTER I */
  ,{   6,   9,   0,   2,   6, acGUI_FontSONG12_004A } /* code 004A, LATIN CAPITAL LETTER J */
  ,{   6,   8,   0,   2,   6, acGUI_FontSONG12_004B } /* code 004B, LATIN CAPITAL LETTER K */
  ,{   6,   8,   0,   2,   6, acGUI_FontSONG12_004C } /* code 004C, LATIN CAPITAL LETTER L */
  ,{   5,   8,   0,   2,   6, acGUI_FontSONG12_004D } /* code 004D, LATIN CAPITAL LETTER M */
  ,{   6,   8,   0,   2,   6, acGUI_FontSONG12_004E } /* code 004E, LATIN CAPITAL LETTER N */
  ,{   5,   8,   0,   2,   6, acGUI_FontSONG12_004F } /* code 004F, LATIN CAPITAL LETTER O */
  ,{   5,   8,   0,   2,   6, acGUI_FontSONG12_0050 } /* code 0050, LATIN CAPITAL LETTER P */
  ,{   5,   9,   0,   2,   6, acGUI_FontSONG12_0051 } /* code 0051, LATIN CAPITAL LETTER Q */
  ,{   6,   8,   0,   2,   6, acGUI_FontSONG12_0052 } /* code 0052, LATIN CAPITAL LETTER R */
  ,{   5,   8,   0,   2,   6, acGUI_FontSONG12_0053 } /* code 0053, LATIN CAPITAL LETTER S */
  ,{   5,   8,   0,   2,   6, acGUI_FontSONG12_0054 } /* code 0054, LATIN CAPITAL LETTER T */
  ,{   6,   8,   0,   2,   6, acGUI_FontSONG12_0055 } /* code 0055, LATIN CAPITAL LETTER U */
  ,{   6,   8,   0,   2,   6, acGUI_FontSONG12_0056 } /* code 0056, LATIN CAPITAL LETTER V */
  ,{   5,   8,   0,   2,   6, acGUI_FontSONG12_0057 } /* code 0057, LATIN CAPITAL LETTER W */
  ,{   5,   8,   0,   2,   6, acGUI_FontSONG12_0058 } /* code 0058, LATIN CAPITAL LETTER X */
  ,{   5,   8,   0,   2,   6, acGUI_FontSONG12_0059 } /* code 0059, LATIN CAPITAL LETTER Y */
  ,{   5,   8,   0,   2,   6, acGUI_FontSONG12_005A } /* code 005A, LATIN CAPITAL LETTER Z */
  ,{   3,  10,   2,   1,   6, acGUI_FontSONG12_005B } /* code 005B, LEFT SQUARE BRACKET */
  ,{   4,  10,   1,   1,   6, acGUI_FontSONG12_005C } /* code 005C, REVERSE SOLIDUS */
  ,{   3,  10,   1,   1,   6, acGUI_FontSONG12_005D } /* code 005D, RIGHT SQUARE BRACKET */
  ,{   3,   2,   1,   1,   6, acGUI_FontSONG12_005E } /* code 005E, CIRCUMFLEX ACCENT */
  ,{   6,   1,   0,  11,   6, acGUI_FontSONG12_005F } /* code 005F, LOW LINE */
  ,{   2,   1,   1,   1,   6, acGUI_FontSONG12_0060 } /* code 0060, GRAVE ACCENT */
  ,{   5,   5,   1,   5,   6, acGUI_FontSONG12_0061 } /* code 0061, LATIN SMALL LETTER A */
  ,{   5,   8,   0,   2,   6, acGUI_FontSONG12_0062 } /* code 0062, LATIN SMALL LETTER B */
  ,{   4,   5,   1,   5,   6, acGUI_FontSONG12_0063 } /* code 0063, LATIN SMALL LETTER C */
  ,{   5,   8,   1,   2,   6, acGUI_FontSONG12_0064 } /* code 0064, LATIN SMALL LETTER D */
  ,{   4,   5,   1,   5,   6, acGUI_FontSONG12_0065 } /* code 0065, LATIN SMALL LETTER E */
  ,{   5,   8,   1,   2,   6, acGUI_FontSONG12_0066 } /* code 0066, LATIN SMALL LETTER F */
  ,{   5,   7,   1,   5,   6, acGUI_FontSONG12_0067 } /* code 0067, LATIN SMALL LETTER G */
  ,{   6,   8,   0,   2,   6, acGUI_FontSONG12_0068 } /* code 0068, LATIN SMALL LETTER H */
  ,{   3,   8,   1,   2,   6, acGUI_FontSONG12_0069 } /* code 0069, LATIN SMALL LETTER I */
  ,{   4,  10,   0,   2,   6, acGUI_FontSONG12_006A } /* code 006A, LATIN SMALL LETTER J */
  ,{   6,   8,   0,   2,   6, acGUI_FontSONG12_006B } /* code 006B, LATIN SMALL LETTER K */
  ,{   5,   8,   0,   2,   6, acGUI_FontSONG12_006C } /* code 006C, LATIN SMALL LETTER L */
  ,{   5,   5,   0,   5,   6, acGUI_FontSONG12_006D } /* code 006D, LATIN SMALL LETTER M */
  ,{   6,   5,   0,   5,   6, acGUI_FontSONG12_006E } /* code 006E, LATIN SMALL LETTER N */
  ,{   4,   5,   1,   5,   6, acGUI_FontSONG12_006F } /* code 006F, LATIN SMALL LETTER O */
  ,{   5,   7,   0,   5,   6, acGUI_FontSONG12_0070 } /* code 0070, LATIN SMALL LETTER P */
  ,{   5,   7,   1,   5,   6, acGUI_FontSONG12_0071 } /* code 0071, LATIN SMALL LETTER Q */
  ,{   5,   5,   0,   5,   6, acGUI_FontSONG12_0072 } /* code 0072, LATIN SMALL LETTER R */
  ,{   4,   5,   1,   5,   6, acGUI_FontSONG12_0073 } /* code 0073, LATIN SMALL LETTER S */
  ,{   4,   7,   1,   3,   6, acGUI_FontSONG12_0074 } /* code 0074, LATIN SMALL LETTER T */
  ,{   6,   5,   0,   5,   6, acGUI_FontSONG12_0075 } /* code 0075, LATIN SMALL LETTER U */
  ,{   6,   5,   0,   5,   6, acGUI_FontSONG12_0076 } /* code 0076, LATIN SMALL LETTER V */
  ,{   5,   5,   0,   5,   6, acGUI_FontSONG12_0077 } /* code 0077, LATIN SMALL LETTER W */
  ,{   5,   5,   0,   5,   6, acGUI_FontSONG12_0078 } /* code 0078, LATIN SMALL LETTER X */
  ,{   6,   7,   0,   5,   6, acGUI_FontSONG12_0079 } /* code 0079, LATIN SMALL LETTER Y */
  ,{   4,   5,   1,   5,   6, acGUI_FontSONG12_007A } /* code 007A, LATIN SMALL LETTER Z */
  ,{   3,  10,   2,   1,   6, acGUI_FontSONG12_007B } /* code 007B, LEFT CURLY BRACKET */
  ,{   1,  12,   3,   0,   6, acGUI_FontSONG12_007C } /* code 007C, VERTICAL LINE */
  ,{   3,  10,   1,   1,   6, acGUI_FontSONG12_007D } /* code 007D, RIGHT CURLY BRACKET */
  ,{   6,   3,   0,   0,   6, acGUI_FontSONG12_007E } /* code 007E, TILDE */
  ,{   9,   8,   1,   1,  12, acGUI_FontSONG12_03A9 } /* code 03A9, GREEK CAPITAL LETTER OMEGA */
  ,{  11,  12,   0,   0,  12, acGUI_FontSONG12_4E0A } /* code 4E0A */
  ,{  11,  11,   0,   1,  12, acGUI_FontSONG12_4E0B } /* code 4E0B */
  ,{   9,  12,   1,   0,  12, acGUI_FontSONG12_4E2D } /* code 4E2D */
  ,{  11,  12,   0,   0,  12, acGUI_FontSONG12_4EA7 } /* code 4EA7 */
  ,{  11,  12,   0,   0,  12, acGUI_FontSONG12_4EEA } /* code 4EEA */
  ,{  11,  12,   0,   0,  12, acGUI_FontSONG12_4EF6 } /* code 4EF6 */
  ,{  11,  12,   0,   0,  12, acGUI_FontSONG12_4FE1 } /* code 4FE1 */
  ,{  11,  12,   0,   0,  12, acGUI_FontSONG12_5145 } /* code 5145 */
  ,{  11,  12,   0,   0,  12, acGUI_FontSONG12_5165 } /* code 5165 */
  ,{  11,  12,   0,   0,  12, acGUI_FontSONG12_5173 } /* code 5173 */
  ,{   9,  12,   1,   0,  12, acGUI_FontSONG12_5185 } /* code 5185 */
  ,{  11,  12,   0,   0,  12, acGUI_FontSONG12_51FA } /* code 51FA */
  ,{  11,  12,   0,   0,  12, acGUI_FontSONG12_5206 } /* code 5206 */
  ,{  11,  12,   0,   0,  12, acGUI_FontSONG12_5236 } /* code 5236 */
  ,{  11,  11,   0,   1,  12, acGUI_FontSONG12_538B } /* code 538B */
  ,{  11,  12,   0,   0,  12, acGUI_FontSONG12_53F7 } /* code 53F7 */
  ,{  11,  12,   0,   0,  12, acGUI_FontSONG12_542F } /* code 542F */
  ,{  11,  12,   0,   0,  12, acGUI_FontSONG12_5668 } /* code 5668 */
  ,{  11,  12,   0,   0,  12, acGUI_FontSONG12_56FE } /* code 56FE */
  ,{  11,  12,   0,   0,  12, acGUI_FontSONG12_5728 } /* code 5728 */
  ,{  11,  12,   0,   0,  12, acGUI_FontSONG12_578B } /* code 578B */
  ,{  11,  12,   0,   0,  12, acGUI_FontSONG12_58F0 } /* code 58F0 */
  ,{  11,  12,   0,   0,  12, acGUI_FontSONG12_59CB } /* code 59CB */
  ,{  11,  12,   0,   0,  12, acGUI_FontSONG12_5B9A } /* code 5B9A */
  ,{  11,  12,   0,   0,  12, acGUI_FontSONG12_5BC6 } /* code 5BC6 */
  ,{  11,  12,   0,   0,  12, acGUI_FontSONG12_5C0F } /* code 5C0F */
  ,{  11,  11,   0,   1,  12, acGUI_FontSONG12_5F00 } /* code 5F00 */
  ,{  11,  12,   0,   0,  12, acGUI_FontSONG12_5F85 } /* code 5F85 */
  ,{  11,  12,   0,   0,  12, acGUI_FontSONG12_5FAA } /* code 5FAA */
  ,{  11,  12,   0,   0,  12, acGUI_FontSONG12_606F } /* code 606F */
  ,{  11,  12,   0,   0,  12, acGUI_FontSONG12_622A } /* code 622A */
  ,{  11,  12,   0,   0,  12, acGUI_FontSONG12_62A5 } /* code 62A5 */
  ,{  11,  12,   0,   0,  12, acGUI_FontSONG12_63A7 } /* code 63A7 */
  ,{  11,  12,   0,   0,  12, acGUI_FontSONG12_653E } /* code 653E */
  ,{  11,  12,   0,   0,  12, acGUI_FontSONG12_6570 } /* code 6570 */
  ,{  11,  12,   0,   0,  12, acGUI_FontSONG12_6587 } /* code 6587 */
  ,{   9,  11,   1,   1,  12, acGUI_FontSONG12_65E5 } /* code 65E5 */
  ,{  11,  12,   0,   0,  12, acGUI_FontSONG12_65F6 } /* code 65F6 */
  ,{  11,  12,   0,   0,  12, acGUI_FontSONG12_662F } /* code 662F */
  ,{  10,  12,   1,   0,  12, acGUI_FontSONG12_66F2 } /* code 66F2 */
  ,{  11,  12,   0,   0,  12, acGUI_FontSONG12_671F } /* code 671F */
  ,{  11,  12,   0,   0,  12, acGUI_FontSONG12_672A } /* code 672A */
  ,{  11,  12,   0,   0,  12, acGUI_FontSONG12_672C } /* code 672C */
  ,{  11,  12,   0,   0,  12, acGUI_FontSONG12_69DB } /* code 69DB */
  ,{  11,  12,   0,   0,  12, acGUI_FontSONG12_6B21 } /* code 6B21 */
  ,{  11,  12,   0,   0,  12, acGUI_FontSONG12_6B62 } /* code 6B62 */
  ,{  11,  11,   0,   1,  12, acGUI_FontSONG12_6B63 } /* code 6B63 */
  ,{  11,  12,   0,   0,  12, acGUI_FontSONG12_6B65 } /* code 6B65 */
  ,{  11,  12,   0,   0,  12, acGUI_FontSONG12_6C22 } /* code 6C22 */
  ,{  11,  12,   0,   0,  12, acGUI_FontSONG12_6C60 } /* code 6C60 */
  ,{  11,  12,   0,   0,  12, acGUI_FontSONG12_6D41 } /* code 6D41 */
  ,{  11,  12,   0,   0,  12, acGUI_FontSONG12_6D4B } /* code 6D4B */
  ,{  11,  12,   0,   0,  12, acGUI_FontSONG12_6E90 } /* code 6E90 */
  ,{  11,  12,   0,   0,  12, acGUI_FontSONG12_7248 } /* code 7248 */
  ,{  11,  11,   0,   1,  12, acGUI_FontSONG12_73AF } /* code 73AF */
  ,{  11,  12,   0,   0,  12, acGUI_FontSONG12_751F } /* code 751F */
  ,{  11,  12,   0,   0,  12, acGUI_FontSONG12_7535 } /* code 7535 */
  ,{  11,  12,   0,   0,  12, acGUI_FontSONG12_77ED } /* code 77ED */
  ,{  11,  12,   0,   0,  12, acGUI_FontSONG12_7801 } /* code 7801 */
  ,{  11,  11,   0,   1,  12, acGUI_FontSONG12_786C } /* code 786C */
  ,{  11,  12,   0,   0,  12, acGUI_FontSONG12_7A0B } /* code 7A0B */
  ,{  11,  12,   0,   0,  12, acGUI_FontSONG12_7B49 } /* code 7B49 */
  ,{  11,  12,   0,   0,  12, acGUI_FontSONG12_7C7B } /* code 7C7B */
  ,{  11,  12,   0,   0,  12, acGUI_FontSONG12_7CFB } /* code 7CFB */
  ,{  11,  12,   0,   0,  12, acGUI_FontSONG12_7EBF } /* code 7EBF */
  ,{  11,  12,   0,   0,  12, acGUI_FontSONG12_7EDF } /* code 7EDF */
  ,{  11,  12,   0,   0,  12, acGUI_FontSONG12_7F16 } /* code 7F16 */
  ,{  11,  12,   0,   0,  12, acGUI_FontSONG12_7F6E } /* code 7F6E */
  ,{  11,  12,   0,   0,  12, acGUI_FontSONG12_8017 } /* code 8017 */
  ,{  11,  12,   0,   0,  12, acGUI_FontSONG12_884C } /* code 884C */
  ,{  11,  12,   0,   0,  12, acGUI_FontSONG12_8A00 } /* code 8A00 */
  ,{  11,  12,   0,   0,  12, acGUI_FontSONG12_8B66 } /* code 8B66 */
  ,{  11,  12,   0,   0,  12, acGUI_FontSONG12_8BBE } /* code 8BBE */
  ,{  11,  12,   0,   0,  12, acGUI_FontSONG12_8BD5 } /* code 8BD5 */
  ,{  11,  12,   0,   0,  12, acGUI_FontSONG12_8BED } /* code 8BED */
  ,{  11,  12,   0,   0,  12, acGUI_FontSONG12_8D1F } /* code 8D1F */
  ,{  11,  12,   0,   0,  12, acGUI_FontSONG12_8D77 } /* code 8D77 */
  ,{  11,  12,   0,   0,  12, acGUI_FontSONG12_8DEF } /* code 8DEF */
  ,{  11,  12,   0,   0,  12, acGUI_FontSONG12_8F6F } /* code 8F6F */
  ,{  11,  12,   0,   0,  12, acGUI_FontSONG12_8F7D } /* code 8F7D */
  ,{  11,  12,   0,   0,  12, acGUI_FontSONG12_8F93 } /* code 8F93 */
  ,{  11,  12,   0,   0,  12, acGUI_FontSONG12_8FC7 } /* code 8FC7 */
  ,{  11,  12,   0,   0,  12, acGUI_FontSONG12_8FD0 } /* code 8FD0 */
  ,{  11,  12,   0,   0,  12, acGUI_FontSONG12_8FD9 } /* code 8FD9 */
  ,{  11,  12,   0,   0,  12, acGUI_FontSONG12_8FDB } /* code 8FDB */
  ,{  11,  12,   0,   0,  12, acGUI_FontSONG12_9009 } /* code 9009 */
  ,{  11,  12,   0,   0,  12, acGUI_FontSONG12_9178 } /* code 9178 */
  ,{  11,  12,   0,   0,  12, acGUI_FontSONG12_94C5 } /* code 94C5 */
  ,{  11,  12,   0,   0,  12, acGUI_FontSONG12_9501 } /* code 9501 */
  ,{  11,  12,   0,   0,  12, acGUI_FontSONG12_9502 } /* code 9502 */
  ,{  11,  12,   0,   0,  12, acGUI_FontSONG12_9530 } /* code 9530 */
  ,{  11,  12,   0,   0,  12, acGUI_FontSONG12_9549 } /* code 9549 */
  ,{  11,  12,   0,   0,  12, acGUI_FontSONG12_954D } /* code 954D */
  ,{  10,  12,   1,   0,  12, acGUI_FontSONG12_95E8 } /* code 95E8 */
  ,{  10,  12,   1,   0,  12, acGUI_FontSONG12_95F4 } /* code 95F4 */
  ,{  11,  11,   0,   1,  12, acGUI_FontSONG12_963B } /* code 963B */
  ,{  11,  12,   0,   0,  12, acGUI_FontSONG12_9650 } /* code 9650 */
  ,{  11,  11,   0,   1,  12, acGUI_FontSONG12_9762 } /* code 9762 */
  ,{  11,  12,   0,   0,  12, acGUI_FontSONG12_97F3 } /* code 97F3 */
  ,{  11,  12,   0,   0,  12, acGUI_FontSONG12_9875 } /* code 9875 */
  ,{   2,   4,   2,   6,  12, acGUI_FontSONG12_FF0C } /* code FF0C, FULLWIDTH COMMA */
  ,{   2,   6,   2,   4,  12, acGUI_FontSONG12_FF1A } /* code FF1A, FULLWIDTH COLON */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontSONG12_Prop101 = {
   0xFF1A /* first character */
  ,0xFF1A /* last character  */
  ,&GUI_FontSONG12_CharInfo[197] /* address of first character */
  ,(GUI_CONST_STORAGE GUI_FONT_PROP_EXT *)0 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontSONG12_Prop100 = {
   0xFF0C /* first character */
  ,0xFF0C /* last character  */
  ,&GUI_FontSONG12_CharInfo[196] /* address of first character */
  ,&GUI_FontSONG12_Prop101 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontSONG12_Prop99 = {
   0x9875 /* first character */
  ,0x9875 /* last character  */
  ,&GUI_FontSONG12_CharInfo[195] /* address of first character */
  ,&GUI_FontSONG12_Prop100 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontSONG12_Prop98 = {
   0x97F3 /* first character */
  ,0x97F3 /* last character  */
  ,&GUI_FontSONG12_CharInfo[194] /* address of first character */
  ,&GUI_FontSONG12_Prop99 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontSONG12_Prop97 = {
   0x9762 /* first character */
  ,0x9762 /* last character  */
  ,&GUI_FontSONG12_CharInfo[193] /* address of first character */
  ,&GUI_FontSONG12_Prop98 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontSONG12_Prop96 = {
   0x9650 /* first character */
  ,0x9650 /* last character  */
  ,&GUI_FontSONG12_CharInfo[192] /* address of first character */
  ,&GUI_FontSONG12_Prop97 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontSONG12_Prop95 = {
   0x963B /* first character */
  ,0x963B /* last character  */
  ,&GUI_FontSONG12_CharInfo[191] /* address of first character */
  ,&GUI_FontSONG12_Prop96 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontSONG12_Prop94 = {
   0x95F4 /* first character */
  ,0x95F4 /* last character  */
  ,&GUI_FontSONG12_CharInfo[190] /* address of first character */
  ,&GUI_FontSONG12_Prop95 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontSONG12_Prop93 = {
   0x95E8 /* first character */
  ,0x95E8 /* last character  */
  ,&GUI_FontSONG12_CharInfo[189] /* address of first character */
  ,&GUI_FontSONG12_Prop94 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontSONG12_Prop92 = {
   0x954D /* first character */
  ,0x954D /* last character  */
  ,&GUI_FontSONG12_CharInfo[188] /* address of first character */
  ,&GUI_FontSONG12_Prop93 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontSONG12_Prop91 = {
   0x9549 /* first character */
  ,0x9549 /* last character  */
  ,&GUI_FontSONG12_CharInfo[187] /* address of first character */
  ,&GUI_FontSONG12_Prop92 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontSONG12_Prop90 = {
   0x9530 /* first character */
  ,0x9530 /* last character  */
  ,&GUI_FontSONG12_CharInfo[186] /* address of first character */
  ,&GUI_FontSONG12_Prop91 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontSONG12_Prop89 = {
   0x9501 /* first character */
  ,0x9502 /* last character  */
  ,&GUI_FontSONG12_CharInfo[184] /* address of first character */
  ,&GUI_FontSONG12_Prop90 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontSONG12_Prop88 = {
   0x94C5 /* first character */
  ,0x94C5 /* last character  */
  ,&GUI_FontSONG12_CharInfo[183] /* address of first character */
  ,&GUI_FontSONG12_Prop89 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontSONG12_Prop87 = {
   0x9178 /* first character */
  ,0x9178 /* last character  */
  ,&GUI_FontSONG12_CharInfo[182] /* address of first character */
  ,&GUI_FontSONG12_Prop88 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontSONG12_Prop86 = {
   0x9009 /* first character */
  ,0x9009 /* last character  */
  ,&GUI_FontSONG12_CharInfo[181] /* address of first character */
  ,&GUI_FontSONG12_Prop87 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontSONG12_Prop85 = {
   0x8FDB /* first character */
  ,0x8FDB /* last character  */
  ,&GUI_FontSONG12_CharInfo[180] /* address of first character */
  ,&GUI_FontSONG12_Prop86 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontSONG12_Prop84 = {
   0x8FD9 /* first character */
  ,0x8FD9 /* last character  */
  ,&GUI_FontSONG12_CharInfo[179] /* address of first character */
  ,&GUI_FontSONG12_Prop85 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontSONG12_Prop83 = {
   0x8FD0 /* first character */
  ,0x8FD0 /* last character  */
  ,&GUI_FontSONG12_CharInfo[178] /* address of first character */
  ,&GUI_FontSONG12_Prop84 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontSONG12_Prop82 = {
   0x8FC7 /* first character */
  ,0x8FC7 /* last character  */
  ,&GUI_FontSONG12_CharInfo[177] /* address of first character */
  ,&GUI_FontSONG12_Prop83 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontSONG12_Prop81 = {
   0x8F93 /* first character */
  ,0x8F93 /* last character  */
  ,&GUI_FontSONG12_CharInfo[176] /* address of first character */
  ,&GUI_FontSONG12_Prop82 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontSONG12_Prop80 = {
   0x8F7D /* first character */
  ,0x8F7D /* last character  */
  ,&GUI_FontSONG12_CharInfo[175] /* address of first character */
  ,&GUI_FontSONG12_Prop81 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontSONG12_Prop79 = {
   0x8F6F /* first character */
  ,0x8F6F /* last character  */
  ,&GUI_FontSONG12_CharInfo[174] /* address of first character */
  ,&GUI_FontSONG12_Prop80 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontSONG12_Prop78 = {
   0x8DEF /* first character */
  ,0x8DEF /* last character  */
  ,&GUI_FontSONG12_CharInfo[173] /* address of first character */
  ,&GUI_FontSONG12_Prop79 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontSONG12_Prop77 = {
   0x8D77 /* first character */
  ,0x8D77 /* last character  */
  ,&GUI_FontSONG12_CharInfo[172] /* address of first character */
  ,&GUI_FontSONG12_Prop78 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontSONG12_Prop76 = {
   0x8D1F /* first character */
  ,0x8D1F /* last character  */
  ,&GUI_FontSONG12_CharInfo[171] /* address of first character */
  ,&GUI_FontSONG12_Prop77 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontSONG12_Prop75 = {
   0x8BED /* first character */
  ,0x8BED /* last character  */
  ,&GUI_FontSONG12_CharInfo[170] /* address of first character */
  ,&GUI_FontSONG12_Prop76 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontSONG12_Prop74 = {
   0x8BD5 /* first character */
  ,0x8BD5 /* last character  */
  ,&GUI_FontSONG12_CharInfo[169] /* address of first character */
  ,&GUI_FontSONG12_Prop75 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontSONG12_Prop73 = {
   0x8BBE /* first character */
  ,0x8BBE /* last character  */
  ,&GUI_FontSONG12_CharInfo[168] /* address of first character */
  ,&GUI_FontSONG12_Prop74 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontSONG12_Prop72 = {
   0x8B66 /* first character */
  ,0x8B66 /* last character  */
  ,&GUI_FontSONG12_CharInfo[167] /* address of first character */
  ,&GUI_FontSONG12_Prop73 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontSONG12_Prop71 = {
   0x8A00 /* first character */
  ,0x8A00 /* last character  */
  ,&GUI_FontSONG12_CharInfo[166] /* address of first character */
  ,&GUI_FontSONG12_Prop72 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontSONG12_Prop70 = {
   0x884C /* first character */
  ,0x884C /* last character  */
  ,&GUI_FontSONG12_CharInfo[165] /* address of first character */
  ,&GUI_FontSONG12_Prop71 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontSONG12_Prop69 = {
   0x8017 /* first character */
  ,0x8017 /* last character  */
  ,&GUI_FontSONG12_CharInfo[164] /* address of first character */
  ,&GUI_FontSONG12_Prop70 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontSONG12_Prop68 = {
   0x7F6E /* first character */
  ,0x7F6E /* last character  */
  ,&GUI_FontSONG12_CharInfo[163] /* address of first character */
  ,&GUI_FontSONG12_Prop69 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontSONG12_Prop67 = {
   0x7F16 /* first character */
  ,0x7F16 /* last character  */
  ,&GUI_FontSONG12_CharInfo[162] /* address of first character */
  ,&GUI_FontSONG12_Prop68 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontSONG12_Prop66 = {
   0x7EDF /* first character */
  ,0x7EDF /* last character  */
  ,&GUI_FontSONG12_CharInfo[161] /* address of first character */
  ,&GUI_FontSONG12_Prop67 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontSONG12_Prop65 = {
   0x7EBF /* first character */
  ,0x7EBF /* last character  */
  ,&GUI_FontSONG12_CharInfo[160] /* address of first character */
  ,&GUI_FontSONG12_Prop66 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontSONG12_Prop64 = {
   0x7CFB /* first character */
  ,0x7CFB /* last character  */
  ,&GUI_FontSONG12_CharInfo[159] /* address of first character */
  ,&GUI_FontSONG12_Prop65 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontSONG12_Prop63 = {
   0x7C7B /* first character */
  ,0x7C7B /* last character  */
  ,&GUI_FontSONG12_CharInfo[158] /* address of first character */
  ,&GUI_FontSONG12_Prop64 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontSONG12_Prop62 = {
   0x7B49 /* first character */
  ,0x7B49 /* last character  */
  ,&GUI_FontSONG12_CharInfo[157] /* address of first character */
  ,&GUI_FontSONG12_Prop63 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontSONG12_Prop61 = {
   0x7A0B /* first character */
  ,0x7A0B /* last character  */
  ,&GUI_FontSONG12_CharInfo[156] /* address of first character */
  ,&GUI_FontSONG12_Prop62 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontSONG12_Prop60 = {
   0x786C /* first character */
  ,0x786C /* last character  */
  ,&GUI_FontSONG12_CharInfo[155] /* address of first character */
  ,&GUI_FontSONG12_Prop61 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontSONG12_Prop59 = {
   0x7801 /* first character */
  ,0x7801 /* last character  */
  ,&GUI_FontSONG12_CharInfo[154] /* address of first character */
  ,&GUI_FontSONG12_Prop60 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontSONG12_Prop58 = {
   0x77ED /* first character */
  ,0x77ED /* last character  */
  ,&GUI_FontSONG12_CharInfo[153] /* address of first character */
  ,&GUI_FontSONG12_Prop59 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontSONG12_Prop57 = {
   0x7535 /* first character */
  ,0x7535 /* last character  */
  ,&GUI_FontSONG12_CharInfo[152] /* address of first character */
  ,&GUI_FontSONG12_Prop58 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontSONG12_Prop56 = {
   0x751F /* first character */
  ,0x751F /* last character  */
  ,&GUI_FontSONG12_CharInfo[151] /* address of first character */
  ,&GUI_FontSONG12_Prop57 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontSONG12_Prop55 = {
   0x73AF /* first character */
  ,0x73AF /* last character  */
  ,&GUI_FontSONG12_CharInfo[150] /* address of first character */
  ,&GUI_FontSONG12_Prop56 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontSONG12_Prop54 = {
   0x7248 /* first character */
  ,0x7248 /* last character  */
  ,&GUI_FontSONG12_CharInfo[149] /* address of first character */
  ,&GUI_FontSONG12_Prop55 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontSONG12_Prop53 = {
   0x6E90 /* first character */
  ,0x6E90 /* last character  */
  ,&GUI_FontSONG12_CharInfo[148] /* address of first character */
  ,&GUI_FontSONG12_Prop54 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontSONG12_Prop52 = {
   0x6D4B /* first character */
  ,0x6D4B /* last character  */
  ,&GUI_FontSONG12_CharInfo[147] /* address of first character */
  ,&GUI_FontSONG12_Prop53 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontSONG12_Prop51 = {
   0x6D41 /* first character */
  ,0x6D41 /* last character  */
  ,&GUI_FontSONG12_CharInfo[146] /* address of first character */
  ,&GUI_FontSONG12_Prop52 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontSONG12_Prop50 = {
   0x6C60 /* first character */
  ,0x6C60 /* last character  */
  ,&GUI_FontSONG12_CharInfo[145] /* address of first character */
  ,&GUI_FontSONG12_Prop51 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontSONG12_Prop49 = {
   0x6C22 /* first character */
  ,0x6C22 /* last character  */
  ,&GUI_FontSONG12_CharInfo[144] /* address of first character */
  ,&GUI_FontSONG12_Prop50 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontSONG12_Prop48 = {
   0x6B65 /* first character */
  ,0x6B65 /* last character  */
  ,&GUI_FontSONG12_CharInfo[143] /* address of first character */
  ,&GUI_FontSONG12_Prop49 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontSONG12_Prop47 = {
   0x6B62 /* first character */
  ,0x6B63 /* last character  */
  ,&GUI_FontSONG12_CharInfo[141] /* address of first character */
  ,&GUI_FontSONG12_Prop48 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontSONG12_Prop46 = {
   0x6B21 /* first character */
  ,0x6B21 /* last character  */
  ,&GUI_FontSONG12_CharInfo[140] /* address of first character */
  ,&GUI_FontSONG12_Prop47 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontSONG12_Prop45 = {
   0x69DB /* first character */
  ,0x69DB /* last character  */
  ,&GUI_FontSONG12_CharInfo[139] /* address of first character */
  ,&GUI_FontSONG12_Prop46 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontSONG12_Prop44 = {
   0x672C /* first character */
  ,0x672C /* last character  */
  ,&GUI_FontSONG12_CharInfo[138] /* address of first character */
  ,&GUI_FontSONG12_Prop45 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontSONG12_Prop43 = {
   0x672A /* first character */
  ,0x672A /* last character  */
  ,&GUI_FontSONG12_CharInfo[137] /* address of first character */
  ,&GUI_FontSONG12_Prop44 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontSONG12_Prop42 = {
   0x671F /* first character */
  ,0x671F /* last character  */
  ,&GUI_FontSONG12_CharInfo[136] /* address of first character */
  ,&GUI_FontSONG12_Prop43 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontSONG12_Prop41 = {
   0x66F2 /* first character */
  ,0x66F2 /* last character  */
  ,&GUI_FontSONG12_CharInfo[135] /* address of first character */
  ,&GUI_FontSONG12_Prop42 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontSONG12_Prop40 = {
   0x662F /* first character */
  ,0x662F /* last character  */
  ,&GUI_FontSONG12_CharInfo[134] /* address of first character */
  ,&GUI_FontSONG12_Prop41 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontSONG12_Prop39 = {
   0x65F6 /* first character */
  ,0x65F6 /* last character  */
  ,&GUI_FontSONG12_CharInfo[133] /* address of first character */
  ,&GUI_FontSONG12_Prop40 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontSONG12_Prop38 = {
   0x65E5 /* first character */
  ,0x65E5 /* last character  */
  ,&GUI_FontSONG12_CharInfo[132] /* address of first character */
  ,&GUI_FontSONG12_Prop39 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontSONG12_Prop37 = {
   0x6587 /* first character */
  ,0x6587 /* last character  */
  ,&GUI_FontSONG12_CharInfo[131] /* address of first character */
  ,&GUI_FontSONG12_Prop38 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontSONG12_Prop36 = {
   0x6570 /* first character */
  ,0x6570 /* last character  */
  ,&GUI_FontSONG12_CharInfo[130] /* address of first character */
  ,&GUI_FontSONG12_Prop37 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontSONG12_Prop35 = {
   0x653E /* first character */
  ,0x653E /* last character  */
  ,&GUI_FontSONG12_CharInfo[129] /* address of first character */
  ,&GUI_FontSONG12_Prop36 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontSONG12_Prop34 = {
   0x63A7 /* first character */
  ,0x63A7 /* last character  */
  ,&GUI_FontSONG12_CharInfo[128] /* address of first character */
  ,&GUI_FontSONG12_Prop35 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontSONG12_Prop33 = {
   0x62A5 /* first character */
  ,0x62A5 /* last character  */
  ,&GUI_FontSONG12_CharInfo[127] /* address of first character */
  ,&GUI_FontSONG12_Prop34 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontSONG12_Prop32 = {
   0x622A /* first character */
  ,0x622A /* last character  */
  ,&GUI_FontSONG12_CharInfo[126] /* address of first character */
  ,&GUI_FontSONG12_Prop33 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontSONG12_Prop31 = {
   0x606F /* first character */
  ,0x606F /* last character  */
  ,&GUI_FontSONG12_CharInfo[125] /* address of first character */
  ,&GUI_FontSONG12_Prop32 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontSONG12_Prop30 = {
   0x5FAA /* first character */
  ,0x5FAA /* last character  */
  ,&GUI_FontSONG12_CharInfo[124] /* address of first character */
  ,&GUI_FontSONG12_Prop31 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontSONG12_Prop29 = {
   0x5F85 /* first character */
  ,0x5F85 /* last character  */
  ,&GUI_FontSONG12_CharInfo[123] /* address of first character */
  ,&GUI_FontSONG12_Prop30 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontSONG12_Prop28 = {
   0x5F00 /* first character */
  ,0x5F00 /* last character  */
  ,&GUI_FontSONG12_CharInfo[122] /* address of first character */
  ,&GUI_FontSONG12_Prop29 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontSONG12_Prop27 = {
   0x5C0F /* first character */
  ,0x5C0F /* last character  */
  ,&GUI_FontSONG12_CharInfo[121] /* address of first character */
  ,&GUI_FontSONG12_Prop28 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontSONG12_Prop26 = {
   0x5BC6 /* first character */
  ,0x5BC6 /* last character  */
  ,&GUI_FontSONG12_CharInfo[120] /* address of first character */
  ,&GUI_FontSONG12_Prop27 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontSONG12_Prop25 = {
   0x5B9A /* first character */
  ,0x5B9A /* last character  */
  ,&GUI_FontSONG12_CharInfo[119] /* address of first character */
  ,&GUI_FontSONG12_Prop26 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontSONG12_Prop24 = {
   0x59CB /* first character */
  ,0x59CB /* last character  */
  ,&GUI_FontSONG12_CharInfo[118] /* address of first character */
  ,&GUI_FontSONG12_Prop25 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontSONG12_Prop23 = {
   0x58F0 /* first character */
  ,0x58F0 /* last character  */
  ,&GUI_FontSONG12_CharInfo[117] /* address of first character */
  ,&GUI_FontSONG12_Prop24 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontSONG12_Prop22 = {
   0x578B /* first character */
  ,0x578B /* last character  */
  ,&GUI_FontSONG12_CharInfo[116] /* address of first character */
  ,&GUI_FontSONG12_Prop23 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontSONG12_Prop21 = {
   0x5728 /* first character */
  ,0x5728 /* last character  */
  ,&GUI_FontSONG12_CharInfo[115] /* address of first character */
  ,&GUI_FontSONG12_Prop22 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontSONG12_Prop20 = {
   0x56FE /* first character */
  ,0x56FE /* last character  */
  ,&GUI_FontSONG12_CharInfo[114] /* address of first character */
  ,&GUI_FontSONG12_Prop21 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontSONG12_Prop19 = {
   0x5668 /* first character */
  ,0x5668 /* last character  */
  ,&GUI_FontSONG12_CharInfo[113] /* address of first character */
  ,&GUI_FontSONG12_Prop20 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontSONG12_Prop18 = {
   0x542F /* first character */
  ,0x542F /* last character  */
  ,&GUI_FontSONG12_CharInfo[112] /* address of first character */
  ,&GUI_FontSONG12_Prop19 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontSONG12_Prop17 = {
   0x53F7 /* first character */
  ,0x53F7 /* last character  */
  ,&GUI_FontSONG12_CharInfo[111] /* address of first character */
  ,&GUI_FontSONG12_Prop18 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontSONG12_Prop16 = {
   0x538B /* first character */
  ,0x538B /* last character  */
  ,&GUI_FontSONG12_CharInfo[110] /* address of first character */
  ,&GUI_FontSONG12_Prop17 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontSONG12_Prop15 = {
   0x5236 /* first character */
  ,0x5236 /* last character  */
  ,&GUI_FontSONG12_CharInfo[109] /* address of first character */
  ,&GUI_FontSONG12_Prop16 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontSONG12_Prop14 = {
   0x5206 /* first character */
  ,0x5206 /* last character  */
  ,&GUI_FontSONG12_CharInfo[108] /* address of first character */
  ,&GUI_FontSONG12_Prop15 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontSONG12_Prop13 = {
   0x51FA /* first character */
  ,0x51FA /* last character  */
  ,&GUI_FontSONG12_CharInfo[107] /* address of first character */
  ,&GUI_FontSONG12_Prop14 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontSONG12_Prop12 = {
   0x5185 /* first character */
  ,0x5185 /* last character  */
  ,&GUI_FontSONG12_CharInfo[106] /* address of first character */
  ,&GUI_FontSONG12_Prop13 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontSONG12_Prop11 = {
   0x5173 /* first character */
  ,0x5173 /* last character  */
  ,&GUI_FontSONG12_CharInfo[105] /* address of first character */
  ,&GUI_FontSONG12_Prop12 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontSONG12_Prop10 = {
   0x5165 /* first character */
  ,0x5165 /* last character  */
  ,&GUI_FontSONG12_CharInfo[104] /* address of first character */
  ,&GUI_FontSONG12_Prop11 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontSONG12_Prop9 = {
   0x5145 /* first character */
  ,0x5145 /* last character  */
  ,&GUI_FontSONG12_CharInfo[103] /* address of first character */
  ,&GUI_FontSONG12_Prop10 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontSONG12_Prop8 = {
   0x4FE1 /* first character */
  ,0x4FE1 /* last character  */
  ,&GUI_FontSONG12_CharInfo[102] /* address of first character */
  ,&GUI_FontSONG12_Prop9 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontSONG12_Prop7 = {
   0x4EF6 /* first character */
  ,0x4EF6 /* last character  */
  ,&GUI_FontSONG12_CharInfo[101] /* address of first character */
  ,&GUI_FontSONG12_Prop8 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontSONG12_Prop6 = {
   0x4EEA /* first character */
  ,0x4EEA /* last character  */
  ,&GUI_FontSONG12_CharInfo[100] /* address of first character */
  ,&GUI_FontSONG12_Prop7 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontSONG12_Prop5 = {
   0x4EA7 /* first character */
  ,0x4EA7 /* last character  */
  ,&GUI_FontSONG12_CharInfo[ 99] /* address of first character */
  ,&GUI_FontSONG12_Prop6 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontSONG12_Prop4 = {
   0x4E2D /* first character */
  ,0x4E2D /* last character  */
  ,&GUI_FontSONG12_CharInfo[ 98] /* address of first character */
  ,&GUI_FontSONG12_Prop5 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontSONG12_Prop3 = {
   0x4E0A /* first character */
  ,0x4E0B /* last character  */
  ,&GUI_FontSONG12_CharInfo[ 96] /* address of first character */
  ,&GUI_FontSONG12_Prop4 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontSONG12_Prop2 = {
   0x03A9 /* first character */
  ,0x03A9 /* last character  */
  ,&GUI_FontSONG12_CharInfo[ 95] /* address of first character */
  ,&GUI_FontSONG12_Prop3 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontSONG12_Prop1 = {
   0x0020 /* first character */
  ,0x007E /* last character  */
  ,&GUI_FontSONG12_CharInfo[  0] /* address of first character */
  ,&GUI_FontSONG12_Prop2 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT GUI_FontSONG12 = {
   GUI_FONTTYPE_PROP_EXT /* type of font    */
  ,12 /* height of font  */
  ,12 /* space of font y */
  ,1 /* magnification x */
  ,1 /* magnification y */
  ,{&GUI_FontSONG12_Prop1}
  ,10 /* Baseline */
  ,5 /* Height of lowercase characters */
  ,8 /* Height of capital characters */
};

