/*********************************************************************
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                           www.segger.com                           *
**********************************************************************
*                                                                    *
* C-file generated by                                                *
*                                                                    *
*        emWin Font Converter (ST) version 5.32                      *
*        Compiled Oct  8 2015, 11:58:55                              *
*                                                                    *
*        (c) 1998 - 2015 Segger Microcontroller GmbH & Co. KG        *
*                                                                    *
**********************************************************************
*                                                                    *
* Source file: SONGB16.c                                             *
* Font:        ËÎÌו                                                  *
* Height:      16                                                    *
*                                                                    *
**********************************************************************
*                                                                    *
* Initial font height:  16                                           *
* Range disabled:       0000 - FFFF                                  *
* Read pattern file: C:\Users\Administrator\Desktop\123.txt          *
*                                                                    *
**********************************************************************
*/

#include "GUI.h"

#ifndef GUI_CONST_STORAGE
  #define GUI_CONST_STORAGE const
#endif

/* The following line needs to be included in any file selecting the
   font.
*/
extern GUI_CONST_STORAGE GUI_FONT GUI_FontSONGB16;

/* Start of unicode area <Basic Latin> */
GUI_CONST_STORAGE unsigned char acGUI_FontSONGB16_0020[  1] = { /* code 0020, SPACE */
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontSONGB16_0021[ 11] = { /* code 0021, EXCLAMATION MARK */
  XX______,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______,
  ________,
  ________,
  XXX_____,
  XXX_____};

GUI_CONST_STORAGE unsigned char acGUI_FontSONGB16_0022[  4] = { /* code 0022, QUOTATION MARK */
  __XX_XX_,
  _XXXXXX_,
  _XX_XX__,
  XX_XX___};

GUI_CONST_STORAGE unsigned char acGUI_FontSONGB16_0023[ 11] = { /* code 0023, NUMBER SIGN */
  __XX_XX_,
  __XX_XX_,
  __XX_XX_,
  XXXXXXXX,
  _XX_XX__,
  _XX_XX__,
  _XX_XX__,
  XXXXXXXX,
  _XX_XX__,
  _XX_XX__,
  _XX_XX__};

GUI_CONST_STORAGE unsigned char acGUI_FontSONGB16_0024[ 14] = { /* code 0024, DOLLAR SIGN */
  __XX____,
  _XXXX___,
  XXXXXX__,
  XXXXXX__,
  XXXX____,
  _XXX____,
  __XXX___,
  __XXXX__,
  __XXXX__,
  XXXXXX__,
  XXXXXX__,
  _XXXX___,
  __XX____,
  __XX____};

GUI_CONST_STORAGE unsigned char acGUI_FontSONGB16_0025[ 11] = { /* code 0025, PERCENT SIGN */
  _XX__XX_,
  XXXX_XX_,
  XXXXXX__,
  XXXXXX__,
  XXXXXX__,
  _XXXXXX_,
  ___XXXXX,
  __XXXXXX,
  __XXXXXX,
  __XXXXXX,
  _XX__XX_};

GUI_CONST_STORAGE unsigned char acGUI_FontSONGB16_0026[ 22] = { /* code 0026, AMPERSAND */
  __XXX___,________,
  _XX_XX__,________,
  _XX_XX__,________,
  _XX_XX__,________,
  _XXXX___,________,
  _XXXXXXX,________,
  XXXX_XX_,________,
  XX_XXXX_,________,
  XX__XX__,________,
  XX__XX_X,X_______,
  _XXXXXXX,________};

GUI_CONST_STORAGE unsigned char acGUI_FontSONGB16_0027[  4] = { /* code 0027, APOSTROPHE */
  _XXX____,
  _XXX____,
  __XX____,
  XXX_____};

GUI_CONST_STORAGE unsigned char acGUI_FontSONGB16_0028[ 14] = { /* code 0028, LEFT PARENTHESIS */
  ___XX___,
  __XX____,
  _XX_____,
  _XX_____,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______,
  _XX_____,
  _XX_____,
  __XX____,
  ___XX___};

GUI_CONST_STORAGE unsigned char acGUI_FontSONGB16_0029[ 14] = { /* code 0029, RIGHT PARENTHESIS */
  XX______,
  _XX_____,
  __XX____,
  __XX____,
  ___XX___,
  ___XX___,
  ___XX___,
  ___XX___,
  ___XX___,
  ___XX___,
  __XX____,
  __XX____,
  _XX_____,
  XX______};

GUI_CONST_STORAGE unsigned char acGUI_FontSONGB16_002A[  8] = { /* code 002A, ASTERISK */
  ___XX___,
  ___XX___,
  XXXXXXXX,
  __XXXX__,
  __XXXX__,
  XXXXXXXX,
  ___XX___,
  ___XX___};

GUI_CONST_STORAGE unsigned char acGUI_FontSONGB16_002B[  9] = { /* code 002B, PLUS SIGN */
  ___XX___,
  ___XX___,
  ___XX___,
  ___XX___,
  XXXXXXXX,
  ___XX___,
  ___XX___,
  ___XX___,
  ___XX___};

GUI_CONST_STORAGE unsigned char acGUI_FontSONGB16_002C[  4] = { /* code 002C, COMMA */
  _XXX____,
  _XXX____,
  __XX____,
  XXX_____};

GUI_CONST_STORAGE unsigned char acGUI_FontSONGB16_002D[  1] = { /* code 002D, HYPHEN-MINUS */
  XXXXXXXX};

GUI_CONST_STORAGE unsigned char acGUI_FontSONGB16_002E[  2] = { /* code 002E, FULL STOP */
  XXX_____,
  XXX_____};

GUI_CONST_STORAGE unsigned char acGUI_FontSONGB16_002F[ 13] = { /* code 002F, SOLIDUS */
  ______XX,
  _____XX_,
  _____XX_,
  ____XX__,
  ____XX__,
  ___XX___,
  ___XX___,
  __XX____,
  __XX____,
  _XX_____,
  _XX_____,
  XX______,
  XX______};

GUI_CONST_STORAGE unsigned char acGUI_FontSONGB16_0030[ 11] = { /* code 0030, DIGIT ZERO */
  __XXX___,
  _XX_XX__,
  XX___XX_,
  XX___XX_,
  XX___XX_,
  XX___XX_,
  XX___XX_,
  XX___XX_,
  XX___XX_,
  _XX_XX__,
  __XXX___};

GUI_CONST_STORAGE unsigned char acGUI_FontSONGB16_0031[ 11] = { /* code 0031, DIGIT ONE */
  __XX____,
  XXXX____,
  __XX____,
  __XX____,
  __XX____,
  __XX____,
  __XX____,
  __XX____,
  __XX____,
  __XX____,
  XXXXXX__};

GUI_CONST_STORAGE unsigned char acGUI_FontSONGB16_0032[ 11] = { /* code 0032, DIGIT TWO */
  _XXXXX__,
  XX___XX_,
  XX___XX_,
  XX___XX_,
  ____XX__,
  ____XX__,
  ___XX___,
  __XX____,
  _XX_____,
  XX___XX_,
  XXXXXXX_};

GUI_CONST_STORAGE unsigned char acGUI_FontSONGB16_0033[ 11] = { /* code 0033, DIGIT THREE */
  _XXXXX__,
  XX___XX_,
  XX___XX_,
  ____XX__,
  __XXX___,
  ____XX__,
  _____XX_,
  _____XX_,
  XX___XX_,
  XX__XX__,
  _XXXX___};

GUI_CONST_STORAGE unsigned char acGUI_FontSONGB16_0034[ 11] = { /* code 0034, DIGIT FOUR */
  ____XX__,
  ___XXX__,
  __XXXX__,
  _XX_XX__,
  _XX_XX__,
  XX__XX__,
  XX__XX__,
  XXXXXXX_,
  ____XX__,
  ____XX__,
  __XXXXX_};

GUI_CONST_STORAGE unsigned char acGUI_FontSONGB16_0035[ 11] = { /* code 0035, DIGIT FIVE */
  XXXXXXX_,
  XX______,
  XX______,
  XX______,
  XXXXX___,
  XXX_XX__,
  _____XX_,
  _____XX_,
  XX___XX_,
  XX__XX__,
  _XXXX___};

GUI_CONST_STORAGE unsigned char acGUI_FontSONGB16_0036[ 11] = { /* code 0036, DIGIT SIX */
  __XXXX__,
  _XX_XX__,
  XX______,
  XX______,
  XXXXX___,
  XXX_XX__,
  XX___XX_,
  XX___XX_,
  XX___XX_,
  _XX_XX__,
  __XXX___};

GUI_CONST_STORAGE unsigned char acGUI_FontSONGB16_0037[ 11] = { /* code 0037, DIGIT SEVEN */
  XXXXXXX_,
  XX__XX__,
  XX__XX__,
  ___XX___,
  ___XX___,
  __XX____,
  __XX____,
  __XX____,
  __XX____,
  __XX____,
  __XX____};

GUI_CONST_STORAGE unsigned char acGUI_FontSONGB16_0038[ 11] = { /* code 0038, DIGIT EIGHT */
  _XXXXX__,
  XX___XX_,
  XX___XX_,
  XX___XX_,
  _XX_XX__,
  __XXX___,
  _XX_XX__,
  XX___XX_,
  XX___XX_,
  XX___XX_,
  _XXXXX__};

GUI_CONST_STORAGE unsigned char acGUI_FontSONGB16_0039[ 11] = { /* code 0039, DIGIT NINE */
  __XXX___,
  _XX_XX__,
  XX___XX_,
  XX___XX_,
  XX___XX_,
  _XX_XXX_,
  __XXXXX_,
  _____XX_,
  _____XX_,
  _XX_XX__,
  _XXXX___};

GUI_CONST_STORAGE unsigned char acGUI_FontSONGB16_003A[  8] = { /* code 003A, COLON */
  XXX_____,
  XXX_____,
  ________,
  ________,
  ________,
  ________,
  XXX_____,
  XXX_____};

GUI_CONST_STORAGE unsigned char acGUI_FontSONGB16_003B[  9] = { /* code 003B, SEMICOLON */
  _XX_____,
  ________,
  ________,
  ________,
  ________,
  ________,
  _XX_____,
  _XX_____,
  XX______};

GUI_CONST_STORAGE unsigned char acGUI_FontSONGB16_003C[ 11] = { /* code 003C, LESS-THAN SIGN */
  _____XX_,
  ____XX__,
  ___XX___,
  __XX____,
  _XX_____,
  XX______,
  _XX_____,
  __XX____,
  ___XX___,
  ____XX__,
  _____XX_};

GUI_CONST_STORAGE unsigned char acGUI_FontSONGB16_003D[  5] = { /* code 003D, EQUALS SIGN */
  XXXXXXXX,
  ________,
  ________,
  ________,
  XXXXXXXX};

GUI_CONST_STORAGE unsigned char acGUI_FontSONGB16_003E[ 11] = { /* code 003E, GREATER-THAN SIGN */
  XX______,
  _XX_____,
  __XX____,
  ___XX___,
  ____XX__,
  _____XX_,
  ____XX__,
  ___XX___,
  __XX____,
  _XX_____,
  XX______};

GUI_CONST_STORAGE unsigned char acGUI_FontSONGB16_003F[ 11] = { /* code 003F, QUESTION MARK */
  _XXXXX__,
  XX___XX_,
  XX___XX_,
  XXX__XX_,
  _____XX_,
  ____XX__,
  ___XX___,
  ___XX___,
  ________,
  __XXX___,
  __XXX___};

GUI_CONST_STORAGE unsigned char acGUI_FontSONGB16_0040[ 11] = { /* code 0040, COMMERCIAL AT */
  __XXXX__,
  _XX__XX_,
  _XXXXXXX,
  XXXXXXXX,
  XXXXXXXX,
  XXXXXXXX,
  XXXXXXXX,
  XXXXXXX_,
  _XX___XX,
  _XX__XX_,
  __XXXX__};

GUI_CONST_STORAGE unsigned char acGUI_FontSONGB16_0041[ 22] = { /* code 0041, LATIN CAPITAL LETTER A */
  ___XX___,________,
  ___XX___,________,
  ___XXX__,________,
  __XXXX__,________,
  __XXXX__,________,
  __XX_XX_,________,
  __XXXXX_,________,
  _XX__XX_,________,
  _XX___XX,________,
  _XX___XX,________,
  XXXX_XXX,X_______};

GUI_CONST_STORAGE unsigned char acGUI_FontSONGB16_0042[ 11] = { /* code 0042, LATIN CAPITAL LETTER B */
  XXXXXX__,
  _XX__XX_,
  _XX__XX_,
  _XX__XX_,
  _XXXXX__,
  _XX__XX_,
  _XX___XX,
  _XX___XX,
  _XX___XX,
  _XX__XX_,
  XXXXXX__};

GUI_CONST_STORAGE unsigned char acGUI_FontSONGB16_0043[ 11] = { /* code 0043, LATIN CAPITAL LETTER C */
  __XXXXXX,
  _XX___XX,
  _XX___XX,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______,
  _XX___XX,
  _XX__XX_,
  __XXXX__};

GUI_CONST_STORAGE unsigned char acGUI_FontSONGB16_0044[ 11] = { /* code 0044, LATIN CAPITAL LETTER D */
  XXXXXX__,
  _XX__XX_,
  _XX___XX,
  _XX___XX,
  _XX___XX,
  _XX___XX,
  _XX___XX,
  _XX___XX,
  _XX___XX,
  _XX__XX_,
  XXXXXX__};

GUI_CONST_STORAGE unsigned char acGUI_FontSONGB16_0045[ 11] = { /* code 0045, LATIN CAPITAL LETTER E */
  XXXXXXX_,
  _XX___XX,
  _XX_XX__,
  _XX_XX__,
  _XXXXX__,
  _XX_XX__,
  _XX_XX__,
  _XX_____,
  _XX___XX,
  _XX___XX,
  XXXXXXX_};

GUI_CONST_STORAGE unsigned char acGUI_FontSONGB16_0046[ 11] = { /* code 0046, LATIN CAPITAL LETTER F */
  XXXXXXX_,
  _XX___XX,
  _XX_XX__,
  _XX_XX__,
  _XXXXX__,
  _XX_XX__,
  _XX_XX__,
  _XX_____,
  _XX_____,
  _XX_____,
  XXXX____};

GUI_CONST_STORAGE unsigned char acGUI_FontSONGB16_0047[ 11] = { /* code 0047, LATIN CAPITAL LETTER G */
  __XXXXX_,
  _XX__XX_,
  _XX__XX_,
  XX______,
  XX______,
  XX______,
  XX__XXXX,
  XX___XX_,
  _XX__XX_,
  _XX__XX_,
  __XXXX__};

GUI_CONST_STORAGE unsigned char acGUI_FontSONGB16_0048[ 22] = { /* code 0048, LATIN CAPITAL LETTER H */
  XXXX_XXX,X_______,
  _XX___XX,________,
  _XX___XX,________,
  _XX___XX,________,
  _XX___XX,________,
  _XXXXXXX,________,
  _XX___XX,________,
  _XX___XX,________,
  _XX___XX,________,
  _XX___XX,________,
  XXXX_XXX,X_______};

GUI_CONST_STORAGE unsigned char acGUI_FontSONGB16_0049[ 11] = { /* code 0049, LATIN CAPITAL LETTER I */
  XXXXXX__,
  __XX____,
  __XX____,
  __XX____,
  __XX____,
  __XX____,
  __XX____,
  __XX____,
  __XX____,
  __XX____,
  XXXXXX__};

GUI_CONST_STORAGE unsigned char acGUI_FontSONGB16_004A[ 13] = { /* code 004A, LATIN CAPITAL LETTER J */
  __XXXXXX,
  ____XX__,
  ____XX__,
  ____XX__,
  ____XX__,
  ____XX__,
  ____XX__,
  ____XX__,
  ____XX__,
  ____XX__,
  ____XX__,
  XX__XX__,
  XXXXX___};

GUI_CONST_STORAGE unsigned char acGUI_FontSONGB16_004B[ 11] = { /* code 004B, LATIN CAPITAL LETTER K */
  XXXXXXXX,
  _XX__XX_,
  _XX_XX__,
  _XXXX___,
  _XXXX___,
  _XXXX___,
  _XX_XX__,
  _XX_XX__,
  _XX__XX_,
  _XX__XX_,
  XXXXXXXX};

GUI_CONST_STORAGE unsigned char acGUI_FontSONGB16_004C[ 11] = { /* code 004C, LATIN CAPITAL LETTER L */
  XXXX____,
  _XX_____,
  _XX_____,
  _XX_____,
  _XX_____,
  _XX_____,
  _XX_____,
  _XX_____,
  _XX_____,
  _XX___XX,
  XXXXXXXX};

GUI_CONST_STORAGE unsigned char acGUI_FontSONGB16_004D[ 11] = { /* code 004D, LATIN CAPITAL LETTER M */
  XXXXXXXX,
  _XXXXXX_,
  _XXXXXX_,
  _XXXXXX_,
  _XXXXXX_,
  _XXXXXX_,
  _XXXXXX_,
  _XXXXXX_,
  _XXXXXX_,
  _XXXXXX_,
  XXXXXXXX};

GUI_CONST_STORAGE unsigned char acGUI_FontSONGB16_004E[ 22] = { /* code 004E, LATIN CAPITAL LETTER N */
  XXX__XXX,X_______,
  _XXX__XX,________,
  _XXX__XX,________,
  _XXXX_XX,________,
  _XXXX_XX,________,
  _XX_XXXX,________,
  _XX_XXXX,________,
  _XX_XXXX,________,
  _XX__XXX,________,
  _XX__XXX,________,
  XXXX__XX,________};

GUI_CONST_STORAGE unsigned char acGUI_FontSONGB16_004F[ 11] = { /* code 004F, LATIN CAPITAL LETTER O */
  __XXXX__,
  _XX__XX_,
  XX____XX,
  XX____XX,
  XX____XX,
  XX____XX,
  XX____XX,
  XX____XX,
  XX____XX,
  _XX__XX_,
  __XXXX__};

GUI_CONST_STORAGE unsigned char acGUI_FontSONGB16_0050[ 11] = { /* code 0050, LATIN CAPITAL LETTER P */
  XXXXXXX_,
  _XX___XX,
  _XX___XX,
  _XX___XX,
  _XX___XX,
  _XXXXXX_,
  _XX_____,
  _XX_____,
  _XX_____,
  _XX_____,
  XXXX____};

GUI_CONST_STORAGE unsigned char acGUI_FontSONGB16_0051[ 12] = { /* code 0051, LATIN CAPITAL LETTER Q */
  __XXXX__,
  _XX__XX_,
  XX____XX,
  XX____XX,
  XX____XX,
  XX____XX,
  XX____XX,
  XXXXX_XX,
  XXX_XXXX,
  _XX_XXX_,
  __XXXX__,
  _____XXX};

GUI_CONST_STORAGE unsigned char acGUI_FontSONGB16_0052[ 22] = { /* code 0052, LATIN CAPITAL LETTER R */
  XXXXXXX_,________,
  _XX___XX,________,
  _XX___XX,________,
  _XX___XX,________,
  _XXXXXX_,________,
  _XX_XX__,________,
  _XX_XX__,________,
  _XX__XX_,________,
  _XX__XX_,________,
  _XX___XX,________,
  XXXX__XX,X_______};

GUI_CONST_STORAGE unsigned char acGUI_FontSONGB16_0053[ 11] = { /* code 0053, LATIN CAPITAL LETTER S */
  _XXXXXX_,
  XX___XX_,
  XX___XX_,
  XX______,
  _XX_____,
  __XXX___,
  ____XX__,
  _____XX_,
  XX___XX_,
  XX___XX_,
  XXXXXX__};

GUI_CONST_STORAGE unsigned char acGUI_FontSONGB16_0054[ 11] = { /* code 0054, LATIN CAPITAL LETTER T */
  XXXXXXXX,
  XX_XX_XX,
  ___XX___,
  ___XX___,
  ___XX___,
  ___XX___,
  ___XX___,
  ___XX___,
  ___XX___,
  ___XX___,
  __XXXX__};

GUI_CONST_STORAGE unsigned char acGUI_FontSONGB16_0055[ 22] = { /* code 0055, LATIN CAPITAL LETTER U */
  XXXX_XXX,X_______,
  _XX___XX,________,
  _XX___XX,________,
  _XX___XX,________,
  _XX___XX,________,
  _XX___XX,________,
  _XX___XX,________,
  _XX___XX,________,
  _XX___XX,________,
  _XX___XX,________,
  __XXXXX_,________};

GUI_CONST_STORAGE unsigned char acGUI_FontSONGB16_0056[ 22] = { /* code 0056, LATIN CAPITAL LETTER V */
  XXXX_XXX,X_______,
  _XX___XX,________,
  _XX___XX,________,
  _XX__XX_,________,
  __XX_XX_,________,
  __XX_XX_,________,
  __XXXX__,________,
  __XXXX__,________,
  ___XXX__,________,
  ___XX___,________,
  ___XX___,________};

GUI_CONST_STORAGE unsigned char acGUI_FontSONGB16_0057[ 11] = { /* code 0057, LATIN CAPITAL LETTER W */
  XXXXXXXX,
  XX_XX_XX,
  XX_XX_XX,
  XX_XX_XX,
  XX_XX_XX,
  XXXXXXXX,
  XXXXXXXX,
  _XXXXXX_,
  _XX__XX_,
  _XX__XX_,
  _XX__XX_};

GUI_CONST_STORAGE unsigned char acGUI_FontSONGB16_0058[ 22] = { /* code 0058, LATIN CAPITAL LETTER X */
  XXXX_XXX,X_______,
  _XX___XX,________,
  __XX_XX_,________,
  __XX_XX_,________,
  ___XXX__,________,
  ___XXX__,________,
  ___XXX__,________,
  __XX_XX_,________,
  __XX_XX_,________,
  _XX___XX,________,
  XXXX_XXX,X_______};

GUI_CONST_STORAGE unsigned char acGUI_FontSONGB16_0059[ 11] = { /* code 0059, LATIN CAPITAL LETTER Y */
  XXXXXXXX,
  _XX__XX_,
  _XX__XX_,
  __XXXX__,
  __XXXX__,
  ___XX___,
  ___XX___,
  ___XX___,
  ___XX___,
  ___XX___,
  __XXXX__};

GUI_CONST_STORAGE unsigned char acGUI_FontSONGB16_005A[ 11] = { /* code 005A, LATIN CAPITAL LETTER Z */
  _XXXXXXX,
  XX___XX_,
  _____XX_,
  ____XX__,
  ____XX__,
  ___XX___,
  __XX____,
  __XX____,
  _XX___XX,
  _XX___XX,
  XXXXXXX_};

GUI_CONST_STORAGE unsigned char acGUI_FontSONGB16_005B[ 14] = { /* code 005B, LEFT SQUARE BRACKET */
  XXXXX___,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______,
  XXXXX___};

GUI_CONST_STORAGE unsigned char acGUI_FontSONGB16_005C[ 14] = { /* code 005C, REVERSE SOLIDUS */
  XX______,
  XX______,
  _XX_____,
  _XX_____,
  __XX____,
  __XX____,
  __XX____,
  ___XX___,
  ___XX___,
  ____XX__,
  ____XX__,
  ____XX__,
  _____XX_,
  _____XX_};

GUI_CONST_STORAGE unsigned char acGUI_FontSONGB16_005D[ 14] = { /* code 005D, RIGHT SQUARE BRACKET */
  XXXXX___,
  ___XX___,
  ___XX___,
  ___XX___,
  ___XX___,
  ___XX___,
  ___XX___,
  ___XX___,
  ___XX___,
  ___XX___,
  ___XX___,
  ___XX___,
  ___XX___,
  XXXXX___};

GUI_CONST_STORAGE unsigned char acGUI_FontSONGB16_005E[  2] = { /* code 005E, CIRCUMFLEX ACCENT */
  _XXXX___,
  XX__XX__};

GUI_CONST_STORAGE unsigned char acGUI_FontSONGB16_005F[  2] = { /* code 005F, LOW LINE */
  XXXXXXXX,X_______};

GUI_CONST_STORAGE unsigned char acGUI_FontSONGB16_0061[  7] = { /* code 0061, LATIN SMALL LETTER A */
  _XXXXX__,
  XX___XX_,
  __XXXXX_,
  _XX__XX_,
  XX___XX_,
  XX___XX_,
  _XXXXXXX};

GUI_CONST_STORAGE unsigned char acGUI_FontSONGB16_0062[ 12] = { /* code 0062, LATIN SMALL LETTER B */
  ________,
  XXX_____,
  _XX_____,
  _XX_____,
  _XX_____,
  _XXXXX__,
  _XXX_XX_,
  _XX___XX,
  _XX___XX,
  _XX___XX,
  _XXX_XX_,
  _XXXXX__};

GUI_CONST_STORAGE unsigned char acGUI_FontSONGB16_0063[  7] = { /* code 0063, LATIN SMALL LETTER C */
  __XXXX__,
  _XX__XX_,
  XX______,
  XX______,
  XX______,
  _XX__XX_,
  __XXXX__};

GUI_CONST_STORAGE unsigned char acGUI_FontSONGB16_0064[ 12] = { /* code 0064, LATIN SMALL LETTER D */
  ________,
  ____XXX_,
  _____XX_,
  _____XX_,
  _____XX_,
  __XXXXX_,
  _XX__XX_,
  XX___XX_,
  XX___XX_,
  XX___XX_,
  _XX_XXX_,
  __XXXXXX};

GUI_CONST_STORAGE unsigned char acGUI_FontSONGB16_0065[  7] = { /* code 0065, LATIN SMALL LETTER E */
  _XXXXX__,
  XX___XX_,
  XXXXXXX_,
  XX______,
  XX______,
  XX___XX_,
  _XXXXX__};

GUI_CONST_STORAGE unsigned char acGUI_FontSONGB16_0066[ 11] = { /* code 0066, LATIN SMALL LETTER F */
  ___XXXXX,
  __XX__XX,
  __XX____,
  __XX____,
  XXXXXXX_,
  __XX____,
  __XX____,
  __XX____,
  __XX____,
  __XX____,
  XXXXXX__};

GUI_CONST_STORAGE unsigned char acGUI_FontSONGB16_0067[  9] = { /* code 0067, LATIN SMALL LETTER G */
  _XXXXXX_,
  XX__XX__,
  XX__XX__,
  _XXXX___,
  XX______,
  _XXXXX__,
  XX___XX_,
  XX___XX_,
  _XXXXX__};

GUI_CONST_STORAGE unsigned char acGUI_FontSONGB16_0068[ 24] = { /* code 0068, LATIN SMALL LETTER H */
  ________,________,
  XXX_____,________,
  _XX_____,________,
  _XX_____,________,
  _XX_____,________,
  _XXXXXX_,________,
  _XXX__XX,________,
  _XX___XX,________,
  _XX___XX,________,
  _XX___XX,________,
  _XX___XX,________,
  XXXX_XXX,X_______};

GUI_CONST_STORAGE unsigned char acGUI_FontSONGB16_0069[ 11] = { /* code 0069, LATIN SMALL LETTER I */
  _XXX____,
  _XXX____,
  ________,
  ________,
  XXXX____,
  __XX____,
  __XX____,
  __XX____,
  __XX____,
  __XX____,
  XXXXXX__};

GUI_CONST_STORAGE unsigned char acGUI_FontSONGB16_006A[ 13] = { /* code 006A, LATIN SMALL LETTER J */
  ___XXX__,
  ___XXX__,
  ________,
  ________,
  __XXXX__,
  ____XX__,
  ____XX__,
  ____XX__,
  ____XX__,
  ____XX__,
  ____XX__,
  XX__XX__,
  XXXXX___};

GUI_CONST_STORAGE unsigned char acGUI_FontSONGB16_006B[ 12] = { /* code 006B, LATIN SMALL LETTER K */
  ________,
  XXX_____,
  _XX_____,
  _XX_____,
  _XX_____,
  _XX_XXXX,
  _XX_XX__,
  _XXXX___,
  _XXXXX__,
  _XX_XX__,
  _XX__XX_,
  XXXXXXXX};

GUI_CONST_STORAGE unsigned char acGUI_FontSONGB16_006C[ 11] = { /* code 006C, LATIN SMALL LETTER L */
  XXXX____,
  __XX____,
  __XX____,
  __XX____,
  __XX____,
  __XX____,
  __XX____,
  __XX____,
  __XX____,
  __XX____,
  XXXXXX__};

GUI_CONST_STORAGE unsigned char acGUI_FontSONGB16_006D[ 14] = { /* code 006D, LATIN SMALL LETTER M */
  XXXXXXXX,________,
  _XX_XX_X,X_______,
  _XX_XX_X,X_______,
  _XX_XX_X,X_______,
  _XX_XX_X,X_______,
  _XX_XX_X,X_______,
  XXXXXXXX,X_______};

GUI_CONST_STORAGE unsigned char acGUI_FontSONGB16_006E[ 14] = { /* code 006E, LATIN SMALL LETTER N */
  XXXXXXX_,________,
  _XXX__XX,________,
  _XX___XX,________,
  _XX___XX,________,
  _XX___XX,________,
  _XX___XX,________,
  XXXX_XXX,X_______};

GUI_CONST_STORAGE unsigned char acGUI_FontSONGB16_006F[  7] = { /* code 006F, LATIN SMALL LETTER O */
  _XXXXX__,
  XX___XX_,
  XX___XX_,
  XX___XX_,
  XX___XX_,
  XX___XX_,
  _XXXXX__};

GUI_CONST_STORAGE unsigned char acGUI_FontSONGB16_0070[  9] = { /* code 0070, LATIN SMALL LETTER P */
  XXXXXX__,
  _XXX_XX_,
  _XX___XX,
  _XX___XX,
  _XX___XX,
  _XX__XX_,
  _XXXXX__,
  _XX_____,
  XXXX____};

GUI_CONST_STORAGE unsigned char acGUI_FontSONGB16_0071[  9] = { /* code 0071, LATIN SMALL LETTER Q */
  __XXXXX_,
  _XX__XX_,
  XX___XX_,
  XX___XX_,
  XX___XX_,
  _XX__XX_,
  __XXXXX_,
  _____XX_,
  ____XXXX};

GUI_CONST_STORAGE unsigned char acGUI_FontSONGB16_0072[  7] = { /* code 0072, LATIN SMALL LETTER R */
  XXXXXXXX,
  __XXX_XX,
  __XX____,
  __XX____,
  __XX____,
  __XX____,
  XXXXXX__};

GUI_CONST_STORAGE unsigned char acGUI_FontSONGB16_0073[  7] = { /* code 0073, LATIN SMALL LETTER S */
  _XXXXXX_,
  XX___XX_,
  XX______,
  _XXXXX__,
  _____XX_,
  XX___XX_,
  XXXXXX__};

GUI_CONST_STORAGE unsigned char acGUI_FontSONGB16_0074[  9] = { /* code 0074, LATIN SMALL LETTER T */
  __XX____,
  __XX____,
  XXXXXX__,
  __XX____,
  __XX____,
  __XX____,
  __XX____,
  __XX____,
  ___XXX__};

GUI_CONST_STORAGE unsigned char acGUI_FontSONGB16_0075[ 14] = { /* code 0075, LATIN SMALL LETTER U */
  XXX__XXX,________,
  _XX___XX,________,
  _XX___XX,________,
  _XX___XX,________,
  _XX___XX,________,
  _XX__XXX,________,
  __XXXXXX,X_______};

GUI_CONST_STORAGE unsigned char acGUI_FontSONGB16_0076[ 14] = { /* code 0076, LATIN SMALL LETTER V */
  XXXX_XXX,X_______,
  _XX___XX,________,
  __XX_XX_,________,
  __XX_XX_,________,
  __XXXX__,________,
  ___XX___,________,
  ___XX___,________};

GUI_CONST_STORAGE unsigned char acGUI_FontSONGB16_0077[ 14] = { /* code 0077, LATIN SMALL LETTER W */
  XXXXXXXX,X_______,
  XX_XX_XX,________,
  XX_XX_XX,________,
  XXXXXXXX,________,
  XXXXXXXX,________,
  _XX__XX_,________,
  _XX__XX_,________};

GUI_CONST_STORAGE unsigned char acGUI_FontSONGB16_0078[  7] = { /* code 0078, LATIN SMALL LETTER X */
  XXXXXXX_,
  _XX_XX__,
  __XXX___,
  __XXX___,
  __XXX___,
  _XX_XX__,
  XXXXXXX_};

GUI_CONST_STORAGE unsigned char acGUI_FontSONGB16_0079[ 18] = { /* code 0079, LATIN SMALL LETTER Y */
  XXXX_XXX,X_______,
  _XX___XX,________,
  __XX_XX_,________,
  __XX_XX_,________,
  __XXXX__,________,
  ___XXX__,________,
  ___XX___,________,
  ___XX___,________,
  XXXX____,________};

GUI_CONST_STORAGE unsigned char acGUI_FontSONGB16_007A[  7] = { /* code 007A, LATIN SMALL LETTER Z */
  XXXXXXX_,
  XX__XX__,
  ___XX___,
  __XX____,
  __XX____,
  _XX__XX_,
  XXXXXXX_};

GUI_CONST_STORAGE unsigned char acGUI_FontSONGB16_007B[ 14] = { /* code 007B, LEFT CURLY BRACKET */
  __XXX___,
  _XX_____,
  _XX_____,
  _XX_____,
  _XX_____,
  _XX_____,
  XX______,
  _XX_____,
  _XX_____,
  _XX_____,
  _XX_____,
  _XX_____,
  _XX_____,
  __XXX___};

GUI_CONST_STORAGE unsigned char acGUI_FontSONGB16_007C[ 16] = { /* code 007C, VERTICAL LINE */
  XX______,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______};

GUI_CONST_STORAGE unsigned char acGUI_FontSONGB16_007D[ 14] = { /* code 007D, RIGHT CURLY BRACKET */
  XXX_____,
  __XX____,
  __XX____,
  __XX____,
  __XX____,
  __XX____,
  ___XX___,
  __XX____,
  __XX____,
  __XX____,
  __XX____,
  __XX____,
  __XX____,
  XXX_____};

GUI_CONST_STORAGE unsigned char acGUI_FontSONGB16_007E[  6] = { /* code 007E, TILDE */
  _XXX___X,X_______,
  XX_XXX_X,X_______,
  XX___XXX,________};

/* Start of unicode area <Basic Greek> */
GUI_CONST_STORAGE unsigned char acGUI_FontSONGB16_03A9[ 22] = { /* code 03A9, GREEK CAPITAL LETTER OMEGA */
  ___XXXXX,________,
  __XX___X,X_______,
  _XX_____,XX______,
  XX______,_XX_____,
  XX______,_XX_____,
  XX______,_XX_____,
  XX______,_XX_____,
  _XX_____,XX______,
  __XX___X,X_______,
  XX_XX_XX,_XX_____,
  XXXXX_XX,XXX_____};

/* Start of unicode area <CJK Unified Ideographs> */
GUI_CONST_STORAGE unsigned char acGUI_FontSONGB16_4E0A[ 30] = { /* code 4E0A */
  ______XX,________,
  ______XX,________,
  ______XX,________,
  ______XX,________,
  ______XX,________,
  ______XX,________,
  ______XX,XXXXXX__,
  ______XX,________,
  ______XX,________,
  ______XX,________,
  ______XX,________,
  ______XX,________,
  ______XX,________,
  ______XX,________,
  XXXXXXXX,XXXXXXXX};

GUI_CONST_STORAGE unsigned char acGUI_FontSONGB16_4E0B[ 30] = { /* code 4E0B */
  XXXXXXXX,XXXXXXXX,
  ______XX,________,
  ______XX,________,
  ______XX,________,
  ______XX,________,
  ______XX,_XX_____,
  ______XX,__XX____,
  ______XX,___XX___,
  ______XX,____XX__,
  ______XX,____XX__,
  ______XX,________,
  ______XX,________,
  ______XX,________,
  ______XX,________,
  ______XX,________};

GUI_CONST_STORAGE unsigned char acGUI_FontSONGB16_4E2D[ 32] = { /* code 4E2D */
  _____XX_,________,
  _____XX_,________,
  _____XX_,________,
  _____XX_,________,
  XXXXXXXX,XXXX____,
  XX___XX_,__XX____,
  XX___XX_,__XX____,
  XX___XX_,__XX____,
  XX___XX_,__XX____,
  XX___XX_,__XX____,
  XXXXXXXX,XXXX____,
  XX___XX_,__XX____,
  _____XX_,________,
  _____XX_,________,
  _____XX_,________,
  _____XX_,________};

GUI_CONST_STORAGE unsigned char acGUI_FontSONGB16_5145[ 32] = { /* code 5145 */
  ______XX,________,
  _______X,X_______,
  XXXXXXXX,XXXXXXXX,
  _____XX_,________,
  _____XX_,________,
  ____XX__,__XX____,
  ___XX___,___XX___,
  __XXXXXX,XXXXXX__,
  _____XX_,_XX_XX__,
  _____XX_,_XX_____,
  _____XX_,_XX_____,
  _____XX_,_XX_____,
  ____XX__,_XX__XX_,
  ____XX__,_XX__XX_,
  ___XX___,_XX__XX_,
  _XXX____,__XXXXX_};

GUI_CONST_STORAGE unsigned char acGUI_FontSONGB16_5173[ 32] = { /* code 5173 */
  ___XX___,___XX___,
  ____XX__,___XX___,
  ____XX__,__XX____,
  ________,________,
  __XXXXXX,XXXXXX__,
  _______X,X_______,
  _______X,X_______,
  _______X,X_______,
  XXXXXXXX,XXXXXXXX,
  _______X,X_______,
  ______XX,XX______,
  ______XX,XX______,
  _____XX_,_XX_____,
  ____XX__,__XX____,
  __XXX___,___XXX__,
  XXX_____,_____XXX};

GUI_CONST_STORAGE unsigned char acGUI_FontSONGB16_5185[ 32] = { /* code 5185 */
  ______XX,________,
  ______XX,________,
  ______XX,________,
  XXXXXXXX,XXXXXX__,
  XX____XX,____XX__,
  XX____XX,____XX__,
  XX____XX,____XX__,
  XX___XXX,X___XX__,
  XX___XX_,XX__XX__,
  XX__XX__,_XX_XX__,
  XX_XX___,__XXXX__,
  XXXX____,__XXXX__,
  XX______,____XX__,
  XX______,____XX__,
  XX______,__XXXX__,
  XX______,___XX___};

GUI_CONST_STORAGE unsigned char acGUI_FontSONGB16_51FA[ 32] = { /* code 51FA */
  ______XX,________,
  ______XX,________,
  _XX___XX,___XX___,
  _XX___XX,___XX___,
  _XX___XX,___XX___,
  _XX___XX,___XX___,
  _XXXXXXX,XXXXX___,
  ______XX,___XX___,
  ______XX,________,
  ______XX,________,
  XX____XX,____XX__,
  XX____XX,____XX__,
  XX____XX,____XX__,
  XX____XX,____XX__,
  XXXXXXXX,XXXXXX__,
  ________,____XX__};

GUI_CONST_STORAGE unsigned char acGUI_FontSONGB16_5206[ 32] = { /* code 5206 */
  ________,_XX_____,
  _____XX_,_XX_____,
  _____XX_,__XX____,
  ____XX__,__XX____,
  ___XX___,___XX___,
  __XX____,____XX__,
  _XX_____,_____XX_,
  XX_XXXXX,XXXX__XX,
  _____XX_,__XX____,
  _____XX_,__XX____,
  _____XX_,__XX____,
  ____XX__,__XX____,
  ____XX__,__XX____,
  ___XX___,__XX____,
  __XX___X,XXX_____,
  _XX_____,XX______};

GUI_CONST_STORAGE unsigned char acGUI_FontSONGB16_5236[ 32] = { /* code 5236 */
  _____XX_,_____XX_,
  __XX_XX_,_____XX_,
  __XX_XX_,_____XX_,
  __XXXXXX,XXXX_XX_,
  _XX__XX_,__XX_XX_,
  _____XX_,__XX_XX_,
  XXXXXXXX,XXXX_XX_,
  _____XX_,__XX_XX_,
  _____XX_,__XX_XX_,
  __XXXXXX,XXXX_XX_,
  __XX_XX_,XXXX_XX_,
  __XX_XX_,XXXX_XX_,
  __XX_XXX,XX___XX_,
  __XX_XXX,X____XX_,
  _____XX_,___XXXX_,
  _____XX_,____XX__};

GUI_CONST_STORAGE unsigned char acGUI_FontSONGB16_538B[ 30] = { /* code 538B */
  __XXXXXX,XXXXXXXX,
  __XX____,________,
  __XX____,XX______,
  __XX____,XX______,
  __XX____,XX______,
  __XX____,XX______,
  __XXXXXX,XXXXXXX_,
  __XX____,XX______,
  __XX____,XX______,
  __XX____,XX_XX___,
  __XX____,XX__XX__,
  __XX____,XX__XX__,
  _XX_____,XX______,
  _XXXXXXX,XXXXXXXX,
  XX______,________};

GUI_CONST_STORAGE unsigned char acGUI_FontSONGB16_56FE[ 30] = { /* code 56FE */
  XXXXXXXX,XXXXXX__,
  XX___XX_,____XX__,
  XX___XX_,____XX__,
  XX__XXXX,XXX_XX__,
  XX_XXX__,XX__XX__,
  XXXX_XXX,X___XX__,
  XX____XX,____XX__,
  XX__XXXX,XX__XX__,
  XXXXX___,_XXXXX__,
  XX___XXX,____XX__,
  XX_____X,X___XX__,
  XX__XXX_,____XX__,
  XX____XX,X___XX__,
  XXXXXXXX,XXXXXX__,
  XX______,____XX__};

GUI_CONST_STORAGE unsigned char acGUI_FontSONGB16_578B[ 30] = { /* code 578B */
  ________,_____XX_,
  _XXXXXXX,XX___XX_,
  ___XX_XX,__XX_XX_,
  ___XX_XX,__XX_XX_,
  ___XX_XX,__XX_XX_,
  XXXXXXXX,XXXX_XX_,
  ___XX_XX,__XX_XX_,
  __XX__XX,_____XX_,
  __XX__XX,___XXXX_,
  _XX____X,X___XX__,
  XX_____X,X_______,
  __XXXXXX,XXXXXX__,
  _______X,X_______,
  _______X,X_______,
  XXXXXXXX,XXXXXXXX};

GUI_CONST_STORAGE unsigned char acGUI_FontSONGB16_58F0[ 32] = { /* code 58F0 */
  _______X,X_______,
  _______X,X_______,
  XXXXXXXX,XXXXXXXX,
  _______X,X_______,
  _XXXXXXX,XXXXXXX_,
  ________,________,
  __XXXXXX,XXXXXX__,
  __XX___X,X___XX__,
  __XX___X,X___XX__,
  __XXXXXX,XXXXXX__,
  __XX____,________,
  __XX____,________,
  __XX____,________,
  _XX_____,________,
  _XX_____,________,
  XX______,________};

GUI_CONST_STORAGE unsigned char acGUI_FontSONGB16_59CB[ 32] = { /* code 59CB */
  ___XX___,__XX____,
  ___XX___,__XX____,
  ___XX___,__XX____,
  ___XX___,_XX_____,
  XXXXXXX_,_XX_XX__,
  __XX_XX_,XX___XX_,
  __XX_XXX,XXXXXXXX,
  __XX_XX_,XX____XX,
  __XX_XX_,________,
  _XX_XX__,XXXXXXX_,
  __XXXX__,XX___XX_,
  ___XX___,XX___XX_,
  __XXXX__,XX___XX_,
  _XX__XX_,XX___XX_,
  XX______,XXXXXXX_,
  ________,XX___XX_};

GUI_CONST_STORAGE unsigned char acGUI_FontSONGB16_5F00[ 30] = { /* code 5F00 */
  _XXXXXXX,XXXXXXX_,
  ____XX__,__XX____,
  ____XX__,__XX____,
  ____XX__,__XX____,
  ____XX__,__XX____,
  ____XX__,__XX____,
  XXXXXXXX,XXXXXXXX,
  ____XX__,__XX____,
  ____XX__,__XX____,
  ____XX__,__XX____,
  ____XX__,__XX____,
  ___XX___,__XX____,
  ___XX___,__XX____,
  __XX____,__XX____,
  _XX_____,__XX____};

GUI_CONST_STORAGE unsigned char acGUI_FontSONGB16_5FAA[ 32] = { /* code 5FAA */
  ___XX___,__XXXXX_,
  ___XXXXX,XXXX____,
  __XX_XX_,__XX____,
  _XX__XX_,__XX____,
  XX_XXXXX,XXXXXXXX,
  ___XXXX_,__XX____,
  __XX_XXX,XXXXXXX_,
  _XXX_XXX,X____XX_,
  XXXX_XXX,X____XX_,
  __XX_XXX,XXXXXXX_,
  __XX_XXX,X____XX_,
  __XX_XXX,XXXXXXX_,
  __XXXX_X,X____XX_,
  __XXXX_X,X____XX_,
  __XXX__X,XXXXXXX_,
  __XX___X,X____XX_};

GUI_CONST_STORAGE unsigned char acGUI_FontSONGB16_622A[ 32] = { /* code 622A */
  ____XX__,__XX____,
  ____XX__,__XXXX__,
  _XXXXXXX,X_XX_XX_,
  ____XX__,__XX____,
  XXXXXXXX,XXXXXXXX,
  ___XXXX_,__XX____,
  __XX__XX,__XX_XX_,
  _XXXXXXX,XXXX_XX_,
  XXXX_XX_,__XX_XX_,
  __XXXXXX,X_XXXX__,
  __XX_XX_,__XXXX__,
  __XXXXXX,X__XX___,
  __XX_XX_,___XX_XX,
  __XXXXXX,XXXXXXXX,
  __XX____,_XX__XXX,
  __XX____,XX____XX};

GUI_CONST_STORAGE unsigned char acGUI_FontSONGB16_62A5[ 32] = { /* code 62A5 */
  ___XX___,________,
  ___XX__X,XXXXXXX_,
  ___XX__X,X____XX_,
  ___XX__X,X____XX_,
  XXXXXXXX,X__XXXX_,
  ___XX__X,X___XX__,
  ___XX__X,X_______,
  ___XXXXX,XXXXXXX_,
  ___XXX_X,XXX__XX_,
  __XXX__X,XXX__XX_,
  XXXXX__X,X_XXXX__,
  ___XX__X,X_XXXX__,
  ___XX__X,X__XX___,
  ___XX__X,X_XXXX__,
  _XXXX__X,XXX__XX_,
  __XX___X,XX____XX};

GUI_CONST_STORAGE unsigned char acGUI_FontSONGB16_63A7[ 32] = { /* code 63A7 */
  ___XX___,_XX_____,
  ___XX___,__XX____,
  ___XX___,__XX____,
  ___XX_XX,XXXXXXXX,
  XXXXXXXX,______XX,
  ___XXXX_,XX_XXXX_,
  ___XX__X,X___XX__,
  ___XXXXX,_____XX_,
  __XXX___,________,
  XXXXX__X,XXXXXXX_,
  ___XX___,__XX____,
  ___XX___,__XX____,
  ___XX___,__XX____,
  ___XX___,__XX____,
  _XXXXXXX,XXXXXXXX,
  __XX____,________};

GUI_CONST_STORAGE unsigned char acGUI_FontSONGB16_653E[ 32] = { /* code 653E */
  __XX____,_XX_____,
  ___XX___,_XX_____,
  ________,_XX_____,
  XXXXXXXX,XX______,
  __XX____,XXXXXXXX,
  __XX___X,X___XX__,
  __XXXXXX,XX__XX__,
  __XX_XX_,XX__XX__,
  __XX_XX_,XX__XX__,
  __XX_XX_,_XXXX___,
  __XX_XX_,_XXXX___,
  __XX_XX_,__XX____,
  _XX__XX_,_XXXX___,
  _XXXXXX_,XX__XX__,
  XX__XX_X,X____XX_,
  ______XX,______XX};

GUI_CONST_STORAGE unsigned char acGUI_FontSONGB16_6570[ 32] = { /* code 6570 */
  ____XX__,__XX____,
  _XX_XX_X,X_XX____,
  __XXXXXX,__XX____,
  ____XX__,__XXXXXX,
  XXXXXXXX,XXX__XX_,
  __XXXXXX,_XX__XX_,
  _XX_XX_X,XXX__XX_,
  XX__XX__,XXXX_XX_,
  ___XX___,__XXXX__,
  XXXXXXXX,__XXXX__,
  __XX__XX,___XX___,
  _XX___XX,___XX___,
  _XXX_XX_,__XXXX__,
  ___XXX__,__XXXX__,
  __XXXXX_,_XX__XX_,
  XXX___XX,XX____XX};

GUI_CONST_STORAGE unsigned char acGUI_FontSONGB16_6587[ 32] = { /* code 6587 */
  ______XX,________,
  _______X,X_______,
  _______X,X_______,
  XXXXXXXX,XXXXXXXX,
  ___XX___,___XX___,
  ___XX___,___XX___,
  ____XX__,__XX____,
  ____XX__,__XX____,
  _____XX_,_XX_____,
  ______XX,XX______,
  _______X,X_______,
  ______XX,XX______,
  _____XX_,_XX_____,
  ____XX__,__XX____,
  __XXX___,___XXX__,
  XXX_____,_____XXX};

GUI_CONST_STORAGE unsigned char acGUI_FontSONGB16_65F6[ 32] = { /* code 65F6 */
  ________,___XX___,
  ________,___XX___,
  XXXXXX__,___XX___,
  XX__XX__,___XX___,
  XX__XXXX,XXXXXXX_,
  XX__XX__,___XX___,
  XX__XX__,___XX___,
  XXXXXX__,___XX___,
  XX__XX_X,X__XX___,
  XX__XX__,XX_XX___,
  XX__XX__,XX_XX___,
  XX__XX__,___XX___,
  XXXXXX__,___XX___,
  XX__XX__,___XX___,
  ________,_XXXX___,
  ________,__XX____};

GUI_CONST_STORAGE unsigned char acGUI_FontSONGB16_66F2[ 32] = { /* code 66F2 */
  ____XX__,XX______,
  ____XX__,XX______,
  ____XX__,XX______,
  ____XX__,XX______,
  XXXXXXXX,XXXXXX__,
  XX__XX__,XX__XX__,
  XX__XX__,XX__XX__,
  XX__XX__,XX__XX__,
  XX__XX__,XX__XX__,
  XXXXXXXX,XXXXXX__,
  XX__XX__,XX__XX__,
  XX__XX__,XX__XX__,
  XX__XX__,XX__XX__,
  XX__XX__,XX__XX__,
  XXXXXXXX,XXXXXX__,
  XX______,____XX__};

GUI_CONST_STORAGE unsigned char acGUI_FontSONGB16_69DB[ 32] = { /* code 69DB */
  ___XX___,_XX_XX__,
  ___XX__X,XXX_XX__,
  ___XX__X,XXX_XXXX,
  ___XX__X,XXXXX___,
  XXXXXXXX,XXXXXX__,
  ___XX__X,XXX__XX_,
  __XXX__X,XXX__XX_,
  __XXXX__,_XX_____,
  _XXXXXX_,________,
  _XXXXXXX,XXXXXXX_,
  XX_XX__X,XXXXXXX_,
  ___XX__X,XXXXXXX_,
  ___XX__X,XXXXXXX_,
  ___XX__X,XXXXXXX_,
  ___XXXXX,XXXXXXXX,
  ___XX___,________};

GUI_CONST_STORAGE unsigned char acGUI_FontSONGB16_6B21[ 32] = { /* code 6B21 */
  ________,XX______,
  _XX_____,XX______,
  __XX____,XX______,
  __XX____,XXXXXXX_,
  _______X,X____XX_,
  ____XX_X,X___XX__,
  ____XXXX,_XX_____,
  ___XXXX_,_XX_____,
  ___XX___,_XX_____,
  XXXX____,XXXX____,
  __XX____,XXXX____,
  __XX___X,X__XX___,
  __XX___X,X__XX___,
  __XX__XX,____XX__,
  __XX_XX_,_____XX_,
  ____XX__,______XX};

GUI_CONST_STORAGE unsigned char acGUI_FontSONGB16_6B62[ 30] = { /* code 6B62 */
  _______X,X_______,
  _______X,X_______,
  _______X,X_______,
  _______X,X_______,
  ___XX__X,X_______,
  ___XX__X,X_______,
  ___XX__X,XXXXXX__,
  ___XX__X,X_______,
  ___XX__X,X_______,
  ___XX__X,X_______,
  ___XX__X,X_______,
  ___XX__X,X_______,
  ___XX__X,X_______,
  ___XX__X,X_______,
  XXXXXXXX,XXXXXXXX};

GUI_CONST_STORAGE unsigned char acGUI_FontSONGB16_6B65[ 32] = { /* code 6B65 */
  _______X,X_______,
  _______X,X_______,
  ___XX__X,XXXXXX__,
  ___XX__X,X_______,
  ___XX__X,X_______,
  ___XX__X,X_______,
  XXXXXXXX,XXXXXXXX,
  _______X,X_______,
  _______X,X_______,
  ___XX__X,X___XX__,
  ___XX__X,X__XX___,
  __XX___X,X_XX____,
  _XX_____,XXX_____,
  ______XX,X_______,
  ___XXXX_,________,
  XXXX____,________};

GUI_CONST_STORAGE unsigned char acGUI_FontSONGB16_6C60[ 30] = { /* code 6C60 */
  ________,_XX_____,
  __XX____,_XX_____,
  ___XX_XX,_XX_____,
  ___XX_XX,_XXXXX__,
  XX____XX,_XXXXX__,
  _XX___XX,XXX_XX__,
  _XXXX_XX,XXX_XX__,
  ___XXXXX,_XX_XX__,
  ___XX_XX,_XX_XX__,
  __XX__XX,_XX_XX__,
  XXXX__XX,_XXXXX__,
  __XX__XX,_XX___XX,
  __XX__XX,______XX,
  __XX__XX,______XX,
  __XX___X,XXXXXXXX};

GUI_CONST_STORAGE unsigned char acGUI_FontSONGB16_6D41[ 32] = { /* code 6D41 */
  ________,XX______,
  __XX____,_XX_____,
  ___XXXXX,XXXXXXXX,
  ___XX___,XX______,
  XX_____X,X__XX___,
  _XX___XX,____XX__,
  _XX__XXX,XXXXXXX_,
  ___XX___,_____XX_,
  ___XX___,________,
  __XX__XX,_XX_XX__,
  XXXX__XX,_XX_XX__,
  __XX__XX,_XX_XX__,
  __XX__XX,_XX_XX__,
  __XX__XX,_XX_XXXX,
  __XX_XX_,_XX_XXXX,
  ____XX__,_XX__XXX};

GUI_CONST_STORAGE unsigned char acGUI_FontSONGB16_6D4B[ 32] = { /* code 6D4B */
  ________,_____XX_,
  __XX_XXX,XXX__XX_,
  ___XXXX_,_XX__XX_,
  ___XXXX_,_XXXXXX_,
  XX___XXX,XXXXXXX_,
  _XX__XXX,XXXXXXX_,
  _XX__XXX,XXXXXXX_,
  ___XXXXX,XXXXXXX_,
  ___XXXXX,XXXXXXX_,
  __XX_XXX,XXXXXXX_,
  XXXX_XXX,XXXXXXX_,
  __XX___X,X____XX_,
  __XX__XX,XX___XX_,
  __XX__XX,_XX__XX_,
  __XX_XX_,___XXXX_,
  ____XX__,____XX__};

GUI_CONST_STORAGE unsigned char acGUI_FontSONGB16_6E90[ 30] = { /* code 6E90 */
  __XX_XXX,XXXXXXXX,
  ___XXXX_,__XX____,
  ___XXXX_,_XX_____,
  XX___XXX,XXXXXXX_,
  _XX__XXX,X____XX_,
  _XX__XXX,XXXXXXX_,
  ___XXXXX,X____XX_,
  ___XXXXX,XXXXXXX_,
  __XX_XXX,X_XX_XX_,
  XXXX_XX_,__XX____,
  __XX_XX_,XXXXXX__,
  __XXXX_X,X_XX_XX_,
  __XXXXXX,__XX__XX,
  __XXX___,XXXX____,
  ________,_XX_____};

GUI_CONST_STORAGE unsigned char acGUI_FontSONGB16_73AF[ 28] = { /* code 73AF */
  XXXXXXXX,XXXXXXXX,
  ___XX___,___XX___,
  ___XX___,___XX___,
  ___XX___,__XX____,
  ___XX___,__XX____,
  _XXXXXX_,_XXXXX__,
  ___XX___,XXXX_XX_,
  ___XX__X,X_XX__XX,
  ___XX_XX,__XX__XX,
  ___XX___,__XX____,
  ___XXXX_,__XX____,
  XXXX____,__XX____,
  _XX_____,__XX____,
  ________,__XX____};

GUI_CONST_STORAGE unsigned char acGUI_FontSONGB16_7535[ 32] = { /* code 7535 */
  _____XX_,________,
  _____XX_,________,
  _____XX_,________,
  XXXXXXXX,XXXX____,
  XX___XX_,__XX____,
  XX___XX_,__XX____,
  XX___XX_,__XX____,
  XXXXXXXX,XXXX____,
  XX___XX_,__XX____,
  XX___XX_,__XX____,
  XX___XX_,__XX____,
  XXXXXXXX,XXXX____,
  XX___XX_,__XXXX__,
  _____XX_,____XX__,
  _____XX_,____XX__,
  ______XX,XXXXXX__};

GUI_CONST_STORAGE unsigned char acGUI_FontSONGB16_77ED[ 32] = { /* code 77ED */
  __XX____,________,
  __XX___X,XXXXXXXX,
  __XXXXX_,________,
  _XXXX___,________,
  XX_XX___,XXXXXXX_,
  ___XX___,XX___XX_,
  ___XX___,XX___XX_,
  XXXXXXXX,XX___XX_,
  ___XX___,XXXXXXX_,
  ___XX___,________,
  ___XX___,XX___XX_,
  __XXXX__,_XX__XX_,
  __XX_XX_,_XX_XX__,
  _XX__XX_,________,
  _XX____X,XXXXXXXX,
  XX______,________};

GUI_CONST_STORAGE unsigned char acGUI_FontSONGB16_7A0B[ 32] = { /* code 7A0B */
  ____XX__,________,
  ___XXXXX,XXXXXXX_,
  XXXXX__X,X____XX_,
  ___XX__X,X____XX_,
  ___XX__X,X____XX_,
  XXXXXXXX,XXXXXXX_,
  ___XX___,________,
  __XXX___,________,
  __XXXX_X,XXXXXXXX,
  _XXXXXX_,__XX____,
  _XXXXXX_,__XX____,
  XX_XX__X,XXXXXXX_,
  ___XX___,__XX____,
  ___XX___,__XX____,
  ___XX_XX,XXXXXXXX,
  ___XX___,________};

GUI_CONST_STORAGE unsigned char acGUI_FontSONGB16_7C7B[ 32] = { /* code 7C7B */
  _______X,X_______,
  ___XX__X,X__XX___,
  ____XX_X,X_XX____,
  _______X,X_______,
  _XXXXXXX,XXXXXXX_,
  _____XXX,XXX_____,
  ____XX_X,X_XX____,
  ___XX__X,X__XX___,
  _XXX____,____XX__,
  _______X,X_______,
  XXXXXXXX,XXXXXXXX,
  ______XX,XX______,
  _____XX_,_XX_____,
  ____XX__,__XX____,
  __XXX___,___XXX__,
  XXX_____,_____XXX};

GUI_CONST_STORAGE unsigned char acGUI_FontSONGB16_7CFB[ 32] = { /* code 7CFB */
  _______X,XXXXX___,
  _XXXXXXX,________,
  ____XX__,________,
  ___XX___,_XX_____,
  __XX____,XX______,
  _XXXXXXX,X_______,
  ______XX,________,
  ____XXX_,__XX____,
  __XXX___,___XX___,
  XXXXXXXX,XXXXXX__,
  ______XX,____XX__,
  ___XX_XX,_XX_____,
  __XX__XX,__XX____,
  _XX___XX,___XX___,
  XX__XXXX,____XX__,
  _____XX_,________};

GUI_CONST_STORAGE unsigned char acGUI_FontSONGB16_7EBF[ 32] = { /* code 7EBF */
  ___XX___,_XXXX___,
  ___XX___,_XX_XX__,
  __XX____,_XX_____,
  __XX_XX_,_XXXXXX_,
  _XX__XXX,XXXX____,
  XXXXXX__,_XX_____,
  ___XX___,_XXXXXXX,
  __XX__XX,XXXX____,
  _XX_____,_XX__XX_,
  XXXXXXX_,_XX_XX__,
  _XX_____,__XXX___,
  ________,__XX__XX,
  ___XXXX_,_XXXX_XX,
  XXXX____,XX__XXXX,
  _XX___XX,X____XXX,
  ________,______XX};

GUI_CONST_STORAGE unsigned char acGUI_FontSONGB16_7EDF[ 32] = { /* code 7EDF */
  ___XX___,_XX_____,
  ___XX___,__XX____,
  __XX____,__XX____,
  __XX__XX,XXXXXXXX,
  _XX_XX__,_XX_____,
  XXXXXX__,XX__XX__,
  ___XX__X,X____XX_,
  __XX__XX,XXXXXXXX,
  _XX_____,XX_XX_XX,
  XXXXXX__,XX_XX___,
  _XX_____,XX_XX___,
  ________,XX_XX___,
  ___XXX_X,X__XX_XX,
  XXXX___X,X__XX_XX,
  _XX___XX,____XXXX,
  _____XX_,________};

GUI_CONST_STORAGE unsigned char acGUI_FontSONGB16_7F6E[ 30] = { /* code 7F6E */
  _XXXXXXX,XXXXXXX_,
  _XX__XX_,_XX__XX_,
  _XXXXXXX,XXXXXXX_,
  _______X,X_______,
  _XXXXXXX,XXXXXXX_,
  _______X,X_______,
  ___XXXXX,XXXXX___,
  ___XX___,___XX___,
  ___XXXXX,XXXXX___,
  ___XX___,___XX___,
  ___XXXXX,XXXXX___,
  ___XX___,___XX___,
  ___XXXXX,XXXXX___,
  ___XX___,___XX___,
  XXXXXXXX,XXXXXXXX};

GUI_CONST_STORAGE unsigned char acGUI_FontSONGB16_8A00[ 32] = { /* code 8A00 */
  ______XX,________,
  _______X,X_______,
  XXXXXXXX,XXXXXXXX,
  ________,________,
  ________,________,
  __XXXXXX,XXXXXX__,
  ________,________,
  ________,________,
  __XXXXXX,XXXXXX__,
  ________,________,
  ________,________,
  __XXXXXX,XXXXXX__,
  __XX____,____XX__,
  __XX____,____XX__,
  __XXXXXX,XXXXXX__,
  __XX____,____XX__};

GUI_CONST_STORAGE unsigned char acGUI_FontSONGB16_8B66[ 32] = { /* code 8B66 */
  __XX_XX_,__XX____,
  XXXXXXXX,X_XX____,
  __XX_XX_,_XXXXXXX,
  _XXXXXXX,XXX__XX_,
  XX____XX,__XXXX__,
  _XXXXXXX,___XX___,
  _XX_XXXX,__XXXX__,
  _XXXXXXX,XXX__XXX,
  _____XXX,X_______,
  XXXXXXXX,XXXXXXXX,
  ________,________,
  __XXXXXX,XXXXXX__,
  ________,________,
  __XXXXXX,XXXXXX__,
  __XX____,____XX__,
  __XXXXXX,XXXXXX__};

GUI_CONST_STORAGE unsigned char acGUI_FontSONGB16_8BBE[ 30] = { /* code 8BBE */
  __XX___X,XXXXX___,
  ___XX__X,X__XX___,
  ___XX__X,X__XX___,
  _______X,X__XX___,
  ______XX,____XXXX,
  XXXXXXX_,________,
  ___XX_XX,XXXXXX__,
  ___XX__X,X___XX__,
  ___XX__X,X__XX___,
  ___XX___,XX_XX___,
  ___XXXX_,XXXX____,
  ___XXX__,_XX_____,
  ___XX___,XXXX____,
  ______XX,X__XXX__,
  ____XXX_,_____XXX};

GUI_CONST_STORAGE unsigned char acGUI_FontSONGB16_8BD5[ 32] = { /* code 8BD5 */
  ________,__XXXX__,
  __XX____,__XX_XX_,
  ___XX___,__XX_XX_,
  ___XX___,__XX____,
  _____XXX,XXXXXXXX,
  ________,__XX____,
  XXXXX___,__XX____,
  ___XXXXX,XXXX____,
  ___XX__X,X_XX____,
  ___XX__X,X__XX___,
  ___XX__X,X__XX___,
  ___XXXXX,X__XX___,
  ___XXX_X,XXX_XXXX,
  ___XXXXX,X___XXXX,
  ______XX,_____XXX,
  ________,______XX};

GUI_CONST_STORAGE unsigned char acGUI_FontSONGB16_8BED[ 30] = { /* code 8BED */
  _XX__XXX,XXXXXXX_,
  __XX____,_XX_____,
  __XX____,_XX_____,
  ______XX,XXXXXX__,
  ________,XX__XX__,
  XXXX____,XX__XX__,
  __XX_XXX,XXXXXXXX,
  __XX____,________,
  __XX____,________,
  __XX__XX,XXXXXX__,
  __XX__XX,____XX__,
  __XXXXXX,____XX__,
  __XXX_XX,____XX__,
  __XX__XX,XXXXXX__,
  ______XX,____XX__};

GUI_CONST_STORAGE unsigned char acGUI_FontSONGB16_8D1F[ 32] = { /* code 8D1F */
  ____XX__,________,
  ____XX__,________,
  ___XXXXX,XXX_____,
  __XX____,_XX_____,
  _XX_____,XX______,
  XXXXXXXX,XXXX____,
  __XX____,__XX____,
  __XX__XX,__XX____,
  __XX__XX,__XX____,
  __XX__XX,__XX____,
  __XX__XX,__XX____,
  __XX_XX_,__XX____,
  _____XXX,XX______,
  ____XX__,_XX_____,
  __XXX___,__XX____,
  XXX_____,___XX___};

GUI_CONST_STORAGE unsigned char acGUI_FontSONGB16_8D77[ 32] = { /* code 8D77 */
  ____XX__,________,
  ____XX__,________,
  ____XX__,XXXXXX__,
  _XXXXXXX,____XX__,
  ____XX__,____XX__,
  ____XX__,____XX__,
  XXXXXXXX,XXXXXX__,
  ____XX__,XX__XX__,
  __XXXX__,XX______,
  __XXXX__,XX______,
  __XXXXXX,XX___XX_,
  __XXXX__,XX___XX_,
  __XXXX__,_XXXXXX_,
  _XXXXX__,________,
  _XX_XXXX,XXXXXXXX,
  XX______,________};

GUI_CONST_STORAGE unsigned char acGUI_FontSONGB16_8DEF[ 32] = { /* code 8DEF */
  ________,_XX_____,
  _XXXXXX_,_XX_____,
  _XX__XX_,_XXXXX__,
  _XX__XX_,XX__XX__,
  _XX__XXX,XXXXX___,
  _XXXXXX_,__XX____,
  ___XX___,_XXXX___,
  ___XX___,XX__XX__,
  ___XX__X,X____XXX,
  _XXXXXX_,XXXXXX__,
  _XXXX___,XX__XX__,
  _XXXX___,XX__XX__,
  _XXXX___,XX__XX__,
  _XXXXXX_,XX__XX__,
  XXXX____,XXXXXX__,
  ________,XX__XX__};

GUI_CONST_STORAGE unsigned char acGUI_FontSONGB16_8F7D[ 32] = { /* code 8F7D */
  ____XX__,__XX____,
  ____XX__,__XXXX__,
  _XXXXXXX,X_XX_XX_,
  ____XX__,__XX____,
  XXXXXXXX,XXXXXXXX,
  ___XX___,__XX____,
  ___XX___,__XX_XX_,
  XXXXXXXX,X_XX_XX_,
  __XX____,__XX_XX_,
  _XX_XX__,__XXXX__,
  _XXXXXXX,X_XXXX__,
  ____XX__,___XX___,
  ____XXXX,X__XX_XX,
  XXXXXX__,__XXXXXX,
  ____XX__,_XX__XXX,
  ____XX__,XX____XX};

GUI_CONST_STORAGE unsigned char acGUI_FontSONGB16_8F93[ 32] = { /* code 8F93 */
  __XX____,_XX_____,
  __XX____,XXXX____,
  __XX___X,X__XX___,
  XXXXXXXX,____XX__,
  __XX_XXX,XXXXXXXX,
  _XX_____,________,
  _XXXX_XX,XXX__XX_,
  XX_XX_XX,_XXXXXX_,
  XXXXXXXX,_XXXXXX_,
  ___XX_XX,XXXXXXX_,
  ___XXXXX,_XXXXXX_,
  XXXXX_XX,_XXXXXX_,
  _XXXX_XX,XXXXXXX_,
  ___XX_XX,_XX__XX_,
  ___XX_XX,_XXXXXX_,
  ___XX_XX,XXX_XX__};

GUI_CONST_STORAGE unsigned char acGUI_FontSONGB16_8FC7[ 30] = { /* code 8FC7 */
  ________,___XX___,
  __XX____,___XX___,
  ___XX___,___XX___,
  ___XXXXX,XXXXXXXX,
  ________,___XX___,
  ________,___XX___,
  XXXXX_XX,___XX___,
  ___XX__X,X__XX___,
  ___XX__X,X__XX___,
  ___XX___,___XX___,
  ___XX___,___XX___,
  ___XX___,_XXXX___,
  ___XX___,__XX____,
  __XXXX__,________,
  _XX__XXX,XXXXXXXX};

GUI_CONST_STORAGE unsigned char acGUI_FontSONGB16_8FDB[ 30] = { /* code 8FDB */
  ________,XX_XX___,
  __XX____,XX_XX___,
  ___XX___,XX_XX___,
  ___XX_XX,XXXXXXX_,
  ________,XX_XX___,
  ________,XX_XX___,
  XXXXX___,XX_XX___,
  ___XXXXX,XXXXXXXX,
  ___XX___,XX_XX___,
  ___XX___,XX_XX___,
  ___XX__X,X__XX___,
  ___XX__X,X__XX___,
  ___XX_XX,___XX___,
  __XXXX__,________,
  _XX__XXX,XXXXXXXX};

GUI_CONST_STORAGE unsigned char acGUI_FontSONGB16_9009[ 30] = { /* code 9009 */
  ________,_XX_____,
  __XX__XX,_XX_____,
  ___XX_XX,_XX_____,
  ___XX_XX,XXXXXX__,
  _____XX_,_XX_____,
  ________,_XX_____,
  XXXXXXXX,XXXXXXX_,
  ___XX__X,X_XX____,
  ___XX__X,X_XX____,
  ___XX__X,X_XX____,
  ___XX_XX,__XX_XX_,
  ___XX_XX,__XX_XX_,
  ___XXXX_,___XXXX_,
  __XXXX__,________,
  _XX__XXX,XXXXXXXX};

GUI_CONST_STORAGE unsigned char acGUI_FontSONGB16_9502[ 30] = { /* code 9502 */
  ___XX___,________,
  ___XX__X,XXXXXXX_,
  __XXXXXX,X_XX_XX_,
  __XX___X,X_XX_XX_,
  _XX____X,XXXXXXX_,
  XXXXXXXX,X_XX_XX_,
  ___XX__X,X_XX_XX_,
  ___XX__X,XXXXXXX_,
  XXXXXXX_,__XX____,
  ___XX___,__XX____,
  ___XX__X,XXXXXXX_,
  ___XX___,__XX____,
  ___XXXX_,__XX____,
  ___XXX__,__XX____,
  ___XX_XX,XXXXXXXX};

GUI_CONST_STORAGE unsigned char acGUI_FontSONGB16_95E8[ 32] = { /* code 95E8 */
  _XX_____,________,
  __XX_XXX,XXXXXX__,
  __XX____,____XX__,
  XX______,____XX__,
  XX______,____XX__,
  XX______,____XX__,
  XX______,____XX__,
  XX______,____XX__,
  XX______,____XX__,
  XX______,____XX__,
  XX______,____XX__,
  XX______,____XX__,
  XX______,____XX__,
  XX______,____XX__,
  XX______,__XXXX__,
  XX______,___XX___};

GUI_CONST_STORAGE unsigned char acGUI_FontSONGB16_95F4[ 32] = { /* code 95F4 */
  _XX_____,________,
  __XX_XXX,XXXXXX__,
  __XX____,____XX__,
  XX______,____XX__,
  XX__XXXX,XX__XX__,
  XX__XX__,XX__XX__,
  XX__XX__,XX__XX__,
  XX__XX__,XX__XX__,
  XX__XXXX,XX__XX__,
  XX__XX__,XX__XX__,
  XX__XX__,XX__XX__,
  XX__XX__,XX__XX__,
  XX__XXXX,XX__XX__,
  XX______,____XX__,
  XX______,__XXXX__,
  XX______,___XX___};

GUI_CONST_STORAGE unsigned char acGUI_FontSONGB16_963B[ 30] = { /* code 963B */
  XXXXXXXX,XXXXX___,
  XX__XXXX,___XX___,
  XX_XX_XX,___XX___,
  XX_XX_XX,___XX___,
  XXXX__XX,XXXXX___,
  XX_XX_XX,___XX___,
  XX_XX_XX,___XX___,
  XX__XXXX,___XX___,
  XX__XXXX,XXXXX___,
  XX__XXXX,___XX___,
  XXXXX_XX,___XX___,
  XXXX__XX,___XX___,
  XX____XX,___XX___,
  XX__XXXX,XXXXXXX_,
  XX______,________};

GUI_CONST_STORAGE unsigned char acGUI_FontSONGB16_9650[ 30] = { /* code 9650 */
  XXXXXXXX,XXXXX___,
  XX_XXXX_,___XX___,
  XXXX_XX_,___XX___,
  XXXX_XXX,XXXXX___,
  XXX__XX_,___XX___,
  XXXX_XX_,___XX___,
  XX_XXXXX,XXXXX___,
  XX_XXXX_,XX__XX__,
  XX_XXXX_,XX_XX___,
  XXXXXXX_,_XXX____,
  XXXX_XX_,_XX_____,
  XX___XX_,__XX____,
  XX___XXX,X__XX___,
  XX___XXX,____XXX_,
  XX___XX_,________};

GUI_CONST_STORAGE unsigned char acGUI_FontSONGB16_97F3[ 32] = { /* code 97F3 */
  ______XX,________,
  _______X,X_______,
  __XXXXXX,XXXXXX__,
  ________,________,
  ____XX__,__XX____,
  _____XX_,_XX_____,
  XXXXXXXX,XXXXXXXX,
  ________,________,
  ___XXXXX,XXXXX___,
  ___XX___,___XX___,
  ___XX___,___XX___,
  ___XXXXX,XXXXX___,
  ___XX___,___XX___,
  ___XX___,___XX___,
  ___XXXXX,XXXXX___,
  ___XX___,___XX___};

GUI_CONST_STORAGE GUI_CHARINFO_EXT GUI_FontSONGB16_CharInfo[155] = {
   {   1,   1,   0,  14,   9, acGUI_FontSONGB16_0020 } /* code 0020, SPACE */
  ,{   3,  11,   3,   3,   9, acGUI_FontSONGB16_0021 } /* code 0021, EXCLAMATION MARK */
  ,{   7,   4,   1,   1,   9, acGUI_FontSONGB16_0022 } /* code 0022, QUOTATION MARK */
  ,{   8,  11,   0,   3,   9, acGUI_FontSONGB16_0023 } /* code 0023, NUMBER SIGN */
  ,{   6,  14,   1,   2,   9, acGUI_FontSONGB16_0024 } /* code 0024, DOLLAR SIGN */
  ,{   8,  11,   0,   3,   9, acGUI_FontSONGB16_0025 } /* code 0025, PERCENT SIGN */
  ,{   9,  11,   0,   3,   9, acGUI_FontSONGB16_0026 } /* code 0026, AMPERSAND */
  ,{   4,   4,   0,   1,   9, acGUI_FontSONGB16_0027 } /* code 0027, APOSTROPHE */
  ,{   5,  14,   3,   1,   9, acGUI_FontSONGB16_0028 } /* code 0028, LEFT PARENTHESIS */
  ,{   5,  14,   1,   1,   9, acGUI_FontSONGB16_0029 } /* code 0029, RIGHT PARENTHESIS */
  ,{   8,   8,   0,   4,   9, acGUI_FontSONGB16_002A } /* code 002A, ASTERISK */
  ,{   8,   9,   0,   4,   9, acGUI_FontSONGB16_002B } /* code 002B, PLUS SIGN */
  ,{   4,   4,   0,  12,   9, acGUI_FontSONGB16_002C } /* code 002C, COMMA */
  ,{   8,   1,   1,   8,   9, acGUI_FontSONGB16_002D } /* code 002D, HYPHEN-MINUS */
  ,{   3,   2,   1,  12,   9, acGUI_FontSONGB16_002E } /* code 002E, FULL STOP */
  ,{   8,  13,   1,   2,   9, acGUI_FontSONGB16_002F } /* code 002F, SOLIDUS */
  ,{   7,  11,   1,   3,   9, acGUI_FontSONGB16_0030 } /* code 0030, DIGIT ZERO */
  ,{   6,  11,   1,   3,   9, acGUI_FontSONGB16_0031 } /* code 0031, DIGIT ONE */
  ,{   7,  11,   1,   3,   9, acGUI_FontSONGB16_0032 } /* code 0032, DIGIT TWO */
  ,{   7,  11,   1,   3,   9, acGUI_FontSONGB16_0033 } /* code 0033, DIGIT THREE */
  ,{   7,  11,   1,   3,   9, acGUI_FontSONGB16_0034 } /* code 0034, DIGIT FOUR */
  ,{   7,  11,   1,   3,   9, acGUI_FontSONGB16_0035 } /* code 0035, DIGIT FIVE */
  ,{   7,  11,   1,   3,   9, acGUI_FontSONGB16_0036 } /* code 0036, DIGIT SIX */
  ,{   7,  11,   1,   3,   9, acGUI_FontSONGB16_0037 } /* code 0037, DIGIT SEVEN */
  ,{   7,  11,   1,   3,   9, acGUI_FontSONGB16_0038 } /* code 0038, DIGIT EIGHT */
  ,{   7,  11,   1,   3,   9, acGUI_FontSONGB16_0039 } /* code 0039, DIGIT NINE */
  ,{   3,   8,   3,   6,   9, acGUI_FontSONGB16_003A } /* code 003A, COLON */
  ,{   3,   9,   2,   7,   9, acGUI_FontSONGB16_003B } /* code 003B, SEMICOLON */
  ,{   7,  11,   1,   3,   9, acGUI_FontSONGB16_003C } /* code 003C, LESS-THAN SIGN */
  ,{   8,   5,   0,   6,   9, acGUI_FontSONGB16_003D } /* code 003D, EQUALS SIGN */
  ,{   7,  11,   1,   3,   9, acGUI_FontSONGB16_003E } /* code 003E, GREATER-THAN SIGN */
  ,{   7,  11,   1,   3,   9, acGUI_FontSONGB16_003F } /* code 003F, QUESTION MARK */
  ,{   8,  11,   0,   3,   9, acGUI_FontSONGB16_0040 } /* code 0040, COMMERCIAL AT */
  ,{   9,  11,   0,   3,   9, acGUI_FontSONGB16_0041 } /* code 0041, LATIN CAPITAL LETTER A */
  ,{   8,  11,   0,   3,   9, acGUI_FontSONGB16_0042 } /* code 0042, LATIN CAPITAL LETTER B */
  ,{   8,  11,   0,   3,   9, acGUI_FontSONGB16_0043 } /* code 0043, LATIN CAPITAL LETTER C */
  ,{   8,  11,   0,   3,   9, acGUI_FontSONGB16_0044 } /* code 0044, LATIN CAPITAL LETTER D */
  ,{   8,  11,   0,   3,   9, acGUI_FontSONGB16_0045 } /* code 0045, LATIN CAPITAL LETTER E */
  ,{   8,  11,   0,   3,   9, acGUI_FontSONGB16_0046 } /* code 0046, LATIN CAPITAL LETTER F */
  ,{   8,  11,   0,   3,   9, acGUI_FontSONGB16_0047 } /* code 0047, LATIN CAPITAL LETTER G */
  ,{   9,  11,   0,   3,   9, acGUI_FontSONGB16_0048 } /* code 0048, LATIN CAPITAL LETTER H */
  ,{   6,  11,   1,   3,   9, acGUI_FontSONGB16_0049 } /* code 0049, LATIN CAPITAL LETTER I */
  ,{   8,  13,   0,   3,   9, acGUI_FontSONGB16_004A } /* code 004A, LATIN CAPITAL LETTER J */
  ,{   8,  11,   0,   3,   9, acGUI_FontSONGB16_004B } /* code 004B, LATIN CAPITAL LETTER K */
  ,{   8,  11,   0,   3,   9, acGUI_FontSONGB16_004C } /* code 004C, LATIN CAPITAL LETTER L */
  ,{   8,  11,   0,   3,   9, acGUI_FontSONGB16_004D } /* code 004D, LATIN CAPITAL LETTER M */
  ,{   9,  11,   0,   3,   9, acGUI_FontSONGB16_004E } /* code 004E, LATIN CAPITAL LETTER N */
  ,{   8,  11,   0,   3,   9, acGUI_FontSONGB16_004F } /* code 004F, LATIN CAPITAL LETTER O */
  ,{   8,  11,   0,   3,   9, acGUI_FontSONGB16_0050 } /* code 0050, LATIN CAPITAL LETTER P */
  ,{   8,  12,   0,   3,   9, acGUI_FontSONGB16_0051 } /* code 0051, LATIN CAPITAL LETTER Q */
  ,{   9,  11,   0,   3,   9, acGUI_FontSONGB16_0052 } /* code 0052, LATIN CAPITAL LETTER R */
  ,{   7,  11,   1,   3,   9, acGUI_FontSONGB16_0053 } /* code 0053, LATIN CAPITAL LETTER S */
  ,{   8,  11,   0,   3,   9, acGUI_FontSONGB16_0054 } /* code 0054, LATIN CAPITAL LETTER T */
  ,{   9,  11,   0,   3,   9, acGUI_FontSONGB16_0055 } /* code 0055, LATIN CAPITAL LETTER U */
  ,{   9,  11,   0,   3,   9, acGUI_FontSONGB16_0056 } /* code 0056, LATIN CAPITAL LETTER V */
  ,{   8,  11,   0,   3,   9, acGUI_FontSONGB16_0057 } /* code 0057, LATIN CAPITAL LETTER W */
  ,{   9,  11,   0,   3,   9, acGUI_FontSONGB16_0058 } /* code 0058, LATIN CAPITAL LETTER X */
  ,{   8,  11,   0,   3,   9, acGUI_FontSONGB16_0059 } /* code 0059, LATIN CAPITAL LETTER Y */
  ,{   8,  11,   0,   3,   9, acGUI_FontSONGB16_005A } /* code 005A, LATIN CAPITAL LETTER Z */
  ,{   5,  14,   3,   1,   9, acGUI_FontSONGB16_005B } /* code 005B, LEFT SQUARE BRACKET */
  ,{   7,  14,   1,   2,   9, acGUI_FontSONGB16_005C } /* code 005C, REVERSE SOLIDUS */
  ,{   5,  14,   1,   1,   9, acGUI_FontSONGB16_005D } /* code 005D, RIGHT SQUARE BRACKET */
  ,{   6,   2,   2,   1,   9, acGUI_FontSONGB16_005E } /* code 005E, CIRCUMFLEX ACCENT */
  ,{   9,   1,   0,  15,   9, acGUI_FontSONGB16_005F } /* code 005F, LOW LINE */
  ,{   8,   7,   1,   7,   9, acGUI_FontSONGB16_0061 } /* code 0061, LATIN SMALL LETTER A */
  ,{   8,  12,   0,   2,   9, acGUI_FontSONGB16_0062 } /* code 0062, LATIN SMALL LETTER B */
  ,{   7,   7,   1,   7,   9, acGUI_FontSONGB16_0063 } /* code 0063, LATIN SMALL LETTER C */
  ,{   8,  12,   1,   2,   9, acGUI_FontSONGB16_0064 } /* code 0064, LATIN SMALL LETTER D */
  ,{   7,   7,   1,   7,   9, acGUI_FontSONGB16_0065 } /* code 0065, LATIN SMALL LETTER E */
  ,{   8,  11,   1,   3,   9, acGUI_FontSONGB16_0066 } /* code 0066, LATIN SMALL LETTER F */
  ,{   7,   9,   1,   7,   9, acGUI_FontSONGB16_0067 } /* code 0067, LATIN SMALL LETTER G */
  ,{   9,  12,   0,   2,   9, acGUI_FontSONGB16_0068 } /* code 0068, LATIN SMALL LETTER H */
  ,{   6,  11,   1,   3,   9, acGUI_FontSONGB16_0069 } /* code 0069, LATIN SMALL LETTER I */
  ,{   6,  13,   1,   3,   9, acGUI_FontSONGB16_006A } /* code 006A, LATIN SMALL LETTER J */
  ,{   8,  12,   0,   2,   9, acGUI_FontSONGB16_006B } /* code 006B, LATIN SMALL LETTER K */
  ,{   6,  11,   1,   3,   9, acGUI_FontSONGB16_006C } /* code 006C, LATIN SMALL LETTER L */
  ,{   9,   7,   0,   7,   9, acGUI_FontSONGB16_006D } /* code 006D, LATIN SMALL LETTER M */
  ,{   9,   7,   0,   7,   9, acGUI_FontSONGB16_006E } /* code 006E, LATIN SMALL LETTER N */
  ,{   7,   7,   1,   7,   9, acGUI_FontSONGB16_006F } /* code 006F, LATIN SMALL LETTER O */
  ,{   8,   9,   0,   7,   9, acGUI_FontSONGB16_0070 } /* code 0070, LATIN SMALL LETTER P */
  ,{   8,   9,   1,   7,   9, acGUI_FontSONGB16_0071 } /* code 0071, LATIN SMALL LETTER Q */
  ,{   8,   7,   0,   7,   9, acGUI_FontSONGB16_0072 } /* code 0072, LATIN SMALL LETTER R */
  ,{   7,   7,   1,   7,   9, acGUI_FontSONGB16_0073 } /* code 0073, LATIN SMALL LETTER S */
  ,{   6,   9,   1,   5,   9, acGUI_FontSONGB16_0074 } /* code 0074, LATIN SMALL LETTER T */
  ,{   9,   7,   0,   7,   9, acGUI_FontSONGB16_0075 } /* code 0075, LATIN SMALL LETTER U */
  ,{   9,   7,   0,   7,   9, acGUI_FontSONGB16_0076 } /* code 0076, LATIN SMALL LETTER V */
  ,{   9,   7,   0,   7,   9, acGUI_FontSONGB16_0077 } /* code 0077, LATIN SMALL LETTER W */
  ,{   7,   7,   1,   7,   9, acGUI_FontSONGB16_0078 } /* code 0078, LATIN SMALL LETTER X */
  ,{   9,   9,   0,   7,   9, acGUI_FontSONGB16_0079 } /* code 0079, LATIN SMALL LETTER Y */
  ,{   7,   7,   1,   7,   9, acGUI_FontSONGB16_007A } /* code 007A, LATIN SMALL LETTER Z */
  ,{   5,  14,   4,   1,   9, acGUI_FontSONGB16_007B } /* code 007B, LEFT CURLY BRACKET */
  ,{   2,  16,   4,   0,   9, acGUI_FontSONGB16_007C } /* code 007C, VERTICAL LINE */
  ,{   5,  14,   1,   1,   9, acGUI_FontSONGB16_007D } /* code 007D, RIGHT CURLY BRACKET */
  ,{   9,   3,   1,   0,   9, acGUI_FontSONGB16_007E } /* code 007E, TILDE */
  ,{  11,  11,   2,   1,  17, acGUI_FontSONGB16_03A9 } /* code 03A9, GREEK CAPITAL LETTER OMEGA */
  ,{  16,  15,   0,   0,  17, acGUI_FontSONGB16_4E0A } /* code 4E0A */
  ,{  16,  15,   0,   1,  17, acGUI_FontSONGB16_4E0B } /* code 4E0B */
  ,{  12,  16,   2,   0,  17, acGUI_FontSONGB16_4E2D } /* code 4E2D */
  ,{  16,  16,   0,   0,  17, acGUI_FontSONGB16_5145 } /* code 5145 */
  ,{  16,  16,   0,   0,  17, acGUI_FontSONGB16_5173 } /* code 5173 */
  ,{  14,  16,   1,   0,  17, acGUI_FontSONGB16_5185 } /* code 5185 */
  ,{  14,  16,   1,   0,  17, acGUI_FontSONGB16_51FA } /* code 51FA */
  ,{  16,  16,   0,   0,  17, acGUI_FontSONGB16_5206 } /* code 5206 */
  ,{  15,  16,   0,   0,  17, acGUI_FontSONGB16_5236 } /* code 5236 */
  ,{  16,  15,   0,   1,  17, acGUI_FontSONGB16_538B } /* code 538B */
  ,{  14,  15,   1,   1,  17, acGUI_FontSONGB16_56FE } /* code 56FE */
  ,{  16,  15,   0,   0,  17, acGUI_FontSONGB16_578B } /* code 578B */
  ,{  16,  16,   0,   0,  17, acGUI_FontSONGB16_58F0 } /* code 58F0 */
  ,{  16,  16,   0,   0,  17, acGUI_FontSONGB16_59CB } /* code 59CB */
  ,{  16,  15,   0,   1,  17, acGUI_FontSONGB16_5F00 } /* code 5F00 */
  ,{  16,  16,   0,   0,  17, acGUI_FontSONGB16_5FAA } /* code 5FAA */
  ,{  16,  16,   0,   0,  17, acGUI_FontSONGB16_622A } /* code 622A */
  ,{  16,  16,   0,   0,  17, acGUI_FontSONGB16_62A5 } /* code 62A5 */
  ,{  16,  16,   0,   0,  17, acGUI_FontSONGB16_63A7 } /* code 63A7 */
  ,{  16,  16,   0,   0,  17, acGUI_FontSONGB16_653E } /* code 653E */
  ,{  16,  16,   0,   0,  17, acGUI_FontSONGB16_6570 } /* code 6570 */
  ,{  16,  16,   0,   0,  17, acGUI_FontSONGB16_6587 } /* code 6587 */
  ,{  15,  16,   1,   0,  17, acGUI_FontSONGB16_65F6 } /* code 65F6 */
  ,{  14,  16,   1,   0,  17, acGUI_FontSONGB16_66F2 } /* code 66F2 */
  ,{  16,  16,   0,   0,  17, acGUI_FontSONGB16_69DB } /* code 69DB */
  ,{  16,  16,   0,   0,  17, acGUI_FontSONGB16_6B21 } /* code 6B21 */
  ,{  16,  15,   0,   0,  17, acGUI_FontSONGB16_6B62 } /* code 6B62 */
  ,{  16,  16,   0,   0,  17, acGUI_FontSONGB16_6B65 } /* code 6B65 */
  ,{  16,  15,   0,   0,  17, acGUI_FontSONGB16_6C60 } /* code 6C60 */
  ,{  16,  16,   0,   0,  17, acGUI_FontSONGB16_6D41 } /* code 6D41 */
  ,{  15,  16,   0,   0,  17, acGUI_FontSONGB16_6D4B } /* code 6D4B */
  ,{  16,  15,   0,   1,  17, acGUI_FontSONGB16_6E90 } /* code 6E90 */
  ,{  16,  14,   0,   2,  17, acGUI_FontSONGB16_73AF } /* code 73AF */
  ,{  14,  16,   2,   0,  17, acGUI_FontSONGB16_7535 } /* code 7535 */
  ,{  16,  16,   0,   0,  17, acGUI_FontSONGB16_77ED } /* code 77ED */
  ,{  16,  16,   0,   0,  17, acGUI_FontSONGB16_7A0B } /* code 7A0B */
  ,{  16,  16,   0,   0,  17, acGUI_FontSONGB16_7C7B } /* code 7C7B */
  ,{  14,  16,   1,   0,  17, acGUI_FontSONGB16_7CFB } /* code 7CFB */
  ,{  16,  16,   0,   0,  17, acGUI_FontSONGB16_7EBF } /* code 7EBF */
  ,{  16,  16,   0,   0,  17, acGUI_FontSONGB16_7EDF } /* code 7EDF */
  ,{  16,  15,   0,   0,  17, acGUI_FontSONGB16_7F6E } /* code 7F6E */
  ,{  16,  16,   0,   0,  17, acGUI_FontSONGB16_8A00 } /* code 8A00 */
  ,{  16,  16,   0,   0,  17, acGUI_FontSONGB16_8B66 } /* code 8B66 */
  ,{  16,  15,   0,   1,  17, acGUI_FontSONGB16_8BBE } /* code 8BBE */
  ,{  16,  16,   0,   0,  17, acGUI_FontSONGB16_8BD5 } /* code 8BD5 */
  ,{  16,  15,   0,   1,  17, acGUI_FontSONGB16_8BED } /* code 8BED */
  ,{  13,  16,   1,   0,  17, acGUI_FontSONGB16_8D1F } /* code 8D1F */
  ,{  16,  16,   0,   0,  17, acGUI_FontSONGB16_8D77 } /* code 8D77 */
  ,{  16,  16,   0,   0,  17, acGUI_FontSONGB16_8DEF } /* code 8DEF */
  ,{  16,  16,   0,   0,  17, acGUI_FontSONGB16_8F7D } /* code 8F7D */
  ,{  16,  16,   0,   0,  17, acGUI_FontSONGB16_8F93 } /* code 8F93 */
  ,{  16,  15,   0,   0,  17, acGUI_FontSONGB16_8FC7 } /* code 8FC7 */
  ,{  16,  15,   0,   0,  17, acGUI_FontSONGB16_8FDB } /* code 8FDB */
  ,{  16,  15,   0,   0,  17, acGUI_FontSONGB16_9009 } /* code 9009 */
  ,{  16,  15,   0,   0,  17, acGUI_FontSONGB16_9502 } /* code 9502 */
  ,{  14,  16,   1,   0,  17, acGUI_FontSONGB16_95E8 } /* code 95E8 */
  ,{  14,  16,   1,   0,  17, acGUI_FontSONGB16_95F4 } /* code 95F4 */
  ,{  15,  15,   1,   1,  17, acGUI_FontSONGB16_963B } /* code 963B */
  ,{  15,  15,   1,   1,  17, acGUI_FontSONGB16_9650 } /* code 9650 */
  ,{  16,  16,   0,   0,  17, acGUI_FontSONGB16_97F3 } /* code 97F3 */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontSONGB16_Prop62 = {
   0x97F3 /* first character */
  ,0x97F3 /* last character  */
  ,&GUI_FontSONGB16_CharInfo[154] /* address of first character */
  ,(GUI_CONST_STORAGE GUI_FONT_PROP_EXT *)0 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontSONGB16_Prop61 = {
   0x9650 /* first character */
  ,0x9650 /* last character  */
  ,&GUI_FontSONGB16_CharInfo[153] /* address of first character */
  ,&GUI_FontSONGB16_Prop62 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontSONGB16_Prop60 = {
   0x963B /* first character */
  ,0x963B /* last character  */
  ,&GUI_FontSONGB16_CharInfo[152] /* address of first character */
  ,&GUI_FontSONGB16_Prop61 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontSONGB16_Prop59 = {
   0x95F4 /* first character */
  ,0x95F4 /* last character  */
  ,&GUI_FontSONGB16_CharInfo[151] /* address of first character */
  ,&GUI_FontSONGB16_Prop60 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontSONGB16_Prop58 = {
   0x95E8 /* first character */
  ,0x95E8 /* last character  */
  ,&GUI_FontSONGB16_CharInfo[150] /* address of first character */
  ,&GUI_FontSONGB16_Prop59 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontSONGB16_Prop57 = {
   0x9502 /* first character */
  ,0x9502 /* last character  */
  ,&GUI_FontSONGB16_CharInfo[149] /* address of first character */
  ,&GUI_FontSONGB16_Prop58 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontSONGB16_Prop56 = {
   0x9009 /* first character */
  ,0x9009 /* last character  */
  ,&GUI_FontSONGB16_CharInfo[148] /* address of first character */
  ,&GUI_FontSONGB16_Prop57 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontSONGB16_Prop55 = {
   0x8FDB /* first character */
  ,0x8FDB /* last character  */
  ,&GUI_FontSONGB16_CharInfo[147] /* address of first character */
  ,&GUI_FontSONGB16_Prop56 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontSONGB16_Prop54 = {
   0x8FC7 /* first character */
  ,0x8FC7 /* last character  */
  ,&GUI_FontSONGB16_CharInfo[146] /* address of first character */
  ,&GUI_FontSONGB16_Prop55 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontSONGB16_Prop53 = {
   0x8F93 /* first character */
  ,0x8F93 /* last character  */
  ,&GUI_FontSONGB16_CharInfo[145] /* address of first character */
  ,&GUI_FontSONGB16_Prop54 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontSONGB16_Prop52 = {
   0x8F7D /* first character */
  ,0x8F7D /* last character  */
  ,&GUI_FontSONGB16_CharInfo[144] /* address of first character */
  ,&GUI_FontSONGB16_Prop53 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontSONGB16_Prop51 = {
   0x8DEF /* first character */
  ,0x8DEF /* last character  */
  ,&GUI_FontSONGB16_CharInfo[143] /* address of first character */
  ,&GUI_FontSONGB16_Prop52 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontSONGB16_Prop50 = {
   0x8D77 /* first character */
  ,0x8D77 /* last character  */
  ,&GUI_FontSONGB16_CharInfo[142] /* address of first character */
  ,&GUI_FontSONGB16_Prop51 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontSONGB16_Prop49 = {
   0x8D1F /* first character */
  ,0x8D1F /* last character  */
  ,&GUI_FontSONGB16_CharInfo[141] /* address of first character */
  ,&GUI_FontSONGB16_Prop50 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontSONGB16_Prop48 = {
   0x8BED /* first character */
  ,0x8BED /* last character  */
  ,&GUI_FontSONGB16_CharInfo[140] /* address of first character */
  ,&GUI_FontSONGB16_Prop49 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontSONGB16_Prop47 = {
   0x8BD5 /* first character */
  ,0x8BD5 /* last character  */
  ,&GUI_FontSONGB16_CharInfo[139] /* address of first character */
  ,&GUI_FontSONGB16_Prop48 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontSONGB16_Prop46 = {
   0x8BBE /* first character */
  ,0x8BBE /* last character  */
  ,&GUI_FontSONGB16_CharInfo[138] /* address of first character */
  ,&GUI_FontSONGB16_Prop47 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontSONGB16_Prop45 = {
   0x8B66 /* first character */
  ,0x8B66 /* last character  */
  ,&GUI_FontSONGB16_CharInfo[137] /* address of first character */
  ,&GUI_FontSONGB16_Prop46 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontSONGB16_Prop44 = {
   0x8A00 /* first character */
  ,0x8A00 /* last character  */
  ,&GUI_FontSONGB16_CharInfo[136] /* address of first character */
  ,&GUI_FontSONGB16_Prop45 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontSONGB16_Prop43 = {
   0x7F6E /* first character */
  ,0x7F6E /* last character  */
  ,&GUI_FontSONGB16_CharInfo[135] /* address of first character */
  ,&GUI_FontSONGB16_Prop44 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontSONGB16_Prop42 = {
   0x7EDF /* first character */
  ,0x7EDF /* last character  */
  ,&GUI_FontSONGB16_CharInfo[134] /* address of first character */
  ,&GUI_FontSONGB16_Prop43 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontSONGB16_Prop41 = {
   0x7EBF /* first character */
  ,0x7EBF /* last character  */
  ,&GUI_FontSONGB16_CharInfo[133] /* address of first character */
  ,&GUI_FontSONGB16_Prop42 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontSONGB16_Prop40 = {
   0x7CFB /* first character */
  ,0x7CFB /* last character  */
  ,&GUI_FontSONGB16_CharInfo[132] /* address of first character */
  ,&GUI_FontSONGB16_Prop41 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontSONGB16_Prop39 = {
   0x7C7B /* first character */
  ,0x7C7B /* last character  */
  ,&GUI_FontSONGB16_CharInfo[131] /* address of first character */
  ,&GUI_FontSONGB16_Prop40 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontSONGB16_Prop38 = {
   0x7A0B /* first character */
  ,0x7A0B /* last character  */
  ,&GUI_FontSONGB16_CharInfo[130] /* address of first character */
  ,&GUI_FontSONGB16_Prop39 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontSONGB16_Prop37 = {
   0x77ED /* first character */
  ,0x77ED /* last character  */
  ,&GUI_FontSONGB16_CharInfo[129] /* address of first character */
  ,&GUI_FontSONGB16_Prop38 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontSONGB16_Prop36 = {
   0x7535 /* first character */
  ,0x7535 /* last character  */
  ,&GUI_FontSONGB16_CharInfo[128] /* address of first character */
  ,&GUI_FontSONGB16_Prop37 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontSONGB16_Prop35 = {
   0x73AF /* first character */
  ,0x73AF /* last character  */
  ,&GUI_FontSONGB16_CharInfo[127] /* address of first character */
  ,&GUI_FontSONGB16_Prop36 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontSONGB16_Prop34 = {
   0x6E90 /* first character */
  ,0x6E90 /* last character  */
  ,&GUI_FontSONGB16_CharInfo[126] /* address of first character */
  ,&GUI_FontSONGB16_Prop35 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontSONGB16_Prop33 = {
   0x6D4B /* first character */
  ,0x6D4B /* last character  */
  ,&GUI_FontSONGB16_CharInfo[125] /* address of first character */
  ,&GUI_FontSONGB16_Prop34 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontSONGB16_Prop32 = {
   0x6D41 /* first character */
  ,0x6D41 /* last character  */
  ,&GUI_FontSONGB16_CharInfo[124] /* address of first character */
  ,&GUI_FontSONGB16_Prop33 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontSONGB16_Prop31 = {
   0x6C60 /* first character */
  ,0x6C60 /* last character  */
  ,&GUI_FontSONGB16_CharInfo[123] /* address of first character */
  ,&GUI_FontSONGB16_Prop32 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontSONGB16_Prop30 = {
   0x6B65 /* first character */
  ,0x6B65 /* last character  */
  ,&GUI_FontSONGB16_CharInfo[122] /* address of first character */
  ,&GUI_FontSONGB16_Prop31 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontSONGB16_Prop29 = {
   0x6B62 /* first character */
  ,0x6B62 /* last character  */
  ,&GUI_FontSONGB16_CharInfo[121] /* address of first character */
  ,&GUI_FontSONGB16_Prop30 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontSONGB16_Prop28 = {
   0x6B21 /* first character */
  ,0x6B21 /* last character  */
  ,&GUI_FontSONGB16_CharInfo[120] /* address of first character */
  ,&GUI_FontSONGB16_Prop29 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontSONGB16_Prop27 = {
   0x69DB /* first character */
  ,0x69DB /* last character  */
  ,&GUI_FontSONGB16_CharInfo[119] /* address of first character */
  ,&GUI_FontSONGB16_Prop28 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontSONGB16_Prop26 = {
   0x66F2 /* first character */
  ,0x66F2 /* last character  */
  ,&GUI_FontSONGB16_CharInfo[118] /* address of first character */
  ,&GUI_FontSONGB16_Prop27 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontSONGB16_Prop25 = {
   0x65F6 /* first character */
  ,0x65F6 /* last character  */
  ,&GUI_FontSONGB16_CharInfo[117] /* address of first character */
  ,&GUI_FontSONGB16_Prop26 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontSONGB16_Prop24 = {
   0x6587 /* first character */
  ,0x6587 /* last character  */
  ,&GUI_FontSONGB16_CharInfo[116] /* address of first character */
  ,&GUI_FontSONGB16_Prop25 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontSONGB16_Prop23 = {
   0x6570 /* first character */
  ,0x6570 /* last character  */
  ,&GUI_FontSONGB16_CharInfo[115] /* address of first character */
  ,&GUI_FontSONGB16_Prop24 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontSONGB16_Prop22 = {
   0x653E /* first character */
  ,0x653E /* last character  */
  ,&GUI_FontSONGB16_CharInfo[114] /* address of first character */
  ,&GUI_FontSONGB16_Prop23 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontSONGB16_Prop21 = {
   0x63A7 /* first character */
  ,0x63A7 /* last character  */
  ,&GUI_FontSONGB16_CharInfo[113] /* address of first character */
  ,&GUI_FontSONGB16_Prop22 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontSONGB16_Prop20 = {
   0x62A5 /* first character */
  ,0x62A5 /* last character  */
  ,&GUI_FontSONGB16_CharInfo[112] /* address of first character */
  ,&GUI_FontSONGB16_Prop21 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontSONGB16_Prop19 = {
   0x622A /* first character */
  ,0x622A /* last character  */
  ,&GUI_FontSONGB16_CharInfo[111] /* address of first character */
  ,&GUI_FontSONGB16_Prop20 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontSONGB16_Prop18 = {
   0x5FAA /* first character */
  ,0x5FAA /* last character  */
  ,&GUI_FontSONGB16_CharInfo[110] /* address of first character */
  ,&GUI_FontSONGB16_Prop19 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontSONGB16_Prop17 = {
   0x5F00 /* first character */
  ,0x5F00 /* last character  */
  ,&GUI_FontSONGB16_CharInfo[109] /* address of first character */
  ,&GUI_FontSONGB16_Prop18 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontSONGB16_Prop16 = {
   0x59CB /* first character */
  ,0x59CB /* last character  */
  ,&GUI_FontSONGB16_CharInfo[108] /* address of first character */
  ,&GUI_FontSONGB16_Prop17 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontSONGB16_Prop15 = {
   0x58F0 /* first character */
  ,0x58F0 /* last character  */
  ,&GUI_FontSONGB16_CharInfo[107] /* address of first character */
  ,&GUI_FontSONGB16_Prop16 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontSONGB16_Prop14 = {
   0x578B /* first character */
  ,0x578B /* last character  */
  ,&GUI_FontSONGB16_CharInfo[106] /* address of first character */
  ,&GUI_FontSONGB16_Prop15 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontSONGB16_Prop13 = {
   0x56FE /* first character */
  ,0x56FE /* last character  */
  ,&GUI_FontSONGB16_CharInfo[105] /* address of first character */
  ,&GUI_FontSONGB16_Prop14 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontSONGB16_Prop12 = {
   0x538B /* first character */
  ,0x538B /* last character  */
  ,&GUI_FontSONGB16_CharInfo[104] /* address of first character */
  ,&GUI_FontSONGB16_Prop13 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontSONGB16_Prop11 = {
   0x5236 /* first character */
  ,0x5236 /* last character  */
  ,&GUI_FontSONGB16_CharInfo[103] /* address of first character */
  ,&GUI_FontSONGB16_Prop12 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontSONGB16_Prop10 = {
   0x5206 /* first character */
  ,0x5206 /* last character  */
  ,&GUI_FontSONGB16_CharInfo[102] /* address of first character */
  ,&GUI_FontSONGB16_Prop11 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontSONGB16_Prop9 = {
   0x51FA /* first character */
  ,0x51FA /* last character  */
  ,&GUI_FontSONGB16_CharInfo[101] /* address of first character */
  ,&GUI_FontSONGB16_Prop10 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontSONGB16_Prop8 = {
   0x5185 /* first character */
  ,0x5185 /* last character  */
  ,&GUI_FontSONGB16_CharInfo[100] /* address of first character */
  ,&GUI_FontSONGB16_Prop9 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontSONGB16_Prop7 = {
   0x5173 /* first character */
  ,0x5173 /* last character  */
  ,&GUI_FontSONGB16_CharInfo[ 99] /* address of first character */
  ,&GUI_FontSONGB16_Prop8 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontSONGB16_Prop6 = {
   0x5145 /* first character */
  ,0x5145 /* last character  */
  ,&GUI_FontSONGB16_CharInfo[ 98] /* address of first character */
  ,&GUI_FontSONGB16_Prop7 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontSONGB16_Prop5 = {
   0x4E2D /* first character */
  ,0x4E2D /* last character  */
  ,&GUI_FontSONGB16_CharInfo[ 97] /* address of first character */
  ,&GUI_FontSONGB16_Prop6 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontSONGB16_Prop4 = {
   0x4E0A /* first character */
  ,0x4E0B /* last character  */
  ,&GUI_FontSONGB16_CharInfo[ 95] /* address of first character */
  ,&GUI_FontSONGB16_Prop5 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontSONGB16_Prop3 = {
   0x03A9 /* first character */
  ,0x03A9 /* last character  */
  ,&GUI_FontSONGB16_CharInfo[ 94] /* address of first character */
  ,&GUI_FontSONGB16_Prop4 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontSONGB16_Prop2 = {
   0x0061 /* first character */
  ,0x007E /* last character  */
  ,&GUI_FontSONGB16_CharInfo[ 64] /* address of first character */
  ,&GUI_FontSONGB16_Prop3 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontSONGB16_Prop1 = {
   0x0020 /* first character */
  ,0x005F /* last character  */
  ,&GUI_FontSONGB16_CharInfo[  0] /* address of first character */
  ,&GUI_FontSONGB16_Prop2 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT GUI_FontSONGB16 = {
   GUI_FONTTYPE_PROP_EXT /* type of font    */
  ,16 /* height of font  */
  ,16 /* space of font y */
  ,1 /* magnification x */
  ,1 /* magnification y */
  ,{&GUI_FontSONGB16_Prop1}
  ,14 /* Baseline */
  ,7 /* Height of lowercase characters */
  ,11 /* Height of capital characters */
};

