/*********************************************************************
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                           www.segger.com                           *
**********************************************************************
*                                                                    *
* C-file generated by                                                *
*                                                                    *
*        emWin Font Converter (ST) version 5.32                      *
*        Compiled Oct  8 2015, 11:58:55                              *
*                                                                    *
*        (c) 1998 - 2015 Segger Microcontroller GmbH & Co. KG        *
*                                                                    *
**********************************************************************
*                                                                    *
* Source file: SONG16.c                                              *
* Font:        ËÎÌו                                                  *
* Height:      16                                                    *
*                                                                    *
**********************************************************************
*                                                                    *
* Initial font height:  16                                           *
* Range disabled:       0000 - FFFF                                  *
* Read pattern file: C:\Users\Administrator\Desktop\123.txt          *
* Range disabled:       0000 - FFFF                                  *
* Read pattern file: C:\Users\Administrator\Desktop\123.txt          *
*                                                                    *
**********************************************************************
*/

#include "GUI.h"

#ifndef GUI_CONST_STORAGE
  #define GUI_CONST_STORAGE const
#endif

/* The following line needs to be included in any file selecting the
   font.
*/
extern GUI_CONST_STORAGE GUI_FONT GUI_FontSONG16;

/* Start of unicode area <Basic Latin> */
GUI_CONST_STORAGE unsigned char acGUI_FontSONG16_0020[  1] = { /* code 0020, SPACE */
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontSONG16_0021[ 11] = { /* code 0021, EXCLAMATION MARK */
  X_______,
  X_______,
  X_______,
  X_______,
  X_______,
  X_______,
  X_______,
  ________,
  ________,
  XX______,
  XX______};

GUI_CONST_STORAGE unsigned char acGUI_FontSONG16_0022[  4] = { /* code 0022, QUOTATION MARK */
  __X__X__,
  _XX_XX__,
  _X__X___,
  X__X____};

GUI_CONST_STORAGE unsigned char acGUI_FontSONG16_0023[ 11] = { /* code 0023, NUMBER SIGN */
  __X__X__,
  __X__X__,
  __X__X__,
  XXXXXXX_,
  _X__X___,
  _X__X___,
  _X__X___,
  XXXXXXX_,
  _X__X___,
  _X__X___,
  _X__X___};

GUI_CONST_STORAGE unsigned char acGUI_FontSONG16_0024[ 14] = { /* code 0024, DOLLAR SIGN */
  __X_____,
  _XXX____,
  X_X_X___,
  X_X_X___,
  X_X_____,
  _XX_____,
  __XX____,
  __X_X___,
  __X_X___,
  X_X_X___,
  X_X_X___,
  _XXX____,
  __X_____,
  __X_____};

GUI_CONST_STORAGE unsigned char acGUI_FontSONG16_0025[ 11] = { /* code 0025, PERCENT SIGN */
  _X___X__,
  X_X__X__,
  X_X_X___,
  X_X_X___,
  X_X_X___,
  _X_X_X__,
  ___XX_X_,
  __X_X_X_,
  __X_X_X_,
  __X_X_X_,
  _X___X__};

GUI_CONST_STORAGE unsigned char acGUI_FontSONG16_0026[ 11] = { /* code 0026, AMPERSAND */
  __XX____,
  _X__X___,
  _X__X___,
  _X__X___,
  _X_X____,
  _XX_XXX_,
  X_X__X__,
  X__X_X__,
  X___X___,
  X___X__X,
  _XXX_XX_};

GUI_CONST_STORAGE unsigned char acGUI_FontSONG16_0028[ 14] = { /* code 0028, LEFT PARENTHESIS */
  ___X____,
  __X_____,
  _X______,
  _X______,
  X_______,
  X_______,
  X_______,
  X_______,
  X_______,
  X_______,
  _X______,
  _X______,
  __X_____,
  ___X____};

GUI_CONST_STORAGE unsigned char acGUI_FontSONG16_0029[ 14] = { /* code 0029, RIGHT PARENTHESIS */
  X_______,
  _X______,
  __X_____,
  __X_____,
  ___X____,
  ___X____,
  ___X____,
  ___X____,
  ___X____,
  ___X____,
  __X_____,
  __X_____,
  _X______,
  X_______};

GUI_CONST_STORAGE unsigned char acGUI_FontSONG16_002A[  8] = { /* code 002A, ASTERISK */
  ___X____,
  ___X____,
  XX_X_XX_,
  __XXX___,
  __XXX___,
  XX_X_XX_,
  ___X____,
  ___X____};

GUI_CONST_STORAGE unsigned char acGUI_FontSONG16_002B[  9] = { /* code 002B, PLUS SIGN */
  ___X____,
  ___X____,
  ___X____,
  ___X____,
  XXXXXXX_,
  ___X____,
  ___X____,
  ___X____,
  ___X____};

GUI_CONST_STORAGE unsigned char acGUI_FontSONG16_002C[  4] = { /* code 002C, COMMA */
  _XX_____,
  _XX_____,
  __X_____,
  XX______};

GUI_CONST_STORAGE unsigned char acGUI_FontSONG16_002D[  1] = { /* code 002D, HYPHEN-MINUS */
  XXXXXXX_};

GUI_CONST_STORAGE unsigned char acGUI_FontSONG16_002E[  2] = { /* code 002E, FULL STOP */
  XX______,
  XX______};

GUI_CONST_STORAGE unsigned char acGUI_FontSONG16_002F[ 13] = { /* code 002F, SOLIDUS */
  ______X_,
  _____X__,
  _____X__,
  ____X___,
  ____X___,
  ___X____,
  ___X____,
  __X_____,
  __X_____,
  _X______,
  _X______,
  X_______,
  X_______};

GUI_CONST_STORAGE unsigned char acGUI_FontSONG16_0030[ 11] = { /* code 0030, DIGIT ZERO */
  __XX____,
  _X__X___,
  X____X__,
  X____X__,
  X____X__,
  X____X__,
  X____X__,
  X____X__,
  X____X__,
  _X__X___,
  __XX____};

GUI_CONST_STORAGE unsigned char acGUI_FontSONG16_0031[ 11] = { /* code 0031, DIGIT ONE */
  __X_____,
  XXX_____,
  __X_____,
  __X_____,
  __X_____,
  __X_____,
  __X_____,
  __X_____,
  __X_____,
  __X_____,
  XXXXX___};

GUI_CONST_STORAGE unsigned char acGUI_FontSONG16_0032[ 11] = { /* code 0032, DIGIT TWO */
  _XXXX___,
  X____X__,
  X____X__,
  X____X__,
  ____X___,
  ____X___,
  ___X____,
  __X_____,
  _X______,
  X____X__,
  XXXXXX__};

GUI_CONST_STORAGE unsigned char acGUI_FontSONG16_0033[ 11] = { /* code 0033, DIGIT THREE */
  _XXXX___,
  X____X__,
  X____X__,
  ____X___,
  __XX____,
  ____X___,
  _____X__,
  _____X__,
  X____X__,
  X___X___,
  _XXX____};

GUI_CONST_STORAGE unsigned char acGUI_FontSONG16_0034[ 11] = { /* code 0034, DIGIT FOUR */
  ____X___,
  ___XX___,
  __X_X___,
  _X__X___,
  _X__X___,
  X___X___,
  X___X___,
  XXXXXX__,
  ____X___,
  ____X___,
  __XXXX__};

GUI_CONST_STORAGE unsigned char acGUI_FontSONG16_0035[ 11] = { /* code 0035, DIGIT FIVE */
  XXXXXX__,
  X_______,
  X_______,
  X_______,
  X_XX____,
  XX__X___,
  _____X__,
  _____X__,
  X____X__,
  X___X___,
  _XXX____};

GUI_CONST_STORAGE unsigned char acGUI_FontSONG16_0036[ 11] = { /* code 0036, DIGIT SIX */
  __XXX___,
  _X__X___,
  X_______,
  X_______,
  X_XX____,
  XX__X___,
  X____X__,
  X____X__,
  X____X__,
  _X__X___,
  __XX____};

GUI_CONST_STORAGE unsigned char acGUI_FontSONG16_0037[ 11] = { /* code 0037, DIGIT SEVEN */
  XXXXXX__,
  X___X___,
  X___X___,
  ___X____,
  ___X____,
  __X_____,
  __X_____,
  __X_____,
  __X_____,
  __X_____,
  __X_____};

GUI_CONST_STORAGE unsigned char acGUI_FontSONG16_0038[ 11] = { /* code 0038, DIGIT EIGHT */
  _XXXX___,
  X____X__,
  X____X__,
  X____X__,
  _X__X___,
  __XX____,
  _X__X___,
  X____X__,
  X____X__,
  X____X__,
  _XXXX___};

GUI_CONST_STORAGE unsigned char acGUI_FontSONG16_0039[ 11] = { /* code 0039, DIGIT NINE */
  __XX____,
  _X__X___,
  X____X__,
  X____X__,
  X____X__,
  _X__XX__,
  __XX_X__,
  _____X__,
  _____X__,
  _X__X___,
  _XXX____};

GUI_CONST_STORAGE unsigned char acGUI_FontSONG16_003A[  8] = { /* code 003A, COLON */
  XX______,
  XX______,
  ________,
  ________,
  ________,
  ________,
  XX______,
  XX______};

GUI_CONST_STORAGE unsigned char acGUI_FontSONG16_003B[  9] = { /* code 003B, SEMICOLON */
  _X______,
  ________,
  ________,
  ________,
  ________,
  ________,
  _X______,
  _X______,
  X_______};

GUI_CONST_STORAGE unsigned char acGUI_FontSONG16_003C[ 11] = { /* code 003C, LESS-THAN SIGN */
  _____X__,
  ____X___,
  ___X____,
  __X_____,
  _X______,
  X_______,
  _X______,
  __X_____,
  ___X____,
  ____X___,
  _____X__};

GUI_CONST_STORAGE unsigned char acGUI_FontSONG16_003D[  5] = { /* code 003D, EQUALS SIGN */
  XXXXXXX_,
  ________,
  ________,
  ________,
  XXXXXXX_};

GUI_CONST_STORAGE unsigned char acGUI_FontSONG16_003E[ 11] = { /* code 003E, GREATER-THAN SIGN */
  X_______,
  _X______,
  __X_____,
  ___X____,
  ____X___,
  _____X__,
  ____X___,
  ___X____,
  __X_____,
  _X______,
  X_______};

GUI_CONST_STORAGE unsigned char acGUI_FontSONG16_003F[ 11] = { /* code 003F, QUESTION MARK */
  _XXXX___,
  X____X__,
  X____X__,
  XX___X__,
  _____X__,
  ____X___,
  ___X____,
  ___X____,
  ________,
  __XX____,
  __XX____};

GUI_CONST_STORAGE unsigned char acGUI_FontSONG16_0040[ 11] = { /* code 0040, COMMERCIAL AT */
  __XXX___,
  _X___X__,
  _X_XX_X_,
  X_X_X_X_,
  X_X_X_X_,
  X_X_X_X_,
  X_X_X_X_,
  X_XX_X__,
  _X____X_,
  _X___X__,
  __XXX___};

GUI_CONST_STORAGE unsigned char acGUI_FontSONG16_0041[ 11] = { /* code 0041, LATIN CAPITAL LETTER A */
  ___X____,
  ___X____,
  ___XX___,
  __X_X___,
  __X_X___,
  __X__X__,
  __XXXX__,
  _X___X__,
  _X____X_,
  _X____X_,
  XXX__XXX};

GUI_CONST_STORAGE unsigned char acGUI_FontSONG16_0042[ 11] = { /* code 0042, LATIN CAPITAL LETTER B */
  XXXXX___,
  _X___X__,
  _X___X__,
  _X___X__,
  _XXXX___,
  _X___X__,
  _X____X_,
  _X____X_,
  _X____X_,
  _X___X__,
  XXXXX___};

GUI_CONST_STORAGE unsigned char acGUI_FontSONG16_0043[ 11] = { /* code 0043, LATIN CAPITAL LETTER C */
  __XXXXX_,
  _X____X_,
  _X____X_,
  X_______,
  X_______,
  X_______,
  X_______,
  X_______,
  _X____X_,
  _X___X__,
  __XXX___};

GUI_CONST_STORAGE unsigned char acGUI_FontSONG16_0044[ 11] = { /* code 0044, LATIN CAPITAL LETTER D */
  XXXXX___,
  _X___X__,
  _X____X_,
  _X____X_,
  _X____X_,
  _X____X_,
  _X____X_,
  _X____X_,
  _X____X_,
  _X___X__,
  XXXXX___};

GUI_CONST_STORAGE unsigned char acGUI_FontSONG16_0045[ 11] = { /* code 0045, LATIN CAPITAL LETTER E */
  XXXXXX__,
  _X____X_,
  _X__X___,
  _X__X___,
  _XXXX___,
  _X__X___,
  _X__X___,
  _X______,
  _X____X_,
  _X____X_,
  XXXXXX__};

GUI_CONST_STORAGE unsigned char acGUI_FontSONG16_0046[ 11] = { /* code 0046, LATIN CAPITAL LETTER F */
  XXXXXX__,
  _X____X_,
  _X__X___,
  _X__X___,
  _XXXX___,
  _X__X___,
  _X__X___,
  _X______,
  _X______,
  _X______,
  XXX_____};

GUI_CONST_STORAGE unsigned char acGUI_FontSONG16_0047[ 11] = { /* code 0047, LATIN CAPITAL LETTER G */
  __XXXX__,
  _X___X__,
  _X___X__,
  X_______,
  X_______,
  X_______,
  X___XXX_,
  X____X__,
  _X___X__,
  _X___X__,
  __XXX___};

GUI_CONST_STORAGE unsigned char acGUI_FontSONG16_0048[ 11] = { /* code 0048, LATIN CAPITAL LETTER H */
  XXX__XXX,
  _X____X_,
  _X____X_,
  _X____X_,
  _X____X_,
  _XXXXXX_,
  _X____X_,
  _X____X_,
  _X____X_,
  _X____X_,
  XXX__XXX};

GUI_CONST_STORAGE unsigned char acGUI_FontSONG16_0049[ 11] = { /* code 0049, LATIN CAPITAL LETTER I */
  XXXXX___,
  __X_____,
  __X_____,
  __X_____,
  __X_____,
  __X_____,
  __X_____,
  __X_____,
  __X_____,
  __X_____,
  XXXXX___};

GUI_CONST_STORAGE unsigned char acGUI_FontSONG16_004A[ 13] = { /* code 004A, LATIN CAPITAL LETTER J */
  __XXXXX_,
  ____X___,
  ____X___,
  ____X___,
  ____X___,
  ____X___,
  ____X___,
  ____X___,
  ____X___,
  ____X___,
  ____X___,
  X___X___,
  XXXX____};

GUI_CONST_STORAGE unsigned char acGUI_FontSONG16_004B[ 11] = { /* code 004B, LATIN CAPITAL LETTER K */
  XXX_XXX_,
  _X___X__,
  _X__X___,
  _X_X____,
  _XXX____,
  _X_X____,
  _X__X___,
  _X__X___,
  _X___X__,
  _X___X__,
  XXX_XXX_};

GUI_CONST_STORAGE unsigned char acGUI_FontSONG16_004C[ 11] = { /* code 004C, LATIN CAPITAL LETTER L */
  XXX_____,
  _X______,
  _X______,
  _X______,
  _X______,
  _X______,
  _X______,
  _X______,
  _X______,
  _X____X_,
  XXXXXXX_};

GUI_CONST_STORAGE unsigned char acGUI_FontSONG16_004D[ 11] = { /* code 004D, LATIN CAPITAL LETTER M */
  XXX_XXX_,
  _XX_XX__,
  _XX_XX__,
  _XX_XX__,
  _XX_XX__,
  _X_X_X__,
  _X_X_X__,
  _X_X_X__,
  _X_X_X__,
  _X_X_X__,
  XX_X_XX_};

GUI_CONST_STORAGE unsigned char acGUI_FontSONG16_004E[ 11] = { /* code 004E, LATIN CAPITAL LETTER N */
  XX___XXX,
  _XX___X_,
  _XX___X_,
  _X_X__X_,
  _X_X__X_,
  _X__X_X_,
  _X__X_X_,
  _X__X_X_,
  _X___XX_,
  _X___XX_,
  XXX___X_};

GUI_CONST_STORAGE unsigned char acGUI_FontSONG16_004F[ 11] = { /* code 004F, LATIN CAPITAL LETTER O */
  __XXX___,
  _X___X__,
  X_____X_,
  X_____X_,
  X_____X_,
  X_____X_,
  X_____X_,
  X_____X_,
  X_____X_,
  _X___X__,
  __XXX___};

GUI_CONST_STORAGE unsigned char acGUI_FontSONG16_0050[ 11] = { /* code 0050, LATIN CAPITAL LETTER P */
  XXXXXX__,
  _X____X_,
  _X____X_,
  _X____X_,
  _X____X_,
  _XXXXX__,
  _X______,
  _X______,
  _X______,
  _X______,
  XXX_____};

GUI_CONST_STORAGE unsigned char acGUI_FontSONG16_0051[ 12] = { /* code 0051, LATIN CAPITAL LETTER Q */
  __XXX___,
  _X___X__,
  X_____X_,
  X_____X_,
  X_____X_,
  X_____X_,
  X_____X_,
  X_XX__X_,
  XX__X_X_,
  _X__XX__,
  __XXX___,
  _____XX_};

GUI_CONST_STORAGE unsigned char acGUI_FontSONG16_0052[ 11] = { /* code 0052, LATIN CAPITAL LETTER R */
  XXXXXX__,
  _X____X_,
  _X____X_,
  _X____X_,
  _XXXXX__,
  _X__X___,
  _X__X___,
  _X___X__,
  _X___X__,
  _X____X_,
  XXX___XX};

GUI_CONST_STORAGE unsigned char acGUI_FontSONG16_0053[ 11] = { /* code 0053, LATIN CAPITAL LETTER S */
  _XXXXX__,
  X____X__,
  X____X__,
  X_______,
  _X______,
  __XX____,
  ____X___,
  _____X__,
  X____X__,
  X____X__,
  XXXXX___};

GUI_CONST_STORAGE unsigned char acGUI_FontSONG16_0054[ 11] = { /* code 0054, LATIN CAPITAL LETTER T */
  XXXXXXX_,
  X__X__X_,
  ___X____,
  ___X____,
  ___X____,
  ___X____,
  ___X____,
  ___X____,
  ___X____,
  ___X____,
  __XXX___};

GUI_CONST_STORAGE unsigned char acGUI_FontSONG16_0055[ 11] = { /* code 0055, LATIN CAPITAL LETTER U */
  XXX__XXX,
  _X____X_,
  _X____X_,
  _X____X_,
  _X____X_,
  _X____X_,
  _X____X_,
  _X____X_,
  _X____X_,
  _X____X_,
  __XXXX__};

GUI_CONST_STORAGE unsigned char acGUI_FontSONG16_0056[ 11] = { /* code 0056, LATIN CAPITAL LETTER V */
  XXX__XXX,
  _X____X_,
  _X____X_,
  _X___X__,
  __X__X__,
  __X__X__,
  __X_X___,
  __X_X___,
  ___XX___,
  ___X____,
  ___X____};

GUI_CONST_STORAGE unsigned char acGUI_FontSONG16_0057[ 11] = { /* code 0057, LATIN CAPITAL LETTER W */
  XX_X_XX_,
  X__X__X_,
  X__X__X_,
  X__X__X_,
  X__X__X_,
  X_X_X_X_,
  X_X_X_X_,
  _XX_XX__,
  _X___X__,
  _X___X__,
  _X___X__};

GUI_CONST_STORAGE unsigned char acGUI_FontSONG16_0058[ 11] = { /* code 0058, LATIN CAPITAL LETTER X */
  XXX__XXX,
  _X____X_,
  __X__X__,
  __X__X__,
  ___XX___,
  ___XX___,
  ___XX___,
  __X__X__,
  __X__X__,
  _X____X_,
  XXX__XXX};

GUI_CONST_STORAGE unsigned char acGUI_FontSONG16_0059[ 11] = { /* code 0059, LATIN CAPITAL LETTER Y */
  XXX_XXX_,
  _X___X__,
  _X___X__,
  __X_X___,
  __X_X___,
  ___X____,
  ___X____,
  ___X____,
  ___X____,
  ___X____,
  __XXX___};

GUI_CONST_STORAGE unsigned char acGUI_FontSONG16_005A[ 11] = { /* code 005A, LATIN CAPITAL LETTER Z */
  _XXXXXX_,
  X____X__,
  _____X__,
  ____X___,
  ____X___,
  ___X____,
  __X_____,
  __X_____,
  _X____X_,
  _X____X_,
  XXXXXX__};

GUI_CONST_STORAGE unsigned char acGUI_FontSONG16_005B[ 14] = { /* code 005B, LEFT SQUARE BRACKET */
  XXXX____,
  X_______,
  X_______,
  X_______,
  X_______,
  X_______,
  X_______,
  X_______,
  X_______,
  X_______,
  X_______,
  X_______,
  X_______,
  XXXX____};

GUI_CONST_STORAGE unsigned char acGUI_FontSONG16_005C[ 14] = { /* code 005C, REVERSE SOLIDUS */
  X_______,
  X_______,
  _X______,
  _X______,
  __X_____,
  __X_____,
  __X_____,
  ___X____,
  ___X____,
  ____X___,
  ____X___,
  ____X___,
  _____X__,
  _____X__};

GUI_CONST_STORAGE unsigned char acGUI_FontSONG16_005D[ 14] = { /* code 005D, RIGHT SQUARE BRACKET */
  XXXX____,
  ___X____,
  ___X____,
  ___X____,
  ___X____,
  ___X____,
  ___X____,
  ___X____,
  ___X____,
  ___X____,
  ___X____,
  ___X____,
  ___X____,
  XXXX____};

GUI_CONST_STORAGE unsigned char acGUI_FontSONG16_005E[  2] = { /* code 005E, CIRCUMFLEX ACCENT */
  _XXX____,
  X___X___};

GUI_CONST_STORAGE unsigned char acGUI_FontSONG16_005F[  1] = { /* code 005F, LOW LINE */
  XXXXXXXX};

GUI_CONST_STORAGE unsigned char acGUI_FontSONG16_0061[  7] = { /* code 0061, LATIN SMALL LETTER A */
  _XXXX___,
  X____X__,
  __XXXX__,
  _X___X__,
  X____X__,
  X____X__,
  _XXXXXX_};

GUI_CONST_STORAGE unsigned char acGUI_FontSONG16_0062[ 12] = { /* code 0062, LATIN SMALL LETTER B */
  ________,
  XX______,
  _X______,
  _X______,
  _X______,
  _X_XX___,
  _XX__X__,
  _X____X_,
  _X____X_,
  _X____X_,
  _XX__X__,
  _X_XX___};

GUI_CONST_STORAGE unsigned char acGUI_FontSONG16_0063[  7] = { /* code 0063, LATIN SMALL LETTER C */
  __XXX___,
  _X___X__,
  X_______,
  X_______,
  X_______,
  _X___X__,
  __XXX___};

GUI_CONST_STORAGE unsigned char acGUI_FontSONG16_0064[ 12] = { /* code 0064, LATIN SMALL LETTER D */
  ________,
  ____XX__,
  _____X__,
  _____X__,
  _____X__,
  __XXXX__,
  _X___X__,
  X____X__,
  X____X__,
  X____X__,
  _X__XX__,
  __XX_XX_};

GUI_CONST_STORAGE unsigned char acGUI_FontSONG16_0065[  7] = { /* code 0065, LATIN SMALL LETTER E */
  _XXXX___,
  X____X__,
  XXXXXX__,
  X_______,
  X_______,
  X____X__,
  _XXXX___};

GUI_CONST_STORAGE unsigned char acGUI_FontSONG16_0066[ 11] = { /* code 0066, LATIN SMALL LETTER F */
  ___XXXX_,
  __X___X_,
  __X_____,
  __X_____,
  XXXXXX__,
  __X_____,
  __X_____,
  __X_____,
  __X_____,
  __X_____,
  XXXXX___};

GUI_CONST_STORAGE unsigned char acGUI_FontSONG16_0067[  9] = { /* code 0067, LATIN SMALL LETTER G */
  _XXXXX__,
  X___X___,
  X___X___,
  _XXX____,
  X_______,
  _XXXX___,
  X____X__,
  X____X__,
  _XXXX___};

GUI_CONST_STORAGE unsigned char acGUI_FontSONG16_0068[ 12] = { /* code 0068, LATIN SMALL LETTER H */
  ________,
  XX______,
  _X______,
  _X______,
  _X______,
  _X_XXX__,
  _XX___X_,
  _X____X_,
  _X____X_,
  _X____X_,
  _X____X_,
  XXX__XXX};

GUI_CONST_STORAGE unsigned char acGUI_FontSONG16_0069[ 11] = { /* code 0069, LATIN SMALL LETTER I */
  _XX_____,
  _XX_____,
  ________,
  ________,
  XXX_____,
  __X_____,
  __X_____,
  __X_____,
  __X_____,
  __X_____,
  XXXXX___};

GUI_CONST_STORAGE unsigned char acGUI_FontSONG16_006A[ 13] = { /* code 006A, LATIN SMALL LETTER J */
  ___XX___,
  ___XX___,
  ________,
  ________,
  __XXX___,
  ____X___,
  ____X___,
  ____X___,
  ____X___,
  ____X___,
  ____X___,
  X___X___,
  XXXX____};

GUI_CONST_STORAGE unsigned char acGUI_FontSONG16_006B[ 12] = { /* code 006B, LATIN SMALL LETTER K */
  ________,
  XX______,
  _X______,
  _X______,
  _X______,
  _X__XXX_,
  _X__X___,
  _X_X____,
  _XX_X___,
  _X__X___,
  _X___X__,
  XXX_XXX_};

GUI_CONST_STORAGE unsigned char acGUI_FontSONG16_006C[ 11] = { /* code 006C, LATIN SMALL LETTER L */
  XXX_____,
  __X_____,
  __X_____,
  __X_____,
  __X_____,
  __X_____,
  __X_____,
  __X_____,
  __X_____,
  __X_____,
  XXXXX___};

GUI_CONST_STORAGE unsigned char acGUI_FontSONG16_006D[  7] = { /* code 006D, LATIN SMALL LETTER M */
  XXXXXXX_,
  _X__X__X,
  _X__X__X,
  _X__X__X,
  _X__X__X,
  _X__X__X,
  XXX_XX_X};

GUI_CONST_STORAGE unsigned char acGUI_FontSONG16_006E[  7] = { /* code 006E, LATIN SMALL LETTER N */
  XX_XXX__,
  _XX___X_,
  _X____X_,
  _X____X_,
  _X____X_,
  _X____X_,
  XXX__XXX};

GUI_CONST_STORAGE unsigned char acGUI_FontSONG16_006F[  7] = { /* code 006F, LATIN SMALL LETTER O */
  _XXXX___,
  X____X__,
  X____X__,
  X____X__,
  X____X__,
  X____X__,
  _XXXX___};

GUI_CONST_STORAGE unsigned char acGUI_FontSONG16_0070[  9] = { /* code 0070, LATIN SMALL LETTER P */
  XX_XX___,
  _XX__X__,
  _X____X_,
  _X____X_,
  _X____X_,
  _X___X__,
  _XXXX___,
  _X______,
  XXX_____};

GUI_CONST_STORAGE unsigned char acGUI_FontSONG16_0071[  9] = { /* code 0071, LATIN SMALL LETTER Q */
  __XXXX__,
  _X___X__,
  X____X__,
  X____X__,
  X____X__,
  _X___X__,
  __XXXX__,
  _____X__,
  ____XXX_};

GUI_CONST_STORAGE unsigned char acGUI_FontSONG16_0072[  7] = { /* code 0072, LATIN SMALL LETTER R */
  XXX_XXX_,
  __XX__X_,
  __X_____,
  __X_____,
  __X_____,
  __X_____,
  XXXXX___};

GUI_CONST_STORAGE unsigned char acGUI_FontSONG16_0073[  7] = { /* code 0073, LATIN SMALL LETTER S */
  _XXXXX__,
  X____X__,
  X_______,
  _XXXX___,
  _____X__,
  X____X__,
  XXXXX___};

GUI_CONST_STORAGE unsigned char acGUI_FontSONG16_0074[  9] = { /* code 0074, LATIN SMALL LETTER T */
  __X_____,
  __X_____,
  XXXXX___,
  __X_____,
  __X_____,
  __X_____,
  __X_____,
  __X_____,
  ___XX___};

GUI_CONST_STORAGE unsigned char acGUI_FontSONG16_0075[  7] = { /* code 0075, LATIN SMALL LETTER U */
  XX___XX_,
  _X____X_,
  _X____X_,
  _X____X_,
  _X____X_,
  _X___XX_,
  __XXX_XX};

GUI_CONST_STORAGE unsigned char acGUI_FontSONG16_0076[  7] = { /* code 0076, LATIN SMALL LETTER V */
  XXX__XXX,
  _X____X_,
  __X__X__,
  __X__X__,
  __X_X___,
  ___X____,
  ___X____};

GUI_CONST_STORAGE unsigned char acGUI_FontSONG16_0077[  7] = { /* code 0077, LATIN SMALL LETTER W */
  XX_X_XXX,
  X__X__X_,
  X__X__X_,
  X_X_X_X_,
  X_X_X_X_,
  _X___X__,
  _X___X__};

GUI_CONST_STORAGE unsigned char acGUI_FontSONG16_0078[  7] = { /* code 0078, LATIN SMALL LETTER X */
  XX_XXX__,
  _X__X___,
  __XX____,
  __XX____,
  __XX____,
  _X__X___,
  XXX_XX__};

GUI_CONST_STORAGE unsigned char acGUI_FontSONG16_0079[  9] = { /* code 0079, LATIN SMALL LETTER Y */
  XXX__XXX,
  _X____X_,
  __X__X__,
  __X__X__,
  __X_X___,
  ___XX___,
  ___X____,
  ___X____,
  XXX_____};

GUI_CONST_STORAGE unsigned char acGUI_FontSONG16_007A[  7] = { /* code 007A, LATIN SMALL LETTER Z */
  XXXXXX__,
  X___X___,
  ___X____,
  __X_____,
  __X_____,
  _X___X__,
  XXXXXX__};

GUI_CONST_STORAGE unsigned char acGUI_FontSONG16_007B[ 14] = { /* code 007B, LEFT CURLY BRACKET */
  __XX____,
  _X______,
  _X______,
  _X______,
  _X______,
  _X______,
  X_______,
  _X______,
  _X______,
  _X______,
  _X______,
  _X______,
  _X______,
  __XX____};

GUI_CONST_STORAGE unsigned char acGUI_FontSONG16_007C[ 16] = { /* code 007C, VERTICAL LINE */
  X_______,
  X_______,
  X_______,
  X_______,
  X_______,
  X_______,
  X_______,
  X_______,
  X_______,
  X_______,
  X_______,
  X_______,
  X_______,
  X_______,
  X_______,
  X_______};

GUI_CONST_STORAGE unsigned char acGUI_FontSONG16_007D[ 14] = { /* code 007D, RIGHT CURLY BRACKET */
  XX______,
  __X_____,
  __X_____,
  __X_____,
  __X_____,
  __X_____,
  ___X____,
  __X_____,
  __X_____,
  __X_____,
  __X_____,
  __X_____,
  __X_____,
  XX______};

GUI_CONST_STORAGE unsigned char acGUI_FontSONG16_007E[  3] = { /* code 007E, TILDE */
  _XX____X,
  X__XX__X,
  X____XX_};

/* Start of unicode area <Basic Greek> */
GUI_CONST_STORAGE unsigned char acGUI_FontSONG16_03A9[ 22] = { /* code 03A9, GREEK CAPITAL LETTER OMEGA */
  ___XXXX_,________,
  __X____X,________,
  _X______,X_______,
  X_______,_X______,
  X_______,_X______,
  X_______,_X______,
  X_______,_X______,
  _X______,X_______,
  __X____X,________,
  X__X__X_,_X______,
  XXXX__XX,XX______};

/* Start of unicode area <CJK Unified Ideographs> */
GUI_CONST_STORAGE unsigned char acGUI_FontSONG16_4E0A[ 30] = { /* code 4E0A */
  ______X_,________,
  ______X_,________,
  ______X_,________,
  ______X_,________,
  ______X_,________,
  ______X_,________,
  ______XX,XXXXX___,
  ______X_,________,
  ______X_,________,
  ______X_,________,
  ______X_,________,
  ______X_,________,
  ______X_,________,
  ______X_,________,
  XXXXXXXX,XXXXXXX_};

GUI_CONST_STORAGE unsigned char acGUI_FontSONG16_4E0B[ 30] = { /* code 4E0B */
  XXXXXXXX,XXXXXXX_,
  ______X_,________,
  ______X_,________,
  ______X_,________,
  ______X_,________,
  ______X_,_X______,
  ______X_,__X_____,
  ______X_,___X____,
  ______X_,____X___,
  ______X_,____X___,
  ______X_,________,
  ______X_,________,
  ______X_,________,
  ______X_,________,
  ______X_,________};

GUI_CONST_STORAGE unsigned char acGUI_FontSONG16_4E2D[ 32] = { /* code 4E2D */
  _____X__,________,
  _____X__,________,
  _____X__,________,
  _____X__,________,
  XXXXXXXX,XXX_____,
  X____X__,__X_____,
  X____X__,__X_____,
  X____X__,__X_____,
  X____X__,__X_____,
  X____X__,__X_____,
  XXXXXXXX,XXX_____,
  X____X__,__X_____,
  _____X__,________,
  _____X__,________,
  _____X__,________,
  _____X__,________};

GUI_CONST_STORAGE unsigned char acGUI_FontSONG16_4EA7[ 32] = { /* code 4EA7 */
  ______X_,________,
  _______X,________,
  _XXXXXXX,XXXXXX__,
  ________,________,
  ____X___,__X_____,
  _____X__,__X_____,
  _____X__,_X______,
  __XXXXXX,XXXXXXX_,
  __X_____,________,
  __X_____,________,
  __X_____,________,
  __X_____,________,
  __X_____,________,
  _X______,________,
  _X______,________,
  X_______,________};

GUI_CONST_STORAGE unsigned char acGUI_FontSONG16_4EEA[ 32] = { /* code 4EEA */
  ____X___,X_______,
  ____X___,_X__X___,
  ____X_X_,_X__X___,
  ___X__X_,____X___,
  ___X__X_,____X___,
  __XX___X,___X____,
  __XX___X,___X____,
  _X_X___X,___X____,
  X__X____,X_X_____,
  ___X____,X_X_____,
  ___X____,_X______,
  ___X____,_X______,
  ___X____,X_X_____,
  ___X___X,___X____,
  ___X__X_,____X___,
  ___X_X__,_____XX_};

GUI_CONST_STORAGE unsigned char acGUI_FontSONG16_4EF6[ 32] = { /* code 4EF6 */
  ____X___,__X_____,
  ____X___,__X_____,
  ____X__X,__X_____,
  ___X___X,__X_____,
  ___X___X,XXXXXX__,
  __XX__X_,__X_____,
  __XX__X_,__X_____,
  _X_X_X__,__X_____,
  X__X____,__X_____,
  ___X_XXX,XXXXXXX_,
  ___X____,__X_____,
  ___X____,__X_____,
  ___X____,__X_____,
  ___X____,__X_____,
  ___X____,__X_____,
  ___X____,__X_____};

GUI_CONST_STORAGE unsigned char acGUI_FontSONG16_4FE1[ 32] = { /* code 4FE1 */
  ____X___,_X______,
  ____X___,__X_____,
  ____X_XX,XXXXXXX_,
  ___X____,________,
  ___X____,________,
  __XX___X,XXXXXX__,
  __XX____,________,
  _X_X____,________,
  X__X___X,XXXXXX__,
  ___X____,________,
  ___X____,________,
  ___X___X,XXXXXX__,
  ___X___X,_____X__,
  ___X___X,_____X__,
  ___X___X,XXXXXX__,
  ___X___X,_____X__};

GUI_CONST_STORAGE unsigned char acGUI_FontSONG16_5145[ 32] = { /* code 5145 */
  ______X_,________,
  _______X,________,
  XXXXXXXX,XXXXXXX_,
  _____X__,________,
  _____X__,________,
  ____X___,__X_____,
  ___X____,___X____,
  __XXXXXX,XXXXX___,
  _____X__,_X__X___,
  _____X__,_X______,
  _____X__,_X______,
  _____X__,_X______,
  ____X___,_X___X__,
  ____X___,_X___X__,
  ___X____,_X___X__,
  _XX_____,__XXXX__};

GUI_CONST_STORAGE unsigned char acGUI_FontSONG16_5173[ 32] = { /* code 5173 */
  ___X____,___X____,
  ____X___,___X____,
  ____X___,__X_____,
  ________,________,
  __XXXXXX,XXXXX___,
  _______X,________,
  _______X,________,
  _______X,________,
  XXXXXXXX,XXXXXXX_,
  _______X,________,
  ______X_,X_______,
  ______X_,X_______,
  _____X__,_X______,
  ____X___,__X_____,
  __XX____,___XX___,
  XX______,_____XX_};

GUI_CONST_STORAGE unsigned char acGUI_FontSONG16_5185[ 32] = { /* code 5185 */
  ______X_,________,
  ______X_,________,
  ______X_,________,
  XXXXXXXX,XXXXX___,
  X_____X_,____X___,
  X_____X_,____X___,
  X_____X_,____X___,
  X____X_X,____X___,
  X____X__,X___X___,
  X___X___,_X__X___,
  X__X____,__X_X___,
  X_X_____,__X_X___,
  X_______,____X___,
  X_______,____X___,
  X_______,__X_X___,
  X_______,___X____};

GUI_CONST_STORAGE unsigned char acGUI_FontSONG16_51FA[ 32] = { /* code 51FA */
  ______X_,________,
  ______X_,________,
  _X____X_,___X____,
  _X____X_,___X____,
  _X____X_,___X____,
  _X____X_,___X____,
  _XXXXXXX,XXXX____,
  ______X_,___X____,
  ______X_,________,
  ______X_,________,
  X_____X_,____X___,
  X_____X_,____X___,
  X_____X_,____X___,
  X_____X_,____X___,
  XXXXXXXX,XXXXX___,
  ________,____X___};

GUI_CONST_STORAGE unsigned char acGUI_FontSONG16_5206[ 32] = { /* code 5206 */
  ________,_X______,
  _____X__,_X______,
  _____X__,__X_____,
  ____X___,__X_____,
  ___X____,___X____,
  __X_____,____X___,
  _X______,_____X__,
  X__XXXXX,XXX___X_,
  _____X__,__X_____,
  _____X__,__X_____,
  _____X__,__X_____,
  ____X___,__X_____,
  ____X___,__X_____,
  ___X____,__X_____,
  __X____X,_X______,
  _X______,X_______};

GUI_CONST_STORAGE unsigned char acGUI_FontSONG16_5236[ 32] = { /* code 5236 */
  _____X__,_____X__,
  __X__X__,_____X__,
  __X__X__,_____X__,
  __XXXXXX,X_X__X__,
  _X___X__,__X__X__,
  _____X__,__X__X__,
  XXXXXXXX,XXX__X__,
  _____X__,__X__X__,
  _____X__,__X__X__,
  __XXXXXX,X_X__X__,
  __X__X__,X_X__X__,
  __X__X__,X_X__X__,
  __X__XX_,X____X__,
  __X__X_X,_____X__,
  _____X__,___X_X__,
  _____X__,____X___};

GUI_CONST_STORAGE unsigned char acGUI_FontSONG16_538B[ 30] = { /* code 538B */
  __XXXXXX,XXXXXXX_,
  __X_____,________,
  __X_____,X_______,
  __X_____,X_______,
  __X_____,X_______,
  __X_____,X_______,
  __X_XXXX,XXXXXX__,
  __X_____,X_______,
  __X_____,X_______,
  __X_____,X__X____,
  __X_____,X___X___,
  __X_____,X___X___,
  _X______,X_______,
  _X_XXXXX,XXXXXXX_,
  X_______,________};

GUI_CONST_STORAGE unsigned char acGUI_FontSONG16_53F7[ 30] = { /* code 53F7 */
  ___XXXXX,XXXX____,
  ___X____,___X____,
  ___X____,___X____,
  ___X____,___X____,
  ___XXXXX,XXXX____,
  ________,________,
  XXXXXXXX,XXXXXXX_,
  ____X___,________,
  ___X____,________,
  ___XXXXX,XXXX____,
  ________,___X____,
  ________,___X____,
  ________,___X____,
  ________,X_X_____,
  ________,_X______};

GUI_CONST_STORAGE unsigned char acGUI_FontSONG16_5668[ 30] = { /* code 5668 */
  __XXXXX_,_XXXXX__,
  __X___X_,_X___X__,
  __X___X_,_X___X__,
  __XXXXX_,_XXXXX__,
  _______X,__X_____,
  _______X,___X____,
  XXXXXXXX,XXXXXXX_,
  ______X_,X_______,
  ____XX__,_XX_____,
  __XX____,___XX___,
  XX______,_____XX_,
  __XXXXX_,_XXXXX__,
  __X___X_,_X___X__,
  __X___X_,_X___X__,
  __XXXXX_,_XXXXX__};

GUI_CONST_STORAGE unsigned char acGUI_FontSONG16_56FE[ 30] = { /* code 56FE */
  XXXXXXXX,XXXXX___,
  X____X__,____X___,
  X____X__,____X___,
  X___XXXX,XX__X___,
  X__XX___,X___X___,
  X_X__X_X,____X___,
  X_____X_,____X___,
  X___XX_X,X___X___,
  XXXX____,_XXXX___,
  X____XX_,____X___,
  X______X,____X___,
  X___XX__,____X___,
  X_____XX,____X___,
  XXXXXXXX,XXXXX___,
  X_______,____X___};

GUI_CONST_STORAGE unsigned char acGUI_FontSONG16_5728[ 32] = { /* code 5728 */
  ______X_,________,
  ______X_,________,
  _____X__,________,
  XXXXXXXX,XXXXXXX_,
  ____X___,________,
  ____X___,_X______,
  ___X____,_X______,
  __XX____,_X______,
  _X_X_XXX,XXXXXX__,
  X__X____,_X______,
  ___X____,_X______,
  ___X____,_X______,
  ___X____,_X______,
  ___X____,_X______,
  ___XXXXX,XXXXXXX_,
  ___X____,________};

GUI_CONST_STORAGE unsigned char acGUI_FontSONG16_578B[ 30] = { /* code 578B */
  ________,_____X__,
  _XXXXXXX,X____X__,
  ___X__X_,__X__X__,
  ___X__X_,__X__X__,
  ___X__X_,__X__X__,
  XXXXXXXX,X_X__X__,
  ___X__X_,__X__X__,
  __X___X_,_____X__,
  __X___X_,___X_X__,
  _X_____X,____X___,
  X______X,________,
  __XXXXXX,XXXXX___,
  _______X,________,
  _______X,________,
  XXXXXXXX,XXXXXXX_};

GUI_CONST_STORAGE unsigned char acGUI_FontSONG16_58F0[ 32] = { /* code 58F0 */
  _______X,________,
  _______X,________,
  XXXXXXXX,XXXXXXX_,
  _______X,________,
  _XXXXXXX,XXXXXX__,
  ________,________,
  __XXXXXX,XXXXX___,
  __X____X,____X___,
  __X____X,____X___,
  __XXXXXX,XXXXX___,
  __X_____,________,
  __X_____,________,
  __X_____,________,
  _X______,________,
  _X______,________,
  X_______,________};

GUI_CONST_STORAGE unsigned char acGUI_FontSONG16_59CB[ 32] = { /* code 59CB */
  ___X____,__X_____,
  ___X____,__X_____,
  ___X____,__X_____,
  ___X____,_X______,
  XXXXXX__,_X__X___,
  __X__X__,X____X__,
  __X__X_X,XXXXXXX_,
  __X__X__,X_____X_,
  __X__X__,________,
  _X__X___,XXXXXX__,
  __X_X___,X____X__,
  ___X____,X____X__,
  __X_X___,X____X__,
  _X___X__,X____X__,
  X_______,XXXXXX__,
  ________,X____X__};

GUI_CONST_STORAGE unsigned char acGUI_FontSONG16_5C0F[ 32] = { /* code 5C0F */
  _______X,________,
  _______X,________,
  _______X,________,
  _______X,________,
  _______X,________,
  ___X___X,___X____,
  ___X___X,____X___,
  ___X___X,_____X__,
  __X____X,_____X__,
  __X____X,______X_,
  _X_____X,______X_,
  X______X,______X_,
  _______X,________,
  _______X,________,
  _____X_X,________,
  ______X_,________};

GUI_CONST_STORAGE unsigned char acGUI_FontSONG16_5F00[ 30] = { /* code 5F00 */
  _XXXXXXX,XXXXXX__,
  ____X___,__X_____,
  ____X___,__X_____,
  ____X___,__X_____,
  ____X___,__X_____,
  ____X___,__X_____,
  XXXXXXXX,XXXXXXX_,
  ____X___,__X_____,
  ____X___,__X_____,
  ____X___,__X_____,
  ____X___,__X_____,
  ___X____,__X_____,
  ___X____,__X_____,
  __X_____,__X_____,
  _X______,__X_____};

GUI_CONST_STORAGE unsigned char acGUI_FontSONG16_5FAA[ 32] = { /* code 5FAA */
  ___X____,__XXXX__,
  ___X_XXX,XXX_____,
  __X__X__,__X_____,
  _X___X__,__X_____,
  X__X_XXX,XXXXXXX_,
  ___X_X__,__X_____,
  __X__X_X,XXXXXX__,
  _XX__X_X,_____X__,
  X_X__X_X,_____X__,
  __X__X_X,XXXXXX__,
  __X__X_X,_____X__,
  __X__X_X,XXXXXX__,
  __X_X__X,_____X__,
  __X_X__X,_____X__,
  __XX___X,XXXXXX__,
  __X____X,_____X__};

GUI_CONST_STORAGE unsigned char acGUI_FontSONG16_606F[ 30] = { /* code 606F */
  _______X,________,
  ______X_,________,
  ___XXXXX,XXXX____,
  ___X____,___X____,
  ___XXXXX,XXXX____,
  ___X____,___X____,
  ___XXXXX,XXXX____,
  ___X____,___X____,
  ___XXXXX,XXXX____,
  ___X____,___X____,
  _______X,________,
  ____X___,X____X__,
  _X__X___,X__X__X_,
  _X__X___,___X__X_,
  X____XXX,XXXX____};

GUI_CONST_STORAGE unsigned char acGUI_FontSONG16_622A[ 32] = { /* code 622A */
  ____X___,__X_____,
  ____X___,__X_X___,
  _XXXXXXX,__X__X__,
  ____X___,__X_____,
  XXXXXXXX,XXXXXXX_,
  ___X_X__,__X_____,
  __X___X_,__X__X__,
  _XXXXXXX,X_X__X__,
  X_X__X__,__X__X__,
  __XXXXXX,__X_X___,
  __X__X__,__X_X___,
  __XXXXXX,___X____,
  __X__X__,___X__X_,
  __XXXXXX,X_X_X_X_,
  __X_____,_X___XX_,
  __X_____,X_____X_};

GUI_CONST_STORAGE unsigned char acGUI_FontSONG16_62A5[ 32] = { /* code 62A5 */
  ___X____,________,
  ___X___X,XXXXXX__,
  ___X___X,_____X__,
  ___X___X,_____X__,
  XXXXXX_X,___X_X__,
  ___X___X,____X___,
  ___X___X,________,
  ___X_X_X,XXXXXX__,
  ___XX__X,_X___X__,
  __XX___X,_X___X__,
  XX_X___X,__X_X___,
  ___X___X,__X_X___,
  ___X___X,___X____,
  ___X___X,__X_X___,
  _X_X___X,_X___X__,
  __X____X,X_____X_};

GUI_CONST_STORAGE unsigned char acGUI_FontSONG16_63A7[ 32] = { /* code 63A7 */
  ___X____,_X______,
  ___X____,__X_____,
  ___X____,__X_____,
  ___X__XX,XXXXXXX_,
  XXXXX_X_,______X_,
  ___X_X__,X__X_X__,
  ___X___X,____X___,
  ___XX_X_,_____X__,
  __XX____,________,
  XX_X___X,XXXXXX__,
  ___X____,__X_____,
  ___X____,__X_____,
  ___X____,__X_____,
  ___X____,__X_____,
  _X_X_XXX,XXXXXXX_,
  __X_____,________};

GUI_CONST_STORAGE unsigned char acGUI_FontSONG16_653E[ 32] = { /* code 653E */
  __X_____,_X______,
  ___X____,_X______,
  ________,_X______,
  XXXXXXX_,X_______,
  __X_____,XXXXXXX_,
  __X____X,____X___,
  __XXXXX_,X___X___,
  __X__X__,X___X___,
  __X__X__,X___X___,
  __X__X__,_X_X____,
  __X__X__,_X_X____,
  __X__X__,__X_____,
  _X___X__,_X_X____,
  _X_X_X__,X___X___,
  X___X__X,_____X__,
  ______X_,______X_};

GUI_CONST_STORAGE unsigned char acGUI_FontSONG16_6570[ 32] = { /* code 6570 */
  ____X___,__X_____,
  _X__X__X,__X_____,
  __X_X_X_,__X_____,
  ____X___,__XXXXX_,
  XXXXXXXX,_X___X__,
  __X_X_X_,_X___X__,
  _X__X__X,_X___X__,
  X___X___,X_X__X__,
  ___X____,__X_X___,
  XXXXXXX_,__X_X___,
  __X___X_,___X____,
  _X____X_,___X____,
  _XX__X__,__X_X___,
  ___XX___,__X_X___,
  __XX_X__,_X___X__,
  XX____X_,X_____X_};

GUI_CONST_STORAGE unsigned char acGUI_FontSONG16_6587[ 32] = { /* code 6587 */
  ______X_,________,
  _______X,________,
  _______X,________,
  XXXXXXXX,XXXXXXX_,
  ___X____,___X____,
  ___X____,___X____,
  ____X___,__X_____,
  ____X___,__X_____,
  _____X__,_X______,
  ______X_,X_______,
  _______X,________,
  ______X_,X_______,
  _____X__,_X______,
  ____X___,__X_____,
  __XX____,___XX___,
  XX______,_____XX_};

GUI_CONST_STORAGE unsigned char acGUI_FontSONG16_65E5[ 30] = { /* code 65E5 */
  XXXXXXXX,X_______,
  X_______,X_______,
  X_______,X_______,
  X_______,X_______,
  X_______,X_______,
  X_______,X_______,
  XXXXXXXX,X_______,
  X_______,X_______,
  X_______,X_______,
  X_______,X_______,
  X_______,X_______,
  X_______,X_______,
  X_______,X_______,
  XXXXXXXX,X_______,
  X_______,X_______};

GUI_CONST_STORAGE unsigned char acGUI_FontSONG16_65F6[ 32] = { /* code 65F6 */
  ________,___X____,
  ________,___X____,
  XXXXX___,___X____,
  X___X___,___X____,
  X___X_XX,XXXXXX__,
  X___X___,___X____,
  X___X___,___X____,
  XXXXX___,___X____,
  X___X__X,___X____,
  X___X___,X__X____,
  X___X___,X__X____,
  X___X___,___X____,
  XXXXX___,___X____,
  X___X___,___X____,
  ________,_X_X____,
  ________,__X_____};

GUI_CONST_STORAGE unsigned char acGUI_FontSONG16_662F[ 32] = { /* code 662F */
  ___XXXXX,XXXX____,
  ___X____,___X____,
  ___X____,___X____,
  ___XXXXX,XXXX____,
  ___X____,___X____,
  ___X____,___X____,
  ___XXXXX,XXXX____,
  ________,________,
  XXXXXXXX,XXXXXXX_,
  _______X,________,
  ___X___X,________,
  ___X___X,XXXXX___,
  ___X___X,________,
  __X_X__X,________,
  _X___X_X,________,
  X_____XX,XXXXXXX_};

GUI_CONST_STORAGE unsigned char acGUI_FontSONG16_66F2[ 32] = { /* code 66F2 */
  ____X___,X_______,
  ____X___,X_______,
  ____X___,X_______,
  ____X___,X_______,
  XXXXXXXX,XXXXX___,
  X___X___,X___X___,
  X___X___,X___X___,
  X___X___,X___X___,
  X___X___,X___X___,
  XXXXXXXX,XXXXX___,
  X___X___,X___X___,
  X___X___,X___X___,
  X___X___,X___X___,
  X___X___,X___X___,
  XXXXXXXX,XXXXX___,
  X_______,____X___};

GUI_CONST_STORAGE unsigned char acGUI_FontSONG16_671F[ 32] = { /* code 671F */
  __X___X_,________,
  __X___X_,_XXXXX__,
  _XXXXXXX,_X___X__,
  __X___X_,_X___X__,
  __X___X_,_X___X__,
  __XXXXX_,_XXXXX__,
  __X___X_,_X___X__,
  __X___X_,_X___X__,
  __XXXXX_,_X___X__,
  __X___X_,_XXXXX__,
  __X___X_,_X___X__,
  XXXXXXXX,_X___X__,
  _____X__,X____X__,
  __X___X_,X____X__,
  _X_____X,___X_X__,
  X_____X_,____X___};

GUI_CONST_STORAGE unsigned char acGUI_FontSONG16_672A[ 32] = { /* code 672A */
  _______X,________,
  _______X,________,
  _______X,________,
  __XXXXXX,XXXXX___,
  _______X,________,
  _______X,________,
  _______X,________,
  XXXXXXXX,XXXXXXX_,
  ______XX,X_______,
  _____X_X,_X______,
  ____X__X,__X_____,
  ___X___X,___X____,
  __X____X,____X___,
  XX_____X,_____XX_,
  _______X,________,
  _______X,________};

GUI_CONST_STORAGE unsigned char acGUI_FontSONG16_672C[ 32] = { /* code 672C */
  _______X,________,
  _______X,________,
  _______X,________,
  _______X,________,
  _XXXXXXX,XXXXXX__,
  ______XX,X_______,
  _____X_X,_X______,
  _____X_X,_X______,
  ____X__X,__X_____,
  ___X___X,___X____,
  __X____X,____X___,
  _X__XXXX,XXX__X__,
  X______X,______X_,
  _______X,________,
  _______X,________,
  _______X,________};

GUI_CONST_STORAGE unsigned char acGUI_FontSONG16_69DB[ 32] = { /* code 69DB */
  ___X____,_X__X___,
  ___X___X,_X__X___,
  ___X___X,_X__XXX_,
  ___X___X,_X_X____,
  XXXXXX_X,_XX_X___,
  ___X___X,_X___X__,
  __XX___X,_X___X__,
  __XXX___,_X______,
  _X_X_X__,________,
  _X_X_X_X,XXXXXX__,
  X__X___X,_X_X_X__,
  ___X___X,_X_X_X__,
  ___X___X,_X_X_X__,
  ___X___X,_X_X_X__,
  ___X_XXX,XXXXXXX_,
  ___X____,________};

GUI_CONST_STORAGE unsigned char acGUI_FontSONG16_6B21[ 32] = { /* code 6B21 */
  ________,X_______,
  _X______,X_______,
  __X_____,X_______,
  __X_____,XXXXXX__,
  _______X,_____X__,
  ____X__X,____X___,
  ____X_X_,_X______,
  ___X_X__,_X______,
  ___X____,_X______,
  XXX_____,X_X_____,
  __X_____,X_X_____,
  __X____X,___X____,
  __X____X,___X____,
  __X___X_,____X___,
  __X__X__,_____X__,
  ____X___,______X_};

GUI_CONST_STORAGE unsigned char acGUI_FontSONG16_6B62[ 30] = { /* code 6B62 */
  _______X,________,
  _______X,________,
  _______X,________,
  _______X,________,
  ___X___X,________,
  ___X___X,________,
  ___X___X,XXXXX___,
  ___X___X,________,
  ___X___X,________,
  ___X___X,________,
  ___X___X,________,
  ___X___X,________,
  ___X___X,________,
  ___X___X,________,
  XXXXXXXX,XXXXXXX_};

GUI_CONST_STORAGE unsigned char acGUI_FontSONG16_6B63[ 28] = { /* code 6B63 */
  _XXXXXXX,XXXXXX__,
  _______X,________,
  _______X,________,
  _______X,________,
  _______X,________,
  ___X___X,________,
  ___X___X,XXXXX___,
  ___X___X,________,
  ___X___X,________,
  ___X___X,________,
  ___X___X,________,
  ___X___X,________,
  ___X___X,________,
  XXXXXXXX,XXXXXXX_};

GUI_CONST_STORAGE unsigned char acGUI_FontSONG16_6B65[ 32] = { /* code 6B65 */
  _______X,________,
  _______X,________,
  ___X___X,XXXXX___,
  ___X___X,________,
  ___X___X,________,
  ___X___X,________,
  XXXXXXXX,XXXXXXX_,
  _______X,________,
  _______X,________,
  ___X___X,____X___,
  ___X___X,___X____,
  __X____X,__X_____,
  _X______,XX______,
  ______XX,________,
  ___XXX__,________,
  XXX_____,________};

GUI_CONST_STORAGE unsigned char acGUI_FontSONG16_6C22[ 32] = { /* code 6C22 */
  __X_____,________,
  __XXXXXX,XXXXXX__,
  _X______,________,
  X__XXXXX,XXXX____,
  ________,________,
  _XXXXXXX,XXXX____,
  ________,___X____,
  __XXXXXX,XX_X____,
  ______XX,___X____,
  ____XX__,XX_X____,
  _XXX____,__XX____,
  ___XXXXX,XX_X__X_,
  ______X_,____X_X_,
  ______X_,____X_X_,
  _XXXXXXX,XXXX_XX_,
  ________,______X_};

GUI_CONST_STORAGE unsigned char acGUI_FontSONG16_6C60[ 30] = { /* code 6C60 */
  ________,_X______,
  __X_____,_X______,
  ___X__X_,_X______,
  ___X__X_,_X_XX___,
  X_____X_,_XX_X___,
  _X____X_,XX__X___,
  _X_X__XX,_X__X___,
  ___XXXX_,_X__X___,
  ___X__X_,_X__X___,
  __X___X_,_X__X___,
  XXX___X_,_X_XX___,
  __X___X_,_X____X_,
  __X___X_,______X_,
  __X___X_,______X_,
  __X____X,XXXXXXX_};

GUI_CONST_STORAGE unsigned char acGUI_FontSONG16_6D41[ 32] = { /* code 6D41 */
  ________,X_______,
  __X_____,_X______,
  ___X_XXX,XXXXXXX_,
  ___X____,X_______,
  X______X,___X____,
  _X____X_,____X___,
  _X___XXX,XXXXXX__,
  ___X____,_____X__,
  ___X____,________,
  __X___X_,_X__X___,
  XXX___X_,_X__X___,
  __X___X_,_X__X___,
  __X___X_,_X__X___,
  __X___X_,_X__X_X_,
  __X__X__,_X__X_X_,
  ____X___,_X___XX_};

GUI_CONST_STORAGE unsigned char acGUI_FontSONG16_6D4B[ 32] = { /* code 6D4B */
  ________,_____X__,
  __X__XXX,XX___X__,
  ___X_X__,_X___X__,
  ___X_X__,_X_X_X__,
  X____X_X,_X_X_X__,
  _X___X_X,_X_X_X__,
  _X___X_X,_X_X_X__,
  ___X_X_X,_X_X_X__,
  ___X_X_X,_X_X_X__,
  __X__X_X,_X_X_X__,
  XXX__X_X,_X_X_X__,
  __X____X,_____X__,
  __X___X_,X____X__,
  __X___X_,_X___X__,
  __X__X__,___X_X__,
  ____X___,____X___};

GUI_CONST_STORAGE unsigned char acGUI_FontSONG16_6E90[ 30] = { /* code 6E90 */
  __X__XXX,XXXXXXX_,
  ___X_X__,__X_____,
  ___X_X__,_X______,
  X____X_X,XXXXXX__,
  _X___X_X,_____X__,
  _X___X_X,XXXXXX__,
  ___X_X_X,_____X__,
  ___X_X_X,XXXXXX__,
  __X__X_X,__X__X__,
  XXX__X__,__X_____,
  __X__X__,X_X_X___,
  __X_X__X,__X__X__,
  __X_X_X_,__X___X_,
  __XX____,X_X_____,
  ________,_X______};

GUI_CONST_STORAGE unsigned char acGUI_FontSONG16_7248[ 32] = { /* code 7248 */
  ____X___,____X___,
  _X__X___,___XXX__,
  _X__X__X,XXX_____,
  _X__X__X,________,
  _X__X__X,________,
  _XXXXX_X,XXXXXX__,
  _X_____X,_X___X__,
  _X_____X,_X___X__,
  _XXXX__X,_X___X__,
  _X__X__X,__X_X___,
  _X__X__X,__X_X___,
  _X__X__X,___X____,
  _X__X__X,___X____,
  _X__X_X_,__X_X___,
  _X__X_X_,_X___X__,
  X___XX__,X_____X_};

GUI_CONST_STORAGE unsigned char acGUI_FontSONG16_73AF[ 28] = { /* code 73AF */
  XXXXXX_X,XXXXXXX_,
  ___X____,___X____,
  ___X____,___X____,
  ___X____,__X_____,
  ___X____,__X_____,
  _XXXXX__,_XX_X___,
  ___X____,X_X__X__,
  ___X___X,__X___X_,
  ___X__X_,__X___X_,
  ___X____,__X_____,
  ___XXX__,__X_____,
  XXX_____,__X_____,
  _X______,__X_____,
  ________,__X_____};

GUI_CONST_STORAGE unsigned char acGUI_FontSONG16_751F[ 30] = { /* code 751F */
  _______X,________,
  ___X___X,________,
  ___X___X,________,
  ___X___X,________,
  __XXXXXX,XXXXXX__,
  __X____X,________,
  _X_____X,________,
  X______X,________,
  _______X,________,
  __XXXXXX,XXXXX___,
  _______X,________,
  _______X,________,
  _______X,________,
  _______X,________,
  XXXXXXXX,XXXXXXX_};

GUI_CONST_STORAGE unsigned char acGUI_FontSONG16_7535[ 32] = { /* code 7535 */
  _____X__,________,
  _____X__,________,
  _____X__,________,
  XXXXXXXX,XXX_____,
  X____X__,__X_____,
  X____X__,__X_____,
  X____X__,__X_____,
  XXXXXXXX,XXX_____,
  X____X__,__X_____,
  X____X__,__X_____,
  X____X__,__X_____,
  XXXXXXXX,XXX_____,
  X____X__,__X_X___,
  _____X__,____X___,
  _____X__,____X___,
  ______XX,XXXXX___};

GUI_CONST_STORAGE unsigned char acGUI_FontSONG16_77ED[ 32] = { /* code 77ED */
  __X_____,________,
  __X____X,XXXXXXX_,
  __XXXX__,________,
  _X_X____,________,
  X__X____,XXXXXX__,
  ___X____,X____X__,
  ___X____,X____X__,
  XXXXXXX_,X____X__,
  ___X____,XXXXXX__,
  ___X____,________,
  ___X____,X____X__,
  __X_X___,_X___X__,
  __X__X__,_X__X___,
  _X___X__,________,
  _X_____X,XXXXXXX_,
  X_______,________};

GUI_CONST_STORAGE unsigned char acGUI_FontSONG16_786C[ 30] = { /* code 786C */
  _______X,XXXXXXX_,
  XXXXXX__,__X_____,
  ___X____,__X_____,
  ___X___X,XXXXXX__,
  __X____X,__X__X__,
  __XXXX_X,__X__X__,
  _XX__X_X,XXXXXX__,
  _XX__X_X,__X__X__,
  X_X__X_X,__X__X__,
  __X__X_X,XXXXXX__,
  __X__X_X,__X_____,
  __XXXX__,X_X_____,
  __X__X__,_X______,
  __X_____,X_XX____,
  ______XX,____XXX_};

GUI_CONST_STORAGE unsigned char acGUI_FontSONG16_7A0B[ 32] = { /* code 7A0B */
  ____X___,________,
  ___XXX_X,XXXXXX__,
  XXXX___X,_____X__,
  ___X___X,_____X__,
  ___X___X,_____X__,
  XXXXXX_X,XXXXXX__,
  ___X____,________,
  __XX____,________,
  __XXX__X,XXXXXXX_,
  _X_X_X__,__X_____,
  _X_X_X__,__X_____,
  X__X___X,XXXXXX__,
  ___X____,__X_____,
  ___X____,__X_____,
  ___X__XX,XXXXXXX_,
  ___X____,________};

GUI_CONST_STORAGE unsigned char acGUI_FontSONG16_7C7B[ 32] = { /* code 7C7B */
  _______X,________,
  ___X___X,___X____,
  ____X__X,__X_____,
  _______X,________,
  _XXXXXXX,XXXXXX__,
  _____X_X,_X______,
  ____X__X,__X_____,
  ___X___X,___X____,
  _XX_____,____X___,
  _______X,________,
  XXXXXXXX,XXXXXXX_,
  ______X_,X_______,
  _____X__,_X______,
  ____X___,__X_____,
  __XX____,___XX___,
  XX______,_____XX_};

GUI_CONST_STORAGE unsigned char acGUI_FontSONG16_7CFB[ 32] = { /* code 7CFB */
  _______X,XXXX____,
  _XXXXXX_,________,
  ____X___,________,
  ___X____,_X______,
  __X_____,X_______,
  _XXXXXXX,________,
  ______X_,________,
  ____XX__,__X_____,
  __XX____,___X____,
  XXXXXXXX,XXXXX___,
  ______X_,____X___,
  ___X__X_,_X______,
  __X___X_,__X_____,
  _X____X_,___X____,
  X___X_X_,____X___,
  _____X__,________};

GUI_CONST_STORAGE unsigned char acGUI_FontSONG16_7EBF[ 32] = { /* code 7EBF */
  ___X____,_X_X____,
  ___X____,_X__X___,
  __X_____,_X______,
  __X__X__,_X_XXX__,
  _X___X_X,XXX_____,
  XXXXX___,_X______,
  ___X____,_X_XXXX_,
  __X___XX,XXX_____,
  _X______,_X___X__,
  XXXXXX__,_X__X___,
  _X______,__XX____,
  ________,__X___X_,
  ___XXX__,_X_X__X_,
  XXX_____,X___X_X_,
  _X____XX,_____XX_,
  ________,______X_};

GUI_CONST_STORAGE unsigned char acGUI_FontSONG16_7EDF[ 32] = { /* code 7EDF */
  ___X____,_X______,
  ___X____,__X_____,
  __X_____,__X_____,
  __X___XX,XXXXXXX_,
  _X__X___,_X______,
  XXXXX___,X___X___,
  ___X___X,_____X__,
  __X___XX,XXXXXXX_,
  _X______,X__X__X_,
  XXXXX___,X__X____,
  _X______,X__X____,
  ________,X__X____,
  ___XX__X,___X__X_,
  XXX____X,___X__X_,
  _X____X_,____XXX_,
  _____X__,________};

GUI_CONST_STORAGE unsigned char acGUI_FontSONG16_7F16[ 32] = { /* code 7F16 */
  ___X____,X_______,
  ___X____,_X______,
  __X___XX,XXXXXX__,
  __X___X_,_____X__,
  _X__X_X_,_____X__,
  XXXXX_XX,XXXXXX__,
  ___X__X_,________,
  __X___X_,________,
  _X____XX,XXXXXX__,
  XXXXX_XX,_X_X_X__,
  _X____XX,_X_X_X__,
  _____X_X,XXXXXX__,
  ___XXX_X,_X_X_X__,
  XXX__X_X,_X_X_X__,
  _X__X__X,_X___X__,
  _______X,____XX__};

GUI_CONST_STORAGE unsigned char acGUI_FontSONG16_7F6E[ 30] = { /* code 7F6E */
  _XXXXXXX,XXXXXX__,
  _X___X__,_X___X__,
  _XXXXXXX,XXXXXX__,
  _______X,________,
  _XXXXXXX,XXXXXX__,
  _______X,________,
  ___XXXXX,XXXX____,
  ___X____,___X____,
  ___XXXXX,XXXX____,
  ___X____,___X____,
  ___XXXXX,XXXX____,
  ___X____,___X____,
  ___XXXXX,XXXX____,
  ___X____,___X____,
  XXXXXXXX,XXXXXXX_};

GUI_CONST_STORAGE unsigned char acGUI_FontSONG16_8A00[ 32] = { /* code 8A00 */
  ______X_,________,
  _______X,________,
  XXXXXXXX,XXXXXXX_,
  ________,________,
  ________,________,
  __XXXXXX,XXXXX___,
  ________,________,
  ________,________,
  __XXXXXX,XXXXX___,
  ________,________,
  ________,________,
  __XXXXXX,XXXXX___,
  __X_____,____X___,
  __X_____,____X___,
  __XXXXXX,XXXXX___,
  __X_____,____X___};

GUI_CONST_STORAGE unsigned char acGUI_FontSONG16_8B66[ 32] = { /* code 8B66 */
  __X__X__,__X_____,
  XXXXXXXX,__X_____,
  __X__X__,_XXXXXX_,
  _XXXXXX_,XX___X__,
  X_____X_,__X_X___,
  _XXXX_X_,___X____,
  _X__X_X_,__X_X___,
  _XXXX_X_,XX___XX_,
  _____X_X,________,
  XXXXXXXX,XXXXXXX_,
  ________,________,
  __XXXXXX,XXXXX___,
  ________,________,
  __XXXXXX,XXXXX___,
  __X_____,____X___,
  __XXXXXX,XXXXX___};

GUI_CONST_STORAGE unsigned char acGUI_FontSONG16_8BBE[ 30] = { /* code 8BBE */
  __X____X,XXXX____,
  ___X___X,___X____,
  ___X___X,___X____,
  _______X,___X____,
  ______X_,____XXX_,
  XXXX_X__,________,
  ___X__XX,XXXXX___,
  ___X___X,____X___,
  ___X___X,___X____,
  ___X____,X__X____,
  ___X_X__,X_X_____,
  ___XX___,_X______,
  ___X____,X_X_____,
  ______XX,___XX___,
  ____XX__,_____XX_};

GUI_CONST_STORAGE unsigned char acGUI_FontSONG16_8BD5[ 32] = { /* code 8BD5 */
  ________,__X_X___,
  __X_____,__X__X__,
  ___X____,__X__X__,
  ___X____,__X_____,
  _____XXX,XXXXXXX_,
  ________,__X_____,
  XXXX____,__X_____,
  ___X_XXX,XXX_____,
  ___X___X,__X_____,
  ___X___X,___X____,
  ___X___X,___X____,
  ___X_X_X,___X____,
  ___XX__X,XX__X_X_,
  ___X_XXX,____X_X_,
  ______X_,_____XX_,
  ________,______X_};

GUI_CONST_STORAGE unsigned char acGUI_FontSONG16_8BED[ 30] = { /* code 8BED */
  _X___XXX,XXXXXX__,
  __X_____,_X______,
  __X_____,_X______,
  ______XX,XXXXX___,
  ________,X___X___,
  XXX_____,X___X___,
  __X__XXX,XXXXXXX_,
  __X_____,________,
  __X_____,________,
  __X___XX,XXXXX___,
  __X___X_,____X___,
  __X_X_X_,____X___,
  __XX__X_,____X___,
  __X___XX,XXXXX___,
  ______X_,____X___};

GUI_CONST_STORAGE unsigned char acGUI_FontSONG16_8D1F[ 32] = { /* code 8D1F */
  ____X___,________,
  ____X___,________,
  ___XXXXX,XX______,
  __X_____,_X______,
  _X______,X_______,
  X_XXXXXX,XXX_____,
  __X_____,__X_____,
  __X___X_,__X_____,
  __X___X_,__X_____,
  __X___X_,__X_____,
  __X___X_,__X_____,
  __X__X__,__X_____,
  _____X_X,X_______,
  ____X___,_X______,
  __XX____,__X_____,
  XX______,___X____};

GUI_CONST_STORAGE unsigned char acGUI_FontSONG16_8D77[ 32] = { /* code 8D77 */
  ____X___,________,
  ____X___,________,
  ____X___,XXXXX___,
  _XXXXXX_,____X___,
  ____X___,____X___,
  ____X___,____X___,
  XXXXXXX_,XXXXX___,
  ____X___,X___X___,
  __X_X___,X_______,
  __X_X___,X_______,
  __X_XXX_,X____X__,
  __X_X___,X____X__,
  __X_X___,_XXXXX__,
  _X_XX___,________,
  _X__XXXX,XXXXXXX_,
  X_______,________};

GUI_CONST_STORAGE unsigned char acGUI_FontSONG16_8DEF[ 32] = { /* code 8DEF */
  ________,_X______,
  _XXXXX__,_X______,
  _X___X__,_XXXX___,
  _X___X__,X___X___,
  _X___X_X,_X_X____,
  _XXXXX__,__X_____,
  ___X____,_X_X____,
  ___X____,X___X___,
  ___X___X,_____XX_,
  _X_XXX__,XXXXX___,
  _X_X____,X___X___,
  _X_X____,X___X___,
  _X_X____,X___X___,
  _X_XXX__,X___X___,
  XXX_____,XXXXX___,
  ________,X___X___};

GUI_CONST_STORAGE unsigned char acGUI_FontSONG16_8F6F[ 32] = { /* code 8F6F */
  ___X____,_X______,
  ___X____,_X______,
  ___X____,_X______,
  XXXXXXX_,_XXXXX__,
  __X_____,X____X__,
  __X_X___,X___X___,
  _X__X__X,__X_____,
  _XXXXXX_,__X_____,
  ____X___,__X_____,
  ____X___,_X_X____,
  ____XXX_,_X_X____,
  XXXXX___,_X_X____,
  _X__X___,X___X___,
  ____X___,X___X___,
  ____X__X,_____X__,
  ____X_X_,______X_};

GUI_CONST_STORAGE unsigned char acGUI_FontSONG16_8F7D[ 32] = { /* code 8F7D */
  ____X___,__X_____,
  ____X___,__X_X___,
  _XXXXXXX,__X__X__,
  ____X___,__X_____,
  XXXXXXXX,XXXXXXX_,
  ___X____,__X_____,
  ___X____,__X__X__,
  XXXXXXXX,__X__X__,
  __X_____,__X__X__,
  _X__X___,__X_X___,
  _XXXXXXX,__X_X___,
  ____X___,___X____,
  ____XXXX,___X__X_,
  XXXXX___,__X_X_X_,
  ____X___,_X___XX_,
  ____X___,X_____X_};

GUI_CONST_STORAGE unsigned char acGUI_FontSONG16_8F93[ 32] = { /* code 8F93 */
  __X_____,_X______,
  __X_____,X_X_____,
  __X____X,___X____,
  XXXXX_X_,____X___,
  __X__X_X,XXXX_XX_,
  _X______,________,
  _X_X__XX,XX___X__,
  X__X__X_,_X_X_X__,
  XXXXX_X_,_X_X_X__,
  ___X__XX,XX_X_X__,
  ___XX_X_,_X_X_X__,
  XXXX__X_,_X_X_X__,
  _X_X__XX,XX_X_X__,
  ___X__X_,_X___X__,
  ___X__X_,_X_X_X__,
  ___X__X_,XX__X___};

GUI_CONST_STORAGE unsigned char acGUI_FontSONG16_8FC7[ 30] = { /* code 8FC7 */
  ________,___X____,
  __X_____,___X____,
  ___X____,___X____,
  ___X_XXX,XXXXXXX_,
  ________,___X____,
  ________,___X____,
  XXXX__X_,___X____,
  ___X___X,___X____,
  ___X___X,___X____,
  ___X____,___X____,
  ___X____,___X____,
  ___X____,_X_X____,
  ___X____,__X_____,
  __X_X___,________,
  _X___XXX,XXXXXXX_};

GUI_CONST_STORAGE unsigned char acGUI_FontSONG16_8FD9[ 30] = { /* code 8FD9 */
  ________,X_______,
  __X_____,_X______,
  ___X____,_X______,
  ___X_XXX,XXXXXX__,
  ________,___X____,
  ______X_,___X____,
  XXXX___X,__X_____,
  ___X____,X_X_____,
  ___X____,_X______,
  ___X____,X_X_____,
  ___X___X,___X____,
  ___X__X_,____X___,
  ___X_X__,____X___,
  __X_X___,________,
  _X___XXX,XXXXXXX_};

GUI_CONST_STORAGE unsigned char acGUI_FontSONG16_8FDB[ 30] = { /* code 8FDB */
  ________,X__X____,
  __X_____,X__X____,
  ___X____,X__X____,
  ___X__XX,XXXXXX__,
  ________,X__X____,
  ________,X__X____,
  XXXX____,X__X____,
  ___X_XXX,XXXXXXX_,
  ___X____,X__X____,
  ___X____,X__X____,
  ___X___X,___X____,
  ___X___X,___X____,
  ___X__X_,___X____,
  __X_X___,________,
  _X___XXX,XXXXXXX_};

GUI_CONST_STORAGE unsigned char acGUI_FontSONG16_9009[ 30] = { /* code 9009 */
  ________,_X______,
  __X___X_,_X______,
  ___X__X_,_X______,
  ___X__XX,XXXXX___,
  _____X__,_X______,
  ________,_X______,
  XXXX_XXX,XXXXXX__,
  ___X___X,__X_____,
  ___X___X,__X_____,
  ___X___X,__X_____,
  ___X__X_,__X__X__,
  ___X__X_,__X__X__,
  ___X_X__,___XXX__,
  __X_X___,________,
  _X___XXX,XXXXXXX_};

GUI_CONST_STORAGE unsigned char acGUI_FontSONG16_9178[ 32] = { /* code 9178 */
  ________,___X____,
  XXXXXXX_,___X____,
  __X_X___,__X_____,
  __X_X___,_X___X__,
  XXXXXXX_,XXXXXXX_,
  X_X_X_X_,__X_X___,
  X_X_X_X_,_X___X__,
  X_X_X_X_,X_X___X_,
  X_X_XXX_,__XXXX__,
  XX____X_,_X___X__,
  X_____X_,_X___X__,
  XXXXXXX_,X_X_X___,
  X_____X_,___X____,
  X_____X_,__X_X___,
  XXXXXXX_,_X___X__,
  X_____X_,X_____X_};

GUI_CONST_STORAGE unsigned char acGUI_FontSONG16_94C5[ 32] = { /* code 94C5 */
  ___X____,________,
  ___X____,XXXXX___,
  __XXXX__,X___X___,
  __X_____,X___X___,
  _X______,X___X___,
  X_XXXX__,X___X___,
  ___X___X,_____XX_,
  ___X__X_,________,
  XXXXXX__,________,
  ___X___X,XXXXXX__,
  ___X___X,_____X__,
  ___X___X,_____X__,
  ___X_X_X,_____X__,
  ___XX__X,_____X__,
  ___X___X,XXXXXX__,
  _______X,_____X__};

GUI_CONST_STORAGE unsigned char acGUI_FontSONG16_9502[ 30] = { /* code 9502 */
  ___X____,________,
  ___X___X,XXXXXX__,
  __XXXX_X,__X__X__,
  __X____X,__X__X__,
  _X_____X,XXXXXX__,
  X_XXXX_X,__X__X__,
  ___X___X,__X__X__,
  ___X___X,XXXXXX__,
  XXXXXX__,__X_____,
  ___X____,__X_____,
  ___X___X,XXXXXX__,
  ___X____,__X_____,
  ___X_X__,__X_____,
  ___XX___,__X_____,
  ___X__XX,XXXXXXX_};

GUI_CONST_STORAGE unsigned char acGUI_FontSONG16_9530[ 30] = { /* code 9530 */
  __X_____,________,
  __X____X,XXXXXX__,
  __XXX___,____X___,
  __X_____,___X____,
  _X______,__X_____,
  _XXXX_XX,XXXXXXX_,
  X_X_____,__X_____,
  __X_____,X_X_____,
  XXXXX___,_X______,
  __X____X,XXXXXX__,
  __X____X,_X_X_X__,
  __X____X,_X_X_X__,
  __X_X__X,_X_X_X__,
  __XX___X,_X_X_X__,
  __X__XXX,XXXXXXX_};

GUI_CONST_STORAGE unsigned char acGUI_FontSONG16_9549[ 32] = { /* code 9549 */
  __X_____,________,
  __X___XX,XXXXXXX_,
  __XXX___,________,
  __X____X,XXXXXX__,
  _X_____X,_____X__,
  _XXXX__X,_____X__,
  X_X____X,XXXXXX__,
  __X_____,________,
  XXXXX_XX,XXXXXXX_,
  __X___X_,X___X_X_,
  __X___X_,_X_X__X_,
  __X___XX,XXXXXXX_,
  __X_X_X_,__X___X_,
  __XX__X_,__X___X_,
  __X___X_,__X_X_X_,
  ______X_,_____X__};

GUI_CONST_STORAGE unsigned char acGUI_FontSONG16_954D[ 32] = { /* code 954D */
  __X_____,_X______,
  __X_____,X_______,
  __XXX_XX,XXXXX___,
  __X___X_,____X___,
  _X____XX,XXXXX___,
  _XXXX_X_,____X___,
  X_X___XX,XXXXX___,
  __X___X_,____X___,
  XXXXX_XX,XXXXX___,
  __X_____,_X______,
  __X__XXX,XXXXXXX_,
  __X_____,XXX_____,
  __X_X__X,_X_X____,
  __XX__X_,_X__X___,
  __X__X__,_X___XX_,
  ________,_X______};

GUI_CONST_STORAGE unsigned char acGUI_FontSONG16_95E8[ 32] = { /* code 95E8 */
  _X______,________,
  __X__XXX,XXXXX___,
  __X_____,____X___,
  X_______,____X___,
  X_______,____X___,
  X_______,____X___,
  X_______,____X___,
  X_______,____X___,
  X_______,____X___,
  X_______,____X___,
  X_______,____X___,
  X_______,____X___,
  X_______,____X___,
  X_______,____X___,
  X_______,__X_X___,
  X_______,___X____};

GUI_CONST_STORAGE unsigned char acGUI_FontSONG16_95F4[ 32] = { /* code 95F4 */
  _X______,________,
  __X__XXX,XXXXX___,
  __X_____,____X___,
  X_______,____X___,
  X___XXXX,X___X___,
  X___X___,X___X___,
  X___X___,X___X___,
  X___X___,X___X___,
  X___XXXX,X___X___,
  X___X___,X___X___,
  X___X___,X___X___,
  X___X___,X___X___,
  X___XXXX,X___X___,
  X_______,____X___,
  X_______,__X_X___,
  X_______,___X____};

GUI_CONST_STORAGE unsigned char acGUI_FontSONG16_963B[ 30] = { /* code 963B */
  XXXXX_XX,XXXX____,
  X___X_X_,___X____,
  X__X__X_,___X____,
  X__X__X_,___X____,
  X_X___XX,XXXX____,
  X__X__X_,___X____,
  X__X__X_,___X____,
  X___X_X_,___X____,
  X___X_XX,XXXX____,
  X___X_X_,___X____,
  XX_X__X_,___X____,
  X_X___X_,___X____,
  X_____X_,___X____,
  X___XXXX,XXXXXX__,
  X_______,________};

GUI_CONST_STORAGE unsigned char acGUI_FontSONG16_9650[ 30] = { /* code 9650 */
  XXXX_XXX,XXXX____,
  X__X_X__,___X____,
  X_X__X__,___X____,
  X_X__XXX,XXXX____,
  XX___X__,___X____,
  X_X__X__,___X____,
  X__X_XXX,XXXX____,
  X__X_X__,X___X___,
  X__X_X__,X__X____,
  XX_X_X__,_XX_____,
  X_X__X__,_X______,
  X____X__,__X_____,
  X____X_X,___X____,
  X____XX_,____XX__,
  X____X__,________};

GUI_CONST_STORAGE unsigned char acGUI_FontSONG16_97F3[ 32] = { /* code 97F3 */
  ______X_,________,
  _______X,________,
  __XXXXXX,XXXXX___,
  ________,________,
  ____X___,__X_____,
  _____X__,_X______,
  XXXXXXXX,XXXXXXX_,
  ________,________,
  ___XXXXX,XXXX____,
  ___X____,___X____,
  ___X____,___X____,
  ___XXXXX,XXXX____,
  ___X____,___X____,
  ___X____,___X____,
  ___XXXXX,XXXX____,
  ___X____,___X____};

GUI_CONST_STORAGE GUI_CHARINFO_EXT GUI_FontSONG16_CharInfo[181] = {
   {   1,   1,   0,  14,   8, acGUI_FontSONG16_0020 } /* code 0020, SPACE */
  ,{   2,  11,   3,   3,   8, acGUI_FontSONG16_0021 } /* code 0021, EXCLAMATION MARK */
  ,{   6,   4,   1,   1,   8, acGUI_FontSONG16_0022 } /* code 0022, QUOTATION MARK */
  ,{   7,  11,   0,   3,   8, acGUI_FontSONG16_0023 } /* code 0023, NUMBER SIGN */
  ,{   5,  14,   1,   2,   8, acGUI_FontSONG16_0024 } /* code 0024, DOLLAR SIGN */
  ,{   7,  11,   0,   3,   8, acGUI_FontSONG16_0025 } /* code 0025, PERCENT SIGN */
  ,{   8,  11,   0,   3,   8, acGUI_FontSONG16_0026 } /* code 0026, AMPERSAND */
  ,{   4,  14,   3,   1,   8, acGUI_FontSONG16_0028 } /* code 0028, LEFT PARENTHESIS */
  ,{   4,  14,   1,   1,   8, acGUI_FontSONG16_0029 } /* code 0029, RIGHT PARENTHESIS */
  ,{   7,   8,   0,   4,   8, acGUI_FontSONG16_002A } /* code 002A, ASTERISK */
  ,{   7,   9,   0,   4,   8, acGUI_FontSONG16_002B } /* code 002B, PLUS SIGN */
  ,{   3,   4,   0,  12,   8, acGUI_FontSONG16_002C } /* code 002C, COMMA */
  ,{   7,   1,   1,   8,   8, acGUI_FontSONG16_002D } /* code 002D, HYPHEN-MINUS */
  ,{   2,   2,   1,  12,   8, acGUI_FontSONG16_002E } /* code 002E, FULL STOP */
  ,{   7,  13,   1,   2,   8, acGUI_FontSONG16_002F } /* code 002F, SOLIDUS */
  ,{   6,  11,   1,   3,   8, acGUI_FontSONG16_0030 } /* code 0030, DIGIT ZERO */
  ,{   5,  11,   1,   3,   8, acGUI_FontSONG16_0031 } /* code 0031, DIGIT ONE */
  ,{   6,  11,   1,   3,   8, acGUI_FontSONG16_0032 } /* code 0032, DIGIT TWO */
  ,{   6,  11,   1,   3,   8, acGUI_FontSONG16_0033 } /* code 0033, DIGIT THREE */
  ,{   6,  11,   1,   3,   8, acGUI_FontSONG16_0034 } /* code 0034, DIGIT FOUR */
  ,{   6,  11,   1,   3,   8, acGUI_FontSONG16_0035 } /* code 0035, DIGIT FIVE */
  ,{   6,  11,   1,   3,   8, acGUI_FontSONG16_0036 } /* code 0036, DIGIT SIX */
  ,{   6,  11,   1,   3,   8, acGUI_FontSONG16_0037 } /* code 0037, DIGIT SEVEN */
  ,{   6,  11,   1,   3,   8, acGUI_FontSONG16_0038 } /* code 0038, DIGIT EIGHT */
  ,{   6,  11,   1,   3,   8, acGUI_FontSONG16_0039 } /* code 0039, DIGIT NINE */
  ,{   2,   8,   3,   6,   8, acGUI_FontSONG16_003A } /* code 003A, COLON */
  ,{   2,   9,   2,   7,   8, acGUI_FontSONG16_003B } /* code 003B, SEMICOLON */
  ,{   6,  11,   1,   3,   8, acGUI_FontSONG16_003C } /* code 003C, LESS-THAN SIGN */
  ,{   7,   5,   0,   6,   8, acGUI_FontSONG16_003D } /* code 003D, EQUALS SIGN */
  ,{   6,  11,   1,   3,   8, acGUI_FontSONG16_003E } /* code 003E, GREATER-THAN SIGN */
  ,{   6,  11,   1,   3,   8, acGUI_FontSONG16_003F } /* code 003F, QUESTION MARK */
  ,{   7,  11,   0,   3,   8, acGUI_FontSONG16_0040 } /* code 0040, COMMERCIAL AT */
  ,{   8,  11,   0,   3,   8, acGUI_FontSONG16_0041 } /* code 0041, LATIN CAPITAL LETTER A */
  ,{   7,  11,   0,   3,   8, acGUI_FontSONG16_0042 } /* code 0042, LATIN CAPITAL LETTER B */
  ,{   7,  11,   0,   3,   8, acGUI_FontSONG16_0043 } /* code 0043, LATIN CAPITAL LETTER C */
  ,{   7,  11,   0,   3,   8, acGUI_FontSONG16_0044 } /* code 0044, LATIN CAPITAL LETTER D */
  ,{   7,  11,   0,   3,   8, acGUI_FontSONG16_0045 } /* code 0045, LATIN CAPITAL LETTER E */
  ,{   7,  11,   0,   3,   8, acGUI_FontSONG16_0046 } /* code 0046, LATIN CAPITAL LETTER F */
  ,{   7,  11,   0,   3,   8, acGUI_FontSONG16_0047 } /* code 0047, LATIN CAPITAL LETTER G */
  ,{   8,  11,   0,   3,   8, acGUI_FontSONG16_0048 } /* code 0048, LATIN CAPITAL LETTER H */
  ,{   5,  11,   1,   3,   8, acGUI_FontSONG16_0049 } /* code 0049, LATIN CAPITAL LETTER I */
  ,{   7,  13,   0,   3,   8, acGUI_FontSONG16_004A } /* code 004A, LATIN CAPITAL LETTER J */
  ,{   7,  11,   0,   3,   8, acGUI_FontSONG16_004B } /* code 004B, LATIN CAPITAL LETTER K */
  ,{   7,  11,   0,   3,   8, acGUI_FontSONG16_004C } /* code 004C, LATIN CAPITAL LETTER L */
  ,{   7,  11,   0,   3,   8, acGUI_FontSONG16_004D } /* code 004D, LATIN CAPITAL LETTER M */
  ,{   8,  11,   0,   3,   8, acGUI_FontSONG16_004E } /* code 004E, LATIN CAPITAL LETTER N */
  ,{   7,  11,   0,   3,   8, acGUI_FontSONG16_004F } /* code 004F, LATIN CAPITAL LETTER O */
  ,{   7,  11,   0,   3,   8, acGUI_FontSONG16_0050 } /* code 0050, LATIN CAPITAL LETTER P */
  ,{   7,  12,   0,   3,   8, acGUI_FontSONG16_0051 } /* code 0051, LATIN CAPITAL LETTER Q */
  ,{   8,  11,   0,   3,   8, acGUI_FontSONG16_0052 } /* code 0052, LATIN CAPITAL LETTER R */
  ,{   6,  11,   1,   3,   8, acGUI_FontSONG16_0053 } /* code 0053, LATIN CAPITAL LETTER S */
  ,{   7,  11,   0,   3,   8, acGUI_FontSONG16_0054 } /* code 0054, LATIN CAPITAL LETTER T */
  ,{   8,  11,   0,   3,   8, acGUI_FontSONG16_0055 } /* code 0055, LATIN CAPITAL LETTER U */
  ,{   8,  11,   0,   3,   8, acGUI_FontSONG16_0056 } /* code 0056, LATIN CAPITAL LETTER V */
  ,{   7,  11,   0,   3,   8, acGUI_FontSONG16_0057 } /* code 0057, LATIN CAPITAL LETTER W */
  ,{   8,  11,   0,   3,   8, acGUI_FontSONG16_0058 } /* code 0058, LATIN CAPITAL LETTER X */
  ,{   7,  11,   0,   3,   8, acGUI_FontSONG16_0059 } /* code 0059, LATIN CAPITAL LETTER Y */
  ,{   7,  11,   0,   3,   8, acGUI_FontSONG16_005A } /* code 005A, LATIN CAPITAL LETTER Z */
  ,{   4,  14,   3,   1,   8, acGUI_FontSONG16_005B } /* code 005B, LEFT SQUARE BRACKET */
  ,{   6,  14,   1,   2,   8, acGUI_FontSONG16_005C } /* code 005C, REVERSE SOLIDUS */
  ,{   4,  14,   1,   1,   8, acGUI_FontSONG16_005D } /* code 005D, RIGHT SQUARE BRACKET */
  ,{   5,   2,   2,   1,   8, acGUI_FontSONG16_005E } /* code 005E, CIRCUMFLEX ACCENT */
  ,{   8,   1,   0,  15,   8, acGUI_FontSONG16_005F } /* code 005F, LOW LINE */
  ,{   7,   7,   1,   7,   8, acGUI_FontSONG16_0061 } /* code 0061, LATIN SMALL LETTER A */
  ,{   7,  12,   0,   2,   8, acGUI_FontSONG16_0062 } /* code 0062, LATIN SMALL LETTER B */
  ,{   6,   7,   1,   7,   8, acGUI_FontSONG16_0063 } /* code 0063, LATIN SMALL LETTER C */
  ,{   7,  12,   1,   2,   8, acGUI_FontSONG16_0064 } /* code 0064, LATIN SMALL LETTER D */
  ,{   6,   7,   1,   7,   8, acGUI_FontSONG16_0065 } /* code 0065, LATIN SMALL LETTER E */
  ,{   7,  11,   1,   3,   8, acGUI_FontSONG16_0066 } /* code 0066, LATIN SMALL LETTER F */
  ,{   6,   9,   1,   7,   8, acGUI_FontSONG16_0067 } /* code 0067, LATIN SMALL LETTER G */
  ,{   8,  12,   0,   2,   8, acGUI_FontSONG16_0068 } /* code 0068, LATIN SMALL LETTER H */
  ,{   5,  11,   1,   3,   8, acGUI_FontSONG16_0069 } /* code 0069, LATIN SMALL LETTER I */
  ,{   5,  13,   1,   3,   8, acGUI_FontSONG16_006A } /* code 006A, LATIN SMALL LETTER J */
  ,{   7,  12,   0,   2,   8, acGUI_FontSONG16_006B } /* code 006B, LATIN SMALL LETTER K */
  ,{   5,  11,   1,   3,   8, acGUI_FontSONG16_006C } /* code 006C, LATIN SMALL LETTER L */
  ,{   8,   7,   0,   7,   8, acGUI_FontSONG16_006D } /* code 006D, LATIN SMALL LETTER M */
  ,{   8,   7,   0,   7,   8, acGUI_FontSONG16_006E } /* code 006E, LATIN SMALL LETTER N */
  ,{   6,   7,   1,   7,   8, acGUI_FontSONG16_006F } /* code 006F, LATIN SMALL LETTER O */
  ,{   7,   9,   0,   7,   8, acGUI_FontSONG16_0070 } /* code 0070, LATIN SMALL LETTER P */
  ,{   7,   9,   1,   7,   8, acGUI_FontSONG16_0071 } /* code 0071, LATIN SMALL LETTER Q */
  ,{   7,   7,   0,   7,   8, acGUI_FontSONG16_0072 } /* code 0072, LATIN SMALL LETTER R */
  ,{   6,   7,   1,   7,   8, acGUI_FontSONG16_0073 } /* code 0073, LATIN SMALL LETTER S */
  ,{   5,   9,   1,   5,   8, acGUI_FontSONG16_0074 } /* code 0074, LATIN SMALL LETTER T */
  ,{   8,   7,   0,   7,   8, acGUI_FontSONG16_0075 } /* code 0075, LATIN SMALL LETTER U */
  ,{   8,   7,   0,   7,   8, acGUI_FontSONG16_0076 } /* code 0076, LATIN SMALL LETTER V */
  ,{   8,   7,   0,   7,   8, acGUI_FontSONG16_0077 } /* code 0077, LATIN SMALL LETTER W */
  ,{   6,   7,   1,   7,   8, acGUI_FontSONG16_0078 } /* code 0078, LATIN SMALL LETTER X */
  ,{   8,   9,   0,   7,   8, acGUI_FontSONG16_0079 } /* code 0079, LATIN SMALL LETTER Y */
  ,{   6,   7,   1,   7,   8, acGUI_FontSONG16_007A } /* code 007A, LATIN SMALL LETTER Z */
  ,{   4,  14,   4,   1,   8, acGUI_FontSONG16_007B } /* code 007B, LEFT CURLY BRACKET */
  ,{   1,  16,   4,   0,   8, acGUI_FontSONG16_007C } /* code 007C, VERTICAL LINE */
  ,{   4,  14,   1,   1,   8, acGUI_FontSONG16_007D } /* code 007D, RIGHT CURLY BRACKET */
  ,{   8,   3,   1,   0,   8, acGUI_FontSONG16_007E } /* code 007E, TILDE */
  ,{  10,  11,   2,   1,  16, acGUI_FontSONG16_03A9 } /* code 03A9, GREEK CAPITAL LETTER OMEGA */
  ,{  15,  15,   0,   0,  16, acGUI_FontSONG16_4E0A } /* code 4E0A */
  ,{  15,  15,   0,   1,  16, acGUI_FontSONG16_4E0B } /* code 4E0B */
  ,{  11,  16,   2,   0,  16, acGUI_FontSONG16_4E2D } /* code 4E2D */
  ,{  15,  16,   0,   0,  16, acGUI_FontSONG16_4EA7 } /* code 4EA7 */
  ,{  15,  16,   0,   0,  16, acGUI_FontSONG16_4EEA } /* code 4EEA */
  ,{  15,  16,   0,   0,  16, acGUI_FontSONG16_4EF6 } /* code 4EF6 */
  ,{  15,  16,   0,   0,  16, acGUI_FontSONG16_4FE1 } /* code 4FE1 */
  ,{  15,  16,   0,   0,  16, acGUI_FontSONG16_5145 } /* code 5145 */
  ,{  15,  16,   0,   0,  16, acGUI_FontSONG16_5173 } /* code 5173 */
  ,{  13,  16,   1,   0,  16, acGUI_FontSONG16_5185 } /* code 5185 */
  ,{  13,  16,   1,   0,  16, acGUI_FontSONG16_51FA } /* code 51FA */
  ,{  15,  16,   0,   0,  16, acGUI_FontSONG16_5206 } /* code 5206 */
  ,{  14,  16,   0,   0,  16, acGUI_FontSONG16_5236 } /* code 5236 */
  ,{  15,  15,   0,   1,  16, acGUI_FontSONG16_538B } /* code 538B */
  ,{  15,  15,   0,   1,  16, acGUI_FontSONG16_53F7 } /* code 53F7 */
  ,{  15,  15,   0,   1,  16, acGUI_FontSONG16_5668 } /* code 5668 */
  ,{  13,  15,   1,   1,  16, acGUI_FontSONG16_56FE } /* code 56FE */
  ,{  15,  16,   0,   0,  16, acGUI_FontSONG16_5728 } /* code 5728 */
  ,{  15,  15,   0,   0,  16, acGUI_FontSONG16_578B } /* code 578B */
  ,{  15,  16,   0,   0,  16, acGUI_FontSONG16_58F0 } /* code 58F0 */
  ,{  15,  16,   0,   0,  16, acGUI_FontSONG16_59CB } /* code 59CB */
  ,{  15,  16,   0,   0,  16, acGUI_FontSONG16_5C0F } /* code 5C0F */
  ,{  15,  15,   0,   1,  16, acGUI_FontSONG16_5F00 } /* code 5F00 */
  ,{  15,  16,   0,   0,  16, acGUI_FontSONG16_5FAA } /* code 5FAA */
  ,{  15,  15,   0,   0,  16, acGUI_FontSONG16_606F } /* code 606F */
  ,{  15,  16,   0,   0,  16, acGUI_FontSONG16_622A } /* code 622A */
  ,{  15,  16,   0,   0,  16, acGUI_FontSONG16_62A5 } /* code 62A5 */
  ,{  15,  16,   0,   0,  16, acGUI_FontSONG16_63A7 } /* code 63A7 */
  ,{  15,  16,   0,   0,  16, acGUI_FontSONG16_653E } /* code 653E */
  ,{  15,  16,   0,   0,  16, acGUI_FontSONG16_6570 } /* code 6570 */
  ,{  15,  16,   0,   0,  16, acGUI_FontSONG16_6587 } /* code 6587 */
  ,{   9,  15,   3,   1,  16, acGUI_FontSONG16_65E5 } /* code 65E5 */
  ,{  14,  16,   1,   0,  16, acGUI_FontSONG16_65F6 } /* code 65F6 */
  ,{  15,  16,   0,   0,  16, acGUI_FontSONG16_662F } /* code 662F */
  ,{  13,  16,   1,   0,  16, acGUI_FontSONG16_66F2 } /* code 66F2 */
  ,{  14,  16,   0,   0,  16, acGUI_FontSONG16_671F } /* code 671F */
  ,{  15,  16,   0,   0,  16, acGUI_FontSONG16_672A } /* code 672A */
  ,{  15,  16,   0,   0,  16, acGUI_FontSONG16_672C } /* code 672C */
  ,{  15,  16,   0,   0,  16, acGUI_FontSONG16_69DB } /* code 69DB */
  ,{  15,  16,   0,   0,  16, acGUI_FontSONG16_6B21 } /* code 6B21 */
  ,{  15,  15,   0,   0,  16, acGUI_FontSONG16_6B62 } /* code 6B62 */
  ,{  15,  14,   0,   1,  16, acGUI_FontSONG16_6B63 } /* code 6B63 */
  ,{  15,  16,   0,   0,  16, acGUI_FontSONG16_6B65 } /* code 6B65 */
  ,{  15,  16,   0,   0,  16, acGUI_FontSONG16_6C22 } /* code 6C22 */
  ,{  15,  15,   0,   0,  16, acGUI_FontSONG16_6C60 } /* code 6C60 */
  ,{  15,  16,   0,   0,  16, acGUI_FontSONG16_6D41 } /* code 6D41 */
  ,{  14,  16,   0,   0,  16, acGUI_FontSONG16_6D4B } /* code 6D4B */
  ,{  15,  15,   0,   1,  16, acGUI_FontSONG16_6E90 } /* code 6E90 */
  ,{  15,  16,   0,   0,  16, acGUI_FontSONG16_7248 } /* code 7248 */
  ,{  15,  14,   0,   2,  16, acGUI_FontSONG16_73AF } /* code 73AF */
  ,{  15,  15,   0,   0,  16, acGUI_FontSONG16_751F } /* code 751F */
  ,{  13,  16,   2,   0,  16, acGUI_FontSONG16_7535 } /* code 7535 */
  ,{  15,  16,   0,   0,  16, acGUI_FontSONG16_77ED } /* code 77ED */
  ,{  15,  15,   0,   1,  16, acGUI_FontSONG16_786C } /* code 786C */
  ,{  15,  16,   0,   0,  16, acGUI_FontSONG16_7A0B } /* code 7A0B */
  ,{  15,  16,   0,   0,  16, acGUI_FontSONG16_7C7B } /* code 7C7B */
  ,{  13,  16,   1,   0,  16, acGUI_FontSONG16_7CFB } /* code 7CFB */
  ,{  15,  16,   0,   0,  16, acGUI_FontSONG16_7EBF } /* code 7EBF */
  ,{  15,  16,   0,   0,  16, acGUI_FontSONG16_7EDF } /* code 7EDF */
  ,{  14,  16,   0,   0,  16, acGUI_FontSONG16_7F16 } /* code 7F16 */
  ,{  15,  15,   0,   0,  16, acGUI_FontSONG16_7F6E } /* code 7F6E */
  ,{  15,  16,   0,   0,  16, acGUI_FontSONG16_8A00 } /* code 8A00 */
  ,{  15,  16,   0,   0,  16, acGUI_FontSONG16_8B66 } /* code 8B66 */
  ,{  15,  15,   0,   1,  16, acGUI_FontSONG16_8BBE } /* code 8BBE */
  ,{  15,  16,   0,   0,  16, acGUI_FontSONG16_8BD5 } /* code 8BD5 */
  ,{  15,  15,   0,   1,  16, acGUI_FontSONG16_8BED } /* code 8BED */
  ,{  12,  16,   1,   0,  16, acGUI_FontSONG16_8D1F } /* code 8D1F */
  ,{  15,  16,   0,   0,  16, acGUI_FontSONG16_8D77 } /* code 8D77 */
  ,{  15,  16,   0,   0,  16, acGUI_FontSONG16_8DEF } /* code 8DEF */
  ,{  15,  16,   0,   0,  16, acGUI_FontSONG16_8F6F } /* code 8F6F */
  ,{  15,  16,   0,   0,  16, acGUI_FontSONG16_8F7D } /* code 8F7D */
  ,{  15,  16,   0,   0,  16, acGUI_FontSONG16_8F93 } /* code 8F93 */
  ,{  15,  15,   0,   0,  16, acGUI_FontSONG16_8FC7 } /* code 8FC7 */
  ,{  15,  15,   0,   0,  16, acGUI_FontSONG16_8FD9 } /* code 8FD9 */
  ,{  15,  15,   0,   0,  16, acGUI_FontSONG16_8FDB } /* code 8FDB */
  ,{  15,  15,   0,   0,  16, acGUI_FontSONG16_9009 } /* code 9009 */
  ,{  15,  16,   0,   0,  16, acGUI_FontSONG16_9178 } /* code 9178 */
  ,{  15,  16,   0,   0,  16, acGUI_FontSONG16_94C5 } /* code 94C5 */
  ,{  15,  15,   0,   0,  16, acGUI_FontSONG16_9502 } /* code 9502 */
  ,{  15,  15,   0,   0,  16, acGUI_FontSONG16_9530 } /* code 9530 */
  ,{  15,  16,   0,   0,  16, acGUI_FontSONG16_9549 } /* code 9549 */
  ,{  15,  16,   0,   0,  16, acGUI_FontSONG16_954D } /* code 954D */
  ,{  13,  16,   1,   0,  16, acGUI_FontSONG16_95E8 } /* code 95E8 */
  ,{  13,  16,   1,   0,  16, acGUI_FontSONG16_95F4 } /* code 95F4 */
  ,{  14,  15,   1,   1,  16, acGUI_FontSONG16_963B } /* code 963B */
  ,{  14,  15,   1,   1,  16, acGUI_FontSONG16_9650 } /* code 9650 */
  ,{  15,  16,   0,   0,  16, acGUI_FontSONG16_97F3 } /* code 97F3 */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontSONG16_Prop89 = {
   0x97F3 /* first character */
  ,0x97F3 /* last character  */
  ,&GUI_FontSONG16_CharInfo[180] /* address of first character */
  ,(GUI_CONST_STORAGE GUI_FONT_PROP_EXT *)0 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontSONG16_Prop88 = {
   0x9650 /* first character */
  ,0x9650 /* last character  */
  ,&GUI_FontSONG16_CharInfo[179] /* address of first character */
  ,&GUI_FontSONG16_Prop89 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontSONG16_Prop87 = {
   0x963B /* first character */
  ,0x963B /* last character  */
  ,&GUI_FontSONG16_CharInfo[178] /* address of first character */
  ,&GUI_FontSONG16_Prop88 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontSONG16_Prop86 = {
   0x95F4 /* first character */
  ,0x95F4 /* last character  */
  ,&GUI_FontSONG16_CharInfo[177] /* address of first character */
  ,&GUI_FontSONG16_Prop87 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontSONG16_Prop85 = {
   0x95E8 /* first character */
  ,0x95E8 /* last character  */
  ,&GUI_FontSONG16_CharInfo[176] /* address of first character */
  ,&GUI_FontSONG16_Prop86 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontSONG16_Prop84 = {
   0x954D /* first character */
  ,0x954D /* last character  */
  ,&GUI_FontSONG16_CharInfo[175] /* address of first character */
  ,&GUI_FontSONG16_Prop85 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontSONG16_Prop83 = {
   0x9549 /* first character */
  ,0x9549 /* last character  */
  ,&GUI_FontSONG16_CharInfo[174] /* address of first character */
  ,&GUI_FontSONG16_Prop84 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontSONG16_Prop82 = {
   0x9530 /* first character */
  ,0x9530 /* last character  */
  ,&GUI_FontSONG16_CharInfo[173] /* address of first character */
  ,&GUI_FontSONG16_Prop83 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontSONG16_Prop81 = {
   0x9502 /* first character */
  ,0x9502 /* last character  */
  ,&GUI_FontSONG16_CharInfo[172] /* address of first character */
  ,&GUI_FontSONG16_Prop82 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontSONG16_Prop80 = {
   0x94C5 /* first character */
  ,0x94C5 /* last character  */
  ,&GUI_FontSONG16_CharInfo[171] /* address of first character */
  ,&GUI_FontSONG16_Prop81 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontSONG16_Prop79 = {
   0x9178 /* first character */
  ,0x9178 /* last character  */
  ,&GUI_FontSONG16_CharInfo[170] /* address of first character */
  ,&GUI_FontSONG16_Prop80 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontSONG16_Prop78 = {
   0x9009 /* first character */
  ,0x9009 /* last character  */
  ,&GUI_FontSONG16_CharInfo[169] /* address of first character */
  ,&GUI_FontSONG16_Prop79 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontSONG16_Prop77 = {
   0x8FDB /* first character */
  ,0x8FDB /* last character  */
  ,&GUI_FontSONG16_CharInfo[168] /* address of first character */
  ,&GUI_FontSONG16_Prop78 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontSONG16_Prop76 = {
   0x8FD9 /* first character */
  ,0x8FD9 /* last character  */
  ,&GUI_FontSONG16_CharInfo[167] /* address of first character */
  ,&GUI_FontSONG16_Prop77 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontSONG16_Prop75 = {
   0x8FC7 /* first character */
  ,0x8FC7 /* last character  */
  ,&GUI_FontSONG16_CharInfo[166] /* address of first character */
  ,&GUI_FontSONG16_Prop76 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontSONG16_Prop74 = {
   0x8F93 /* first character */
  ,0x8F93 /* last character  */
  ,&GUI_FontSONG16_CharInfo[165] /* address of first character */
  ,&GUI_FontSONG16_Prop75 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontSONG16_Prop73 = {
   0x8F7D /* first character */
  ,0x8F7D /* last character  */
  ,&GUI_FontSONG16_CharInfo[164] /* address of first character */
  ,&GUI_FontSONG16_Prop74 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontSONG16_Prop72 = {
   0x8F6F /* first character */
  ,0x8F6F /* last character  */
  ,&GUI_FontSONG16_CharInfo[163] /* address of first character */
  ,&GUI_FontSONG16_Prop73 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontSONG16_Prop71 = {
   0x8DEF /* first character */
  ,0x8DEF /* last character  */
  ,&GUI_FontSONG16_CharInfo[162] /* address of first character */
  ,&GUI_FontSONG16_Prop72 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontSONG16_Prop70 = {
   0x8D77 /* first character */
  ,0x8D77 /* last character  */
  ,&GUI_FontSONG16_CharInfo[161] /* address of first character */
  ,&GUI_FontSONG16_Prop71 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontSONG16_Prop69 = {
   0x8D1F /* first character */
  ,0x8D1F /* last character  */
  ,&GUI_FontSONG16_CharInfo[160] /* address of first character */
  ,&GUI_FontSONG16_Prop70 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontSONG16_Prop68 = {
   0x8BED /* first character */
  ,0x8BED /* last character  */
  ,&GUI_FontSONG16_CharInfo[159] /* address of first character */
  ,&GUI_FontSONG16_Prop69 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontSONG16_Prop67 = {
   0x8BD5 /* first character */
  ,0x8BD5 /* last character  */
  ,&GUI_FontSONG16_CharInfo[158] /* address of first character */
  ,&GUI_FontSONG16_Prop68 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontSONG16_Prop66 = {
   0x8BBE /* first character */
  ,0x8BBE /* last character  */
  ,&GUI_FontSONG16_CharInfo[157] /* address of first character */
  ,&GUI_FontSONG16_Prop67 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontSONG16_Prop65 = {
   0x8B66 /* first character */
  ,0x8B66 /* last character  */
  ,&GUI_FontSONG16_CharInfo[156] /* address of first character */
  ,&GUI_FontSONG16_Prop66 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontSONG16_Prop64 = {
   0x8A00 /* first character */
  ,0x8A00 /* last character  */
  ,&GUI_FontSONG16_CharInfo[155] /* address of first character */
  ,&GUI_FontSONG16_Prop65 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontSONG16_Prop63 = {
   0x7F6E /* first character */
  ,0x7F6E /* last character  */
  ,&GUI_FontSONG16_CharInfo[154] /* address of first character */
  ,&GUI_FontSONG16_Prop64 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontSONG16_Prop62 = {
   0x7F16 /* first character */
  ,0x7F16 /* last character  */
  ,&GUI_FontSONG16_CharInfo[153] /* address of first character */
  ,&GUI_FontSONG16_Prop63 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontSONG16_Prop61 = {
   0x7EDF /* first character */
  ,0x7EDF /* last character  */
  ,&GUI_FontSONG16_CharInfo[152] /* address of first character */
  ,&GUI_FontSONG16_Prop62 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontSONG16_Prop60 = {
   0x7EBF /* first character */
  ,0x7EBF /* last character  */
  ,&GUI_FontSONG16_CharInfo[151] /* address of first character */
  ,&GUI_FontSONG16_Prop61 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontSONG16_Prop59 = {
   0x7CFB /* first character */
  ,0x7CFB /* last character  */
  ,&GUI_FontSONG16_CharInfo[150] /* address of first character */
  ,&GUI_FontSONG16_Prop60 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontSONG16_Prop58 = {
   0x7C7B /* first character */
  ,0x7C7B /* last character  */
  ,&GUI_FontSONG16_CharInfo[149] /* address of first character */
  ,&GUI_FontSONG16_Prop59 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontSONG16_Prop57 = {
   0x7A0B /* first character */
  ,0x7A0B /* last character  */
  ,&GUI_FontSONG16_CharInfo[148] /* address of first character */
  ,&GUI_FontSONG16_Prop58 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontSONG16_Prop56 = {
   0x786C /* first character */
  ,0x786C /* last character  */
  ,&GUI_FontSONG16_CharInfo[147] /* address of first character */
  ,&GUI_FontSONG16_Prop57 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontSONG16_Prop55 = {
   0x77ED /* first character */
  ,0x77ED /* last character  */
  ,&GUI_FontSONG16_CharInfo[146] /* address of first character */
  ,&GUI_FontSONG16_Prop56 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontSONG16_Prop54 = {
   0x7535 /* first character */
  ,0x7535 /* last character  */
  ,&GUI_FontSONG16_CharInfo[145] /* address of first character */
  ,&GUI_FontSONG16_Prop55 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontSONG16_Prop53 = {
   0x751F /* first character */
  ,0x751F /* last character  */
  ,&GUI_FontSONG16_CharInfo[144] /* address of first character */
  ,&GUI_FontSONG16_Prop54 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontSONG16_Prop52 = {
   0x73AF /* first character */
  ,0x73AF /* last character  */
  ,&GUI_FontSONG16_CharInfo[143] /* address of first character */
  ,&GUI_FontSONG16_Prop53 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontSONG16_Prop51 = {
   0x7248 /* first character */
  ,0x7248 /* last character  */
  ,&GUI_FontSONG16_CharInfo[142] /* address of first character */
  ,&GUI_FontSONG16_Prop52 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontSONG16_Prop50 = {
   0x6E90 /* first character */
  ,0x6E90 /* last character  */
  ,&GUI_FontSONG16_CharInfo[141] /* address of first character */
  ,&GUI_FontSONG16_Prop51 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontSONG16_Prop49 = {
   0x6D4B /* first character */
  ,0x6D4B /* last character  */
  ,&GUI_FontSONG16_CharInfo[140] /* address of first character */
  ,&GUI_FontSONG16_Prop50 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontSONG16_Prop48 = {
   0x6D41 /* first character */
  ,0x6D41 /* last character  */
  ,&GUI_FontSONG16_CharInfo[139] /* address of first character */
  ,&GUI_FontSONG16_Prop49 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontSONG16_Prop47 = {
   0x6C60 /* first character */
  ,0x6C60 /* last character  */
  ,&GUI_FontSONG16_CharInfo[138] /* address of first character */
  ,&GUI_FontSONG16_Prop48 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontSONG16_Prop46 = {
   0x6C22 /* first character */
  ,0x6C22 /* last character  */
  ,&GUI_FontSONG16_CharInfo[137] /* address of first character */
  ,&GUI_FontSONG16_Prop47 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontSONG16_Prop45 = {
   0x6B65 /* first character */
  ,0x6B65 /* last character  */
  ,&GUI_FontSONG16_CharInfo[136] /* address of first character */
  ,&GUI_FontSONG16_Prop46 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontSONG16_Prop44 = {
   0x6B62 /* first character */
  ,0x6B63 /* last character  */
  ,&GUI_FontSONG16_CharInfo[134] /* address of first character */
  ,&GUI_FontSONG16_Prop45 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontSONG16_Prop43 = {
   0x6B21 /* first character */
  ,0x6B21 /* last character  */
  ,&GUI_FontSONG16_CharInfo[133] /* address of first character */
  ,&GUI_FontSONG16_Prop44 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontSONG16_Prop42 = {
   0x69DB /* first character */
  ,0x69DB /* last character  */
  ,&GUI_FontSONG16_CharInfo[132] /* address of first character */
  ,&GUI_FontSONG16_Prop43 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontSONG16_Prop41 = {
   0x672C /* first character */
  ,0x672C /* last character  */
  ,&GUI_FontSONG16_CharInfo[131] /* address of first character */
  ,&GUI_FontSONG16_Prop42 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontSONG16_Prop40 = {
   0x672A /* first character */
  ,0x672A /* last character  */
  ,&GUI_FontSONG16_CharInfo[130] /* address of first character */
  ,&GUI_FontSONG16_Prop41 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontSONG16_Prop39 = {
   0x671F /* first character */
  ,0x671F /* last character  */
  ,&GUI_FontSONG16_CharInfo[129] /* address of first character */
  ,&GUI_FontSONG16_Prop40 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontSONG16_Prop38 = {
   0x66F2 /* first character */
  ,0x66F2 /* last character  */
  ,&GUI_FontSONG16_CharInfo[128] /* address of first character */
  ,&GUI_FontSONG16_Prop39 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontSONG16_Prop37 = {
   0x662F /* first character */
  ,0x662F /* last character  */
  ,&GUI_FontSONG16_CharInfo[127] /* address of first character */
  ,&GUI_FontSONG16_Prop38 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontSONG16_Prop36 = {
   0x65F6 /* first character */
  ,0x65F6 /* last character  */
  ,&GUI_FontSONG16_CharInfo[126] /* address of first character */
  ,&GUI_FontSONG16_Prop37 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontSONG16_Prop35 = {
   0x65E5 /* first character */
  ,0x65E5 /* last character  */
  ,&GUI_FontSONG16_CharInfo[125] /* address of first character */
  ,&GUI_FontSONG16_Prop36 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontSONG16_Prop34 = {
   0x6587 /* first character */
  ,0x6587 /* last character  */
  ,&GUI_FontSONG16_CharInfo[124] /* address of first character */
  ,&GUI_FontSONG16_Prop35 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontSONG16_Prop33 = {
   0x6570 /* first character */
  ,0x6570 /* last character  */
  ,&GUI_FontSONG16_CharInfo[123] /* address of first character */
  ,&GUI_FontSONG16_Prop34 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontSONG16_Prop32 = {
   0x653E /* first character */
  ,0x653E /* last character  */
  ,&GUI_FontSONG16_CharInfo[122] /* address of first character */
  ,&GUI_FontSONG16_Prop33 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontSONG16_Prop31 = {
   0x63A7 /* first character */
  ,0x63A7 /* last character  */
  ,&GUI_FontSONG16_CharInfo[121] /* address of first character */
  ,&GUI_FontSONG16_Prop32 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontSONG16_Prop30 = {
   0x62A5 /* first character */
  ,0x62A5 /* last character  */
  ,&GUI_FontSONG16_CharInfo[120] /* address of first character */
  ,&GUI_FontSONG16_Prop31 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontSONG16_Prop29 = {
   0x622A /* first character */
  ,0x622A /* last character  */
  ,&GUI_FontSONG16_CharInfo[119] /* address of first character */
  ,&GUI_FontSONG16_Prop30 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontSONG16_Prop28 = {
   0x606F /* first character */
  ,0x606F /* last character  */
  ,&GUI_FontSONG16_CharInfo[118] /* address of first character */
  ,&GUI_FontSONG16_Prop29 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontSONG16_Prop27 = {
   0x5FAA /* first character */
  ,0x5FAA /* last character  */
  ,&GUI_FontSONG16_CharInfo[117] /* address of first character */
  ,&GUI_FontSONG16_Prop28 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontSONG16_Prop26 = {
   0x5F00 /* first character */
  ,0x5F00 /* last character  */
  ,&GUI_FontSONG16_CharInfo[116] /* address of first character */
  ,&GUI_FontSONG16_Prop27 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontSONG16_Prop25 = {
   0x5C0F /* first character */
  ,0x5C0F /* last character  */
  ,&GUI_FontSONG16_CharInfo[115] /* address of first character */
  ,&GUI_FontSONG16_Prop26 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontSONG16_Prop24 = {
   0x59CB /* first character */
  ,0x59CB /* last character  */
  ,&GUI_FontSONG16_CharInfo[114] /* address of first character */
  ,&GUI_FontSONG16_Prop25 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontSONG16_Prop23 = {
   0x58F0 /* first character */
  ,0x58F0 /* last character  */
  ,&GUI_FontSONG16_CharInfo[113] /* address of first character */
  ,&GUI_FontSONG16_Prop24 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontSONG16_Prop22 = {
   0x578B /* first character */
  ,0x578B /* last character  */
  ,&GUI_FontSONG16_CharInfo[112] /* address of first character */
  ,&GUI_FontSONG16_Prop23 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontSONG16_Prop21 = {
   0x5728 /* first character */
  ,0x5728 /* last character  */
  ,&GUI_FontSONG16_CharInfo[111] /* address of first character */
  ,&GUI_FontSONG16_Prop22 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontSONG16_Prop20 = {
   0x56FE /* first character */
  ,0x56FE /* last character  */
  ,&GUI_FontSONG16_CharInfo[110] /* address of first character */
  ,&GUI_FontSONG16_Prop21 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontSONG16_Prop19 = {
   0x5668 /* first character */
  ,0x5668 /* last character  */
  ,&GUI_FontSONG16_CharInfo[109] /* address of first character */
  ,&GUI_FontSONG16_Prop20 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontSONG16_Prop18 = {
   0x53F7 /* first character */
  ,0x53F7 /* last character  */
  ,&GUI_FontSONG16_CharInfo[108] /* address of first character */
  ,&GUI_FontSONG16_Prop19 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontSONG16_Prop17 = {
   0x538B /* first character */
  ,0x538B /* last character  */
  ,&GUI_FontSONG16_CharInfo[107] /* address of first character */
  ,&GUI_FontSONG16_Prop18 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontSONG16_Prop16 = {
   0x5236 /* first character */
  ,0x5236 /* last character  */
  ,&GUI_FontSONG16_CharInfo[106] /* address of first character */
  ,&GUI_FontSONG16_Prop17 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontSONG16_Prop15 = {
   0x5206 /* first character */
  ,0x5206 /* last character  */
  ,&GUI_FontSONG16_CharInfo[105] /* address of first character */
  ,&GUI_FontSONG16_Prop16 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontSONG16_Prop14 = {
   0x51FA /* first character */
  ,0x51FA /* last character  */
  ,&GUI_FontSONG16_CharInfo[104] /* address of first character */
  ,&GUI_FontSONG16_Prop15 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontSONG16_Prop13 = {
   0x5185 /* first character */
  ,0x5185 /* last character  */
  ,&GUI_FontSONG16_CharInfo[103] /* address of first character */
  ,&GUI_FontSONG16_Prop14 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontSONG16_Prop12 = {
   0x5173 /* first character */
  ,0x5173 /* last character  */
  ,&GUI_FontSONG16_CharInfo[102] /* address of first character */
  ,&GUI_FontSONG16_Prop13 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontSONG16_Prop11 = {
   0x5145 /* first character */
  ,0x5145 /* last character  */
  ,&GUI_FontSONG16_CharInfo[101] /* address of first character */
  ,&GUI_FontSONG16_Prop12 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontSONG16_Prop10 = {
   0x4FE1 /* first character */
  ,0x4FE1 /* last character  */
  ,&GUI_FontSONG16_CharInfo[100] /* address of first character */
  ,&GUI_FontSONG16_Prop11 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontSONG16_Prop9 = {
   0x4EF6 /* first character */
  ,0x4EF6 /* last character  */
  ,&GUI_FontSONG16_CharInfo[ 99] /* address of first character */
  ,&GUI_FontSONG16_Prop10 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontSONG16_Prop8 = {
   0x4EEA /* first character */
  ,0x4EEA /* last character  */
  ,&GUI_FontSONG16_CharInfo[ 98] /* address of first character */
  ,&GUI_FontSONG16_Prop9 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontSONG16_Prop7 = {
   0x4EA7 /* first character */
  ,0x4EA7 /* last character  */
  ,&GUI_FontSONG16_CharInfo[ 97] /* address of first character */
  ,&GUI_FontSONG16_Prop8 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontSONG16_Prop6 = {
   0x4E2D /* first character */
  ,0x4E2D /* last character  */
  ,&GUI_FontSONG16_CharInfo[ 96] /* address of first character */
  ,&GUI_FontSONG16_Prop7 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontSONG16_Prop5 = {
   0x4E0A /* first character */
  ,0x4E0B /* last character  */
  ,&GUI_FontSONG16_CharInfo[ 94] /* address of first character */
  ,&GUI_FontSONG16_Prop6 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontSONG16_Prop4 = {
   0x03A9 /* first character */
  ,0x03A9 /* last character  */
  ,&GUI_FontSONG16_CharInfo[ 93] /* address of first character */
  ,&GUI_FontSONG16_Prop5 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontSONG16_Prop3 = {
   0x0061 /* first character */
  ,0x007E /* last character  */
  ,&GUI_FontSONG16_CharInfo[ 63] /* address of first character */
  ,&GUI_FontSONG16_Prop4 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontSONG16_Prop2 = {
   0x0028 /* first character */
  ,0x005F /* last character  */
  ,&GUI_FontSONG16_CharInfo[  7] /* address of first character */
  ,&GUI_FontSONG16_Prop3 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontSONG16_Prop1 = {
   0x0020 /* first character */
  ,0x0026 /* last character  */
  ,&GUI_FontSONG16_CharInfo[  0] /* address of first character */
  ,&GUI_FontSONG16_Prop2 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT GUI_FontSONG16 = {
   GUI_FONTTYPE_PROP_EXT /* type of font    */
  ,16 /* height of font  */
  ,16 /* space of font y */
  ,1 /* magnification x */
  ,1 /* magnification y */
  ,{&GUI_FontSONG16_Prop1}
  ,14 /* Baseline */
  ,7 /* Height of lowercase characters */
  ,11 /* Height of capital characters */
};

